docs/source/getting_started/dataframe.rst
docs/source/locale/zh_CN/LC_MESSAGES/getting_started/dataframe.po
mars/dataframe/datasource/read_csv.py
mars/dataframe/datasource/tests/test_hdfs.py

Add docs about reading data from HDFS & Add test for reading parquet files from HDFS.
Resolve #1602.

Add docs about reading data from HDFS

---

.github/workflows/install-minikube.sh
mars/dataframe/indexing/__init__.py
mars/serialize/core.pxd
mars/serialize/core.pyx
mars/tests/core.py

Fix registration for DataFrameSetLabel operand. Tests operand registration also.
Fixes #1630

Fix registration for DataFrameSetLabel operand

---

.github/workflows/install-minikube.sh
mars/dataframe/indexing/__init__.py
mars/serialize/core.pxd
mars/serialize/core.pyx
mars/tests/core.py

[BACKPORT] Fix registration for DataFrameSetLabel operand(#1631)

---

mars/learn/neighbors/_faiss.py
mars/tensor/base/tests/test_base_execute.py
mars/tensor/base/transpose.py

This PR fixes issue that transpose when input has unknown shape.
Fixes #1629 .

Fix issue that serialization of transpose failed when input has unknown shape

---

.github/workflows/install-minikube.sh
mars/scheduler/assigner.py
mars/scheduler/graph.py

[BACKPORT] Eliminate TimeoutError when there are running nodes (#1637)

---

mars/learn/neighbors/_faiss.py
mars/tensor/base/tests/test_base_execute.py
mars/tensor/base/transpose.py

[BACKPORT] Fix issue that serialization of transpose failed when input has unknown shape (#1632)

---

mars/dataframe/sort/psrs.py
mars/dataframe/sort/tests/test_sort_execute.py
mars/scheduler/tests/integrated/test_normal_execution.py
mars/serialize/dataserializer.py

Fix distinct column missing when chunks has fewer rows than partition number.
Fixes #1641

Fix PSRS error when chunks has fewer rows than partition number

---

mars/dataframe/sort/psrs.py
mars/dataframe/sort/tests/test_sort_execute.py
mars/scheduler/tests/integrated/test_normal_execution.py
mars/serialize/dataserializer.py

[BACKPORT] Fix PSRS error when chunks has fewer rows than partition number (#1642)

---

mars/config.py
mars/custom_log.py
mars/dataframe/statistics/quantile.py
mars/learn/metrics/__init__.py
mars/learn/metrics/pairwise/__init__.py
mars/learn/metrics/pairwise/core.py
mars/learn/metrics/pairwise/euclidean.py
mars/learn/metrics/pairwise/pairwise_distances_topk.py
mars/learn/metrics/pairwise/tests/test_pariwise_distances.py
mars/learn/neighbors/base.py
mars/learn/utils/__init__.py
mars/learn/utils/core.py
mars/scheduler/tests/integrated/test_normal_execution.py
mars/serialize/protos/operand.proto

[BACKPORT] Optimize memory usage for brute-force algorithm in `NearestNeighbors` (#1640)

---

docs/source/reference/dataframe/api/mars.dataframe.DataFrame.to_parquet.rst
docs/source/reference/dataframe/frame.rst
mars/dataframe/datasource/read_parquet.py
mars/dataframe/datastore/__init__.py
mars/dataframe/datastore/tests/test_datastore_execute.py
mars/dataframe/datastore/to_parquet.py

Implement `df.to_parquet`.
Resolves #951

Add DataFrame.to_parquet support

---

docs/source/reference/dataframe/api/mars.dataframe.DataFrame.to_parquet.rst
docs/source/reference/dataframe/frame.rst
mars/dataframe/datasource/read_parquet.py
mars/dataframe/datastore/__init__.py
mars/dataframe/datastore/tests/test_datastore_execute.py
mars/dataframe/datastore/to_parquet.py

[BACKPORT] Add `DataFrame.to_parquet` support (#1652)

---

.github/workflows/install-minikube.sh
mars/config.py
mars/dataframe/merge/concat.py
mars/deploy/kubernetes/scheduler.py
mars/learn/proxima/core.py
mars/learn/proxima/simple_index/builder.py
mars/learn/proxima/simple_index/searcher.py
mars/scheduler/resource.py

This PR added check logic in tile of `md.concat` to make sure no unknown chunk shapes.
Fixes #1654 .

Check unknown shape chunks in tile of `md.concat`

---

.github/workflows/install-minikube.sh
mars/dataframe/merge/concat.py

[BACKPORT] Check unknown shape chunks in tile of `md.concat` (#1655)

---

mars/core.py
mars/dataframe/fetch/core.py
mars/dataframe/operands.py
mars/deploy/local/tests/test_cluster.py
mars/learn/operands.py
mars/operands.py
mars/tensor/fetch/core.py
mars/tensor/operands.py

[BACKPORT] Create Fetch operands given output types (#1666)

---

mars/core.py
mars/tests/test_session.py

This PR modifies `df.copy()` so that it generates the identical key.
Fixes #1670 .

Modify `df.copy()` so that it generates the identical key

---

mars/config.py
mars/dataframe/indexing/iloc.py
mars/dataframe/indexing/tests/test_indexing_execution.py
mars/optimizes/runtime/dataframe.py

[BACKPORT] Add a threshold for `DataFrame.head` optimization (#1673)

---

mars/dataframe/arithmetic/core.py
mars/dataframe/arithmetic/tests/test_arithmetic_execution.py
mars/dataframe/merge/concat.py

This PR fixes IndexError when binary op on Series whose type is datetime.
Fixes #1674 .

Fix IndexError when binary op on Series whose type is datetime

---

mars/dataframe/arithmetic/core.py
mars/dataframe/arithmetic/tests/test_arithmetic_execution.py
mars/dataframe/merge/concat.py

[BACKPORT] Fix IndexError when binary op on Series whose type is datetime (#1675)

---

mars/dataframe/merge/concat.py
mars/dataframe/reduction/core.py
mars/dataframe/reduction/count.py
mars/dataframe/reduction/var.py

This PR fixes Series reduction that output type consistent for map and combine phase.
Fixes #1682 .

Fix Series reduction that output type consistent for map and combine phase

---

mars/dataframe/merge/concat.py
mars/dataframe/reduction/core.py
mars/dataframe/reduction/count.py
mars/dataframe/reduction/var.py

[BACKPORT] Fix DataFrame reduction that output type consistent for map and combine phase (#1685)

---

mars/scheduler/analyzer.py
mars/scheduler/tests/test_analyzer.py

Fix assigning operands with expected workers by ignore them and patch back later.
Fixes #1688

Fix assigning operands with expected workers

---

mars/_version.py
mars/learn/neighbors/base.py
mars/learn/neighbors/tests/test_nearest_neighbors.py
mars/learn/proxima/recall.py
mars/learn/proxima/simple_index/__init__.py
mars/learn/proxima/simple_index/builder.py
mars/learn/proxima/simple_index/knn.py
mars/learn/proxima/simple_index/recall.py
mars/learn/proxima/simple_index/searcher.py
mars/learn/proxima/simple_index/tests/integrated/test_distributed_simple_index.py
mars/learn/proxima/simple_index/tests/test_simple_index.py
mars/tests/test_utils.py
mars/utils.py

What do these changes do?
Add recall computation for proxima
NA

Support recall computation for proxima

---

mars/scheduler/analyzer.py
mars/scheduler/tests/test_analyzer.py

[BACKPORT] Fix assigning operands with expected workers (#1689)

---

mars/deploy/kubernetes/config.py
mars/scheduler/graph.py
mars/worker/__main__.py
mars/worker/service.py
mars/worker/tests/test_main.py

[BACKPORT] Add timeout for SharedHolderActor creation (#1684)

---

.github/workflows/install-hadoop.sh
mars/config.py
mars/deploy/local/core.py
mars/node_info.py
mars/scheduler/operands/common.py
mars/scheduler/operands/shuffle.py
mars/scheduler/operands/tests/test_common_exec.py
mars/scheduler/resource.py
mars/tests/test_config.py
mars/web/templates/scheduler_pages/detail.html
mars/web/templates/worker_pages/detail.html
mars/worker/calc.py
mars/worker/execution.py
mars/worker/service.py
mars/worker/tests/test_service.py

This PR did the things below:
1. Add a pane on Mars web to display options
2. Support collecting option values into dicts
3. Cancel allocations when the job is cancelled
Fixes #1696

Add configuration page on Mars Web

---

.github/workflows/install-hadoop.sh
mars/config.py
mars/deploy/local/core.py
mars/node_info.py
mars/scheduler/operands/common.py
mars/scheduler/operands/shuffle.py
mars/scheduler/operands/tests/test_common_exec.py
mars/scheduler/resource.py
mars/tests/test_config.py
mars/web/templates/scheduler_pages/detail.html
mars/web/templates/worker_pages/detail.html
mars/worker/calc.py
mars/worker/execution.py
mars/worker/service.py
mars/worker/tests/test_service.py

[BACKPORT] Add configuration page on Mars Web (#1697)

---

mars/config.py
mars/deploy/local/core.py
mars/utils.py
mars/web/apihandlers.py
mars/worker/__main__.py
mars/worker/service.py
mars/worker/storage/sharedstore.py
mars/worker/storage/tests/test_sharedstore.py
mars/worker/tests/base.py
mars/worker/tests/test_service.py
mars/worker/tests/test_transfer.py

Add limit option on shared memory path (i.e., /dev/shm) for Mars worker.

Add shared limit option for Mars worker

---

.github/workflows/install-hadoop.sh
mars/deploy/kubernetes/config.py
mars/deploy/kubernetes/docker/entrypoint.sh
mars/deploy/kubernetes/tests/test_config.py
mars/resource.py

Remount the shm directory in entrypoint.sh.

Remount the shm directory in entrypoint.sh

---

mars/config.py
mars/deploy/kubernetes/config.py
mars/deploy/kubernetes/docker/entrypoint.sh
mars/deploy/kubernetes/tests/test_config.py
mars/deploy/local/core.py
mars/resource.py
mars/utils.py
mars/web/apihandlers.py
mars/worker/__main__.py
mars/worker/service.py
mars/worker/storage/sharedstore.py
mars/worker/storage/tests/test_sharedstore.py
mars/worker/tests/base.py
mars/worker/tests/test_service.py
mars/worker/tests/test_transfer.py

[BACKPORT] Remount /dev/shm directory in entrypoint.sh in Kubernetes and limit plasma size to avoid SIGBUS

---

mars/dataframe/base/standardize_range_index.py
mars/dataframe/utils.py
mars/operands.py
mars/scheduler/assigner.py
mars/scheduler/graph.py
mars/scheduler/tests/integrated/test_normal_execution.py
mars/web/templates/worker_pages/detail.html
mars/worker/calc.py
mars/worker/execution.py
mars/worker/status.py
mars/worker/storage/objectholder.py

Add pure-depends links for operands. When estimating sizes, those links will not be accounted.
Fixes #1672

Add pure-dependent option for operands

---

mars/dataframe/base/standardize_range_index.py
mars/dataframe/utils.py
mars/operands.py
mars/remote/core.py
mars/scheduler/assigner.py
mars/scheduler/graph.py
mars/scheduler/tests/integrated/no_prepare_op.py
mars/scheduler/tests/integrated/test_normal_execution.py
mars/tensor/base/shape.py
mars/tensor/datastore/to_hdf5.py
mars/web/templates/worker_pages/detail.html
mars/worker/calc.py
mars/worker/execution.py
mars/worker/status.py
mars/worker/storage/objectholder.py

[BACKPORT] Add pure-dependent option for operands (#1706)

---

docs/source/reference/dataframe/frame.rst
docs/source/reference/dataframe/series.rst
mars/_version.py
mars/dataframe/base/__init__.py
mars/dataframe/base/explode.py
mars/dataframe/base/tests/test_base_execution.py
mars/serialize/dataserializer.py
mars/serialize/protos/operand.proto

[BACKPORT] Implements {DataFrame,Series}.explode (#1714)

---

mars/dataframe/sort/core.py
mars/dataframe/sort/psrs.py
mars/dataframe/sort/sort_index.py
mars/dataframe/sort/sort_values.py
mars/dataframe/sort/tests/test_sort_execute.py

[BACKPORT] Fix sort functions in CUDA (#1723)

---

mars/dataframe/merge/append.py
mars/dataframe/reduction/nunique.py
mars/dataframe/sort/sort_index.py
mars/dataframe/sort/sort_values.py
mars/serialize/protos/operand.proto
mars/tensor/base/__init__.py
mars/tensor/base/rebalance.py
mars/tensor/base/tests/test_base_execute.py
mars/tensor/rechunk/rechunk.py

Implements tensor.rebalance().
Note that opcode of REBALANCE is changed.
Fixes #1730

Add rebalance method for tensors

---

mars/dataframe/base/__init__.py
mars/dataframe/base/apply.py
mars/dataframe/base/map.py
mars/dataframe/base/rebalance.py
mars/dataframe/base/rechunk.py
mars/dataframe/base/tests/test_base_execution.py
mars/dataframe/base/transform.py
mars/dataframe/datasource/from_tensor.py
mars/dataframe/groupby/apply.py
mars/dataframe/groupby/transform.py
mars/dataframe/initializer.py
mars/dataframe/merge/append.py
mars/dataframe/reduction/nunique.py
mars/dataframe/sort/sort_index.py
mars/dataframe/sort/sort_values.py
mars/dataframe/tests/test_initializer.py
mars/dataframe/tests/test_utils.py
mars/dataframe/utils.py
mars/serialize/protos/operand.proto
mars/tensor/base/__init__.py
mars/tensor/base/rebalance.py
mars/tensor/base/tests/test_base_execute.py
mars/tensor/rechunk/rechunk.py

[BACKPORT] Support `num_partitions` argument for DataFrame initializers (#1729)

---

docs/source/reference/dataframe/api/mars.dataframe.groupby.GroupBy.kurt.rst
docs/source/reference/dataframe/api/mars.dataframe.groupby.GroupBy.kurtosis.rst
docs/source/reference/dataframe/api/mars.dataframe.groupby.GroupBy.sem.rst
docs/source/reference/dataframe/api/mars.dataframe.groupby.GroupBy.skew.rst
docs/source/reference/dataframe/groupby.rst
mars/dataframe/groupby/__init__.py
mars/dataframe/groupby/aggregation.py
mars/dataframe/groupby/core.py
mars/dataframe/groupby/tests/test_groupby_execution.py
mars/dataframe/reduction/nunique.py

[BACKPORT] Unify groupby.agg() using ReductionCompiler (#1635)

---

mars/dataframe/sort/psrs.py
mars/scheduler/operands/common.py
mars/scheduler/operands/core.py
mars/scheduler/operands/shuffle.py
mars/tensor/base/psrs.py
mars/worker/dispatcher.py

Make PSRS chunks more balanced. Also stop reporting WorkerDead when timeout.
NA

Make PSRS chunks more balanced

---

mars/dataframe/sort/psrs.py
mars/scheduler/operands/common.py
mars/scheduler/operands/core.py
mars/scheduler/operands/shuffle.py
mars/tensor/base/psrs.py
mars/tensor/reduction/all.py
mars/tensor/reduction/any.py
mars/tensor/reduction/core.py
mars/tensor/reduction/sum.py
mars/tensor/reduction/tests/test_reduction_execute.py
mars/worker/dispatcher.py

[BACKPORT] Support string dtype for tensor reductions (#1745) & balance PSRS chunks (#1742)

---

mars/dataframe/__init__.py
mars/dataframe/groupby/aggregation.py
mars/dataframe/groupby/getitem.py
mars/dataframe/groupby/tests/test_groupby_execution.py
mars/dataframe/reduction/aggregation.py
mars/dataframe/reduction/core.py
mars/dataframe/reduction/tests/test_reduction.py
mars/dataframe/reduction/tests/test_reduction_execute.py
mars/worker/service.py
mars/worker/tests/test_service.py

Add support for named aggregations, both for agg and groupby-agg.
Fixes #1744

Add support for named aggregations

---

mars/dataframe/__init__.py
mars/dataframe/groupby/aggregation.py
mars/dataframe/groupby/getitem.py
mars/dataframe/groupby/tests/test_groupby_execution.py
mars/dataframe/reduction/aggregation.py
mars/dataframe/reduction/core.py
mars/dataframe/reduction/tests/test_reduction.py
mars/dataframe/reduction/tests/test_reduction_execute.py
mars/worker/service.py
mars/worker/tests/test_service.py

[BACKPORT] Add support for named aggregations (#1747)

---

mars/dataframe/initializer.py
mars/dataframe/merge/concat.py
mars/dataframe/operands.py
mars/dataframe/tests/test_initializer.py
mars/learn/contrib/lightgbm/tests/integrated/test_distributed_lightgbm.py
mars/learn/contrib/xgboost/tests/integrated/test_distributed_xgboost.py
mars/scheduler/__main__.py
mars/scheduler/operands/shuffle.py
mars/scheduler/tests/integrated/test_normal_execution.py

[BACKPORT] Fix XGBoost and LightGBM on DataFrames (#1750)

---

mars/_utils.pyx
mars/dataframe/groupby/aggregation.py
mars/dataframe/groupby/core.py
mars/dataframe/groupby/tests/test_groupby_execution.py
mars/dataframe/indexing/iloc.py
mars/scheduler/graph.py
mars/scheduler/operands/common.py
mars/scheduler/tests/integrated/test_normal_execution.py
mars/tests/test_utils.py
mars/worker/storage/client.py

[BACKPORT] Fix repeated execution of same code in distributed mode (#1749)

---

mars/dataframe/datasource/from_tensor.py
mars/dataframe/indexing/setitem.py
mars/dataframe/indexing/tests/test_indexing_execution.py

This PR support setting a column with scalar for DataFrame.
Fixes #1754 .

Support setting scalar which is a tensor for DataFrame

---

mars/dataframe/datasource/from_tensor.py
mars/dataframe/indexing/setitem.py
mars/dataframe/indexing/tests/test_indexing_execution.py

[BACKPORT] Support setting scalar which is a tensor for DataFrame (#1755)

---

mars/_version.py

[Skip CI] Bump version to 0.6.0

---

requirements-wheel.txt

Upgrade cython version to 0.29.14

---

docs/source/user_guide/learn/index.rst
docs/source/user_guide/learn/joblib.rst
mars/_utils.pyx
mars/_version.py
mars/api.py
mars/learn/contrib/joblib/__init__.py
mars/learn/contrib/joblib/backend.py
mars/learn/contrib/joblib/tests/__init__.py
mars/learn/contrib/joblib/tests/integrated/__init__.py
mars/learn/contrib/joblib/tests/integrated/test_distributed_backend.py
mars/learn/contrib/joblib/tests/test_backend.py
mars/ray/core.py
mars/serialize/core.pxd
mars/serialize/core.pyx
mars/serialize/jsonserializer.pyx
mars/serialize/pbserializer.pyx
mars/serialize/protos/value.proto
mars/serialize/tests/test_serialize.py
mars/serialize/tests/testser.proto
mars/session.py
mars/tests/test_utils.py
mars/web/apihandlers.py
mars/web/session.py
mars/web/tests/test_api.py
requirements-wheel.txt

Add preliminary joblib support by scheduling tasks at client. More optimizations needed later on.
Fixes #1756

Add preliminary joblib support

---

mars/dataframe/reduction/aggregation.py
mars/dataframe/reduction/core.py
mars/deploy/local/tests/test_cluster.py
mars/scheduler/graph.py
mars/scheduler/operands/base.py

[BACKPORT] Spawn serialization of executable graphs (#1769)

---

mars/dataframe/base/__init__.py
mars/dataframe/base/cartesian_chunk.py
mars/dataframe/base/map_chunk.py
mars/dataframe/base/tests/test_base_execution.py
mars/serialize/protos/operand.proto

This PR added `{DataFrame, Series}.cartesian_chunk` support.
Resolves #1773 .

Add `{DataFrame, Series}.cartesian_chunk` support

---

mars/dataframe/base/__init__.py
mars/dataframe/base/cartesian_chunk.py
mars/dataframe/base/map_chunk.py
mars/dataframe/base/tests/test_base_execution.py
mars/learn/contrib/xgboost/tests/integrated/test_distributed_xgboost.py
mars/learn/contrib/xgboost/tests/test_classifier.py
mars/serialize/protos/operand.proto

[BACKPORT] Add `{DataFrame, Series}.cartesian_chunk` support (#1774)

---

docs/source/installation/index.rst
docs/source/installation/kubernetes.rst
docs/source/installation/yarn.rst
mars/dataframe/datasource/read_csv.py
mars/dataframe/datasource/read_parquet.py
mars/dataframe/datasource/tests/test_datasource_execution.py
mars/dataframe/datasource/tests/test_hdfs.py
mars/dataframe/datastore/tests/test_datastore_execute.py

[BACKPORT] Fix reading partitioned parquet files in HDFS (#1782)

---

mars/_version.py
mars/dataframe/datasource/read_parquet.py
mars/dataframe/datasource/tests/test_datasource_execution.py
mars/dataframe/indexing/getitem.py
mars/dataframe/indexing/tests/test_indexing.py
mars/dataframe/reduction/tests/test_reduction_execute.py
mars/dataframe/utils.py

This PR fixes creating Mars Series from empty pandas Series.
Fixes #1786 .
This is the followed fix of #1521 .

Fix creating Mars Series from empty pandas Series

---

mars/_version.py
mars/dataframe/datasource/read_parquet.py
mars/dataframe/datasource/tests/test_datasource_execution.py
mars/dataframe/indexing/getitem.py
mars/dataframe/indexing/tests/test_indexing.py
mars/dataframe/reduction/tests/test_reduction_execute.py
mars/dataframe/utils.py

[BACKPORT] Fix creating Mars Series from empty pandas Series (#1787)

---

mars/dataframe/core.py
mars/dataframe/datasource/from_tensor.py
mars/dataframe/merge/concat.py
mars/dataframe/merge/tests/test_merge_execution.py
mars/dataframe/tests/test_core.py

This PR supports `md.concat` on DataFrame and Series.
Fixes #1796 .

Support md.concat on DataFrame and Series

---

docs/source/reference/dataframe/api/mars.dataframe.CustomReduction.rst
docs/source/reference/dataframe/api/mars.dataframe.DataFrame.backfill.rst
docs/source/reference/dataframe/api/mars.dataframe.DataFrame.bfill.rst
docs/source/reference/dataframe/api/mars.dataframe.DataFrame.explode.rst
docs/source/reference/dataframe/api/mars.dataframe.DataFrame.ffill.rst
docs/source/reference/dataframe/api/mars.dataframe.DataFrame.isnull.rst
docs/source/reference/dataframe/api/mars.dataframe.DataFrame.notnull.rst
docs/source/reference/dataframe/api/mars.dataframe.DataFrame.pad.rst
docs/source/reference/dataframe/api/mars.dataframe.DataFrame.replace.rst
docs/source/reference/dataframe/api/mars.dataframe.DataFrame.rst
docs/source/reference/dataframe/api/mars.dataframe.Series.explode.rst
docs/source/reference/dataframe/api/mars.dataframe.Series.rst
docs/source/reference/learn/generated/mars.learn.contrib.statsmodels.MarsDistributedModel.rst
docs/source/reference/learn/generated/mars.learn.contrib.statsmodels.MarsResults.rst
mars/dataframe/datastore/tests/test_datastore_execute.py
mars/dataframe/datastore/to_parquet.py
mars/learn/contrib/xgboost/predict.py
mars/learn/contrib/xgboost/tests/test_classifier.py

[BACKPORT] Fix bug that explicit execute may be required for to_parquet and XGB predict (#1794)

---

mars/dataframe/core.py
mars/dataframe/datasource/from_tensor.py
mars/dataframe/merge/concat.py
mars/dataframe/merge/tests/test_merge_execution.py
mars/dataframe/tests/test_core.py

[BACKPORT] Support md.concat on DataFrame and Series (#1798)

---

docs/source/installation/yarn.rst
mars/deploy/kubernetes/client.py
mars/deploy/utils.py
mars/deploy/yarn/client.py

Bug fix for timeout error on yarn.
Fixes #1791 .

Fix TypeError when timeout argument is absent when starting Mars cluster in YARN

---

README.rst
mars/learn/proxima/simple_index/builder.py
mars/learn/proxima/simple_index/recall.py
mars/learn/proxima/simple_index/searcher.py

[BACKPORT] Improve proxima `recall_by_id` computation method (#1805)

---

.github/workflows/core-ci.yml
.github/workflows/os-compat-ci.yml
mars/dataframe/datasource/read_csv.py
mars/dataframe/datasource/read_parquet.py
mars/dataframe/datasource/tests/test_datasource_execution.py
mars/deploy/kubernetes/core.py
mars/learn/cluster/_k_means_init.py
mars/operands.py
mars/tests/test_session.py
mars/utils.py
requirements-extra.txt

[BACKPORT] Add memory estimation for `read_parquet` as well as `read_csv` (#1811)

---

mars/dataframe/groupby/aggregation.py
mars/dataframe/reduction/aggregation.py
mars/dataframe/reduction/all.py
mars/dataframe/reduction/any.py
mars/dataframe/reduction/core.py
mars/dataframe/reduction/count.py
mars/dataframe/reduction/custom_reduction.py
mars/dataframe/reduction/kurtosis.py
mars/dataframe/reduction/max.py
mars/dataframe/reduction/mean.py
mars/dataframe/reduction/min.py
mars/dataframe/reduction/nunique.py
mars/dataframe/reduction/prod.py
mars/dataframe/reduction/reduction_size.py
mars/dataframe/reduction/sem.py
mars/dataframe/reduction/skew.py
mars/dataframe/reduction/str_concat.py
mars/dataframe/reduction/sum.py
mars/dataframe/reduction/unique.py
mars/dataframe/reduction/var.py

[BACKPORT] Support using compound agg function in lambda (#1810)

---

.github/workflows/core-ci.yml
.github/workflows/os-compat-ci.yml
mars/learn/cluster/_k_means_init.py
mars/learn/cluster/_kmeans.py
mars/learn/cluster/tests/test_k_means.py

[BACKPORT] Fix compatibility for scikit-learn 0.24.0 (#1817)

---

mars/deploy/kubedl/config.py

1. remove `tolerations` with single `Exists` operator so as to avoid being scheduled to a unexpected node.
2. provide a ratio to set replicas resources limits, scheduler/webservice `limit_resources_ratio=1` defaulted, worker `limit_resources_ratio=2` defaulted.

Refine kubedl cluster-api.

---

mars/dataframe/indexing/reset_index.py
mars/dataframe/indexing/tests/test_indexing_execution.py
mars/dataframe/merge/concat.py
mars/deploy/kubedl/config.py
mars/tensor/datasource/from_dense.py

[BACKPORT] Add `incremental_index` argument to `reset_index` which by default is False (#1823)

---

docs/source/reference/learn/reference.rst
mars/_version.py
mars/dataframe/arithmetic/core.py
mars/dataframe/utils.py
mars/learn/base.py
mars/learn/cluster/_kmeans.py
mars/learn/preprocessing/__init__.py
mars/learn/preprocessing/_data.py
mars/learn/preprocessing/tests/test_data.py
mars/learn/preprocessing/tests/test_normalize.py
mars/tensor/datasource/array.py
requirements-dev.txt
requirements.txt

This PR implements `mars.learn.preprocessing.{MinMaxScaler, minmax_scale}`
Resolves #1812 .

Implements `mars.learn.preprocessing.{MinMaxScaler, minmax_scale}`

---

mars/deploy/kubedl/client.py
mars/deploy/kubedl/config.py

- Pass `modules` to `MarsWorkerSpecConfig`.
- Add `MARS_K8S_REMOUNT_SHM` in worker ENV.

Enhancements for Mars on kubedl

---

docs/source/reference/dataframe/groupby.rst
mars/base_app.py
mars/dataframe/groupby/__init__.py
mars/dataframe/groupby/aggregation.py
mars/dataframe/groupby/core.py
mars/dataframe/groupby/head.py
mars/dataframe/groupby/tests/test_groupby_execution.py
mars/dataframe/sort/psrs.py
mars/serialize/protos/operand.proto
mars/web/__main__.py

Implements head() on groupby objects
Fixes #1813

Implements head() on groupby objects

---

docs/source/reference/dataframe/groupby.rst
mars/base_app.py
mars/dataframe/groupby/__init__.py
mars/dataframe/groupby/aggregation.py
mars/dataframe/groupby/core.py
mars/dataframe/groupby/head.py
mars/dataframe/groupby/tests/test_groupby_execution.py
mars/dataframe/sort/psrs.py
mars/serialize/protos/operand.proto
mars/tensor/core.py
mars/web/__main__.py
requirements-dev.txt
requirements.txt

[BACKPORT] Implements head() on groupby objects (#1849)

---

mars/dataframe/operands.py
mars/executor.py
mars/learn/operands.py
mars/operands.py
mars/ray/core.py
mars/ray/tests/test_ray_execution.py
mars/tensor/operands.py

This PR tried to resolve KeyError when calling `delete_keys` for ray backend.
Fixes #1719 
Fixes #1721

Resolve KeyError when calling `delete_keys` for ray backend

---

mars/core.py
mars/dataframe/core.py
mars/dataframe/utils.py
mars/tests/test_session.py

This PR supports `to_pandas` in a batch way for DataFrame and Series.
Resolves #1852 .

Support `to_pandas` in a batch way for DataFrame and Series

---

mars/dataframe/operands.py
mars/executor.py
mars/learn/operands.py
mars/operands.py
mars/ray/core.py
mars/ray/tests/test_ray_execution.py
mars/tensor/operands.py

[BACKPORT] Resolve KeyError when calling `delete_keys` for ray backend (#1846)

---

mars/deploy/kubedl/config.py
mars/deploy/kubernetes/client.py
mars/deploy/kubernetes/config.py
mars/deploy/kubernetes/tests/test_config.py
mars/resource.py

Allow specifying memory limit scale. This will reduce Mars workers being killed by cluster management.
Fixes #1855

Support specifying memory limit scale in kubernetes

---

docs/source/reference/learn/reference.rst
mars/_version.py
mars/dataframe/arithmetic/core.py
mars/dataframe/utils.py
mars/learn/base.py
mars/learn/cluster/_kmeans.py
mars/learn/preprocessing/__init__.py
mars/learn/preprocessing/_data.py
mars/learn/preprocessing/tests/test_data.py
mars/learn/preprocessing/tests/test_normalize.py
mars/tensor/datasource/array.py

[BACKPORT] Implements  `mars.learn.preprocessing.{MinMaxScaler, minmax_scale}`(#1844)

---

mars/core.py
mars/dataframe/core.py
mars/dataframe/utils.py
mars/tests/test_session.py

[BACKPORT] Support `to_pandas` in a batch way for DataFrame and Series (#1853)

---

mars/deploy/kubedl/config.py
mars/deploy/kubernetes/client.py
mars/deploy/kubernetes/config.py
mars/deploy/kubernetes/tests/test_config.py
mars/resource.py

[BACKPORT] Support specifying memory scale in kubernetes (#1856)

---

.github/workflows/platform-ci.yml
mars/dataframe/arithmetic/bitwise_and.py
mars/dataframe/arithmetic/bitwise_or.py
mars/dataframe/arithmetic/bitwise_xor.py
mars/dataframe/arithmetic/core.py
mars/dataframe/arithmetic/tests/test_arithmetic_execution.py
mars/dataframe/arrays.py
mars/dataframe/base/transform.py
mars/dataframe/groupby/core.py
mars/dataframe/reduction/aggregation.py
mars/dataframe/reduction/core.py
mars/dataframe/reduction/tests/test_reduction.py
mars/dataframe/reduction/tests/test_reduction_execute.py
mars/dataframe/tests/test_arrays.py
mars/dataframe/utils.py
mars/dataframe/window/rolling/aggregation.py
mars/dataframe/window/rolling/tests/test_rolling_execute.py
mars/utils.py
requirements-dev.txt
requirements.txt

[BACKPORT] Fix compatibility for pandas 1.2.0 (#1847)

---

docs/source/locale/zh_CN/LC_MESSAGES/reference/dataframe/indexing.po
docs/source/reference/dataframe/index.rst
docs/source/reference/dataframe/indexing.rst
mars/dataframe/arithmetic/core.py
mars/dataframe/arithmetic/is_ufuncs.py
mars/dataframe/base/__init__.py
mars/dataframe/base/astype.py
mars/dataframe/base/cartesian_chunk.py
mars/dataframe/base/map.py
mars/dataframe/base/tests/test_base_execution.py
mars/dataframe/base/transform.py
mars/dataframe/core.py
mars/dataframe/datasource/index.py
mars/dataframe/missing/__init__.py
mars/dataframe/missing/checkna.py
mars/dataframe/missing/dropna.py
mars/dataframe/missing/fillna.py
mars/dataframe/missing/tests/test_missing_execute.py
mars/dataframe/reduction/__init__.py
mars/dataframe/reduction/aggregation.py
mars/dataframe/reduction/all.py
mars/dataframe/reduction/any.py
mars/dataframe/reduction/max.py
mars/dataframe/reduction/min.py
mars/dataframe/reduction/nunique.py
mars/dataframe/reduction/tests/test_reduction_execute.py
mars/dataframe/tests/test_utils.py
mars/operands.py
mars/tests/test_session.py

[BACKPORT] Add more functionalities for `md.Index` (#1860)

---

CODEOWNERS
CODE_OF_CONDUCT.md
MAINTAINERS.md
RELEASES.md
SUPPORT.md

This PR added LFAI & Data required documents, no code effected, thus CI will be skipped.
NA

LFAI & Data: Add required documents

---

docs/source/locale/zh_CN/LC_MESSAGES/reference/dataframe/indexing.po
docs/source/reference/dataframe/frame.rst
docs/source/reference/dataframe/indexing.rst
docs/source/reference/dataframe/series.rst
mars/dataframe/core.py
mars/dataframe/indexing/__init__.py
mars/dataframe/indexing/rename.py
mars/dataframe/indexing/rename_axis.py
mars/dataframe/indexing/tests/test_indexing_execution.py
mars/serialize/protos/operand.proto
mars/tests/test_session.py

[BACKPORT] Implements `{DataFrame,Series}.rename_axis` (#1867)

---

CODEOWNERS
mars/dataframe/base/cartesian_chunk.py
mars/dataframe/core.py
mars/dataframe/datasource/from_tensor.py
mars/dataframe/datasource/tests/test_datasource_execution.py
mars/ray/tests/test_ray_execution.py
mars/tensor/base/flatten.py
mars/tensor/reshape/reshape.py
mars/tensor/reshape/tests/test_reshape.py
mars/tensor/reshape/tests/test_reshape_execute.py
mars/tensor/statistics/histogram.py
mars/tensor/statistics/tests/test_statistics_execute.py
mars/tests/test_session.py

[BACKPORT] Support unknown shape for mt.reshape, mt.histogram and md.DataFrame (#1869)

---

mars/actors/pool/gevent_pool.pyx
requirements-extra.txt

[BACKPORT] Fix stuck of threaded actor operations in gevent==20.12.0 (#1879)

---

mars/config.py
mars/scheduler/tests/test_graph.py
mars/utils.py
mars/worker/execution.py

[BACKPORT] Allow internal serialization to use JSON (#1880)

---

.github/workflows/core-ci.yml
.github/workflows/platform-ci.yml
mars/dataframe/datasource/core.py
mars/dataframe/datasource/read_csv.py
mars/dataframe/datasource/read_parquet.py
mars/dataframe/indexing/tests/test_indexing_execution.py
mars/executor.py
mars/learn/tests/integrated/base.py
mars/optimizes/runtime/dataframe.py
mars/optimizes/tileable_graph/__init__.py
mars/optimizes/tileable_graph/head.py
mars/optimizes/tileable_graph/tests/integrated/__init__.py
mars/optimizes/tileable_graph/tests/integrated/raise_iloc.py
mars/optimizes/tileable_graph/tests/integrated/test_distributed_optimization.py
mars/optimizes/tileable_graph/tests/test_head.py
mars/scheduler/graph.py

This PR includes optimization about:
NA

Optimize performance of {md.read_csv(), md.read_parquet()}.head()

---

.github/workflows/core-ci.yml
.github/workflows/platform-ci.yml
mars/dataframe/datasource/core.py
mars/dataframe/datasource/read_csv.py
mars/dataframe/datasource/read_parquet.py
mars/dataframe/indexing/tests/test_indexing_execution.py
mars/executor.py
mars/learn/tests/integrated/base.py
mars/optimizes/runtime/dataframe.py
mars/optimizes/tileable_graph/head.py
mars/optimizes/tileable_graph/tests/integrated/__init__.py
mars/optimizes/tileable_graph/tests/integrated/raise_iloc.py
mars/optimizes/tileable_graph/tests/integrated/test_distributed_optimization.py
mars/optimizes/tileable_graph/tests/test_head.py
mars/scheduler/graph.py

[BACKPORT] Optimize performance of {md.read_csv(), md.read_parquet()}.head() (#1878)

---

mars/dataframe/base/value_counts.py
mars/dataframe/sort/core.py
mars/dataframe/sort/sort_index.py
mars/dataframe/sort/sort_values.py
mars/optimizes/tileable_graph/__init__.py
mars/optimizes/tileable_graph/head.py
mars/optimizes/tileable_graph/tests/test_head.py

This PR optimized performance of `df.sort_values().head()`
NA

Optimize performance of `df.sort_values().head()`

---

mars/dataframe/base/value_counts.py
mars/dataframe/sort/core.py
mars/dataframe/sort/sort_index.py
mars/dataframe/sort/sort_values.py
mars/optimizes/tileable_graph/__init__.py
mars/optimizes/tileable_graph/head.py
mars/optimizes/tileable_graph/tests/test_head.py

[BACKPORT] Optimize performance of `df.sort_values().head()` (#1884)

---

mars/dataframe/datasource/core.py
mars/dataframe/datasource/read_csv.py
mars/dataframe/datasource/read_parquet.py
mars/dataframe/datasource/read_sql.py
mars/optimizes/tileable_graph/__init__.py
mars/optimizes/tileable_graph/column_pruning.py
mars/optimizes/tileable_graph/tests/test_column_pruning.py

This pR supported column pruning for groupby().agg() on data sources.
#1884 should be merge first.
NA

Support column pruning for groupby().agg() on data sources

---

mars/dataframe/datasource/core.py
mars/dataframe/datasource/read_csv.py
mars/dataframe/datasource/read_parquet.py
mars/dataframe/datasource/read_sql.py
mars/optimizes/tileable_graph/__init__.py
mars/optimizes/tileable_graph/column_pruning.py
mars/optimizes/tileable_graph/tests/test_column_pruning.py

[BACKPORT] Support column pruning for groupby().agg() on data sources (#1886)

---

mars/dataframe/core.py
mars/dataframe/datasource/index.py
mars/dataframe/initializer.py
mars/dataframe/sort/psrs.py
mars/dataframe/sort/tests/test_sort_execute.py
mars/tensor/base/tests/test_base_execute.py

[BACKPORT] Fix sorting string columns with None value & sorting with empty chunks (#1891)

---

mars/_version.py
mars/api.py
mars/context.py
mars/dataframe/initializer.py
mars/deploy/local/tests/test_cluster.py
mars/scheduler/graph.py
mars/scheduler/tests/integrated/test_normal_execution.py
mars/tensor/datasource/array.py
mars/tests/test_session.py
mars/web/apihandlers.py
mars/web/session.py
requirements-extra.txt

This PR improved `named_{dataframe, series, tensor}` that it's able to get more meta
Fixes #1894 .

Improve `named_{dataframe, series, tensor}` that it's able to get more meta

---

docs/source/locale/zh_CN/LC_MESSAGES/reference/dataframe/general_functions.po
docs/source/reference/dataframe/frame.rst
docs/source/reference/dataframe/general_functions.rst
mars/dataframe/__init__.py
mars/dataframe/base/__init__.py
mars/dataframe/base/eval.py
mars/dataframe/base/tests/test_base.py
mars/dataframe/base/tests/test_base_execution.py
mars/deploy/local/tests/test_cluster.py
mars/serialize/protos/operand.proto
mars/tests/integrated/base.py

Implements ``DataFrame.{eval,query}``.
Fixes #1219

Implements `DataFrame.{eval,query}`

---

docs/source/locale/zh_CN/LC_MESSAGES/reference/dataframe/general_functions.po
docs/source/reference/dataframe/frame.rst
docs/source/reference/dataframe/general_functions.rst
mars/dataframe/__init__.py
mars/dataframe/base/__init__.py
mars/dataframe/base/eval.py
mars/dataframe/base/tests/test_base.py
mars/dataframe/base/tests/test_base_execution.py
mars/deploy/local/tests/test_cluster.py
mars/serialize/protos/operand.proto
mars/tests/integrated/base.py

[BACKPORT] Implements `DataFrame.{eval,query}` (#1898)

---

docs/source/reference/dataframe/frame.rst
docs/source/reference/dataframe/series.rst
mars/dataframe/base/__init__.py
mars/dataframe/base/_duplicate.py
mars/dataframe/base/drop_duplicates.py
mars/dataframe/base/duplicated.py
mars/dataframe/base/tests/test_base_execution.py
mars/serialize/protos/operand.proto

This PR implements `{DataFrame, Series}.duplicated()`.
Resolves #1339 .

Implements `{DataFrame, Series}.duplicated()`

---

.github/workflows/platform-ci.yml
docs/source/reference/dataframe/frame.rst
docs/source/reference/dataframe/series.rst
mars/config.py
mars/context.py
mars/dataframe/base/__init__.py
mars/dataframe/base/_duplicate.py
mars/dataframe/base/drop_duplicates.py
mars/dataframe/base/duplicated.py
mars/dataframe/base/tests/test_base_execution.py
mars/dataframe/datastore/to_vineyard.py
mars/deploy/local/tests/test_cluster.py
mars/serialize/protos/operand.proto
mars/tensor/datastore/to_vineyard.py
mars/worker/storage/vineyardhandler.py

Backport of  #1907 and #1899 .

[BACKPORT] Implements `{DataFrame, Series}.duplicated()` (#1907)

---

mars/dataframe/base/rechunk.py
mars/dataframe/datastore/tests/test_datastore_execute.py
mars/dataframe/datastore/to_csv.py
mars/deploy/kubedl/client.py
mars/deploy/kubernetes/core.py
mars/learn/contrib/xgboost/tests/test_classifier.py
mars/tensor/rechunk/rechunk.py

[BACKPORT] Fix rechunk when input tileable has unknown shape (#1912)

---

mars/dataframe/reduction/core.py
mars/dataframe/utils.py

[BACKPORT] Optimize generating mock DataFrames (#1913)

---

CODEOWNERS
mars/dataframe/arithmetic/core.py
mars/dataframe/groupby/aggregation.py
mars/dataframe/groupby/cum.py
mars/dataframe/groupby/tests/test_groupby_execution.py
mars/dataframe/groupby/transform.py
mars/dataframe/missing/replace.py
mars/dataframe/statistics/quantile.py
mars/deploy/local/tests/test_cluster.py
mars/learn/neighbors/tree.py
mars/tensor/statistics/histogram.py
mars/tests/core.py
mars/utils.py

[BACKPORT] Fix KeyError when comparing series (#1920)

---

mars/oscar/api.py
mars/oscar/backend.py
mars/oscar/backends/mars/__init__.py
mars/oscar/backends/mars/backend.py
mars/oscar/backends/mars/driver.py
mars/oscar/backends/mars/pool.pyx
mars/oscar/context.pyx
mars/oscar/core.pyx
mars/oscar/driver.py

This PR added actor driver & did some structure adjustment.
NA

Add actor driver & structure adjustment

---

mars/learn/contrib/lightgbm/_train.py
mars/learn/utils/__init__.py
mars/learn/utils/collect_ports.py
mars/serialize/protos/operand.proto
mars/utils.py

Collect ports at workers before running LightGBM task.
Fixes #1917

Collect available ports before running LightGBM task

---

CODEOWNERS
mars/_version.py
mars/dataframe/base/rechunk.py
mars/dataframe/base/tests/test_base_execution.py
mars/dataframe/utils.py
mars/tensor/rechunk/rechunk.py

[BACKPORT] Fix rechunk when chunks have different dtypes that cannot compare (#1922)

---

mars/learn/contrib/lightgbm/_train.py
mars/learn/utils/__init__.py
mars/learn/utils/collect_ports.py
mars/serialize/protos/operand.proto
mars/utils.py

[BACKPORT] Collect available ports before running LightGBM task (#1924)

---

mars/deploy/kubedl/client.py
mars/deploy/kubedl/config.py
mars/optimizes/tileable_graph/core.py
mars/optimizes/tileable_graph/tests/test_head.py

[BACKPORT] Fix KeyError when column pruning is applied (#1929)

---

mars/learn/contrib/xgboost/start_tracker.py
mars/learn/contrib/xgboost/tests/integrated/test_distributed_xgboost.py
mars/learn/contrib/xgboost/train.py
mars/learn/model_selection/tests/integrated/__init__.py
mars/learn/model_selection/tests/integrated/test_distributed_split.py
mars/learn/utils/shuffle.py
mars/tests/integrated/base.py

Fix error when shuffling data in `mars.learn` module (#1931) and estimation of StartTracker for XGBoost (#1934)

---

mars/_utils.pyx
mars/lib/groupby_wrapper.py
mars/lib/tests/test_lib.py
mars/scheduler/operands/core.py
mars/serialization/__init__.py
mars/serialization/arrow.py
mars/serialization/core.py
mars/serialization/cuda.py
mars/serialization/mars_objects.py
mars/serialization/numpy.py
mars/serialization/scipy.py
mars/serialization/tests/__init__.py
mars/serialization/tests/test_serial.py
mars/tests/test_utils.py
mars/utils.py
requirements.txt

Add new implementation of serialization. Serializer now provides header and buffers to facilitate serialization in detail.

Add new serializer implementation

---

docs/source/reference/dataframe/indexing.rst
docs/source/reference/dataframe/series.rst
mars/dataframe/base/__init__.py
mars/dataframe/base/check_monotonic.py
mars/dataframe/base/tests/test_base_execution.py
mars/deploy/kubernetes/tests/test_kubernetes.py
mars/learn/contrib/lightgbm/classifier.py
mars/learn/contrib/lightgbm/ranker.py
mars/learn/contrib/lightgbm/regressor.py
mars/learn/contrib/utils.py
mars/learn/contrib/xgboost/classifier.py
mars/learn/contrib/xgboost/regressor.py
mars/serialize/protos/operand.proto

Add support for `{Series,Index}.{is_monotonic,is_monotonic_decreasing,is_monotonic_decreasing}`. To support more general functionality, `check_monotonic` is also added with `strict` option.
Fixes #1834

Implements is_monotonic properties

---

docs/source/reference/dataframe/indexing.rst
docs/source/reference/dataframe/series.rst
mars/dataframe/base/__init__.py
mars/dataframe/base/check_monotonic.py
mars/dataframe/base/tests/test_base_execution.py
mars/deploy/kubernetes/tests/test_kubernetes.py
mars/learn/contrib/lightgbm/classifier.py
mars/learn/contrib/lightgbm/ranker.py
mars/learn/contrib/lightgbm/regressor.py
mars/learn/contrib/utils.py
mars/learn/contrib/xgboost/classifier.py
mars/learn/contrib/xgboost/regressor.py
mars/serialize/protos/operand.proto

[BACKPORT] Implements `is_monotonic` properties (#1939)

---

mars/dataframe/core.py
mars/dataframe/tests/test_core.py
mars/learn/metrics/_check_targets.py
mars/learn/metrics/_classification.py
mars/learn/metrics/tests/integrated/test_ranking.py
mars/learn/utils/multiclass.py

This PR fixes `accuracy_score` for distributed execution.
Fixes #1943 .
Fixes #1840 .

Fix `accuracy_score` for distributed execution

---

mars/dataframe/core.py
mars/dataframe/tests/test_core.py
mars/learn/metrics/_check_targets.py
mars/learn/metrics/_classification.py
mars/learn/metrics/tests/integrated/test_ranking.py
mars/learn/utils/multiclass.py

[BACKPORT] Fix `accuracy_score` for distributed execution (#1945)

---

.github/workflows/cd.yml
.github/workflows/core-ci.yml
.github/workflows/install-conda.sh
.github/workflows/os-compat-ci.yml
mars/dataframe/datasource/date_range.py
mars/learn/metrics/pairwise/core.py
mars/lib/sparse/coo.py
mars/tensor/reduction/tests/test_reduction_execute.py
mars/tensor/statistics/cov.py
mars/tensor/statistics/tests/test_statistics_execute.py
requirements-wheel.txt

Add tests and releases for Python 3.9. Also fixes tests for numpy 1.20.0.
Fixes #1953

Add tests and releases for Python 3.9

---

.github/workflows/cd.yml
.github/workflows/core-ci.yml
.github/workflows/install-conda.sh
mars/dataframe/datasource/date_range.py
mars/learn/cluster/tests/test_k_means.py
mars/learn/metrics/pairwise/core.py
mars/lib/sparse/coo.py
mars/tensor/reduction/tests/test_reduction_execute.py
mars/tensor/statistics/cov.py
mars/tensor/statistics/tests/test_statistics_execute.py
requirements-wheel.txt

[BACKPORT] Add tests and releases for Python 3.9 (#1954)

---

docs/source/locale/zh_CN/LC_MESSAGES/user_guide/learn/lightgbm.po
docs/source/user_guide/learn/lightgbm.rst
mars/learn/contrib/lightgbm/core.py
mars/learn/contrib/lightgbm/tests/test_classifier.py
mars/learn/contrib/lightgbm/tests/test_ranker.py
mars/learn/contrib/lightgbm/tests/test_regressor.py

Allow wrapping existing models with Mars class constructors.

Allow wrapping existing models with Mars class constructors

---

docs/source/locale/zh_CN/LC_MESSAGES/user_guide/learn/lightgbm.po
docs/source/user_guide/learn/lightgbm.rst
mars/learn/contrib/lightgbm/core.py
mars/learn/contrib/lightgbm/tests/test_classifier.py
mars/learn/contrib/lightgbm/tests/test_ranker.py
mars/learn/contrib/lightgbm/tests/test_regressor.py
mars/scheduler/analyzer.py

[BACKPORT] Allow wrapping existing models with Mars class constructors (#1956)

---

mars/dataframe/base/describe.py
mars/dataframe/base/rechunk.py
mars/dataframe/base/tests/test_base_execution.py

[BACKPORT] Optimize performance of `DataFrame.describe()` (#1961)

---

.github/workflows/os-compat-ci.yml
.github/workflows/platform-ci.yml
.github/workflows/run-tests.sh
mars/learn/cluster/tests/test_k_means.py
mars/oscar/__init__.py
mars/oscar/backends/ray/tests/test_ray_actor_context.py
mars/oscar/core.pyx
mars/oscar/tests/test_local_context.py
mars/ray/tests/test_ray_execution.py
mars/tests/core.py

Fix actor promise calls. Coverage is also refined.

[oscar] Fix actor promise & add tests

---

mars/tensor/base/psrs.py
mars/tensor/base/tests/test_base_execute.py
mars/web/session.py

Fix the `IndexError` when sorting tensor with empty chunks.
Fixes #1960

Fix tensor sorting with empty chunks

---

mars/tensor/base/psrs.py
mars/tensor/base/tests/test_base_execute.py
mars/web/session.py

[BACKPORT] Fix tensor sorting with empty chunks (#1968)

---

mars/dataframe/base/rechunk.py
mars/dataframe/base/tests/test_base.py
mars/learn/contrib/xgboost/classifier.py
mars/learn/contrib/xgboost/predict.py
mars/learn/contrib/xgboost/regressor.py
mars/learn/contrib/xgboost/tests/test_train.py
mars/tensor/rechunk/rechunk.py

[BACKPORT] Fix `MarsDMatrix` when input tensor has unknown chunk shape (#1966)

---

mars/dataframe/indexing/__init__.py
mars/dataframe/indexing/iloc.py
mars/dataframe/indexing/index_lib.py
mars/dataframe/indexing/tests/test_indexing_execution.py
mars/dataframe/operands.py
mars/session.py
mars/web/session.py
mars/web/tests/test_api.py

Implements Index.\_\_getitem__ by copying code from Series.iloc. Also stop submitting empty graphs to services.
Fixes #1112

Implements Index.__getitem__

---

mars/dataframe/indexing/__init__.py
mars/dataframe/indexing/iloc.py
mars/dataframe/indexing/index_lib.py
mars/dataframe/indexing/tests/test_indexing_execution.py
mars/dataframe/operands.py
mars/session.py
mars/web/session.py
mars/web/tests/test_api.py

[BACKPORT] Implements Index.__getitem__ (#1971)

---

docs/source/reference/dataframe/frame.rst
docs/source/reference/dataframe/series.rst
mars/dataframe/base/map_chunk.py
mars/dataframe/base/tests/test_base_execution.py
mars/dataframe/indexing/__init__.py
mars/dataframe/indexing/sample.py
mars/dataframe/indexing/tests/test_indexing_execution.py
mars/learn/cluster/_k_means_init.py
mars/tensor/base/__init__.py
mars/tensor/base/map_chunk.py
mars/tensor/base/tests/test_base_execute.py
mars/tensor/random/__init__.py
mars/tensor/random/core.py

Implements {DataFrame,Series}.sample.
Fixes #1350

Implements {DataFrame,Series}.sample

---

.github/workflows/platform-ci.yml
docs/source/reference/dataframe/frame.rst
docs/source/reference/dataframe/series.rst
mars/dataframe/base/map_chunk.py
mars/dataframe/base/tests/test_base_execution.py
mars/dataframe/indexing/__init__.py
mars/dataframe/indexing/sample.py
mars/dataframe/indexing/tests/test_indexing_execution.py
mars/learn/cluster/_k_means_init.py
mars/tensor/base/__init__.py
mars/tensor/base/map_chunk.py
mars/tensor/base/tests/test_base_execute.py
mars/tensor/random/__init__.py
mars/tensor/random/core.py

[BACKPORT] Implements {DataFrame,Series}.sample (#1983)

---

mars/deploy/local/tests/test_cluster.py
mars/tensor/statistics/histogram.py
mars/worker/calc.py

[BACKPORT] Fix job hang when error message can't be pickled (#1990)

---

.codecov.yml
.coveragerc
.coveragerc-threaded
.github/codecov-upstream.yml
mars/storage/cuda.py
mars/storage/tests/test_libs.py

We will achieve a fully support for running on GPUs when reaches Mars 1.0, cuda storage backend is the first step for this goal.

[storage][cuda] Add cuda backend storage implementation

---

.github/workflows/platform-ci.yml
mars/storage/ray.py
mars/storage/tests/test_libs.py

Implement ray storage backend.
Fixes #1991

[storage][ray] Implements Ray storage

---

.github/workflows/platform-ci.yml
mars/ray/core.py
mars/ray/tests/test_ray_execution.py

[BACKPORT] Fix mars crashes on ray >= 1.2.0 (#1998)

---

mars/deploy/kubernetes/config.py
mars/deploy/kubernetes/core.py
mars/tensor/arithmetic/core.py
mars/tensor/base/copyto.py
mars/tensor/base/tests/test_base_execute.py
mars/tensor/base/where.py
mars/utils.py

[BACKPORT] Fix errors when calling where() on reshape results (#2011)

---

mars/_utils.pyx
mars/config.py
mars/deploy/kubedl/client.py
mars/deploy/kubedl/config.py
mars/learn/proxima/core.py
mars/learn/proxima/simple_index/builder.py
mars/learn/proxima/simple_index/searcher.py
mars/learn/proxima/simple_index/tests/integrated/test_distributed_simple_index.py
mars/scheduler/operands/common.py
mars/tensor/merge/concatenate.py
mars/worker/execution.py

[BACKPORT] Use mmap files to reduce memory usage in proxima builder (#1866)

---

mars/dataframe/datasource/from_tensor.py
mars/dataframe/datasource/tests/test_datasource_execution.py
mars/dataframe/indexing/reindex.py
mars/dataframe/indexing/setitem.py
mars/dataframe/indexing/tests/test_indexing_execution.py
mars/dataframe/initializer.py
mars/dataframe/tests/test_initializer.py
mars/dataframe/utils.py
mars/tensor/merge/stack.py
mars/tensor/merge/tests/test_merge_execute.py

This PR addresses a few issues:
1. Support setting column with different index for DataFrame
2. `md.DataFrame` can create with empty data.
3. `md.DataFrame` now supports creating from  a list of tileables.
Fixes #2018 .

Support setting column with different index for DataFrame

---

mars/custom_log.py
mars/oscar/backends/mars/tests/test_mars_actor_context.py
mars/scheduler/tests/integrated/test_normal_execution.py
mars/tests/test_utils.py

Fix log error when yielding to another remote.
Fixes #2021

Fix log error when yielding to another remote

---

mars/dataframe/datasource/from_tensor.py
mars/dataframe/datasource/tests/test_datasource_execution.py
mars/dataframe/indexing/reindex.py
mars/dataframe/indexing/setitem.py
mars/dataframe/indexing/tests/test_indexing_execution.py
mars/dataframe/initializer.py
mars/dataframe/tests/test_initializer.py
mars/dataframe/utils.py
mars/tensor/merge/stack.py
mars/tensor/merge/tests/test_merge_execute.py

[BACKPORT] Support setting column with different index for DataFrame (#2020)

---

mars/custom_log.py
mars/scheduler/tests/integrated/test_normal_execution.py

[BACKPORT] Fix log error when yielding to another remote (#2022)

---

mars/dataframe/arithmetic/tests/test_arithmetic.py
mars/optimizes/runtime/tests/test_compose.py
mars/scheduler/tests/test_analyzer.py
mars/tensor/__init__.py
mars/tensor/arithmetic/__init__.py
mars/tensor/arithmetic/add.py
mars/tensor/arithmetic/core.py
mars/tensor/arithmetic/multiply.py
mars/tensor/arithmetic/tests/test_arithmetic.py
mars/tensor/arithmetic/tests/test_arithmetic_execution.py
mars/tensor/arithmetic/utils.py
mars/tensor/einsum/core.py
mars/tensor/linalg/lu.py
mars/tensor/linalg/matmul.py
mars/tensor/linalg/solve_triangular.py
mars/tensor/linalg/tensordot.py
mars/tensor/reduction/core.py
mars/tensor/special/core.py
mars/tensor/statistics/histogram.py
mars/tests/test_executor.py
mars/worker/tests/test_calc.py

[BACKPORT] Implements tree arithmetic for tensor add and multiplication (#2024)

---

mars/dataframe/reduction/tests/test_reduction_execute.py
mars/oscar/backends/mars/communication/socket.py
mars/oscar/backends/mars/communication/tests/test_comm.py
mars/oscar/backends/mars/communication/utils.py
mars/oscar/backends/mars/context.py
mars/oscar/backends/mars/core.py
mars/oscar/backends/mars/tests/test_pool.py
mars/oscar/core.pyx
mars/serialization/aio.py
mars/storage/cuda.py
mars/storage/tests/test_libs.py

Add serialize and deserialize utils for cuda buffers as they need to be copied to host in actor calls.

Support cuda buffer serializations in actor communication

---

mars/oscar/backends/mars/communication/tests/test_comm.py
mars/oscar/backends/mars/communication/utils.py
mars/oscar/backends/mars/tests/test_mars_actor_context.py
mars/oscar/core.pyx

Fix cancellation on actor promises by handling `asyncio.CancelledError`. Also fixes import issues for communication backend.

Fix cancelling actor promises

---

.github/workflows/core-ci.yml
.github/workflows/os-compat-ci.yml
.github/workflows/platform-ci.yml
mars/deploy/kubedl/client.py
mars/deploy/kubernetes/core.py

Support reusing cluster by specify job name.

Support reusing kubedl cluster by job name

---

mars/core.py
mars/dataframe/core.py
mars/services/meta/__init__.py
mars/services/meta/api.py
mars/services/meta/core.py
mars/services/meta/store/__init__.py
mars/services/meta/store/base.py
mars/services/meta/store/mock.py
mars/services/meta/store/tests/__init__.py
mars/services/meta/store/tests/test_meta_store.py
mars/services/meta/tests/__init__.py
mars/services/meta/tests/test_api.py
mars/tensor/core.py

This PR initialized meta service with mock support
NA

Initialize meta service with mock support

---

mars/oscar/__init__.py
mars/oscar/api.py
mars/oscar/backends/mars/driver.py
mars/oscar/backends/ray/context.pyx
mars/oscar/backends/ray/driver.py
mars/oscar/backends/ray/tests/test_ray_actor_context.py
mars/oscar/backends/ray/tests/test_ray_actor_driver.py
mars/oscar/backends/ray/utils.py
mars/oscar/driver.py

Create a placement group in `setup_cluster` and create actor in placement group by address.
Closes https://github.com/mars-project/mars/issues/2017

[Ray backend] setup_cluster use placement group

---

mars/tensor/base/insert.py
mars/tensor/base/tests/test_base_execute.py

[BACKPORT] Fix wrong results of `mt.insert` (#2046)

---

mars/deploy/kubedl/client.py
mars/tensor/base/insert.py
mars/tensor/base/tests/test_base_execute.py

Fix for `mt.insert` and small changes in deploy for kubedl.

Fix for `mt.insert` when insert values is a mars tensor

---

mars/deploy/kubedl/client.py
mars/tensor/base/insert.py
mars/tensor/base/tests/test_base_execute.py

[BACKPORT] Fix for `mt.insert` when insert values is a mars tensor (#2052)

---

mars/oscar/backends/ray/tests/test_ray_actor_driver.py

Fix ray cluster_utils import on ray 2.0.

[Ray] Fix ray cluster_utils import

---

mars/_version.py

Bump version to 0.6.7

---

mars/oscar/backends/mars/pool.py
mars/oscar/backends/mars/tests/test_pool.py
mars/services/meta/api.py
mars/services/meta/core.py
mars/services/meta/store/base.py
mars/services/meta/store/dictionary.py
mars/services/meta/store/tests/test_meta_store.py
mars/services/meta/supervisor/__init__.py
mars/services/meta/supervisor/core.py
mars/services/meta/supervisor/service.py
mars/services/meta/tests/test_service.py
mars/services/storage/api.py

This PR enhances meta service.

Enhance meta service

---

mars/oscar/backends/mars/pool.py
mars/oscar/backends/mars/tests/test_pool.py
mars/services/storage/api.py
mars/services/storage/core.py
mars/services/storage/tests/__init__.py
mars/services/storage/tests/test_api.py
mars/services/storage/tests/test_service.py
mars/services/storage/worker/__init__.py
mars/services/storage/worker/service.py
mars/storage/base.py
mars/storage/cuda.py
mars/storage/filesystem.py
mars/storage/plasma.py
mars/storage/ray.py
mars/storage/shared_memory.py
mars/storage/vineyard.py

Initial implementation for storage service with the basic `put` and `get` method.

Initial implementation for storage service

---

mars/services/cluster/gather.py
mars/services/cluster/tests/test_gather.py
mars/services/meta/api.py
mars/services/meta/core.py
mars/services/meta/store/base.py
mars/services/meta/store/dictionary.py
mars/services/meta/tests/test_api.py

Add bands to chunk meta

---

mars/oscar/backends/mars/tests/test_mars_actor_context.py
mars/oscar/core.pyx
mars/services/cluster/api.py
mars/tests/test_utils.py
mars/utils.py

This PR tries to enrich usage experience for extensible function
Below is the example
```python
from mars.utils import extensible
class MyWriter:
@extensible
def write_line(self, name, line):
with open(name, 'w') as f:
f.write(line)
@write_line.batch
def write_line(self, args_list, kwargs_list):
name = args_list[0][0]
with open(name, 'w') as f:
for arg in args_list:
line = arg[1]
f.write(line)
name = 'my_file'
with open('my_file', 'w') as f:
f.write('')
data = ['s' * 1000 + '\n'] * 1000
writer = MyWriter()
%%time
for line in data:
writer.write_line(name, line)
%%time
writer.write_line.batch(
*(writer.write_line.delay(name, line) for line in data))
```

Enrich usage experience for extensible function

---

.github/workflows/core-ci.yml
mars/services/cluster/api.py
mars/services/meta/core.py
mars/services/storage/__init__.py
mars/services/storage/api.py
mars/services/storage/core.py
mars/services/storage/tests/test_api.py
mars/services/tests/test_utils.py
mars/services/utils.py
mars/storage/base.py
mars/storage/plasma.py
mars/storage/tests/test_libs.py
mars/utils.py

Add API interface to get data info. Turn data classes into slot classes as well.

Add API interface to get data info

---

mars/worker/storage/vineyardhandler.py

Add a log to `delete` as well to find out what happens when failed.
Fixes the failure in CI: https://github.com/mars-project/mars/runs/2233774757?check_suite_focus=true

Use a ref count to make delete works when multiple workers connect to the same vineyardd

---

mars/worker/storage/vineyardhandler.py

[BACKPORT] Use a ref count to make delete works when multiple workers connect to the same vineyard (#2077)

---

.github/workflows/install-hadoop.sh
mars/tensor/__init__.py
mars/tensor/merge/__init__.py
mars/tensor/merge/block.py
mars/tensor/merge/tests/test_merge_execute.py

Implement `mars.tensor.block`.
Closes https://github.com/mars-project/mars/issues/569

Implements `mt.block`

---

.github/workflows/install-hadoop.sh
mars/tensor/__init__.py
mars/tensor/merge/__init__.py
mars/tensor/merge/block.py
mars/tensor/merge/tests/test_merge_execute.py

[BACKPORT] Implements `mt.block` (#2069)

---

.github/workflows/cancel-prev.yml

This PR enables cancelling previous runs on PRs and commits.

Allow cancelling flows automatically

---

.github/workflows/cancel-prev.yml
mars/_version.py

[Skip CI] Bump version to v0.6.8

---

.codecov.yml
.coveragerc
.coveragerc-threaded
.github/ISSUE_TEMPLATE/bug_report.md
.github/codecov-upstream.yml
.github/workflows/upload-packages.sh
LICENSE
conda-spec.txt
docs/source/development/contributing.rst
docs/source/locale/zh_CN/LC_MESSAGES/development/contributing.po
mars/deploy/kubernetes/docker/Dockerfile.base
requirements-dev.txt
requirements-extra.txt
requirements-wheel.txt

Remove protobuf dependencies in all files.

Remove protobuf dependency

---

mars/dataframe/datasource/core.py
mars/dataframe/datasource/read_csv.py
mars/dataframe/datasource/read_parquet.py
mars/dataframe/datasource/read_sql.py
mars/learn/datasets/tests/integrated/__init__.py
mars/learn/datasets/tests/integrated/test_distributed_samples_generator.py
mars/learn/decomposition/_pca.py
mars/learn/utils/shuffle.py
mars/optimizes/runtime/dataframe.py
mars/optimizes/tileable_graph/tests/test_column_pruning.py

[BACKPORT] Fix distributed `make_blobs` and column pruning in `read_sql` (#2092)

---

mars/deploy/oscar/local.py
mars/deploy/oscar/service.py
mars/deploy/oscar/tests/test_local.py
mars/services/__init__.py
mars/services/cluster/api.py
mars/services/cluster/supervisor/node_info.py
mars/services/cluster/uploader.py
mars/services/core.py
mars/services/meta/api.py
mars/services/meta/core.py
mars/services/meta/store/base.py
mars/services/meta/store/dictionary.py
mars/services/storage/__init__.py
mars/services/storage/api.py
mars/services/storage/core.py
mars/services/storage/errors.py
mars/services/storage/supervisor/__init__.py
mars/services/storage/tests/test_api.py
mars/services/storage/worker/__init__.py
mars/services/storage/worker/service.py
mars/services/task/analyzer/analyzer.py
mars/services/task/analyzer/assigner.py
mars/services/task/core.py
mars/services/task/supervisor/task_manager.py
mars/services/task/supervisor/tests/test_task_manager.py
mars/services/task/tests/test_service.py
mars/services/task/worker/subtask.py
mars/services/task/worker/tests/test_subtask.py
mars/storage/shared_memory.py

Hold data reference in DataManager to avoid be released by storage like Plasma.

Hold data ref in DataManager

---

mars/config.py
mars/core/graph/builder/chunk.py
mars/core/session.py
mars/deploy/oscar/config.yml
mars/deploy/oscar/local.py
mars/deploy/oscar/session.py
mars/deploy/oscar/tests/check_enabled_config.yml
mars/deploy/oscar/tests/local_test_config.yml
mars/deploy/oscar/tests/session.py
mars/deploy/oscar/tests/test_checked_session.py
mars/deploy/oscar/tests/test_local.py
mars/deploy/oscar/typing.py
mars/oscar/backends/router.py
mars/services/task/__init__.py
mars/services/task/analyzer/analyzer.py
mars/services/task/api.py
mars/services/task/core.py
mars/services/task/supervisor/service.py
mars/services/task/supervisor/task_manager.py
mars/services/task/supervisor/tests/task_processor.py
mars/services/task/supervisor/tests/test_task_manager.py
mars/services/task/tests/core.py
mars/services/task/worker/service.py
mars/services/task/worker/subtask.py
mars/services/task/worker/tests/__init__.py
mars/services/task/worker/tests/subtask_processor.py
mars/services/task/worker/tests/test_subtask.py
mars/tests/core.py

This pr integrated mars object check for session.
NA

Integrate mars object check for session

---

mars/__init__.py
mars/core/session.py
mars/storage/__init__.py

This PR wraps sync method in session so that they will be running in threads.
Fixes #2108 .

Wrap sync method in session so that they will be running in threads

---

.github/workflows/os-compat-ci.yml
.github/workflows/platform-ci.yml
mars/dataframe/datasource/tests/test_datasource_execution.py
mars/oscar/backends/communication/socket.py
mars/oscar/backends/mars/tests/test_pool.py
mars/storage/plasma.py
mars/storage/shared_memory.py
mars/storage/tests/test_libs.py

This PR resolves 3 problems:
1. Fix shared memory usage in Windows
2. Fix oscar cases in Windows
3. Add references for plasma reader & writer

Fix pool cases and shared memory cases in Windows

---

mars/utils.py

fix `mars.utils._get_ports_from_netstat` hang
closes #2115

Fix `_get_ports_from_netstat` hang

---

.codecov.yml
.coveragerc
.coveragerc-threaded
.github/workflows/os-compat-ci.yml
.github/workflows/platform-ci.yml
mars/deploy/oscar/ray.py
mars/oscar/backends/mars/tests/test_pool.py
mars/oscar/backends/pool.py
mars/oscar/backends/ray/communication.py
mars/oscar/backends/ray/pool.py
mars/oscar/backends/ray/tests/test_communication.py
mars/oscar/backends/ray/tests/test_ray_pool.py
mars/tests/core.py

Support ray subprocess covarage 
https://github.com/ray-project/ray/issues/15437
#2112

[Ray] Support ray subprocess covarage

---

mars/config.py
mars/oscar/backends/ray/tests/test_ray_pool.py
mars/services/storage/tests/test_api.py
mars/services/task/supervisor/tests/test_task_manager_on_ray.py
mars/services/web/worker.py
mars/storage/ray.py
mars/storage/tests/test_libs.py
mars/tests/conftest.py
mars/tests/test_config.py

Unpickle mars config will raises `RecursionError: maximum recursion depth exceeded`.
Closes https://github.com/mars-project/mars/issues/2129

Fix unpickle mars config error

---

mars/deploy/oscar/config.yml
mars/deploy/oscar/pool.py
mars/deploy/oscar/rayconfig.yml
mars/deploy/oscar/tests/check_enabled_config.yml
mars/deploy/oscar/tests/local_test_config.yml
mars/deploy/oscar/tests/test_local.py
mars/deploy/oscar/tests/test_ray.py
mars/oscar/backends/mars/backend.py
mars/oscar/backends/mars/tests/test_mars_actor_context.py
mars/oscar/backends/ray/backend.py
mars/oscar/core.pyx
mars/serialization/core.py
mars/services/session/supervisor/core.py
mars/services/storage/api/oscar.py
mars/services/storage/core.py
mars/services/storage/errors.py
mars/services/storage/tests/test_api.py
mars/services/storage/tests/test_service.py
mars/services/storage/tests/test_transfer.py
mars/services/storage/transfer.py
mars/services/storage/worker/service.py
mars/services/task/supervisor/tests/test_task_manager.py
mars/services/task/tests/test_service.py
mars/services/task/worker/subtask.py
mars/services/task/worker/tests/test_subtask.py
mars/storage/base.py
mars/storage/plasma.py
mars/storage/ray.py
mars/storage/shared_memory.py
mars/storage/tests/test_libs.py

Support data transfer for storage service

Add transfer support for storage service

---

docs/source/reference/dataframe/frame.rst
docs/source/reference/dataframe/series.rst
mars/dataframe/indexing/__init__.py
mars/dataframe/indexing/add_prefix.py
mars/dataframe/indexing/tests/test_indexing_execution.py
mars/serialize/dataserializer.py

[BACKPORT] Add `add_prefix` support (#2132)

---

azure-pipelines.yml

Filter pipeline jobs by branch.

Filter pipeline jobs by branch

---

azure-pipelines.yml

Configure azure pipelines job timeout

Configure azure pipelines job timeout

---

mars/_version.py

[Skip CI] Bump version to v0.6.9

---

mars/oscar/backends/mars/tests/test_pool.py
mars/oscar/backends/pool.py

This PR fixes race condition when creating actors with IdleLabel strategy in a parallel way.
Fixes #2142 .

Fix race condition when creating actors with IdleLabel strategy in a parallel way

---

mars/deploy/oscar/tests/test_local.py
mars/deploy/oscar/tests/test_ray.py
mars/services/storage/api/oscar.py
mars/services/storage/core.py
mars/services/task/supervisor/task_manager.py
mars/services/task/supervisor/tests/test_task_manager.py

For shuffle task, we decref mapper chunks when shuffle proxy finishes, it leads to `KeyError` as reducer chunks depends on mapper chunks. This PR fixes by incref mapper chunks when processing reducers.
Fixes #2145

Fix shuffle task on oscar

---

mars/dataframe/base/tests/test_base.py
mars/dataframe/core.py

I re-implemented {DataFrame, Series}.empty and add related test cases.
Issue #1830 should be resolved

Implement {DataFrame, Series}.empty

---

mars/oscar/__init__.py
mars/oscar/backends/context.py
mars/oscar/backends/mars/pool.py
mars/oscar/backends/mars/tests/test_debug.py
mars/oscar/core.pyx
mars/oscar/debug.py

Add options for debug messages for oscar.

Add debug options for oscar

---

azure-pipelines.yml
mars/learn/contrib/tensorflow/run_script.py
mars/learn/utils/collect_ports.py
mars/tensor/arithmetic/tests/test_arithmetic_execution.py

This PR tries to collect available ports before running tensorflow scripts.
NA

Collects available ports before running tensorflow scripts

---

mars/deploy/kubernetes/client.py
mars/deploy/kubernetes/config.yml
mars/deploy/kubernetes/core.py
mars/deploy/oscar/cmdline.py
mars/deploy/oscar/local.py
mars/deploy/oscar/supervisor.py
mars/deploy/oscar/worker.py
mars/oscar/__init__.py
mars/oscar/backends/communication/socket.py
mars/oscar/backends/context.py
mars/oscar/backends/mars/tests/test_debug.py
mars/oscar/backends/mars/tests/test_mars_actor_context.py
mars/oscar/backends/message.py
mars/oscar/backends/pool.py
mars/oscar/core.pyx
mars/oscar/debug.py
mars/services/cluster/api/web.py
mars/services/scheduling/worker/execution.py
mars/services/web/api/web.py
mars/services/web/supervisor.py
mars/services/web/tests/extra_handler.py
mars/services/web/tests/test_core.py
mars/storage/shared_memory.py
mars/tensor/linalg/tests/test_linalg_execute.py
setup.cfg

Add cycle detection for oscar debug mode. Also silent messages when pools closed.
Fixes #1785

Add cycle detection for oscar debug mode

---

mars/_version.py
mars/dataframe/base/tests/test_base.py
mars/dataframe/core.py
mars/utils.py

[BACKPORT] Implement {DataFrame, Series}.empty (#2155)

---

mars/deploy/oscar/config.yml
mars/lib/filesystem/core.py
mars/oscar/backends/pool.py
mars/services/storage/api/oscar.py
mars/services/storage/core.py
mars/services/storage/spill.py
mars/services/storage/tests/test_spill.py
mars/services/storage/tests/test_transfer.py
mars/services/storage/transfer.py
mars/services/subtask/worker/processor.py
mars/storage/base.py
mars/storage/core.py
mars/storage/cuda.py
mars/storage/errors.py
mars/storage/filesystem.py
mars/storage/plasma.py
mars/storage/ray.py
mars/storage/shared_memory.py
mars/storage/tests/test_base.py
mars/storage/vineyard.py
mars/utils.py

Add spill support for storage service.

Add spill support for oscar

---

mars/dataframe/groupby/aggregation.py
mars/dataframe/groupby/tests/test_groupby_execution.py
mars/dataframe/reduction/core.py
mars/dataframe/reduction/tests/test_reduction.py

[BACKPORT] Fix unexpected NaNs in groupby-agg (#2177)

---

LICENSE
conda-spec.txt
mars/services/cluster/api/web.py
mars/services/lifecycle/api/web.py
mars/services/meta/api/web.py
mars/services/session/api/web.py
mars/services/storage/api/web.py
mars/services/task/api/web.py
mars/services/web/core.py
mars/services/web/tests/test_core.py
setup.cfg

Use `aiohttp` to make requests instead of tornado.
Solve part of #2182

Use `aiohttp` to handle web requests

---

mars/_version.py
mars/dataframe/base/drop_duplicates.py
mars/dataframe/base/duplicated.py
mars/dataframe/groupby/core.py
mars/dataframe/groupby/tests/test_groupby_execution.py
mars/dataframe/merge/merge.py
mars/dataframe/utils.py

[BACKPORT] Fix groupby on indexes with duplicate items (#2186)

---

.github/workflows/core-ci.yml
mars/dataframe/indexing/iloc.py
mars/services/scheduling/worker/workerslot.py
mars/tests/core.py

Fix import error in master branch

Fix import error in master branch

---

mars/services/storage/api/web.py
mars/services/task/api/web.py
mars/services/task/tests/test_service.py
mars/services/web/ui/src/Utils.js
mars/services/web/ui/src/task_info/TaskListPage.js

Fix deserializing task errors on web clients. Also fix frontend status display.

Fix deserializing task errors on web clients

---

.github/workflows/platform-ci.yml
mars/dataframe/window/ewm/core.py
mars/dataframe/window/expanding/core.py
mars/dataframe/window/rolling/core.py

Make window function under old pandas versions work.

Make window function under old pandas versions work

---

.github/workflows/install-hadoop.sh
.github/workflows/platform-ci.yml
docs/source/development/contributing.rst
docs/source/installation/yarn.rst
mars/dataframe/arrays.py
mars/dataframe/base/astype.py
mars/dataframe/base/shift.py
mars/dataframe/base/transform.py
mars/dataframe/base/value_counts.py
mars/dataframe/groupby/aggregation.py
mars/dataframe/groupby/apply.py
mars/dataframe/groupby/core.py
mars/dataframe/groupby/getitem.py
mars/dataframe/groupby/transform.py
mars/dataframe/indexing/iloc.py
mars/dataframe/indexing/loc.py
mars/dataframe/reduction/aggregation.py
mars/dataframe/reduction/tests/test_reduction_execute.py
mars/dataframe/statistics/quantile.py
mars/dataframe/tests/test_arrays.py
mars/dataframe/utils.py
mars/dataframe/window/ewm/core.py
mars/dataframe/window/expanding/core.py
mars/dataframe/window/rolling/core.py
mars/lib/groupby_wrapper.py
mars/tests/core.py

[BACKPORT] Fix compatibility issue for pandas 1.3 (#2197)

---

mars/dataframe/sort/tests/test_sort_execute.py
mars/dataframe/tests/test_utils.py
mars/dataframe/utils.py
mars/services/scheduling/supervisor/assigner.py

Fix concatenating row chunks with MultiIndex.

Fix concatenating row chunks with MultiIndex

---

mars/dataframe/tests/test_utils.py
mars/dataframe/utils.py

[BACKPORT] Fix merge_index_value when index_values come from multi range indexes (#2207)

---

.github/workflows/os-compat-ci.yml
mars/__init__.py
mars/_version.py
mars/dataframe/base/tests/test_base_execution.py
mars/dataframe/groupby/aggregation.py
mars/dataframe/groupby/tests/test_groupby_execution.py
mars/dataframe/reduction/all.py
mars/dataframe/reduction/any.py
mars/dataframe/reduction/core.py
mars/dataframe/reduction/count.py
mars/dataframe/reduction/custom_reduction.py
mars/dataframe/reduction/kurtosis.py
mars/dataframe/reduction/max.py
mars/dataframe/reduction/mean.py
mars/dataframe/reduction/min.py
mars/dataframe/reduction/prod.py
mars/dataframe/reduction/sem.py
mars/dataframe/reduction/skew.py
mars/dataframe/reduction/std.py
mars/dataframe/reduction/sum.py
mars/dataframe/reduction/tests/test_reduction_execute.py
mars/dataframe/reduction/unique.py
mars/dataframe/reduction/var.py
mars/optimization/logical/tileable/tests/test_head.py

This PR added support for choosing aggregation algorithm at runtime.
Resolves #2215 .

Support choosing aggregation algorithm at runtime

---

mars/oscar/__init__.py
mars/oscar/api.py
mars/oscar/backends/context.py
mars/oscar/backends/mars/tests/test_mars_actor_context.py
mars/oscar/backends/mars/tests/test_pool.py
mars/oscar/backends/message.py
mars/oscar/backends/pool.py
mars/oscar/context.pyx
mars/oscar/core.pxd
mars/oscar/core.pyx
mars/services/cluster/api/oscar.py
mars/services/cluster/tests/test_uploader.py
mars/services/cluster/uploader.py
mars/services/scheduling/worker/workerslot.py
mars/tests/test_session.py

[BACKPORT] Add support for stateless actors (#2218)

---

azure-pipelines.yml
mars/dataframe/groupby/aggregation.py
mars/dataframe/groupby/tests/test_groupby_execution.py
mars/deploy/oscar/cmdline.py
mars/deploy/oscar/supervisor.py
mars/deploy/oscar/worker.py
mars/oscar/backends/config.py
mars/oscar/backends/mars/pool.py
mars/oscar/backends/mars/tests/test-logging.conf
mars/oscar/backends/mars/tests/test_pool.py
mars/oscar/backends/pool.py
mars/tests/core.py

[BACKPORT] Pass logging config file name into sub pools (#2222)

---

mars/services/scheduling/worker/tests/test_execution.py
mars/services/storage/api/oscar.py
mars/services/storage/core.py
mars/services/storage/errors.py
mars/services/storage/handler.py
mars/services/storage/spill.py
mars/services/storage/tests/test_spill.py
mars/services/storage/tests/test_transfer.py
mars/services/storage/transfer.py
mars/services/subtask/worker/processor.py
mars/storage/core.py

[BACKPORT] Fix `NoDataToSpill` when multiple storage quota requests happen simultaneously (#2203)

---

.github/workflows/os-compat-ci.yml
mars/__init__.py
mars/_version.py
mars/dataframe/base/tests/test_base_execution.py
mars/dataframe/groupby/aggregation.py
mars/dataframe/groupby/tests/test_groupby_execution.py
mars/dataframe/reduction/all.py
mars/dataframe/reduction/any.py
mars/dataframe/reduction/core.py
mars/dataframe/reduction/count.py
mars/dataframe/reduction/custom_reduction.py
mars/dataframe/reduction/kurtosis.py
mars/dataframe/reduction/max.py
mars/dataframe/reduction/mean.py
mars/dataframe/reduction/min.py
mars/dataframe/reduction/prod.py
mars/dataframe/reduction/sem.py
mars/dataframe/reduction/skew.py
mars/dataframe/reduction/std.py
mars/dataframe/reduction/sum.py
mars/dataframe/reduction/tests/test_reduction_execute.py
mars/dataframe/reduction/unique.py
mars/dataframe/reduction/var.py
mars/optimization/logical/tileable/tests/test_head.py

[BACKPORT] Support choosing aggregation algorithm at runtime (#2213)

---

mars/core/__init__.py
mars/core/entity/__init__.py
mars/core/entity/tileables.py
mars/core/operand/core.py
mars/dataframe/base/tests/test_base_execution.py
mars/deploy/oscar/session.py
mars/services/subtask/worker/processor.py
mars/services/task/supervisor/preprocessor.py
mars/services/task/supervisor/tests/task_preprocessor.py

Since isolation exists, it's hard to store local session in a thread local variable. 
NA

Stop using thread local to store default session.

---

azure-pipelines.yml
mars/deploy/oscar/local.py
mars/deploy/oscar/session.py
mars/deploy/oscar/tests/test_local.py
mars/services/session/supervisor/core.py
mars/services/storage/api/oscar.py
mars/services/storage/core.py
mars/services/storage/handler.py
mars/services/subtask/worker/processor.py
mars/services/subtask/worker/tests/subtask_processor.py
mars/services/task/supervisor/processor.py
mars/storage/core.py
mars/tests/core.py

This PR added `get_storage_level_info` api.
NA

Add get_storage_level_info api

---

mars/deploy/oscar/local.py
mars/deploy/oscar/session.py
mars/deploy/oscar/tests/test_local.py

[BACKPORT] Add method to session to get web endpoint (#2236)

---

mars/dataframe/datasource/core.py
mars/services/cluster/api/core.py
mars/services/cluster/api/oscar.py
mars/services/cluster/api/web.py
mars/services/cluster/supervisor/node_info.py
mars/services/cluster/uploader.py
mars/services/core.py
mars/services/meta/api/oscar.py
mars/services/meta/core.py
mars/services/meta/store/base.py
mars/services/meta/store/dictionary.py
mars/services/scheduling/supervisor/globalslot.py
mars/services/scheduling/supervisor/manager.py
mars/services/scheduling/supervisor/tests/test_assigner.py
mars/services/scheduling/supervisor/tests/test_manager.py
mars/services/scheduling/supervisor/tests/test_queue_balance.py
mars/services/scheduling/worker/quota.py
mars/services/scheduling/worker/workerslot.py
mars/services/subtask/core.py
mars/services/subtask/worker/processor.py
mars/services/subtask/worker/runner.py
mars/services/task/analyzer/analyzer.py
mars/services/task/analyzer/assigner.py
mars/services/task/supervisor/preprocessor.py
mars/services/task/supervisor/processor.py
mars/services/task/supervisor/stage.py
mars/services/task/supervisor/tests/task_preprocessor.py
mars/tensor/datastore/to_hdf5.py

This PR fixes possible CI failure when destroying remote object for incremental index.

Fix possible CI failure when destroying remote object for incremental index

---

mars/core/entity/executable.py
mars/deploy/oscar/local.py
mars/deploy/oscar/session.py
mars/deploy/oscar/tests/test_local.py
mars/services/session/supervisor/core.py
mars/services/storage/api/oscar.py
mars/services/storage/core.py
mars/services/storage/handler.py
mars/services/subtask/worker/processor.py
mars/services/subtask/worker/tests/subtask_processor.py
mars/services/task/supervisor/processor.py
mars/storage/core.py
mars/tensor/datastore/to_hdf5.py
mars/tests/core.py

[BACKPORT] Add get_storage_level_info api (#2228)

---

mars/core/__init__.py
mars/core/entity/__init__.py
mars/core/entity/tileables.py
mars/core/operand/core.py
mars/dataframe/base/tests/test_base_execution.py
mars/deploy/oscar/session.py
mars/services/subtask/worker/processor.py
mars/services/task/supervisor/preprocessor.py
mars/services/task/supervisor/tests/task_preprocessor.py

[BACKPORT] Stop using thread local to store default session (#2217)

---

mars/lib/filesystem/arrow.py
mars/storage/core.py
mars/storage/shared_memory.py
mars/storage/tests/test_libs.py

Add support for seek method in memory cases.
Fixes #2249

Add support for `seek` method in memory cases

---

mars/oscar/backends/pool.py
mars/oscar/backends/ray/communication.py
mars/oscar/core.pyx
mars/oscar/debug.py

Refine oscar debugging so that we can locate hang issues more easily.

Refine oscar debugging

---

mars/deploy/oscar/tests/test_local.py
mars/services/meta/api/oscar.py
mars/services/subtask/worker/processor.py
mars/services/task/supervisor/processor.py

[BACKPORT] Record mapper meta for shuffle task (#2248)

---

mars/oscar/backends/pool.py
mars/oscar/backends/ray/communication.py
mars/oscar/core.pyx
mars/oscar/debug.py

[BACKPORT] Refine oscar debugging (#2252)

---

mars/dataframe/groupby/tests/test_groupby_execution.py
mars/deploy/oscar/tests/local_test_with_ray_config.yml
mars/deploy/oscar/tests/test_local.py
mars/deploy/oscar/tests/test_ray.py
mars/services/session/api/core.py
mars/services/session/api/web.py

[BACKPORT] Support `fetch_log` for web session (#2257)

---

mars/lib/filesystem/arrow.py
mars/storage/core.py
mars/storage/shared_memory.py
mars/storage/tests/test_libs.py

[BACKPORT] Add support for `seek` method in memory cases (#2250)

---

mars/lib/sparse/__init__.py
mars/lib/sparse/array.py
mars/tensor/special/__init__.py
mars/tensor/special/bessel.py
mars/tensor/special/tests/test_special_execute.py

[BACKPORT] Add partial support of bessel functions (#2258)

---

mars/dataframe/base/apply.py
mars/deploy/oscar/tests/test_cmdline.py
mars/services/cluster/uploader.py
mars/services/scheduling/worker/execution.py
mars/services/scheduling/worker/quota.py
mars/services/scheduling/worker/service.py
mars/services/scheduling/worker/tests/test_execution.py
mars/services/scheduling/worker/tests/test_quota.py
mars/services/task/supervisor/stage.py

Add an option in scheduling service to suspend pool killing on task cancel.
Fixes #2272

Allow turning off actor killing

---

mars/dataframe/base/apply.py
mars/deploy/oscar/tests/test_cmdline.py
mars/services/cluster/uploader.py
mars/services/scheduling/worker/execution.py
mars/services/scheduling/worker/quota.py
mars/services/scheduling/worker/service.py
mars/services/scheduling/worker/tests/test_execution.py
mars/services/scheduling/worker/tests/test_quota.py
mars/services/task/supervisor/stage.py

[BACKPORT] Allow turning off actor killing (#2273)

---

mars/core/base.py
mars/deploy/oscar/tests/test_fault_injection.py
mars/oscar/backends/communication/errors.py
mars/oscar/errors.py
mars/services/scheduling/errors.py
mars/services/scheduling/supervisor/assigner.py
mars/services/scheduling/supervisor/tests/test_assigner.py
mars/services/storage/errors.py
mars/services/subtask/worker/tests/subtask_processor.py
mars/services/task/errors.py
mars/services/tests/fault_injection_manager.py
mars/storage/errors.py

Assign bands according to its device.
Fixes #2275

Assign bands given devices of subtasks

---

mars/oscar/backends/mars/pool.py
mars/services/meta/api/oscar.py
mars/services/scheduling/worker/tests/test_execution.py
mars/services/storage/api/oscar.py
mars/services/storage/core.py
mars/services/storage/handler.py
mars/services/storage/spill.py
mars/services/storage/tests/test_api.py
mars/services/storage/tests/test_spill.py
mars/services/storage/tests/test_transfer.py
mars/services/storage/transfer.py

[BACKPORT] Use batch method to reduce transferring cost for shuffle tasks (#2233)

---

mars/core/base.py
mars/oscar/backends/communication/errors.py
mars/oscar/errors.py
mars/services/scheduling/errors.py
mars/services/scheduling/supervisor/assigner.py
mars/services/scheduling/supervisor/tests/test_assigner.py
mars/services/storage/errors.py
mars/services/task/errors.py
mars/storage/errors.py

[BACKPORT] Assign bands given devices of subtasks (#2276)

---

docs/source/conf.py
mars/core/operand/core.py
mars/dataframe/indexing/getitem.py
mars/dataframe/indexing/setitem.py
mars/learn/contrib/utils.py
mars/oscar/backends/communication/utils.py
mars/oscar/backends/message.py
mars/services/scheduling/supervisor/queueing.py
mars/services/scheduling/worker/execution.py
mars/services/scheduling/worker/quota.py
mars/services/scheduling/worker/tests/test_execution.py
mars/services/storage/handler.py
mars/utils.py

Reduce memory estimation for specific operands. Also reduce scheduling overhead.

Reduce memory estimation for specific operands

---

docs/source/conf.py
mars/core/operand/core.py
mars/dataframe/indexing/getitem.py
mars/dataframe/indexing/setitem.py
mars/learn/contrib/utils.py
mars/oscar/backends/communication/utils.py
mars/oscar/backends/message.py
mars/services/scheduling/supervisor/queueing.py
mars/services/scheduling/worker/execution.py
mars/services/scheduling/worker/quota.py
mars/services/scheduling/worker/tests/test_execution.py
mars/services/storage/handler.py
mars/utils.py

[BACKPORT] Reduce memory estimation for specific operands (#2283)

---

README.rst
docs/source/development/oscar/batch.rst
docs/source/development/oscar/index.rst
docs/source/development/services/cluster.rst
docs/source/development/services/meta.rst
docs/source/development/services/scheduling.rst
docs/source/development/services/storage.rst
docs/source/development/services/task.rst
docs/source/locale/zh_CN/LC_MESSAGES/development/oscar/batch.po
docs/source/locale/zh_CN/LC_MESSAGES/development/services/cluster.po
docs/source/locale/zh_CN/LC_MESSAGES/development/services/lifecycle.po
docs/source/locale/zh_CN/LC_MESSAGES/development/services/meta.po
docs/source/locale/zh_CN/LC_MESSAGES/development/services/scheduling.po
docs/source/locale/zh_CN/LC_MESSAGES/development/services/session.po
docs/source/locale/zh_CN/LC_MESSAGES/development/services/storage.po
docs/source/locale/zh_CN/LC_MESSAGES/development/services/task.po
mars/services/cluster/__init__.py
mars/services/storage/worker/service.py

Add docs for batch methods

---

README.rst
docs/source/development/oscar/batch.rst
docs/source/development/oscar/index.rst
docs/source/development/services/cluster.rst
docs/source/development/services/meta.rst
docs/source/development/services/scheduling.rst
docs/source/development/services/storage.rst
docs/source/development/services/task.rst
docs/source/locale/zh_CN/LC_MESSAGES/development/oscar/batch.po
docs/source/locale/zh_CN/LC_MESSAGES/development/services/cluster.po
docs/source/locale/zh_CN/LC_MESSAGES/development/services/lifecycle.po
docs/source/locale/zh_CN/LC_MESSAGES/development/services/meta.po
docs/source/locale/zh_CN/LC_MESSAGES/development/services/scheduling.po
docs/source/locale/zh_CN/LC_MESSAGES/development/services/session.po
docs/source/locale/zh_CN/LC_MESSAGES/development/services/storage.po
docs/source/locale/zh_CN/LC_MESSAGES/development/services/task.po
mars/services/cluster/__init__.py
mars/services/storage/worker/service.py

[BACKPORT] Add docs for batch methods (#2293)

---

docs/source/reference/tensor/set.rst
mars/tensor/__init__.py
mars/tensor/base/__init__.py
mars/tensor/base/in1d.py
mars/tensor/base/isin.py
mars/tensor/base/tests/test_base.py
mars/tensor/base/tests/test_base_execute.py

This PR implements `mars.tensor.in1d`.
Fixes #2296 .

Implements mars.tensor.in1d

---

docs/source/reference/tensor/set.rst
mars/tensor/__init__.py
mars/tensor/base/__init__.py
mars/tensor/base/in1d.py
mars/tensor/base/isin.py
mars/tensor/base/tests/test_base.py
mars/tensor/base/tests/test_base_execute.py

[BACKPORT] Implements mars.tensor.in1d (#2297)

---

.github/workflows/checks.yml
.github/workflows/upload-packages.sh

Fix delocate version to 0.8.2 to avoid deploy error.

Fix delocate version to 0.8.2 to avoid deploy error

---

.github/workflows/checks.yml
mars/dataframe/indexing/setitem.py
mars/dataframe/indexing/tests/test_indexing_execution.py
mars/deploy/oscar/session.py

Support setting multiple columns in DataFrame
Fixes #2268

Support setting multiple columns in DataFrame

---

mars/_utils.pyx
mars/dataframe/datasource/dataframe.py
mars/dataframe/datasource/index.py
mars/dataframe/datasource/series.py
mars/dataframe/datasource/tests/test_datasource_execution.py
mars/dataframe/initializer.py
mars/dataframe/tests/test_initializer.py
mars/dataframe/utils.py
mars/oscar/core.pyx
mars/serialization/serializables/field_type.py
mars/services/web/ui/src/node_info/NodeEnvTab.js
mars/services/web/ui/src/node_info/NodeResourceTab.js
mars/tensor/base/tests/test_base.py
mars/tensor/datasource/array.py
mars/tensor/datasource/tests/test_datasource.py
mars/tensor/datasource/tests/test_datasource_execute.py

Add supports for initialization from CUDA objects.
Fixes #599

Support initializing Mars objects from CUDA

---

mars/dataframe/indexing/setitem.py
mars/dataframe/indexing/tests/test_indexing_execution.py
mars/deploy/oscar/session.py

[BACKPORT] Support setting multiple columns in DataFrame (#2303)

---

mars/_utils.pyx
mars/dataframe/datasource/dataframe.py
mars/dataframe/datasource/index.py
mars/dataframe/datasource/series.py
mars/dataframe/datasource/tests/test_datasource_execution.py
mars/dataframe/initializer.py
mars/dataframe/tests/test_initializer.py
mars/dataframe/utils.py
mars/oscar/core.pyx
mars/serialization/serializables/field_type.py
mars/services/web/ui/src/node_info/NodeEnvTab.js
mars/services/web/ui/src/node_info/NodeResourceTab.js
mars/tensor/base/tests/test_base.py
mars/tensor/datasource/array.py
mars/tensor/datasource/tests/test_datasource.py
mars/tensor/datasource/tests/test_datasource_execute.py

[BACKPORT] Support initializing Mars objects from CUDA (#2308)

---

mars/services/task/supervisor/processor.py
mars/services/task/tests/test_service.py
mars/services/web/ui/.eslintrc.yml
mars/services/web/ui/package-lock.json
mars/services/web/ui/package.json
mars/services/web/ui/src/PageRouter.js
mars/services/web/ui/src/Utils.js
mars/services/web/ui/src/node_info/NodeEnvTab.js
mars/services/web/ui/src/node_info/NodeListPage.js
mars/services/web/ui/src/node_info/NodeResourceTab.js
mars/services/web/ui/src/node_info/SupervisorDetailPage.js
mars/services/web/ui/src/node_info/TabPanel.js
mars/services/web/ui/src/node_info/WorkerDetailPage.js
mars/services/web/ui/src/task_info/TaskDetail.js
mars/services/web/ui/src/task_info/TaskListPage.js
mars/services/web/ui/src/task_info/TaskTileableGraph.js
mars/services/web/ui/src/task_info/TileableDetail.js

[BACKPORT] Add visualization page for tileable graphs (#2282)

---

mars/dataframe/__init__.py
mars/dataframe/base/tests/test_base.py
mars/dataframe/base/tests/test_base_execution.py
mars/dataframe/base/to_numeric.py

Support md.to_numeric

---

docs/source/reference/tensor/statistics.rst
mars/_utils.pyx
mars/config.yml
mars/core/entity/tests/__init__.py
mars/core/entity/tests/test_utils.py
mars/core/entity/utils.py
mars/core/graph/builder/chunk.py
mars/deploy/oscar/session.py
mars/opcodes.py
mars/services/task/analyzer/analyzer.py
mars/services/task/supervisor/processor.py
mars/tensor/base/searchsorted.py
mars/tensor/base/tests/test_base.py
mars/tensor/base/tests/test_base_execute.py
mars/tensor/stats/core.py
mars/tensor/stats/ks_2samp.py
mars/tensor/stats/tests/test_stats_execute.py
setup.cfg

This PR implements `mars.tensor.stats.ks_2samp`.
Resolves #2265

Implements `mars.tensor.stats.ks_2samp`

---

docs/source/reference/tensor/statistics.rst
mars/_utils.pyx
mars/config.yml
mars/core/entity/tests/__init__.py
mars/core/entity/tests/test_utils.py
mars/core/entity/utils.py
mars/core/graph/builder/chunk.py
mars/deploy/oscar/session.py
mars/opcodes.py
mars/services/task/analyzer/analyzer.py
mars/services/task/supervisor/processor.py
mars/tensor/base/searchsorted.py
mars/tensor/base/tests/test_base.py
mars/tensor/base/tests/test_base_execute.py
mars/tensor/stats/core.py
mars/tensor/stats/ks_2samp.py
mars/tensor/stats/tests/test_stats_execute.py
setup.cfg

[BACKPORT] Implements `mars.tensor.stats.ks_2samp` (#2324)

---

mars/deploy/oscar/ray.py
mars/deploy/oscar/tests/test_ray.py
mars/services/core.py
mars/services/lifecycle/supervisor/tracker.py
mars/services/task/analyzer/analyzer.py
mars/services/task/analyzer/assigner.py
mars/services/task/supervisor/preprocessor.py
mars/services/task/supervisor/processor.py

[BACKPORT] Optimize scheduling service on supervisors (#2325)

---

README.rst
docs/source/getting_started/learn.rst
docs/source/user_guide/learn/joblib.rst
docs/source/user_guide/learn/lightgbm.rst
docs/source/user_guide/learn/statsmodels.rst
docs/source/user_guide/learn/tensorflow.rst
docs/source/user_guide/learn/xgboost.rst
mars/core/operand/core.py
mars/core/operand/tests/test_core.py
mars/tensor/stats/tests/test_stats_execute.py

[BACKPORT] Gives an error when input DataFrame has unknown dtypes (#2355)

---

.github/workflows/core-ci.yml
mars/services/subtask/worker/processor.py
mars/services/task/api/oscar.py
mars/services/task/api/web.py
mars/services/task/supervisor/manager.py
mars/services/task/supervisor/processor.py
mars/services/task/supervisor/stage.py
mars/services/task/tests/test_service.py
mars/services/web/ui/src/task_info/TaskTileableGraph.js
mars/services/web/ui/src/task_info/TileableDetail.js

[BACKPORT] Add API to retrieve progress and status of tileables (#2357)

---

README.rst
docs/source/getting_started/learn.rst
docs/source/index.rst
docs/source/locale/zh_CN/LC_MESSAGES/getting_started/learn.po
docs/source/locale/zh_CN/LC_MESSAGES/index.po
docs/source/locale/zh_CN/LC_MESSAGES/reference/dataframe/frame.po
docs/source/locale/zh_CN/LC_MESSAGES/reference/dataframe/indexing.po
docs/source/locale/zh_CN/LC_MESSAGES/reference/dataframe/series.po
docs/source/locale/zh_CN/LC_MESSAGES/reference/learn/generated/mars.learn.contrib.pytorch.MarsDataset.po
docs/source/locale/zh_CN/LC_MESSAGES/reference/tensor/set.po
docs/source/locale/zh_CN/LC_MESSAGES/reference/tensor/statistics.po
docs/source/locale/zh_CN/LC_MESSAGES/user_guide/learn/pytorch.po
docs/source/reference/learn/reference.rst
docs/source/user_guide/learn/index.rst
docs/source/user_guide/learn/pytorch.rst
mars/learn/contrib/pytorch/__init__.py
mars/learn/contrib/pytorch/dataset.py
mars/learn/contrib/pytorch/run_script.py
mars/learn/contrib/pytorch/sampler.py
mars/learn/contrib/pytorch/tests/pytorch_dataset.py
mars/learn/contrib/pytorch/tests/test_dataset.py
mars/learn/contrib/tensorflow/run_script.py
mars/remote/run_script.py

[BACKPORT] Support PyTorch Dataset for oscar (#2246)

---

docs/source/reference/dataframe/frame.rst
mars/dataframe/core.py
mars/dataframe/tests/test_core.py

Fix documentation of assign as they cannot work as expected. Also reduce unneeded tests.

Fix docs of `DataFrame.assign`

---

docs/source/reference/dataframe/frame.rst
mars/dataframe/core.py
mars/dataframe/tests/test_core.py

[BACKPORT] Implements DataFrame.assign (#2362)

---

.github/workflows/core-ci.yml
.github/workflows/os-compat-ci.yml
mars/dataframe/datasource/read_csv.py
mars/deploy/oscar/tests/test_local.py
mars/lib/filesystem/_oss_lib/__init__.py
mars/lib/filesystem/_oss_lib/common.py
mars/lib/filesystem/_oss_lib/glob.py
mars/lib/filesystem/_oss_lib/handle.py
mars/lib/filesystem/core.py
mars/lib/filesystem/oss.py
mars/lib/filesystem/tests/test_oss.py
mars/tests/test_utils.py
mars/utils.py
setup.cfg

[BACKPORT] Support reading csv file from oss (#2292)

---

LICENSE
mars/contrib/dask/__init__.py
mars/dataframe/utils.py
mars/lib/filesystem/_oss_lib/common.py
mars/lib/filesystem/_oss_lib/handle.py
mars/lib/filesystem/oss.py
mars/remote/tests/test_remote_function.py
mars/services/subtask/worker/processor.py
mars/services/task/tests/test_service.py
mars/tensor/images/imread.py
mars/tensor/linalg/cholesky.py
mars/tensor/special/bessel.py
mars/tensor/special/convenience.py
mars/tensor/special/core.py
mars/tensor/special/err_fresnel.py
mars/tensor/special/gamma_funcs.py
mars/tensor/special/info_theory.py
mars/tests/test_utils.py
mars/utils.py

Fix KeyError when remote function returns None.
Fixes #2356

Fix KeyError when remote function returns None

---

LICENSE
mars/dataframe/utils.py
mars/lib/filesystem/_oss_lib/common.py
mars/lib/filesystem/_oss_lib/handle.py
mars/lib/filesystem/oss.py
mars/remote/tests/test_remote_function.py
mars/services/subtask/worker/processor.py
mars/services/task/tests/test_service.py
mars/tensor/images/imread.py
mars/tensor/linalg/cholesky.py
mars/tensor/special/bessel.py
mars/tensor/special/convenience.py
mars/tensor/special/core.py
mars/tensor/special/err_fresnel.py
mars/tensor/special/gamma_funcs.py
mars/tensor/special/info_theory.py
mars/tests/test_utils.py
mars/utils.py

[BACKPORT] Fix KeyError when remote function returns None (#2371)

---

mars/services/task/supervisor/processor.py
mars/services/web/ui/src/task_info/TaskTileableGraph.js

[BACKPORT] Display tileable progress, status and dependency link type on task detail page (#2360)

---

docs/source/locale/zh_CN/LC_MESSAGES/reference/dataframe/frame.po
docs/source/locale/zh_CN/LC_MESSAGES/reference/learn/reference.po
docs/source/reference/learn/reference.rst
mars/_version.py
mars/dataframe/arithmetic/core.py
mars/dataframe/arithmetic/tests/test_comparison.py
mars/services/task/tests/test_service.py
mars/tensor/base/astype.py
mars/utils.py

[BACKPORT] Fix DataFrame comparison when data type is period (#2373)

---

mars/dataframe/core.py
mars/dataframe/tests/test_core.py

[BACKPORT] Implements `Series.between` (#2368)

---

mars/deploy/oscar/tests/test_ray.py

Fix ci failure in autoscaling for ray:
```
@pytest.mark.timeout(timeout=120)
@pytest.mark.parametrize('ray_large_cluster', [{'num_nodes': 4}], indirect=True)
@require_ray
@pytest.mark.asyncio
async def test_ownership_when_scale_in(ray_large_cluster):
client = await new_cluster('test_cluster',
worker_num=0,
worker_cpu=2,
worker_mem=100 * 1024 ** 2,
config={
'scheduling.autoscale.enabled': True,
'scheduling.autoscale.scheduler_check_interval': 1,
'scheduling.autoscale.scheduler_backlog_timeout': 1,
'scheduling.autoscale.worker_idle_timeout': 5,
'scheduling.autoscale.min_workers': 1,
'scheduling.autoscale.max_workers': 4
})
async with client:
from mars.services.scheduling.supervisor.autoscale import AutoscalerActor
autoscaler_ref = mo.create_actor_ref(
uid=AutoscalerActor.default_uid(), …
```

[Ray] Fix occasionally failed unittest `test_ownership_when_scale_in`

---

docs/source/locale/zh_CN/LC_MESSAGES/user_guide/learn/tensorflow.po
docs/source/reference/learn/reference.rst
docs/source/user_guide/learn/tensorflow.rst
mars/learn/contrib/tensorflow/__init__.py
mars/learn/contrib/tensorflow/dataset.py
mars/learn/contrib/tensorflow/run_script.py
mars/learn/contrib/tensorflow/tests/test_dataset.py
mars/learn/contrib/tensorflow/tests/test_run_script.py
mars/learn/contrib/tensorflow/tests/tf_dataset.py
mars/services/task/analyzer/assigner.py
setup.cfg

[BACKPORT] Add TensorFlow dataset (#2383)

---

mars/services/task/api/oscar.py
mars/services/task/api/web.py
mars/services/task/supervisor/manager.py
mars/services/task/supervisor/processor.py
mars/services/task/supervisor/stage.py
mars/services/task/tests/test_service.py
mars/services/web/ui/src/task_info/TaskDetail.js
mars/services/web/ui/src/task_info/TaskTileableGraph.js
mars/services/web/ui/src/task_info/TileableDetail.js

[BACKPORT] API for subtask DAG structure (#2389)

---

mars/learn/base.py
mars/learn/linear_model/__init__.py
mars/learn/linear_model/_base.py
mars/learn/linear_model/tests/__init__.py
mars/learn/linear_model/tests/test_base.py
mars/learn/preprocessing/normalize.py
mars/learn/utils/validation.py

[BACKPORT] Implements `linear_model.LinearRegression` (#2260)

---

docs/source/reference/learn/reference.rst
mars/learn/metrics/__init__.py
mars/learn/metrics/_classification.py
mars/learn/metrics/tests/test_classification.py

[BACKPORT] Implements `mars.learn.metrics.log_loss` (#2418)

---

docs/source/reference/dataframe/frame.rst
docs/source/reference/dataframe/indexing.rst
docs/source/reference/dataframe/series.rst
mars/dataframe/base/__init__.py
mars/dataframe/base/tests/test_base.py
mars/dataframe/base/tests/test_base_execution.py
mars/dataframe/base/transpose.py
mars/dataframe/core.py
mars/dataframe/tests/test_core.py
mars/tests/core.py

[BACKPORT] Implements `DataFrame.transpose()` (#2327)

---

docs/source/reference/learn/reference.rst
mars/core/entity/utils.py
mars/learn/metrics/__init__.py
mars/learn/metrics/_scorer.py
mars/learn/metrics/tests/test_scorer.py
mars/learn/tests/__init__.py
mars/learn/tests/test_wrappers.py
mars/learn/utils/core.py
mars/learn/wrappers.py

This PR implements `mars.learn.wrappers.ParallelPostFit`
Resolves #2392 .

Implements `mars.learn.wrappers.ParallelPostFit`

---

docs/source/reference/learn/reference.rst
mars/core/entity/utils.py
mars/learn/metrics/__init__.py
mars/learn/metrics/_scorer.py
mars/learn/metrics/tests/test_scorer.py
mars/learn/tests/__init__.py
mars/learn/tests/test_wrappers.py
mars/learn/utils/core.py
mars/learn/wrappers.py

[BACKPORT] Implements `mars.learn.wrappers.ParallelPostFit` (#2425)

---

.dockerignore
.github/workflows/docker-cd.yml
.github/workflows/pypi-cd.yml
bin/kube-image-tool.sh
mars/deploy/kubernetes/docker/Dockerfile
mars/deploy/kubernetes/docker/Dockerfile.base
mars/services/web/core.py

As image build is now a paid function, we need to build and upload docker images in continuous deployment.

Build and upload docker images in continuous deployment

---

.dockerignore
.github/workflows/docker-cd.yml
.github/workflows/pypi-cd.yml
bin/kube-image-tool.sh
mars/deploy/kubernetes/docker/Dockerfile
mars/deploy/kubernetes/docker/Dockerfile.base
mars/services/web/core.py
mars/services/web/ui/src/task_info/TaskTileableGraph.js
mars/services/web/ui/src/task_info/TileableDetail.js
mars/services/web/ui/src/task_info/charts/DAGChart.js
mars/services/web/ui/src/task_info/charts/DAGPropTypes.js

[BACKPORT] Fix missing DAGs when initializing with empty API results (#2439)

---

.github/workflows/docker-cd.yml
mars/_version.py
mars/dataframe/reduction/aggregation.py
mars/dataframe/reduction/kurtosis.py
mars/dataframe/reduction/skew.py
mars/services/subtask/core.py
mars/services/subtask/worker/processor.py
mars/services/task/supervisor/processor.py
mars/services/task/supervisor/stage.py
mars/services/web/ui/src/Utils.js
mars/tests/test_session.py

[BACKPORT] Fix skew and kurt errors under MacOS (#2443)

---

mars/deploy/oscar/session.py
mars/services/task/api/web.py
mars/services/web/core.py
mars/services/web/tests/test_core.py

Fix timeout error when waiting for a submitted task.

Fix timeout error when waiting for a submitted task

---

mars/deploy/oscar/session.py
mars/services/task/api/web.py
mars/services/task/supervisor/processor.py
mars/services/web/core.py
mars/services/web/tests/test_core.py

[BACKPORT] Fix timeout error when waiting for a submitted task (#2457)

---

.github/workflows/docker-cd.yml
ci/reload-env.sh
docs/source/installation/kubernetes.rst
docs/source/installation/yarn.rst
docs/source/locale/zh_CN/LC_MESSAGES/installation/kubernetes.po
docs/source/locale/zh_CN/LC_MESSAGES/installation/yarn.po
mars/deploy/kubernetes/client.py
mars/deploy/kubernetes/config.py
mars/deploy/kubernetes/core.py
mars/deploy/kubernetes/tests/test_kubernetes.py
mars/deploy/yarn/client.py
mars/deploy/yarn/tests/test_yarn.py
mars/resource.py
mars/utils.py

[BACKPORT] Add nightly builds for docker images (#2456)

---

azure-pipelines.yml

Manually specify token for Azure pipeline.

Fix coverage for Azure pipeline

---

LICENSE
mars/services/task/api/oscar.py
mars/services/task/api/web.py
mars/services/task/supervisor/manager.py
mars/services/task/supervisor/processor.py
mars/services/task/tests/test_service.py
mars/services/web/ui/package-lock.json
mars/services/web/ui/package.json
mars/services/web/ui/src/task_info/SubtaskGraph.js
mars/services/web/ui/src/task_info/TileableDetail.js
mars/services/web/ui/src/task_info/charts/DAGCanvasChart.js
mars/services/web/ui/src/task_info/charts/DAGChart.js

[BACKPORT] Support visualizing subtask graphs on Mars Web (#2426)

---

mars/deploy/oscar/cmdline.py
mars/deploy/oscar/supervisor.py
mars/deploy/oscar/tests/test_cmdline.py
mars/deploy/oscar/worker.py
mars/deploy/utils.py

[BACKPORT] Make cmdline support third party modules (#2454)

---

azure-pipelines.yml

[BACKPORT] Fix coverage for Azure pipeline (#2474)

---

mars/oscar/backends/mars/pool.py
mars/oscar/backends/mars/tests/test_pool.py
mars/oscar/backends/pool.py
mars/oscar/backends/ray/pool.py
mars/oscar/backends/test/pool.py

[BACKPORT] Fix hang when start sub pool fails (#2468)

---

mars/learn/metrics/_ranking.py
mars/learn/metrics/tests/test_ranking.py

[BACKPORT] Add `_binary_roc_auc_score` method (#2403)

---

docs/source/locale/zh_CN/LC_MESSAGES/installation/deploy.po

Fix wrong translation in cluster deployment.
Fixes #2484

Fix wrong translation in cluster deployment.

---

docs/source/locale/zh_CN/LC_MESSAGES/installation/deploy.po
mars/dataframe/base/eval.py
mars/dataframe/base/tests/test_base_execution.py

[BACKPORT] Fix bug that failed to execute query when there are multiple arguments (#2490)

---

docs/source/reference/dataframe/series.rst
mars/dataframe/core.py
mars/dataframe/tests/test_core.py

[BACKPORT] Support `Series.median` (#2566)

---

azure-pipelines.yml
docs/source/locale/zh_CN/LC_MESSAGES/development/operand.po
mars/deploy/oscar/session.py
mars/oscar/backends/communication/dummy.py
mars/oscar/backends/message.py
mars/resource.py
mars/services/cluster/uploader.py
mars/services/context.py
mars/services/session/api/oscar.py

Reduce overhead of `cpu_percent()` calls.

Reduce time cost of `cpu_percent()` calls

---

azure-pipelines.yml
docs/source/locale/zh_CN/LC_MESSAGES/development/operand.po
mars/deploy/oscar/session.py
mars/oscar/backends/communication/dummy.py
mars/oscar/backends/message.py
mars/resource.py
mars/services/cluster/uploader.py
mars/services/context.py
mars/services/session/api/oscar.py

[BACKPORT] Reduce time cost of `cpu_percent()` calls (#2567)

---

mars/dataframe/indexing/getitem.py
mars/dataframe/indexing/tests/test_indexing_execution.py
mars/dataframe/indexing/utils.py

[BACKPORT] Fix DataFrame getitem when exists duplicate columns (#2581)

---

.github/workflows/platform-ci.yml
mars/dataframe/datasource/from_vineyard.py
mars/dataframe/datastore/tests/test_datastore_execution.py
mars/dataframe/datastore/to_vineyard.py
mars/storage/vineyard.py
mars/tensor/datasource/from_vineyard.py
mars/tensor/datastore/tests/test_datastore_execution.py
mars/tensor/datastore/to_vineyard.py
setup.cfg

Remove the fixed version constraints for vineyard.
None, fixes the failures in CI.

Upgrade required version of vineyard.

---

.github/workflows/platform-ci.yml
mars/dataframe/datasource/from_vineyard.py
mars/dataframe/datastore/tests/test_datastore_execution.py
mars/dataframe/datastore/to_vineyard.py
mars/storage/vineyard.py
mars/tensor/datasource/from_vineyard.py
mars/tensor/datastore/tests/test_datastore_execution.py
mars/tensor/datastore/to_vineyard.py
setup.cfg

[BACKPORT] Upgrade required version of vineyard (#2588)

---

mars/deploy/oscar/session.py
mars/deploy/oscar/tests/test_local.py
mars/services/task/api/web.py

[BACKPORT] Fix progress always is 0 or 100% (#2591)

---

mars/dataframe/base/map_chunk.py
mars/dataframe/base/tests/test_base_execution.py

[BACKPORT] Stop calling user funcs when dtypes is specified (#2587)

---

mars/core/entrypoints.py
mars/core/tests/test_entrypoints.py
mars/deploy/oscar/local.py
mars/deploy/oscar/ray.py
mars/deploy/oscar/session.py
mars/oscar/backends/pool.py

[BACKPORT] Supports adding Mars extensions via setup entrypoints (#2589)

---

mars/learn/proxima/core.py
mars/services/task/analyzer/analyzer.py

[BACKPORT] Make Proxima work with latest Mars (#2599)

---

README.rst
docs/source/index.rst
docs/source/installation/index.rst
docs/source/installation/ray.rst
docs/source/locale/zh_CN/LC_MESSAGES/index.po
docs/source/locale/zh_CN/LC_MESSAGES/installation/ray.po
mars/__init__.py
mars/conftest.py
mars/deploy/oscar/__init__.py
mars/deploy/oscar/ray.py
mars/deploy/oscar/tests/test_ray.py
mars/oscar/backends/ray/driver.py

[BACKPORT][Ray] Refine mars on ray usability (#2580)

---

mars/dataframe/reduction/aggregation.py
mars/serialization/cuda.py
mars/serialization/tests/test_serial.py

[BACKPORT] Fix tests for cudf 21.10 (#2574)

---

mars/services/meta/api/oscar.py
mars/services/subtask/worker/processor.py

[BACKPORT] Skip details of shuffled chunks in meta (#2600)

---

mars/core/entity/executable.py
mars/dataframe/core.py
mars/learn/tests/test_wrappers.py
mars/services/meta/api/web.py
mars/services/storage/api/web.py
mars/utils.py

Implement batch handlers for web APIs for meta and storage services to reduce the time of fetching data.
Fixes #2592

Reduce the time cost of fetching tileable data

---

mars/core/entity/executable.py
mars/dataframe/core.py
mars/learn/tests/test_wrappers.py
mars/services/meta/api/web.py
mars/services/storage/api/web.py
mars/utils.py

[BACKPORT] Reduce the time cost of fetching tileable data (#2594)

---

mars/services/task/supervisor/processor.py
mars/services/task/supervisor/stage.py

[BACKPORT] Fix duplicate decref of subtask input chunk (#2611)

---

mars/services/scheduling/supervisor/globalslot.py
mars/services/scheduling/supervisor/queueing.py
mars/services/scheduling/supervisor/tests/test_queue_balance.py
mars/services/scheduling/supervisor/tests/test_queueing.py

[BACKPORT] Use batched request to apply for slots (#2601)

---

.github/workflows/install-hadoop.sh
mars/deploy/oscar/local.py
mars/deploy/oscar/ray.py
mars/deploy/oscar/session.py
mars/deploy/oscar/supervisor.py
mars/deploy/oscar/tests/test_cmdline.py
mars/oscar/backends/core.py
mars/oscar/backends/mars/tests/test_pool.py
mars/oscar/backends/message.py
mars/oscar/backends/pool.py
mars/oscar/core.pyx
mars/services/cluster/api/oscar.py
mars/services/lifecycle/api/web.py
mars/services/meta/api/web.py
mars/services/session/api/web.py
mars/services/session/supervisor/core.py
mars/services/storage/api/web.py
mars/services/subtask/worker/runner.py
mars/services/task/api/web.py
mars/services/web/core.py
mars/services/web/ui/package-lock.json

[BACKPORT] Allow specifying multiple supervisor processes (#2452)

---

.github/workflows/core-ci.yml
.github/workflows/os-compat-ci.yml
.github/workflows/platform-ci.yml
mars/oscar/batch.py
mars/oscar/tests/test_batch.py

[BACKPORT] Fix `NotImplementedError` for `mo.batch` when single call not implemented (#2635)

---

azure-pipelines.yml
docs/source/conf.py
mars/dataframe/arrays.py
mars/dataframe/base/apply.py
mars/dataframe/base/memory_usage.py
mars/dataframe/base/tests/test_base_execution.py
mars/dataframe/base/to_numeric.py
mars/dataframe/datasource/index.py
mars/dataframe/groupby/head.py
mars/dataframe/groupby/tests/test_groupby_execution.py
mars/dataframe/indexing/getitem.py
mars/dataframe/indexing/iloc.py
mars/dataframe/indexing/loc.py
mars/dataframe/indexing/reindex.py
mars/dataframe/indexing/reset_index.py
mars/dataframe/missing/fillna.py
mars/dataframe/missing/replace.py
mars/dataframe/tests/test_arrays.py
mars/dataframe/utils.py
mars/dataframe/window/aggregation.py
mars/dataframe/window/ewm/core.py
mars/oscar/utils.pyx
mars/serialization/serializables/field.py
mars/serialization/serializables/tests/test_field_type.py
mars/serialization/serializables/tests/test_serializable.py
mars/tensor/indexing/core.py
mars/tensor/reduction/all.py
mars/tensor/reduction/any.py
mars/tensor/reduction/sum.py
mars/utils.py

Fix compatibility for pandas 1.4
Fixes #xxxx

Fix compatibility for pandas 1.4

---

mars/dataframe/groupby/aggregation.py
mars/dataframe/groupby/tests/test_groupby_execution.py

[BACKPORT] Fix `IndexError` raise by aggregation of DataFrameGroupBy (#2641)

---

mars/dataframe/base/rechunk.py
mars/dataframe/indexing/loc.py
mars/dataframe/indexing/tests/test_indexing.py
mars/dataframe/utils.py
mars/utils.py

[BACKPORT] Fix df.loc[:] to make sure same index_value key generated (#2643)

---

mars/dataframe/groupby/aggregation.py
mars/dataframe/groupby/tests/test_groupby_execution.py
mars/dataframe/reduction/aggregation.py
mars/dataframe/reduction/core.py
mars/dataframe/reduction/tests/test_reduction.py

[BACKPORT] Fix aggregation with comparison (#2647)

---

mars/dataframe/groupby/__init__.py
mars/dataframe/groupby/fill.py
mars/dataframe/groupby/tests/test_groupby.py
mars/dataframe/groupby/tests/test_groupby_execution.py

[BACKPORT] Add support for GroupBy.{ffill, bfill,fillna} (#2639)

---

mars/_version.py
mars/dataframe/datasource/core.py
mars/dataframe/datasource/read_csv.py
mars/dataframe/datasource/read_parquet.py
mars/dataframe/datasource/tests/test_datasource.py
mars/dataframe/datasource/tests/test_datasource_execution.py

This PR added  merging small files support for `md.{read_parquet, read_csv}`.
Fixes #2659 .

Added  merging small files support for `md.{read_parquet, read_csv}`

---

mars/deploy/oscar/session.py
mars/deploy/oscar/tests/test_local.py
mars/services/cluster/api/web.py
mars/services/lifecycle/api/web.py
mars/services/meta/api/web.py
mars/services/mutable/api/web.py
mars/services/scheduling/api/web.py
mars/services/session/api/web.py
mars/services/storage/api/web.py
mars/services/task/api/web.py
mars/services/web/core.py
mars/services/web/tests/test_core.py

[BACKPORT] Add support for HTTP request rewriter (#2664)

---

mars/dataframe/indexing/index_lib.py
mars/dataframe/indexing/tests/test_indexing.py

[BACKPORT] Fix the wrong index_value generated by df.loc[:] (#2658)

---

mars/core/graph/builder/base.py
mars/dataframe/arithmetic/core.py
mars/optimization/logical/common/column_pruning.py
mars/optimization/logical/common/head.py
mars/optimization/logical/core.py
mars/optimization/logical/tileable/arithmetic_query.py
mars/optimization/logical/tileable/tests/test_arithmetic_query.py

Try optimizing DataFrame filtering with boolean condition composed with its own fields by using df.query.
Fixes #2559

Optimize filtering DataFrame with its fields

---

mars/_version.py
mars/dataframe/datasource/core.py
mars/dataframe/datasource/read_csv.py
mars/dataframe/datasource/read_parquet.py
mars/dataframe/datasource/tests/test_datasource.py
mars/dataframe/datasource/tests/test_datasource_execution.py

[BACKPORT] Add merging small files support for `md.{read_parquet, read_csv}` (#2661)

---

mars/core/graph/builder/base.py
mars/dataframe/arithmetic/core.py
mars/optimization/logical/common/column_pruning.py
mars/optimization/logical/common/head.py
mars/optimization/logical/core.py
mars/optimization/logical/tileable/__init__.py
mars/optimization/logical/tileable/arithmetic_query.py
mars/optimization/logical/tileable/tests/test_arithmetic_query.py

[BACKPORT] Optimize filtering DataFrame with its fields (#2571)

---

MANIFEST.in
docs/source/development/contributing.rst
mars/dataframe/groupby/aggregation.py
mars/dataframe/groupby/tests/test_groupby_execution.py
mars/dataframe/reduction/core.py
pyproject.toml

[BACKPORT] Fix as_index when calling groupby-agg (#2676)

---

mars/optimization/logical/core.py
mars/optimization/logical/tileable/arithmetic_query.py
mars/optimization/logical/tileable/tests/test_arithmetic_query.py

Fix error on dependent DataFrame setitems. Also add support for merging multiple setitems.
Fixes #2700

Fix error on dependent DataFrame setitems

---

README.rst

Add the Slack invite link to README.rst
N/A

Add Slack invite link

---

mars/optimization/logical/core.py
mars/optimization/logical/tileable/arithmetic_query.py
mars/optimization/logical/tileable/tests/test_arithmetic_query.py

[BACKPORT] Fix error on dependent DataFrame setitems (#2701)

---

mars/dataframe/groupby/apply.py
mars/dataframe/groupby/tests/test_groupby.py
mars/dataframe/tests/test_utils.py
mars/dataframe/utils.py

This PR introduces mechanism that auto merge small chunks when `df.groupby().apply(func)` is doing aggregation.
Fixes #2692 .

Auto merge small chunks when `df.groupby().apply(func)` is doing aggregation

---

mars/_version.py
mars/tests/test_utils.py
mars/utils.py

[BACKPORT] Fix `estimate_pandas_size` on `pd.MultiIndex` (#2707)

---

mars/dataframe/groupby/aggregation.py
mars/dataframe/groupby/tests/test_groupby_execution.py
mars/services/subtask/worker/tests/subtask_processor.py

Now we decide aggregation strategy at runtime described in #2215 , this PR's optimization try to avoid some bad choices for tile method.

Optimize GroupBy's aggregation algorithm

---

mars/storage/vineyard.py

Import `vineyard.data.pickle` to fixes the CI.

Import vineyard.data.pickle to make members available.

---

mars/storage/vineyard.py

[BACKPORT] Import vineyard.data.pickle to make members available (#2714)

---

mars/dataframe/arithmetic/tests/test_arithmetic.py
mars/dataframe/core.py
mars/dataframe/datasource/date_range.py
mars/dataframe/datasource/tests/test_datasource_execution.py
mars/dataframe/indexing/set_index.py
mars/dataframe/sort/psrs.py
mars/dataframe/sort/sort_values.py
mars/dataframe/tests/test_utils.py
mars/dataframe/utils.py
mars/learn/ensemble/_bagging.py
mars/services/scheduling/worker/tests/test_execution.py
mars/tensor/statistics/bincount.py

[BACKPORT] Support inclusive argument for pd.date_range (#2718)

---

.github/workflows/platform-ci.yml
docs/source/installation/ray.rst
mars/dataframe/__init__.py
mars/dataframe/contrib/raydataset/dataset.py
mars/dataframe/contrib/raydataset/mldataset.py
mars/dataframe/datasource/read_raydataset.py
mars/dataframe/datasource/tests/test_datasource_execution.py
setup.cfg

Remove custom ray dataset subclasses for integration

[Ray] refine ray dataset integration

---

.github/workflows/platform-ci.yml
docs/source/installation/ray.rst
mars/dataframe/__init__.py
mars/dataframe/contrib/raydataset/dataset.py
mars/dataframe/contrib/raydataset/mldataset.py
mars/dataframe/datasource/read_raydataset.py
mars/dataframe/datasource/tests/test_datasource_execution.py
setup.cfg

[BACKPORT][Ray] refine ray dataset integration (#2705)

---

mars/learn/utils/shuffle.py
mars/learn/utils/tests/test_shuffle.py

[BACKPORT] Fix shuffle when ndim of input tensors are different (#2727)

---

azure-pipelines.yml
mars/dataframe/datasource/read_parquet.py
mars/dataframe/datasource/tests/test_datasource_execution.py

[BACKPORT] Add support for reading partitioned parquet for fastparquet (#2724)

---

mars/deploy/oscar/session.py
mars/deploy/oscar/tests/test_local.py

[BACKPORT] Fix duplicate exceptions in log (#2723)

---

mars/_version.py
mars/dataframe/arithmetic/dot.py
mars/dataframe/datasource/from_tensor.py
mars/dataframe/datasource/tests/test_datasource.py
mars/dataframe/datasource/tests/test_datasource_execution.py
mars/dataframe/initializer.py
mars/dataframe/merge/concat.py
mars/dataframe/statistics/quantile.py
mars/dataframe/tests/test_initializer.py
mars/storage/filesystem.py
mars/storage/plasma.py
mars/storage/shared_memory.py
mars/storage/vineyard.py
mars/tensor/datasource/array.py
mars/tensor/datasource/diag.py
mars/tensor/datasource/ones.py
mars/tensor/datasource/tests/test_datasource.py
mars/tensor/datasource/tri.py
mars/tensor/datasource/zeros.py
mars/tensor/linalg/cholesky.py
mars/tensor/linalg/lu.py

[BACKPORT] Fix DataFrame initializer when Mars object exists in list (#2770)

---

.codecov.yml
mars/_utils.pyx
mars/conftest.py
mars/deploy/oscar/cmdline.py
mars/deploy/oscar/service.py
mars/deploy/oscar/tests/local_test_config.yml
mars/deploy/oscar/tests/test_cmdline.py
mars/oscar/backends/mars/pool.py
mars/oscar/backends/mars/tests/test_pool.py
mars/services/cluster/tests/test_locator.py
mars/services/scheduling/worker/quota.py
mars/services/task/tests/test_service.py
mars/utils.py
setup.cfg

Increase test stability for command-line tests by adding manual retry on cmdline tests.
Fixes #xxxx

Increase test stability for command-line tests

---

.codecov.yml
mars/conftest.py
mars/deploy/oscar/cmdline.py
mars/deploy/oscar/service.py
mars/deploy/oscar/tests/local_test_config.yml
mars/deploy/oscar/tests/test_cmdline.py
mars/oscar/backends/mars/pool.py
mars/oscar/backends/mars/tests/test_pool.py
mars/services/cluster/tests/test_locator.py
mars/services/scheduling/worker/quota.py
mars/services/task/tests/test_service.py
mars/utils.py
setup.cfg

[BACKPORT] Increase test stability for command-line tests (#2779)

---

mars/services/task/supervisor/processor.py

[BACKPORT] Fix duplicate dec object ref (#2741)

---

docs/source/reference/dataframe/general_functions.rst
mars/oscar/backends/ray/tests/test_ray_pool.py
mars/services/subtask/core.py
mars/services/task/supervisor/processor.py
mars/services/task/supervisor/stage.py
mars/tensor/__init__.py

[BACKPORT] Remove deprecate warnings when import mars.tensor (#2788)

---

.github/workflows/platform-ci.yml
mars/deploy/oscar/ray.py
mars/deploy/oscar/tests/test_ray.py
mars/oscar/backend.py
mars/oscar/backends/mars/backend.py
mars/oscar/backends/ray/backend.py
mars/oscar/backends/ray/driver.py
mars/oscar/backends/ray/pool.py
mars/oscar/backends/ray/tests/test_ray_actor_context.py
mars/oscar/backends/ray/tests/test_ray_actor_driver.py
mars/oscar/backends/ray/tests/test_ray_pool.py
mars/oscar/backends/ray/utils.py
mars/oscar/backends/test/backend.py

[BACKPORT][Ray] New ray actor creation model (#2783)

---

.github/workflows/core-ci.yml
.github/workflows/docker-cd.yml
.github/workflows/os-compat-ci.yml
.github/workflows/platform-ci.yml
mars/_utils.pxd
mars/_utils.pyx
mars/tests/test_utils.py
mars/utils.py

Build docker images at 18:00 UTC every day to reduce redundant images. If no commits last day, build will be skipped.
Fixes #xxxx

Build docker images cronically

---

mars/conftest.py
mars/dataframe/contrib/raydataset/tests/test_mldataset.py
mars/dataframe/contrib/raydataset/tests/test_raydataset.py
mars/deploy/oscar/ray.py
mars/deploy/oscar/tests/test_ray.py
mars/oscar/backends/ray/driver.py
mars/oscar/backends/ray/tests/test_ray_actor_context.py
mars/services/scheduling/supervisor/assigner.py
mars/services/scheduling/worker/tests/test_workerslot.py
mars/tests/core.py

[BACKPORT][Ray] Refine ray tests (#2793)

---

mars/services/task/supervisor/stage.py

[Bug] Fix duplicate subtask submit

---

mars/dataframe/utils.py
mars/services/lifecycle/supervisor/tracker.py
mars/services/task/supervisor/graph_visualizer.py
mars/services/task/supervisor/processor.py
mars/services/task/supervisor/tests/test_task_manager.py

[BACKPORT] Support generating a DOT file for subtask graph (#2803)

---

mars/dataframe/datasource/dataframe.py
mars/dataframe/datasource/from_records.py
mars/dataframe/datasource/from_vineyard.py
mars/dataframe/datasource/index.py
mars/dataframe/datasource/series.py
mars/dataframe/indexing/iloc.py
mars/dataframe/indexing/loc.py
mars/dataframe/reduction/core.py
mars/dataframe/sort/core.py
mars/learn/neighbors/_faiss.py
mars/tensor/arithmetic/tests/test_arithmetic.py
mars/tensor/datasource/array.py
mars/tensor/datasource/diag.py
mars/tensor/datasource/diagflat.py
mars/tensor/datasource/empty.py
mars/tensor/datasource/eye.py
mars/tensor/datasource/from_tiledb.py
mars/tensor/datasource/from_vineyard.py
mars/tensor/datasource/full.py
mars/tensor/datasource/identity.py
mars/tensor/datasource/linspace.py
mars/tensor/datasource/ones.py
mars/tensor/datasource/scalar.py
mars/tensor/datasource/tests/test_datasource.py
mars/tensor/datasource/zeros.py
mars/tensor/fft/fftfreq.py
mars/tensor/fft/rfftfreq.py

[BACKPORT] Fix default value of `gpu` property for some operands (#2811)

---

mars/core/context.py
mars/core/custom_log.py
mars/core/graph/tests/test_graph.py
mars/dataframe/datastore/tests/test_datastore_execution.py
mars/learn/contrib/pytorch/run_script.py
mars/learn/contrib/tensorflow/run_script.py
mars/learn/contrib/xgboost/start_tracker.py
mars/learn/contrib/xgboost/tests/test_train.py
mars/services/context.py
mars/services/lifecycle/supervisor/tracker.py
mars/services/storage/handler.py
mars/services/task/supervisor/processor.py
mars/utils.py

[BACKPORT] Fix running xgboost on Ray cluster (#2826)

---

docs/source/reference/learn/reference.rst
mars/learn/metrics/__init__.py
mars/learn/metrics/_base.py
mars/learn/metrics/_ranking.py
mars/learn/metrics/tests/test_ranking.py
mars/learn/preprocessing/_label.py
mars/learn/utils/_encode.py
mars/learn/utils/multiclass.py
mars/services/lifecycle/supervisor/tracker.py
mars/services/task/supervisor/processor.py
mars/tensor/base/map_chunk.py

This PR implements `mars.learn.metrics.roc_auc_score`
Fixes #2267

Added support for `mars.learn.metrics.roc_auc_score`

---

mars/core/graph/entity.py
mars/lib/filesystem/oss.py
mars/optimization/logical/common/column_pruning.py
mars/optimization/logical/core.py
mars/optimization/logical/tileable/arithmetic_query.py
mars/services/scheduling/supervisor/queueing.py
mars/services/scheduling/worker/execution.py
mars/services/scheduling/worker/service.py
mars/services/subtask/core.py
mars/services/subtask/tests/test_service.py
mars/services/subtask/worker/processor.py
mars/services/task/supervisor/stage.py

[BACKPORT] Enhance subtask details in logs (#2836) and fix FileSystem.ls for OSS (#2837) 

---

mars/services/scheduling/worker/execution.py
mars/services/scheduling/worker/tests/test_execution.py
mars/services/subtask/core.py
mars/services/subtask/worker/processor.py

Remove reliance of `Fetch` chunks when it is a pure dependency.
Fixes #2839

Stop fetching data when pure dependencies specified

---

mars/services/scheduling/worker/execution.py
mars/services/scheduling/worker/tests/test_execution.py
mars/services/subtask/core.py
mars/services/subtask/worker/processor.py

[BACKPORT] Stop fetching data when pure dependencies specified (#2840)

---

mars/core/context.py
mars/deploy/oscar/cmdline.py
mars/learn/contrib/xgboost/dmatrix.py
mars/learn/contrib/xgboost/predict.py
mars/learn/contrib/xgboost/start_tracker.py
mars/learn/contrib/xgboost/tracker.py
mars/learn/contrib/xgboost/train.py
mars/services/context.py

Configure n_threads of XGBoost jobs with slot size. Also add debug logs.
Fixes #xxxx

Configure nthread of XGBoost jobs

---

mars/core/context.py
mars/deploy/oscar/cmdline.py
mars/learn/contrib/xgboost/dmatrix.py
mars/learn/contrib/xgboost/predict.py
mars/learn/contrib/xgboost/start_tracker.py
mars/learn/contrib/xgboost/tracker.py
mars/learn/contrib/xgboost/train.py
mars/services/context.py

[BACKPORT] Configure cores of XGBoost jobs (#2844)

---

mars/services/subtask/worker/processor.py
mars/services/subtask/worker/tests/subtask_processor.py
mars/services/web/ui/package-lock.json

[BACKPORT] Fix store duplicate chunk and meta per subtask (#2845)

---

mars/learn/contrib/xgboost/start_tracker.py
mars/learn/contrib/xgboost/tests/test_train.py
mars/learn/contrib/xgboost/tracker.py
mars/learn/contrib/xgboost/train.py

[BACKPORT] Fix XGBoost when some workers do not have `evals` data (#2861)

---

.gitignore
mars/deploy/kubernetes/tests/test_kubernetes.py
mars/services/cluster/api/oscar.py
mars/services/cluster/backends/fixed.py
mars/services/cluster/locator.py
mars/services/cluster/tests/test_api.py
mars/services/scheduling/worker/tests/test_execution.py
mars/services/scheduling/worker/workerslot.py
mars/services/session/supervisor/core.py
mars/services/session/tests/test_service.py

[BACKPORT] Raise ActorNotExist when no supervisors available (#2859)

---

asv_bench/benchmarks/graph_assigner.py
mars/core/graph/tests/test_graph.py
mars/dataframe/arithmetic/tests/test_arithmetic.py
mars/oscar/backends/context.py
mars/oscar/backends/pool.py
mars/oscar/backends/ray/communication.py
mars/oscar/core.pyx
mars/services/scheduling/worker/quota.py
mars/services/task/analyzer/assigner.py
mars/utils.py

Backport of #2857, #2871 and #2879.

[BACKPORT] Fix dtype infer in DataFrame arithmetic on datetime consts (#2879)

---

mars/oscar/__init__.py
mars/oscar/api.py
mars/oscar/backends/context.py
mars/oscar/backends/core.py
mars/oscar/backends/pool.py
mars/oscar/context.pyx
mars/services/cluster/api/core.py
mars/services/cluster/api/oscar.py
mars/services/cluster/api/web.py
mars/services/cluster/procinfo.py
mars/services/cluster/supervisor/service.py
mars/services/cluster/tests/test_api.py
mars/services/cluster/tests/test_procinfo.py
mars/services/cluster/worker/service.py
mars/services/web/ui/package-lock.json
mars/services/web/ui/src/node_info/NodeResourceTab.js
mars/services/web/ui/src/node_info/NodeStackTab.js
mars/services/web/ui/src/node_info/SupervisorDetailPage.js
mars/services/web/ui/src/node_info/WorkerDetailPage.js

[BACKPORT] Add stack display page on Mars Web (#2876)

---

mars/core/entity/tests/test_utils.py
mars/core/entity/utils.py
mars/core/graph/builder/chunk.py
mars/dataframe/base/cut.py
mars/dataframe/base/describe.py
mars/dataframe/datasource/core.py
mars/dataframe/indexing/index_lib.py
mars/dataframe/merge/merge.py
mars/dataframe/merge/tests/test_merge_execution.py
mars/learn/ensemble/_blockwise.py
mars/learn/metrics/_check_targets.py
mars/learn/metrics/pairwise/pairwise_distances_topk.py
mars/learn/preprocessing/_label.py
mars/learn/utils/multiclass.py
mars/services/lifecycle/supervisor/tracker.py
mars/services/task/supervisor/manager.py
mars/services/task/supervisor/preprocessor.py
mars/services/task/supervisor/processor.py
mars/services/task/supervisor/tests/task_preprocessor.py
mars/services/task/supervisor/tests/test_task_manager.py
mars/tensor/indexing/index_lib.py
mars/tensor/indexing/setitem.py
mars/tensor/rechunk/core.py
mars/tensor/statistics/bincount.py
mars/tensor/statistics/histogram.py
mars/tensor/statistics/quantile.py
mars/tests/test_session.py

This PR optimized iterative tiling by pruning unrelated chunks.
After this PR, the example in #2868 shows as below.
Fixes #2868 .

Optimized iterative tiling by pruning unrelated chunks

---

mars/services/task/api/web.py
mars/services/task/supervisor/manager.py
mars/services/task/supervisor/processor.py
mars/services/task/supervisor/service.py
mars/services/task/tests/test_service.py

[BACKPORT] Fix timeout for `wait_task` (#2883)

---

mars/dataframe/arithmetic/bitwise_or.py
mars/dataframe/arithmetic/core.py
mars/dataframe/base/isin.py
mars/dataframe/base/tests/test_base.py
mars/dataframe/base/tests/test_base_execution.py
mars/dataframe/core.py
mars/dataframe/datasource/from_index.py
mars/dataframe/datasource/read_sql.py
mars/dataframe/indexing/getitem.py
mars/dataframe/indexing/tests/test_indexing_execution.py
mars/opcodes.py
mars/services/storage/handler.py
mars/services/task/api/web.py
mars/tensor/arithmetic/utils.py
mars/utils.py

This PR optimizes `DataFrameIsin`'s tile to avoid potential single-point bottleneck.
Fixes #2856

Optimize `DataFrameIsin`'s tile

---

mars/core/entity/executable.py
mars/deploy/oscar/local.py
mars/oscar/backends/mars/tests/test_mars_actor_context.py
mars/oscar/backends/pool.py
mars/services/session/api/core.py
mars/services/session/api/oscar.py
mars/services/session/api/web.py
mars/services/session/supervisor/core.py
mars/services/session/tests/test_service.py
mars/services/subtask/worker/runner.py
mars/storage/shared_memory.py

[BACKPORT] Make sure errors can be raised in `Actor.__pre_destroy__` (#2887)

---

asv_bench/benchmarks/serialize.py
setup.py

Add a benchmark for serialization.
Fixes #xxxx

Add benchmark for serialization

---

mars/services/meta/__init__.py
mars/services/meta/api/__init__.py
mars/services/meta/api/oscar.py
mars/services/meta/supervisor/core.py
mars/services/meta/tests/test_api.py
mars/services/meta/tests/test_service.py
mars/services/meta/worker/__init__.py
mars/services/meta/worker/core.py
mars/services/meta/worker/service.py

This PR added support for worker meta service.
#2908

Support worker meta service

---

mars/services/lifecycle/api/core.py
mars/services/lifecycle/api/oscar.py
mars/services/lifecycle/api/web.py
mars/services/lifecycle/supervisor/tests/test_tracker.py
mars/services/lifecycle/supervisor/tracker.py
mars/services/task/execution/mars/executor.py

This PR refines lifecycle api to support incref or decref with ref counts.
Fixes #xxxx

Refine lifecycle api to support incref or decref with ref counts

---

README.rst

update Slack link which never expires.

Update Slack link

---

mars/contrib/dask/scheduler.py
mars/contrib/dask/tests/test_dask.py

Add support for `dask.persist`
Fixes #2930

Add support for `dask.persist`

---

docs/source/development/index.rst
docs/source/development/metrics.rst
docs/source/locale/zh_CN/LC_MESSAGES/development/metrics.po

Add metrics docs including:
* How to use metrics
* Metrics backend
* Metrics naming convention
Fixes #xxxx

Add metrics docs

---

.gitignore
mars/core/__init__.py
mars/core/base.py
mars/dataframe/groupby/aggregation.py
mars/oscar/context.pyx
mars/oscar/utils.pyx
mars/services/scheduling/tests/test_service.py
mars/services/scheduling/worker/execution.py
mars/services/subtask/worker/processor.py
mars/services/subtask/worker/tests/test_subtask.py
mars/utils.py

[BACKPORT] Wrap errors in operand execution to protect scheduling service (#2964)

---

azure-pipelines.yml
mars/dataframe/base/apply.py
mars/dataframe/base/tests/test_base.py
mars/dataframe/groupby/tests/test_groupby.py
mars/dataframe/reduction/custom_reduction.py
mars/dataframe/reduction/tests/test_reduction_execution.py
mars/oscar/backends/message.pyx

Fix dtype of series result for `DataFrame.apply`.
Fixes #2965

Fix dtype of series result for `DataFrame.apply`

---

azure-pipelines.yml
mars/dataframe/base/apply.py
mars/dataframe/base/tests/test_base.py
mars/dataframe/groupby/tests/test_groupby.py
mars/dataframe/reduction/custom_reduction.py
mars/dataframe/reduction/tests/test_reduction_execution.py

[BACKPORT] Fix dtype of series result for DataFrame.apply (#2978)

---

mars/deploy/oscar/tests/test_local.py

Fixes ray cases caused by #2975 
Fixes #xxxx

Fix Ray cases

---

.github/workflows/install-minikube.sh
benchmarks/asv_bench/benchmarks/tokenize.py
mars/_utils.pyx

Fix version mismatch between kubernetes and minikube.
Fixes #xxxx

Fix version mismatch between kubernetes and minikube

---

.github/workflows/install-minikube.sh

[BACKPORT] Fix version mismatch between kubernetes and minikube (#2986)

---

LICENSE
mars/config.yml
mars/deploy/oscar/cmdline.py
mars/deploy/oscar/supervisor.py
mars/oscar/backends/mars/pool.py
mars/oscar/backends/ray/pool.py
mars/oscar/backends/ray/tests/test_communication.py
mars/serialization/aio.py
mars/services/web/core.py
mars/supervisor.py
mars/tests/test_cluster.py
mars/utils.py
mars/worker.py
setup.cfg

[BACKPORT] Fix default config to ensure storage backends configured (#2935)

---

mars/dataframe/datasource/dataframe.py
mars/dataframe/datasource/tests/test_datasource.py
mars/dataframe/utils.py

[BACKPORT] Fix potential empty chunks when creating DataFrame from pandas (#2987)

---

mars/contrib/dask/scheduler.py
mars/contrib/dask/tests/test_dask.py

[BACKPORT] Add support for `dask.persist` (#2953)

---

mars/deploy/oscar/tests/test_ray.py
mars/oscar/backends/ray/communication.py

Support new ray cluster through ray client.
Fixes https://github.com/mars-project/mars/issues/2977

[Ray] Support new ray cluster through ray client

---

mars/services/scheduling/worker/execution.py
mars/services/storage/handler.py

[BACKPORT] Skip adding band when fetch shuffle data (#2922)

---

mars/core/entity/chunks.py
mars/dataframe/merge/merge.py
mars/services/scheduling/supervisor/assigner.py
mars/services/scheduling/supervisor/tests/test_assigner.py
mars/utils.py

[BACKPORT] Ignore broadcaster's locality when assign subtasks (#2943)

---

benchmarks/tpch/run_queries.py
mars/oscar/backends/mars/pool.py

Allow selecting TPC queries.
Fixes #xxxx

Allow selecting TPC queries

---

mars/core/operand/base.py
mars/core/operand/tests/test_core.py
mars/dataframe/sort/core.py
mars/dataframe/sort/psrs.py
mars/dataframe/sort/sort_values.py
mars/dataframe/sort/tests/test_sort_execution.py
mars/oscar/backends/mars/pool.py
mars/services/task/analyzer/analyzer.py

Backport of #2984, #2999, #3004 and part of #3005.

[BACKPORT] Fix incorrect result for df.sort_values when specifying multiple ascending (#2984)

---

.github/workflows/pypi-cd.yml
setup.cfg

[BACKPORT] Build web code before CIBW when deploying to PyPI (#3014)

---

mars/services/lifecycle/supervisor/tracker.py
mars/services/storage/api/oscar.py

Fix errors when deleting mapper data & remove duplicate logs.
Fixes #3017

Fix errors when deleting mapper data

---

mars/deploy/oscar/tests/test_ray_dag.py
mars/services/task/execution/ray/executor.py

This pr implement the ray task executor progress function. `TaskProcessor` can get task progress by calling `RayTaskExecutor::get_progress`.
#2893

[Ray] Implement ray task executor progress

---

mars/lib/tbcode.py
mars/lib/tblib/__init__.py
mars/lib/tblib/cpython.py
mars/lib/tblib/decorators.py
mars/lib/tblib/pickling_support.py
mars/lib/tests/test_lib.py
mars/services/task/api/web.py
pyproject.toml

[BACKPORT] Dump remote tracebacks to make local ones more friendly (#3028)

---

docs/source/reference/tensor/special.rst
mars/lib/sparse/__init__.py
mars/lib/sparse/array.py
mars/tensor/special/__init__.py
mars/tensor/special/err_fresnel.py
mars/tensor/special/tests/test_special.py
mars/tensor/special/tests/test_special_execution.py

[BACKPORT] Integrate special error functions (#3060)

---

mars/services/lifecycle/supervisor/tracker.py
mars/services/storage/api/oscar.py

[BACKPORT] Fix errors when deleting mapper data (#3018)

---

mars/conftest.py
mars/dataframe/base/standardize_range_index.py
mars/dataframe/utils.py
mars/lib/sparse/array.py
mars/lib/sparse/tests/test_sparse.py
mars/remote/core.py
mars/tensor/base/shape.py
mars/tensor/base/tests/test_base_execution.py

[BACKPORT] Refine ThreadedServiceContext.get_chunks_meta usage (#3037)

---

mars/dataframe/tests/test_utils.py
mars/dataframe/utils.py

[BACKPORT] Fix chunk index error in auto_merge_chunks (#3057)

---

mars/core/entity/tests/test_utils.py
mars/core/entity/utils.py
mars/services/task/supervisor/tests/task_preprocessor.py

[BACKPORT] Fix recursive_tile that it may cause duplicated tile for one tileable (#3021)

---

mars/core/entity/executable.py
mars/dataframe/base/bloom_filter.py
mars/dataframe/merge/merge.py
mars/dataframe/merge/tests/test_merge.py
mars/dataframe/merge/tests/test_merge_execution.py

[BACKPORT] Disable bloom filter in merge for now (#2967)

---

.github/workflows/platform-ci.yml
mars/conftest.py
mars/dataframe/base/tests/test_base_execution.py
mars/services/task/execution/ray/context.py
mars/services/task/execution/ray/executor.py
mars/services/task/execution/ray/tests/test_ray_execution_backend.py
pyproject.toml

[BACKPORT][Ray] Implements get_chunks_result for Ray execution context (#3023)

---

mars/services/scheduling/worker/execution.py
mars/services/storage/transfer.py

[BACKPORT] Use tell when remove mapper data after execution (#3027)

---

benchmarks/tpch/run_queries.py
mars/core/operand/shuffle.py
mars/dataframe/groupby/aggregation.py
mars/services/task/analyzer/analyzer.py
mars/services/task/analyzer/assigner.py
mars/services/task/analyzer/tests/test_assigner.py

[BACKPORT] Assign reducer ops in task assigner to make them more balanced across cluster (#3048)

---

mars/services/task/execution/api.py
mars/services/task/execution/ray/executor.py
mars/services/task/execution/ray/tests/test_ray_execution_backend.py
mars/services/task/supervisor/processor.py

[BACKPORT][Ray] Destroy Ray executor when the task finish (#3049)

---

mars/dataframe/base/tests/test_base_execution.py
mars/services/task/execution/ray/context.py
mars/services/task/execution/ray/executor.py
mars/services/task/execution/ray/fetcher.py
mars/services/task/execution/ray/tests/test_ray_execution_backend.py
mars/tensor/base/tests/test_base_execution.py

[BACKPORT][Ray] Implements get_chunks_meta for Ray execution context (#3052)

---

.github/workflows/platform-ci.yml
mars/learn/metrics/pairwise/tests/test_haversine_distances.py
mars/services/cluster/api/web.py
mars/services/task/api/web.py
mars/services/web/core.py
mars/services/web/tests/test_core.py

[BACKPORT] Call immutable web API only once when previous call blocks (#3085)

---

mars/_resource.pyx
mars/oscar/batch.py
mars/oscar/core.pyx
mars/serialization/core.pxd
mars/serialization/core.pyx
mars/serialization/tests/test_serial.py
mars/services/web/ui/src/node_info/NodeEnvTab.js
mars/services/web/ui/src/node_info/NodeResourceTab.js

[BACKPORT] Simplify argument passing in actor batch calls (#3098)

---

mars/dataframe/base/tests/test_base_execution.py
mars/services/task/execution/api.py
mars/services/task/execution/mars/config.py
mars/services/task/execution/mars/executor.py
mars/services/task/execution/ray/config.py
mars/services/task/execution/ray/context.py
mars/services/task/execution/ray/executor.py
mars/services/task/execution/ray/tests/test_ray_execution_backend.py
mars/services/task/execution/utils.py
mars/tensor/base/tests/test_base_execution.py

[BACKPORT] [Ray] Implements get_total_n_cpu for Ray execution context (#3059)

---

docs/source/reference/tensor/special.rst
mars/lib/sparse/__init__.py
mars/lib/sparse/array.py
mars/tensor/special/__init__.py
mars/tensor/special/ellip_func_integrals.py
mars/tensor/special/tests/test_special.py
mars/tensor/special/tests/test_special_execution.py

[BACKPORT] Integrate part of scipy elliptic functions and integrals (#3111)

---

mars/deploy/oscar/local.py
mars/deploy/oscar/tests/test_local.py
mars/deploy/oscar/tests/test_ray_dag.py
mars/services/task/execution/ray/config.py
mars/services/task/execution/ray/executor.py

[BACKPORT][Ray] Implement cancel method on Ray task executor (#3044)

---

.github/workflows/benchmark-ci.yml
benchmarks/asv_bench/benchmarks/storage.py
mars/deploy/oscar/tests/test_local.py
mars/oscar/backends/mars/pool.py
mars/oscar/debug.py
mars/tests/test_utils.py

[BACKPORT] Stop importing main module when starting Mars local cluster (#3110)

---

.github/workflows/platform-ci.yml
mars/deploy/oscar/ray.py
mars/deploy/oscar/tests/test_ray.py
mars/oscar/backends/ray/pool.py
mars/tests/test_utils.py
mars/utils.py

[BACKPORT] [Ray] Fix ray worker failover (#3080)

---

mars/deploy/oscar/tests/test_ray_dag.py
mars/lib/ordered_set.py
mars/services/task/execution/ray/config.py
mars/services/task/execution/ray/executor.py
mars/services/task/execution/ray/tests/test_ray_execution_backend.py

[BACKPORT][Ray] Implement gc for ray task executor context (#3061)

---

.github/workflows/platform-ci.yml
mars/dataframe/base/tests/test_base_execution.py
mars/dataframe/datasource/read_raydataset.py
mars/dataframe/datasource/tests/test_datasource_execution.py
mars/services/task/execution/ray/config.py
mars/services/task/supervisor/tests/test_task_manager.py

Fix get dtypes error when dataset is created from pandas DataFrames.
Fixes #2945 
https://github.com/ray-project/ray/pull/23402

[Ray] Fix pandas schema parsing when reading Ray dataset

---

.github/workflows/platform-ci.yml
mars/dataframe/base/tests/test_base_execution.py
mars/dataframe/datasource/read_raydataset.py
mars/dataframe/datasource/tests/test_datasource_execution.py
mars/services/task/execution/ray/config.py
mars/services/task/supervisor/tests/test_task_manager.py

[BACKPORT][Ray] Fix pandas schema parsing when reading Ray dataset (#2946)

---

mars/services/task/execution/ray/config.py
mars/services/task/execution/ray/executor.py
mars/services/task/execution/ray/tests/test_ray_execution_backend.py

This PR fixes the context GC bug of Ray. When the `MARS_CI_BACKEND=ray` env is set, the GC interval will be set to 0 to detect the GC bug as early as possible.
Fixes https://github.com/mars-project/mars/issues/3119

[Ray] Fix Ray context GC

---

.github/workflows/platform-ci.yml
mars/conftest.py
mars/deploy/oscar/tests/test_ray.py
mars/deploy/oscar/tests/test_ray_client.py
mars/deploy/oscar/tests/test_ray_cluster_standalone.py
mars/deploy/oscar/tests/test_ray_dag.py
mars/deploy/oscar/tests/test_ray_fault_injection.py
mars/deploy/oscar/tests/test_ray_scheduling.py
mars/oscar/backends/ray/driver.py

[BACKPORT][Ray] Optimize Ray CI execution time and stability (#3102)

---

mars/deploy/oscar/tests/test_ray_scheduling.py
mars/oscar/backends/ray/pool.py
mars/services/scheduling/supervisor/autoscale.py

[BACKPORT] [Ray] fix auto scale-in hang (#3043)

---

.github/workflows/pypi-cd.yml

Make PyPI user name configurable in secrets of Github Actions.
Fixes #xxxx

Make PyPI user name configurable

---

.github/workflows/pypi-cd.yml
mars/tensor/special/__init__.py
mars/tensor/special/ellip_func_integrals.py
mars/tensor/special/tests/test_special.py

[BACKPORT] Update pytest imports for test_special.py (#3129)

---

mars/deploy/oscar/tests/test_ray.py
mars/deploy/oscar/tests/test_ray_cluster_standalone.py

[BACKPORT][Ray] Fix flaky test `test_optional_supervisor_node` (#3133)

---

mars/tensor/arithmetic/add.py
mars/tensor/arithmetic/multiply.py
mars/tensor/reduction/core.py
mars/tensor/reduction/tests/test_reduction_execution.py
mars/tensor/reshape/reshape.py

[BACKPORT] Fix mt.{cumsum, cumprod} when the first chunk is empty (#3134)

---

benchmarks/asv_bench/benchmarks/graph_builder.py
benchmarks/tpch/run_queries.py
mars/dataframe/align.py
mars/dataframe/indexing/setitem.py
mars/dataframe/utils.py

[BACKPORT] Optimize tile of DataFrame.__setitem__ by reducing time of generating chunk meta (#3140)

---

mars/dataframe/groupby/sample.py
mars/serialization/serializables/core.py
mars/tensor/random/core.py
mars/tensor/random/tests/test_random.py

This PR fix groupby sample when running a multiple process cluster
Fixes #3148

Fix deserializing RandomStateField when its value is None

---

docs/source/reference/tensor/special.rst
mars/services/meta/api/oscar.py
mars/tensor/special/__init__.py
mars/tensor/special/core.py
mars/tensor/special/err_fresnel.py
mars/tensor/special/tests/test_special.py
mars/tensor/special/tests/test_special_execution.py
mars/tensor/utils.py

[BACKPORT] Support scipy special function with tuple output (#3139)

---

mars/core/graph/core.pyx
mars/dataframe/groupby/sample.py
mars/serialization/serializables/core.py
mars/tensor/random/core.py
mars/tensor/random/tests/test_random.py

[BACKPORT] Fix deserializing RandomStateField when its value is None (#3149)

---

mars/dataframe/arithmetic/__init__.py
mars/dataframe/arithmetic/core.py
mars/dataframe/arithmetic/dot.py
mars/dataframe/arithmetic/tests/test_arithmetic_execution.py
mars/dataframe/arithmetic/tests/test_comparison.py
mars/dataframe/arithmetic/tests/test_dot.py
mars/dataframe/base/accessor.py
mars/dataframe/base/tests/test_base.py
mars/dataframe/operands.py
mars/dataframe/tseries/to_datetime.py
mars/typing.py

[BACKPORT] Patch pandas magic functions to allow reverse operands (#3155)

---

ci/reload-env.sh
mars/services/scheduling/worker/execution.py

This PR fix `AttributeError: 'mars.oscar.core.ActorRef' object has no attribute '_remove_mapper_data'`
Fixes #3213

fix remove mapper data

---

mars/dataframe/datastore/to_parquet.py
mars/lib/filesystem/__init__.py
mars/lib/filesystem/_glob.py
mars/lib/filesystem/azure.py
mars/lib/filesystem/base.py
mars/lib/filesystem/core.py
mars/lib/filesystem/fsspec_adapter.py
mars/lib/filesystem/tests/test_filesystem.py
mars/lib/filesystem/tests/test_fsspec_adapter.py
setup.cfg

Integrate with `fsspec` to support cloud storage system like AWS S3, Azure Storage Blob, etc. This PR only implements AzureBlobFileSystem for Azure Blob.
Fixes #xxxx

fsspec integration

---

.github/workflows/platform-ci.yml
mars/conftest.py
mars/dataframe/base/tests/test_base_execution.py
mars/dataframe/contrib/raydataset/tests/test_mldataset.py
mars/dataframe/contrib/raydataset/tests/test_raydataset.py
mars/dataframe/datasource/tests/test_datasource.py
mars/dataframe/datasource/tests/test_datasource_execution.py
mars/dataframe/groupby/tests/test_groupby_execution.py
mars/dataframe/indexing/tests/test_indexing_execution.py
mars/dataframe/merge/tests/test_merge_execution.py
mars/dataframe/statistics/tests/test_statistics_execution.py
mars/deploy/oscar/ray.py
pyproject.toml

- Enable CI in mars/dataframe for Ray DAG
Fixes https://github.com/mars-project/mars/issues/3249

[Ray] Enable CI of mars/dataframe for Ray DAG

---

.github/workflows/platform-ci.yml

- Enable CI of mars/tensor for Ray DAG
Fixes #xxxx

[Ray] Enable CI of mars/tensor for Ray DAG

---

setup.cfg

Bump up required vineyard version to address the CI failure.

---

docs/requirements-doc.txt
mars/dataframe/datasource/date_range.py
mars/dataframe/datasource/tests/test_datasource_execution.py
mars/tensor/stats/tests/test_stats_execution.py

Fix stats tests and pin sphinx version.
Fixes #3312

Fix stats tests and pin sphinx version

---

.github/workflows/platform-ci.yml
README.rst
mars/dataframe/indexing/sample.py

- Fix pandas compatibility issues on Ray executor
- Unpin pandas<1.4 for Ray CI
Fixes https://github.com/mars-project/mars/issues/3252

Fix pandas compatibility issues on Ray executor

---

.github/workflows/platform-ci.yml
azure-pipelines.yml
mars/learn/datasets/tests/test_samples_generator.py
mars/learn/utils/tests/test_multiclass.py
mars/tensor/__init__.py
mars/tests/test_session.py

Fix compatibility with NumPy v1.24

---

mars/lib/nvutils.py
mars/lib/tests/test_nvutils.py

CP one commit from xprobe-inc/mars, for enhancing GPU-related utils.
After merging this, I would open another PR, coming from xprobe-inc/xorbits, to fix a series of similar issues. 
All credits in this PR belong to xprobe-inc.

[ENH] Enrich `nvutils.py` for GPU/CUDA initialization

---

README.rst

Update document domain into readthedocs.

Update document domain into readthedocs

---

mars/learn/contrib/lightgbm/_train.py
mars/learn/contrib/lightgbm/tests/test_classifier.py
mars/metrics/api.py

Fix lgihtgbm train TypeError when running on a cluster.
Fixes #3348

[Learn] Fix lightgbm train TypeError

---

mars/learn/cluster/_k_means_init.py
mars/learn/neighbors/base.py
mars/lib/sparse/tests/test_sparse.py
mars/tensor/reduction/core.py
mars/tensor/statistics/tests/test_statistics.py

Fix test fail with numpy 1.25.
NA

Fix test fail with numpy 1.25

---

mars/dataframe/arrays.py
mars/dataframe/core.py
mars/dataframe/tests/test_arrays.py
mars/learn/contrib/joblib/backend.py
mars/learn/contrib/lightgbm/classifier.py
mars/learn/contrib/lightgbm/core.py
mars/learn/contrib/lightgbm/ranker.py
mars/learn/contrib/lightgbm/regressor.py
mars/learn/contrib/lightgbm/tests/test_classifier.py
mars/learn/contrib/lightgbm/tests/test_ranker.py
mars/learn/contrib/lightgbm/tests/test_regressor.py
mars/learn/contrib/xgboost/classifier.py
mars/learn/contrib/xgboost/core.py
mars/learn/contrib/xgboost/regressor.py
mars/lib/mkl_interface.py
mars/utils.py
setup.cfg
setup.py
versioneer.py

Conversions from pandas DataFrames containing ArrowArrays to arrow RecordBatch is now fixed. Also fix some compatibility issues due to dependency updates.
Fixes #xxxx

Fix conversion from arrow column to arrow RecordBatch

---

.github/workflows/benchmark-ci.yml
.github/workflows/platform-ci.yml
mars/dataframe/contrib/raydataset/dataset.py
mars/dataframe/contrib/raydataset/mldataset.py
mars/dataframe/contrib/raydataset/tests/test_mldataset.py
mars/dataframe/datasource/read_raydataset.py
mars/dataframe/datasource/tests/test_datasource_execution.py
mars/dataframe/merge/tests/test_merge_execution.py
mars/dataframe/utils.py
mars/learn/contrib/lightgbm/_predict.py
mars/learn/contrib/lightgbm/_train.py
mars/learn/contrib/lightgbm/core.py
mars/learn/contrib/lightgbm/tests/test_classifier.py
mars/learn/linear_model/_base.py
mars/learn/linear_model/tests/test_base.py
mars/learn/metrics/pairwise/pairwise.py
mars/storage/vineyard.py
mars/tensor/base/tile.py
mars/tensor/utils.py
mars/utils.py
setup.cfg

Fix test failures
