mars-project/mars

mars/compat/__init__.py
For python 2.7, mock is only required for unittest, but we did not catch the ImportError, so if the mock not installed, the error will be raised if try to import mars.tensor
=> try catch ImportError if mock not installed(#2)

.coveragerc, .travis.yml, bin/travis-prepare-osx.sh, bin/travis-upload.sh, mars/actors/pool/gevent_pool.pyx, mars/scheduler/graph.py, mars/scheduler/resource.py, mars/scheduler/tests/test_main.py, mars/scheduler/tests/test_operand.py, mars/tests/test_promise.py, mars/utils.py, mars/web/session.py, mars/web/tests/test_api.py, requirements-dev.txt, requirements.txt
appveyor.yml not included temporarily, as we need to test Mars in Windows without plasma_store.
Altered cases:
* test_gevent_pool.py::Test::testRemoteConnections
Under MacOS in Travis CI, the number of connections exceeds the system limitation.
* scheduler/test_main.py::Test::testMain
Sometimes KVStoreActor is not ready when the worker is about to register.
* test_promise::Test::testAll
Orders of latter ```gen_promise``` and prior ```thread_body``` may change randomly, which is consistent with the expectation.
Fixed cases:
* test_api::Test::testApi
Web session does not handle timeout properly.
* test_operand.py::Test::testOperandActorWithCancel
stop_graph sometimes get stuck due to sync operation.
Changed dependency:
* numpy >= 1.14, as pyarrow depends on the new API.
=> Add travis config

mars/scheduler/graph.py, mars/web/api.py
fix #21 
Old version:
`ResultReceiverActor` call `GraphActor.get_tiled_tensor` and execute the tiled tensor, however `GraphActor.get_tiled_tensor` will lead to serialization error because of weakref objs.
Now:
delete the `GraphActor.get_tiled_tensor` and add `GraphActor.get_tensor_merge_graph`, in the new method, we generate a executable DAG contains target tensor's chunks and convert them into fetch chunks, then concatenate chunk will concat all of them. `ResultReceiverActor` receives serialized graph and return the value of `Executor.execute_graph`.
=> fix fetch tensor data

mars/scheduler/graph.py, mars/scheduler/tests/test_main.py, mars/web/session.py, mars/web/tests/test_api.py
When there are any errors happened in GraphActor.execute_graph(), the state of the graph is switched to ``GraphState.FAILED`` which can be fetched by queries in the web. This may fix #19.
=> Switch the graph into FAILED when preparation failed

mars/scheduler/graph.py, mars/web/api.py, mars/web/session.py
`GraphActor.stop_graph` will raise `KeyError` when operand actor hasn't been created.
fix #19
=> fix KeyError in stop_graph when graph preparation failed

mars/web/session.py, mars/web/tests/test_api.py
Web session `run` method signature is now same as local session's.
resolve #30
=> Fix web session when submit multiply tensors

mars/deploy/local/tests/test_cluster.py, mars/scheduler/graph.py
When the graph is deserializing and failed, the stop graph is also failed cuz it cannot fetch the chunk graph to do some clear job which make the client hang, fix it and add a test for it.
fix #19
=> Fix stop graph failed due to failure of serialization

mars/tensor/expressions/linalg/core.py, mars/tensor/expressions/linalg/svd.py, mars/tensor/expressions/tests/test_linalg.py
Fix chunk index of tensor of singular values calculated by svd, it should be 1-d.
Fix #55
=> Fix chunk index of tensor of singular values calculated by svd decompition

mars/deploy/local/core.py, mars/deploy/local/session.py, mars/session.py, mars/web/session.py, mars/web/tests/test_api.py
Add endpoint setter in web session so that it still works if web endpoint changed.
=> Support set endpoint for web session to reuse the session but with a different web

mars/tensor/core.py, mars/web/tests/test_api.py
remove `n_parallel` in method `ExecutableTuple .execute` that make tensor tuple executable when default session is web session. for example:
```
In [1]: from mars.session import new_session
In [2]: import mars.tensor as mt
In [3]: sess = new_session('http://0.0.0.0:12345').as_default()
In [4]: mt.linalg.svd(mt.random.rand(5, 5)).execute()
Out[4]: 
[array([[-0.45379165,  0.36902001, -0.61379637,  0.05699746,  0.52716475],
[-0.2773592 ,  0.00516561, -0.30709199,  0.61963784, -0.66692477],
[-0.60954901,  0.47904603,  0.49533444, -0.30122631, -0.25074173],
[-0.366785  , -0.37958852,  0.47355348,  0.54936446,  0.44195826],
[-0.45941679, -0.7001607 , -0.24359684, -0.4693204 , -0.13823948]]),
array([2.57692364, 0.66406779, 0.56091901, 0.25509547, 0.13434668]),
array([[-0.44804643, -0.59556564, …
```
=> Fix execute method of ExecutableTuple

.travis.yml
The 'sudo' is now deprecated in Traivs, remove it. Refer to: [Travis are now recommending removing the __sudo__ tag](https://blog.travis-ci.com/2018-11-19-required-linux-infrastructure-migration)
=> Remove sudo in Travis CI

mars/deploy/local/tests/test_cluster.py, mars/tensor/execution/indexing.py, mars/tensor/execution/tests/test_index_execute.py, mars/tensor/expressions/indexing/getitem.py, mars/tensor/expressions/indexing/setitem.py, mars/tensor/expressions/tests/test_base.py, mars/web/tests/test_api.py
`Index` operand has a special input `indexes` which may be not a tensor type, so we will handle it before `new_tensors` or `new_chunks`. however, when `new_chunks` is called in `GraphActor.get_executable_operand_dag`, only input tensor will be pass, we need get `indexes` from operand itself.
`IndexSetValue` is the same as `index` except that it has another parameter `value`.
resolve #64
=> Fix Index and IndexSetValue operand when new chunks without indexes parameter

mars/api.py, mars/deploy/local/session.py, mars/deploy/local/tests/test_cluster.py, mars/session.py, mars/tensor/execution/core.py, mars/tests/test_session.py, mars/web/session.py, mars/web/tests/test_api.py
Add `fetch` parameter to `execute` and `session.run` to support execute tensor without fetching data. Also refine `session.fetch` to support fetch a few tensors at same time.
This is an enhancement for the #80 .
Resolve #84
=> Support execute tensor without fetching data

mars/deploy/local/tests/test_cluster.py, mars/tensor/expressions/indexing/getitem.py, mars/tensor/expressions/indexing/setitem.py, mars/tensor/expressions/tests/test_indexing.py
Set `indexes` or `value` before generate operand key in `TensorIndexSetValue` and `TensorIndex` if they are provided.
fixes #98
=> Fix setitem and getitem generate same operand key

mars/graph.pyx, mars/tensor/core.py
Use property instead of weak-key dict to store cix in order to accelerate. This avoids __eq__() calls in WeakKeyDictionary when seeking items and can reduce the time of tiling by at least 50%.
N/A
=> Use property instead of weak-key dict to store cix

mars/tensor/execution/tests/test_linalg_execute.py, mars/tensor/expressions/linalg/core.py, mars/tensor/expressions/linalg/qr.py, mars/tensor/expressions/linalg/svd.py, mars/tensor/expressions/tests/test_linalg.py
Add 'sfqr' method for `mt.linalg.qr`.
resolve #114
=> Support QR decomposition on short-and-fat tensor(sfqr method)

mars/tensor/core.py, mars/tests/test_session.py
Implement the `__array__` protocol, so that `numpy.asarray` can convert mars tensor to numpy ndarray.
Resolve #125
=> Implement __array__ protocol for Tensor

docs/source/index.rst
Mistake in index.rst: "import numpy" should be "import numpy as np"
=> Typo in index.rst: "import numpy" should be "import numpy as np"

docs/source/install.rst
Mistake in  install.rst:  "import mars.tensor as mt" should be added in local cluster example.
=> Fix missing import in install.rst

README.rst, docs/source/install.rst, mars/deploy/local/core.py, mars/scheduler/service.py, mars/worker/__main__.py, mars/worker/service.py
Previously Mars workers are started on machines with sufficient memory, and the default value of --cache-mem, 48%, works well. When it is started on a machine with insufficient memory, however, the worker fails when doing memory test. Now we change the strategy by using half of free memory to ensure that it can start under most of the circumstances.
What's more, we add fixes on docs to add memory tuning section and errors on endpoints.
#140 (Fix not added, just for verification)
=> Fix worker start fail on machines with insufficient memory (also some doc fixes)

.travis.yml, bin/fix-gevent-cov.sh, mars/compat/__init__.py, mars/worker/__main__.py, mars/worker/service.py
Fix BrokenPipeErrors caused by ``--phy-mem`` arg and during the running procedure under Python 2.7.
Fixes #158
=> Fix --phy-mem arg error and BrokenPipeErrors under Python 2.7

mars/serialize/jsonserializer.pyx, mars/serialize/pbserializer.pyx
Use dataserializer to serde ndarray instead of `numpy.save` and `numpy.load`.
**Note that this will break compatibility if the client is 0.1.x and server is 0.2.x, vice versa.**
Resolve #160
=> Use dataserializer to serde ndarray in protobuf and json serializers instead of numpy.save and numpy.load

mars/serialize/core.pxd, mars/serialize/core.pyx, mars/serialize/dataserializer.py, mars/serialize/jsonserializer.pyx, mars/serialize/pbserializer.pyx, mars/serialize/protos/value.proto, mars/serialize/protos/value_pb2.py, mars/serialize/tests/test_serialize.py, mars/worker/chunkstore.py
Add IndexField, SeriesField, DataFrameField for protobuf and json serializer, remove DataTuple for dataserializer which is not needed any more.
Note that this PR will break compatibility between 0.1.x and 0.2.x.
Resolve #161
=> Add IndexField, SeriesField, DataFrameField for protobuf and json serializer, remove DataTuple for dataserializer

.travis.yml, bin/travis-prepare-osx.sh, setup.py
1. Use Miniconda instead of pyenv to run ci on MacOS to save run time.
2. Remove Cython.Coverage when not needs. This reduces fluctuation of coverage when running tests with and without CYTHON_TRACE.
NA
=> Use miniconda to test on OSX

.travis.yml, bin/travis-prepare-osx.sh, mars/base_app.py, mars/compat/__init__.py, mars/config.py, mars/deploy/local/core.py, mars/deploy/local/session.py, mars/deploy/local/tests/test_cluster.py, mars/kvstore.py, mars/lib/sparse/core.py, mars/scheduler/__main__.py, mars/scheduler/tests/test_main.py, mars/tensor/execution/array.py, mars/tensor/execution/core.py, mars/tensor/execution/fft.py, mars/tensor/execution/linalg.py, mars/web/__main__.py, mars/web/session.py, mars/worker/__main__.py, mars/worker/service.py, mars/worker/tests/test_main.py, mars/worker/tests/test_service.py
1. Decouple services from applications. Change services into attributes of applications.
2. Merge ``start_local`` into ``start`` in ``WorkerService``. A ``distributed`` arg is provided to configure start mode.
3. Add cases so that every branch of memory size calculation is covered.
4. Accelerate testing by removing ``--cov-append``.
1. In ``BaseApplication``, ``start_service`` is renamed as ``start`` and ``stop_service`` is renamed as ``stop``. Those changes may break compatibility of inherited applications.
Deal with #167 (#171 will fix the bug on v0.1).
=> Decouple services from applications & unify worker start logic

mars/worker/__main__.py
Provide a straightforward solution to fix cache_mem parse error on v0.1. Complete refactored version is in #170 which will be released with v0.2.
Fixes #167.
=> Fix parse error of cache_mem on v0.1

mars/scheduler/chunkmeta.py, mars/scheduler/operand.py, mars/scheduler/tests/test_chunkmeta.py
1. Add ``batch_set_chunk_broadcasts`` to support configuring broadcast in batch.
2. Add ``batch_set_chunk_meta`` to allow setting metas in batch. Useful in shuffle.
Fixes #165
=> Add batch support for broadcasts and local meta setting

.travis.yml
Fix CI failure under python 2.7 in osx, caused by newly-released setuptools 40.7.0.
Related error log:
```
Collecting scandir; python_version < "3.5" (from pathlib2>=2.2.0; python_version < "3.6"->pytest>=3.5.0->-r requirements-dev.txt (line 6))
Downloading https://files.pythonhosted.org/packages/16/2a/557af1181e6b4e30254d5a6163b18f5053791ca66e251e77ab08887e8fe3/scandir-1.9.0.tar.gz
Complete output from command python setup.py egg_info:
/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/extension.py:133: UserWarning: Unknown Extension options: 'optional'
warnings.warn(msg)
running egg_info
creating pip-egg-info/scandir.egg-info
writing pip-egg-info/scandir.egg-info/PKG-INFO
writing top-level names to …
```
=> Fix CI failure under python 2.7 in osx

.travis.yml, appveyor.yml, bin/travis-build-wheels.sh, bin/travis-upload.sh, mars/_version.py, requirements-wheel.txt
Use fixed versions of dependencies to build wheels to reduce potential errors caused by upgraded versions of dependencies.
Tag build see https://travis-ci.org/wjsi/mars/builds/486882560, test packages at testpypi.
Fixes #197
=> Use fixed versions of dependencies to build wheels

mars/base_app.py, mars/cluster_info.py, mars/core.py, mars/lib/gipc.pyx, mars/operands/random.py, mars/scheduler/service.py, mars/scheduler/tests/test_kvstore.py, mars/scheduler/tests/test_main.py, mars/worker/execution.py, mars/worker/service.py
Fix starting with multiple schedulers with ``--schedulers`` arg, also add cases for multiple schedulers with and without etcd. Remove profile in ``base_app`` as it is useless under multiple process scenarios. 
Fixes #201
=> Fix starting with multiple schedulers with --schedulers

mars/base_app.py, mars/deploy/local/core.py, mars/deploy/local/tests/test_cluster.py, mars/lib/gipc.pyx, mars/scheduler/chunkmeta.py, mars/tensor/expressions/base/expand_dims.py, mars/tensor/expressions/random/dirichlet.py, mars/worker/service.py
Fix process clean up when local cluster terminates by restoring default SIGINT handler. Also fixes codacy errors.
#205
=> Fix process clean up when local cluster terminates

mars/tensor/expressions/datasource/core.py, mars/tensor/expressions/tests/test_core.py
Backport of #210 
Note that the PR has been modified due to the reason that there is no `_new_chunks` and `_new_entities` in v0.1 branch, instead, `new_chunks` and `new_tensors` should be involved.
=> [BACKPORT] Fix bug that TensorZeros generate same key even if their shapes are different in TensorDiag.tile (#210)

mars/scheduler/tests/test_analyzer.py, mars/tensor/execution/tests/test_core_execute.py, mars/tensor/expressions/datasource/core.py, mars/tensor/expressions/tests/test_core.py, mars/tests/test_eager_mode.py, mars/tests/test_session.py, mars/worker/tests/test_main.py
Fix bug that chunks of ones and zeros with same shape generated different key.
Fixes #214
=> Fix bug that chunks of ones and zeros with same shape generated different key

mars/executor.py, mars/tests/test_session.py
Skip the output chunks not in the graph to ensure they will not be executed.
resolve #220
=> Fix execute one of the multiple output tensors

mars/tensor/execution/tests/test_core_execute.py, mars/tensor/expressions/datasource/core.py, mars/tensor/expressions/tests/test_core.py
=> [BACKPORT] Fix bug that chunks of ones and zeros with same shape generated different key

mars/scheduler/tests/test_kvstore.py, mars/scheduler/tests/test_main.py, mars/tensor/core.py, mars/tensor/expressions/tests/test_base.py, mars/worker/chunkholder.py, mars/worker/chunkstore.py, mars/worker/service.py, mars/worker/tests/test_chunkholder.py, mars/worker/tests/test_execution.py, mars/worker/tests/test_transfer.py, mars/worker/transfer.py, mars/worker/utils.py
Use random object id in plasma store to avoid potential collision. A worker-wide kv store maintains mappings between chunk keys and plasma object ids.
Fixes #224 #233
=> Use random object id in plasma store to avoid potential collision

mars/graph.pyx, mars/scheduler/analyzer.py, mars/scheduler/graph.py, mars/scheduler/tests/test_analyzer.py, mars/scheduler/tests/test_graph.py, mars/tensor/execution/tests/test_datasource_execute.py, mars/tests/test_graph.py
Assign initial chunks to dominant workers for eager mode to reduce data transfer caused by random allocation. The main changes are in ```calc_initial_assignments```, where an ```input_chunk_metas``` argument is added to provide information on data distribution. Allocations are done in ```_iter_assignments_by_transfer_sizes```.
Fixes #195
=> Assign initials given existing data in eager mode

mars/_version.py, mars/executor.py, mars/tensor/execution/tests/test_linalg_execute.py
Add `deleted_chunk_keys` in executor to avoid duplicate deletion.
resolve #248
=> Fix executor's behavior of result deletions

mars/tensor/execution/tests/test_linalg_execute.py, mars/tensor/expressions/linalg/inv.py
Use input tensor's `nsplits` to set `eye`'s chunk size instead of first chunk's shape in `TensorInv`'s tile.
resolve #250
=> Fix TensorInv tile when input tensor has only one chunk

.travis.yml, mars/scheduler/tests/test_main.py
Enable using ``COVERALLS_PARALLEL=true`` for coveralls according to https://docs.coveralls.io/parallel-build-webhook to reduce errors.
NA
=> Use parallel build for coveralls

.coveragerc, .coveragerc-tensor, .travis.yml, mars/lib/sparse/__init__.py, mars/lib/sparse/matrix.py, mars/lib/sparse/tests/test_sparse.py, mars/lib/sparse/vector.py, mars/tensor/execution/linalg.py, mars/tensor/execution/tests/test_linalg_execute.py, mars/tensor/expressions/linalg/inv.py, mars/tensor/expressions/linalg/solve.py, mars/tensor/expressions/linalg/solve_triangular.py, mars/tensor/expressions/tests/test_linalg.py
=> [BACKPORT] Fix solve_triangular operand's sparse attributes & use parallel build for coveralls (#257, #261)

mars/executor.py, mars/scheduler/analyzer.py, mars/scheduler/assigner.py, mars/scheduler/graph.py, mars/scheduler/tests/test_assigner.py, mars/scheduler/tests/test_graph.py, mars/tensor/core.py, mars/tensor/execution/arithmetic.py, mars/tensor/execution/base.py, mars/tensor/execution/cp.py, mars/tensor/execution/indexing.py, mars/tensor/execution/ne.py, mars/tensor/execution/reshape.py, mars/tensor/execution/tests/test_base_execute.py, mars/tensor/execution/tests/test_index_execute.py, mars/tensor/execution/tests/test_linalg_execute.py, mars/tensor/execution/tests/test_numexpr_execute.py, mars/tensor/execution/utils.py, mars/tensor/expressions/base/argwhere.py, mars/tensor/expressions/base/repeat.py, mars/tensor/expressions/fuse/core.py, mars/tensor/expressions/indexing/getitem.py, mars/tensor/expressions/indexing/nonzero.py, mars/tensor/expressions/reshape/reshape.py, mars/tensor/expressions/tests/test_base.py, mars/tensor/expressions/tests/test_indexing.py, mars/tensor/expressions/tests/test_reshape.py, mars/tensor/expressions/utils.py, mars/worker/chunkstore.py, mars/worker/execution.py
Remove all rough_nbytes and rough_sizes from tensor expressions and add size estimation in execution. Also remove chunk registration when creation failed.
Fixes #265
Fixes #269
=> Remove rough_size from tensor & remove chunk registration when creation failed

mars/tensor/execution/tests/test_linalg_execute.py, mars/tensor/expressions/linalg/lu.py, mars/tensor/expressions/tests/test_linalg.py
Remove the limitation in lu decomposition that all of input tensor's chunks must be square.
resolve #271
=> Remove chunk square limitation in lu decomposition

mars/tests/test_eager_mode.py, mars/utils.py
Use `finally` statement to make sure `_kernel_mode.eager` set to `None`.
resolve #268
=> Fix kernel_mode decorator when an exception occurred in wrapped function 

mars/deploy/local/tests/test_cluster.py, mars/executor.py, mars/scheduler/graph.py, mars/tensor/expressions/fetch/core.py, mars/tensor/expressions/utils.py, mars/utils.py
Pass sparse parameter when create fetch operand and skip the fetch chunk when estimate the needed memory size.
fixes #276
=> Pass sparse parameter when create fetch operand

.coveragerc, .coveragerc-tensor, mars/errors.py, mars/executor.py, mars/promise.py, mars/tensor/execution/linalg.py, mars/tests/test_promise.py, mars/worker/chunkholder.py, mars/worker/chunkstore.py, mars/worker/execution.py, mars/worker/taskqueue.py, mars/worker/tests/test_chunkholder.py, mars/worker/tests/test_daemon.py, mars/worker/utils.py
Given the implementation of allocating mmap in Apache Arrow, as is listed below,
https://github.com/apache/arrow/blob/7ddad36e0fd3707f0a893bbfda3e2f9149909708/cpp/src/plasma/malloc.cc#L163
the granularity when allocating mmap files are multiplied by 2 every time when data chunk is allocated. This behavior limit the total amount of memory plasma store can allocate when checked by original version of ``get_actual_capacity``, which allocates memory by 4MB block. To reduce the influence of this behavior, the new version of ``get_actual_capacity`` first tries to allocate 90% of the requested size, then allocates the rest part in an iterative manner. Test results show that the new strategy can effectively enlarge the size of allocated cache memory.
Fixes #286
=> Use new allocation strategy to circumvent inflating granularity in arrow

mars/api.py, mars/deploy/local/session.py, mars/deploy/local/tests/test_cluster.py, mars/executor.py, mars/scheduler/graph.py, mars/scheduler/session.py, mars/tests/test_session.py, mars/web/api.py, mars/web/session.py
Users can submit tensors with specify `compose=False` to run without fusion, including distributed mode and local mode.
resolve #290
=> Support execute graph without fusion

mars/executor.py, mars/tests/test_executor.py
When calculating memory size when ``mock=True``, use maximal calculation size in calculation to replace memory size estimation for the final node.
Fixes #308
=> Fix execution size for fuse nodes

mars/tensor/execution/arithmetic.py, mars/tensor/execution/tests/test_arithmetic_execute.py, mars/tensor/expressions/arithmetic/core.py
Fix the behavior of arithmetic operands with specified `where`.
refer to `Numpy`'s Docs:
> where : array_like, optional
Values of True indicate to calculate the ufunc at that position, values of False indicate to leave the value in the output alone.
fixes #306 
fixes #282
=> Fix arithmetic calculation with `where`

mars/worker/__main__.py, mars/worker/service.py
As arrow removes ``use_one_memory_mapped_file`` in ARROW-4296, we shall remove it when starting plasma_store.
NA
=> Remove use_one_memory_mapped_file argument when starting plasma_store

mars/config.py, mars/worker/__main__.py, mars/worker/chunkholder.py, mars/worker/chunkstore.py, mars/worker/service.py, mars/worker/tests/test_chunkholder.py, mars/worker/tests/test_execution.py, mars/worker/tests/test_transfer.py, mars/worker/transfer.py, mars/worker/utils.py
Try the old calling routine before removing the argument and retry for compatibility. Note that this is related to but NOT a straightforward backport of #318 and review is needed.
This also includes a back-port for #226 to solve error in testHolder.
NA
=> Resolve use_one_memory_mapped_file argument issue when starting plasma_store

mars/actors/pool/gevent_pool.pyx, mars/node_info.py, mars/resource.py, mars/tests/test_resource.py, mars/utils.py, mars/web/templates/worker_detail.html, mars/worker/chunkholder.py, mars/worker/service.py, mars/worker/status.py
Add support for detecting NVIDIA GPU resources by grabbing outputs from ``nvidia-smi -q -x``. We do not need to call it very frequently to daemon resource usage as we did for host memory.
Fixes #316
=> Add support for detecting NVIDIA GPU resources

mars/tensor/execution/tests/test_linalg_execute.py, mars/tensor/expressions/linalg/cholesky.py
Remove the limitation in cholesky decomposition that all chunks must be square.
We can use cholesky decomposition to solve pseudo-inverse matrix, for a non-square matrix `A`, `A.T.dot(A)` is always a symmetric matrix.
fixes #326
=> Remove chunk square limitation in cholesky decomposition

mars/session.py, mars/tensor/execution/datastore.py, mars/tensor/execution/tests/test_datastore_execute.py, mars/tensor/expressions/datasource/scalar.py, mars/tensor/expressions/reduction/core.py, mars/tensor/expressions/tests/test_datastore.py, mars/tensor/expressions/utils.py
Fix that when setting tiledb DenseArray' data with slice within numpy int64, error will be raised. Also rename all `np.asscalar` to scalar.item() cause that `np.asscalar` is deprecated.
Fixes #334
=> Fix tiledb error when numpy int64 in shape

mars/base_app.py, mars/config.py, mars/deploy/local/core.py, mars/promise.py, mars/scheduler/assigner.py, mars/scheduler/chunkmeta.py, mars/scheduler/operands/base.py, mars/scheduler/operands/common.py, mars/scheduler/operands/tests/test_common_exec.py, mars/scheduler/operands/tests/test_common_ut.py, mars/scheduler/resource.py, mars/scheduler/tests/test_main.py, mars/tests/test_promise.py, mars/tests/test_utils.py, mars/utils.py, mars/worker/chunkstore.py, mars/worker/execution.py, mars/worker/service.py, mars/worker/spill.py, mars/worker/tests/base.py, mars/worker/tests/test_daemon.py, mars/worker/tests/test_execution.py, mars/worker/tests/test_transfer.py, mars/worker/transfer.py, mars/worker/utils.py
* Broadcast peer worker failures to workers and reject corresponding promise calls
* Fix KeyError in PlasmaChunkStore when previous transfer does not stop elegantly and stops fail-over procedure
* Fix worker start failure caused by logging in gipc under some installations
Fixes #240
=> Allow batch rejecting peers in workers by endpoints

mars/session.py, mars/tensor/execution/datastore.py, mars/tensor/execution/tests/test_datastore_execute.py, mars/tensor/expressions/datasource/scalar.py, mars/tensor/expressions/reduction/core.py, mars/tensor/expressions/tests/test_datastore.py, mars/tensor/expressions/utils.py
=> [BACKPORT] Fix tiledb error when numpy int64 in shape (#339)

.coveragerc, .coveragerc-tensor, mars/actors/__init__.py, mars/actors/core.pxd, mars/actors/core.pyx, mars/actors/pool/gevent_pool.pyx, mars/actors/pool/tests/test_gevent_pool.py, mars/scheduler/tests/op_delayer.py, setup.py
Add plugin mechanism for actors, now we can use ``register_actor_implementation`` to replace actor implementations in plugins.
=> Support replacing actor classes given registration

mars/tensor/execution/random.py, mars/tensor/execution/tests/test_random_execute.py
Estimate result size of sparse ``TensorRandInt`` by multiplying its ``nbytes`` with density.
Fixes #354
=> Add size estimator for sparse randint

mars/api.py, mars/deploy/local/session.py, mars/scheduler/graph.py, mars/serialize/dataserializer.py, mars/serialize/tests/test_serialize.py, mars/web/api.py, mars/web/session.py, mars/web/tests/test_api.py
Pass an acceptable compression list when fetching results from server. The server end will send result directly if existing compression is in the compatible list, or pick a supported compression to encode the data.
Fixes #344
=> Pass an acceptable compression list when fetching results from server

mars/_utils.pyx, mars/promise.py, mars/tests/core.py, mars/tests/test_promise.py, mars/tests/test_utils.py, mars/worker/calc.py, mars/worker/chunkholder.py, mars/worker/execution.py, mars/worker/quota.py, mars/worker/tests/base.py, mars/worker/tests/test_chunkholder.py, mars/worker/tests/test_dispatcher.py, mars/worker/tests/test_execution.py, mars/worker/tests/test_quota.py, mars/worker/tests/test_transfer.py, mars/worker/tests/test_utils.py, mars/worker/transfer.py
1. Add capability for renaming allocation keys
2. Add test cases to refine coverage for QuotaActor
Fixes #335
=> Allow renaming allocation keys in QuotaActor

mars/deploy/local/session.py, mars/session.py
As introduced in #294 , `WebSession` support passing arguments like `req_session`, `new_session` should support passing `**kwargs` when creating web session.
=> Support **kwargs in new_session

mars/serialize/dataserializer.py, mars/serialize/tests/test_serialize.py, mars/worker/chunkstore.py
Removes DataTuple in v0.1 as standard tuples can also be serialized with pyarrow without copy.
Fixes #370
=> Remove DataTuple in v0.1

mars/core.py, mars/dataframe/__init__.py, mars/dataframe/core.py, mars/dataframe/execution/arithmetic.py, mars/dataframe/execution/tests/test_arithmetic_execution.py, mars/dataframe/expressions/arithmetic/add.py, mars/dataframe/expressions/arithmetic/core.py, mars/dataframe/expressions/arithmetic/tests/__init__.py, mars/dataframe/expressions/arithmetic/tests/test_utils.py, mars/dataframe/expressions/arithmetic/utils.py, mars/dataframe/expressions/tests/test_arithmetic.py, mars/dataframe/expressions/tests/test_utils.py, mars/dataframe/expressions/utils.py, mars/dataframe/utils.py, mars/graph.pyx, mars/serialize/jsonserializer.pyx, mars/serialize/pbserializer.pyx, mars/serialize/protos/indexvalue.proto, mars/serialize/protos/indexvalue_pb2.py, mars/tensor/core.py
This PR aims to enhance the tile of DataFrame's `add` including:
1. If some axis of both side of inputs have only 1 chunk, avoid shuffle despite they are not monotonic. This is useful because real data may have small size of columns(1 chunk on `columns`), we could avoid shuffle even if the columns are not ordered.
2. Generate `index_value` and `columns` for all chunks generated during the tile of arithmetic.
3. Prevent generating `DataFrameIndexAlignMap` as far as possible, for example, if both side of inputs have the same chunked index and columns.
Resolves #364
=> Enhance tile for DataFrame's `add`

LICENSE, MANIFEST.in, mars/_utils.pyx, mars/actors/distributor.pyx, mars/actors/pool/tests/test_gevent_pool.py, mars/dataframe/utils.py, mars/lib/mmh3_src/MurmurHash3.cpp, mars/lib/mmh3_src/MurmurHash3.h, mars/lib/mmh3_src/mmh3module.cpp, mars/scheduler/distributor.py, mars/utils.py, setup.py
Use MurmurHash (https://github.com/hajimes/mmh3) to replace hashlib.md5 when calculating hash, both for tokenize and hash_index.
Fixes #369
=> Use MurmurHash3 instead of hashlib when calculating hash

mars/core.py, mars/tensor/execution/linalg.py, mars/tensor/execution/tests/test_linalg_execute.py, mars/tensor/expressions/linalg/lu.py, mars/tensor/expressions/linalg/solve_triangular.py, mars/tensor/expressions/tests/test_linalg.py
Try to let `lu` decomposition support non-square matrix.
An issue is that because we append zeros on axis 0 or 1, the `SolveTriangular` op which generated in tiling of `lu` could oftenly encounter  the error: `LinAlgError: singular matrix: resolution failed at diagonal 0
` which is quite annoying. Thus I try to use `np.linalg.lstsq` to address the problem, but the effort is enabled only for the `SolveTriangular` generated by `lu`.
Resolves #380
=> Support non-square matrix for lu decomposition

mars/core.py, mars/tensor/expressions/linalg/core.py, mars/tensor/expressions/linalg/qr.py, mars/tensor/expressions/tests/test_linalg.py
Try to fix the wrong `nsplits` generated by QR decomposition.
Fixes #384 .
=> Fix `nsplits` of tensors generated in the tile of QR decomposition

mars/api.py, mars/distributor.py, mars/scheduler/graph.py, mars/scheduler/operands/base.py, mars/scheduler/session.py, mars/tests/test_distributor.py, mars/utils.py, mars/web/server.py, mars/worker/tests/test_quota.py
Submit tiling of tensors into a thread pool and then gevent can switch to other lines. What's more, the function of GraphMetaActor is enhanced to hold state of every operand.
Fixes #389
=> Fix stuck web interface when tiling a graph

mars/web/api.py, mars/web/session.py
Pass string 0 or 1 instead of boolean string in web sessions to fix mismatch compose arg.
Fixes #394
=> Fix defunct compose option in web session

mars/dataframe/execution/arithmetic.py, mars/dataframe/execution/core.py, mars/dataframe/execution/merge.py, mars/dataframe/execution/tests/test_arithmetic_execution.py, mars/dataframe/execution/tests/test_datasource_execution.py, mars/dataframe/expressions/__init__.py, mars/dataframe/expressions/arithmetic/core.py, mars/dataframe/expressions/merge/__init__.py, mars/dataframe/expressions/merge/concat.py, mars/dataframe/expressions/tests/test_arithmetic.py, mars/dataframe/expressions/utils.py, mars/executor.py, mars/session.py, mars/tensor/expressions/utils.py, mars/utils.py
Support `execute_dataframe` for `mars.executor.Executor` that the DataFrame chunks can be concatenated into one chunk.
Resolves #234
=> Support concatenating DataFrame chunks into one

mars/tensor/expressions/linalg/core.py, mars/tensor/expressions/linalg/qr.py, mars/tensor/expressions/tests/test_linalg.py
=> [BACKPORT] Fix `nsplits` of tensors generated in the tile of QR decomposition (#387)

mars/dataframe/core.py, mars/dataframe/expressions/fetch/core.py, mars/dataframe/expressions/tests/test_datasource.py, mars/graph.pyx, mars/scheduler/graph.py, mars/serialize/core.pyx, mars/serialize/jsonserializer.pyx, mars/serialize/pbserializer.pyx, mars/serialize/tests/test_serialize.py, mars/utils.py
Fix serialization of DataFrame's `index_value` or `columns_value` if its type is int64.
This PR also optimizes serialization of OneOfField, when the value is not None, and no type in OneOfField can be matched, error will be raised.
Fixes #400
=> Fix serialization of DataFrame's index_value or columns_value if its type is int64

mars/serialize/core.pxd, mars/serialize/core.pyx, mars/serialize/jsonserializer.pyx, mars/serialize/pbserializer.pyx, mars/serialize/tests/test_serialize.py
Reference type in `ReferenceField` or `ListField` with reference should be checked.
Fixes #413
=> Check reference type in serialization

.gitignore, .travis.yml, mars/api.py, mars/deploy/local/tests/test_cluster.py, mars/scheduler/__init__.py, mars/scheduler/assigner.py, mars/scheduler/chunkmeta.py, mars/scheduler/graph.py, mars/scheduler/operands/base.py, mars/scheduler/operands/common.py, mars/scheduler/operands/tests/test_common_exec.py, mars/scheduler/operands/tests/test_common_ut.py, mars/scheduler/session.py, mars/scheduler/tests/test_assigner.py, mars/scheduler/tests/test_chunkmeta.py, mars/scheduler/tests/test_session.py, mars/scheduler/utils.py, mars/tests/test_api.py, mars/web/tests/test_api.py, mars/worker/calc.py, mars/worker/execution.py, mars/worker/tests/test_execution.py, mars/worker/transfer.py, mars/worker/utils.py
Replace central ChunkMetaActor with a local client to reduce latency.
Fixes #420
=> Remove central ChunkMetaActor in schedulers

mars/api.py, mars/config.py, mars/scheduler/tests/test_kvstore.py, mars/scheduler/tests/test_main.py, mars/serialize/dataserializer.py, mars/serialize/tests/test_serialize.py, mars/tests/core.py, mars/tests/test_kvstore.py, mars/web/api.py, mars/web/session.py, mars/web/tests/test_api.py, mars/worker/__main__.py, mars/worker/service.py, mars/worker/spill.py, mars/worker/transfer.py
1. Use Enum instead of numbers to specify compression types.
2. Use options.worker.disk_compression and options.worker.transfer_compression to specify type of compression.
Closes #423
=> Use Enum instead of numbers to specify compression types

mars/resource.py, mars/scheduler/assigner.py, mars/tensor/execution/core.py, mars/tensor/execution/tests/test_core_execute.py, mars/tensor/execution/utils.py, mars/worker/execution.py
Fix execution memory size estimation for fused dags sent to workers. The value is now total stored size in chunk_result minus total size of Fetch nodes.
Note that we assume that Numexpr and Cupy will automatically reuse allocated buffers if the size is sufficient, we does not calculate memory size of inputs when estimating sizes for CpFuse and NeFuse. The arg ``update_local`` indicates the behavior we use when calculating sizes.
#434 (fix for v0.1)
=> Fix memory size estimation for Fuse nodes in v0.1

mars/executor.py, mars/resource.py, mars/tensor/execution/utils.py, mars/tests/test_executor.py, mars/worker/execution.py
Fix execution memory size estimation for fused dags sent to workers. The value is now total stored size in chunk_result minus total size of Fetch nodes.
Note that we assume that Numexpr and Cupy will automatically reuse allocated buffers if the size is sufficient, we does not calculate memory size of inputs when estimating sizes for CpFuse and NeFuse. The arg ``update_local`` indicates the behavior we use when calculating sizes.
Fixes #434
=> Fix memory size estimation for Fuse nodes in v0.2

mars/resource.py, mars/scheduler/graph.py, mars/scheduler/operands/base.py, mars/scheduler/operands/common.py, mars/scheduler/tests/test_graph.py
Simplify building executable graphs by adding existing operands into DAGs directly. The building step is also moved to graph initialization to reduce runtime load.
Fixes #454
=> Simplify building executable graph

mars/dataframe/expressions/arithmetic/core.py, mars/dataframe/expressions/tests/test_arithmetic.py, mars/dataframe/utils.py
If adding two dataframes with same index and columns, shuffle can be avoided. Add more ut for shuffle case.
Fixes #428
=> Avoid shuffle for adding two dataframes whose index and columns are identical

mars/actors/pool/gevent_pool.pyx, mars/promise.py, mars/tests/test_promise.py
This PR mainly deals with reference counting issues in ``promise`` module.
1. Fix cycled references for accept / reject handlers (as is stated in #473) by setting these handlers to ``None`` after they are called.
2. Deal with ``_promise_pool`` more carefully. References are added to ``_promise_pool`` only when the promise object have unfinished calls.
3. Stop calling ``step_next`` directly in the wrapped function if the promise has immediate results. Instead the function will return a tuple containing ``_internal_step_next`` and args. This can help python cleaning previous results.
4. A ``spawn_promised`` function is added to ``PromiseActor`` to make use of async libraries.
Fixes #473
=> Fix promise reference counting issues

mars/_utils.pyx, mars/actors/pool/messages.pxd, mars/actors/pool/messages.pyx, mars/config.py, mars/scheduler/graph.py, mars/scheduler/resource.py, mars/scheduler/tests/test_main.py, mars/worker/transfer.py
1. Add a heartbeat actor to help judging whether the scheduler is busy.
2. Record worker list when assigning initial nodes to help decide whether to start fail-over.
Fixes #469
Fixes #470
=> Add resource heartbeat to avoid fake worker death

docs/source/install.rst, mars/base_app.py, mars/web/__main__.py, mars/web/tests/test_api.py
Merge --ui-port option into -p for Mars Web. The old option is still kept for compatibility.
Fixes #481
=> Remove --ui-port option for Mars Web

.coveragerc, .coveragerc-tensor, mars/lib/nvutils.py, mars/lib/sparse/core.py, mars/node_info.py, mars/resource.py, mars/scheduler/node_info.py, mars/serialize/dataserializer.py, mars/tensor/execution/array.py, mars/tensor/execution/core.py, mars/tests/test_resource.py, mars/tests/test_utils.py, mars/utils.py, mars/worker/status.py
1. Use lazy import for cupy and cudf to stop calling cuInit() before forking
2. Use ctypes instead of calling nvidia-smi to retrieve GPU status
Fixes #479
=> Use lazy import for cupy and cudf

mars/scheduler/operands/core.py
Specify an ` __order__ ` attribute in Enum class `OperandState`.
fixed #501
=> Specify an __order__ attribute in Enum class OperandState

.travis.yml, bin/travis-install-conda.sh, mars/config.py, mars/deploy/local/core.py, mars/deploy/local/tests/test_cluster.py, mars/web/api.py, mars/web/dashboard.py, mars/web/scheduler_pages.py, mars/web/server.py, mars/web/task_pages.py, mars/web/templates/base.html, mars/web/templates/scheduler_list.html, mars/web/templates/task_list.html, mars/web/templates/task_operands.html, mars/web/templates/worker_list.html, mars/web/tests/test_api.py, mars/web/worker_pages.py
Previously Mars web uses bokeh applications to render all the pages, which is inflexible as bokeh does not support urls with multiple slashes, and we have to use complex query strings. To avoid this and pave way for more information on the web ui, tornado handlers are now used and bokeh applications are limited to graphs and embedded into pages with scripts.
Dynamic refreshing issue of progress graphs are also fixed.
Fixes #510
=> Refactor web using standalone tornado handlers

mars/dataframe/core.py, mars/tests/test_eager_mode.py
Define `__str__` and `__repr__` for `DataFrameData`, `IndexData` and `SeriesData` properly, as what we have done for `TensorData`, and respect the eager mode settings.
#508.
=> Define __str__ and __repr__ for DataFrame, Index, and Series.

mars/api.py, mars/deploy/local/session.py, mars/scheduler/graph.py, mars/scheduler/mutable.py, mars/scheduler/session.py, mars/session.py, mars/tensor/core.py, mars/tensor/expressions/utils.py, mars/tests/test_mutable.py, mars/worker/chunkholder.py, mars/worker/seal.py, mars/worker/service.py, mars/worker/transfer.py
Support mutable tensor.
+ A `MutableTensorActor` on scheduler to manager mutable tensors and perform the underlying operations.
+ A `MutableTensor` and `MutableTensorData` to manage chunks of mutable tensors.
+ `allocate/read/write` interface in `ResultSenderActor` (on workers).
+ Chunk allocation:
- The chunks are stored in plasma store (currently pinned in memory for convenience) before seal.
- No compression is performed on mutable tensor thunks, and `read/write` operation is implemented by reading/writing a `np.ndarray` constructed by the memory view directly (zero copy and no read/write overhead). 
TODO
#415
Resolves #439 
Resolves #450.
=> Add mutable tensor support for local cluster

mars/_version.py, mars/scheduler/tests/test_graph.py, mars/worker/quota.py, mars/worker/tests/test_quota.py
Callbacks will be sent when there are unidentified errors when allocating resources in ``QuotaActor``.
Fixes #515
=> Send callback on quota allocation failure

mars/core.py, mars/deploy/local/tests/test_cluster.py, mars/web/session.py, mars/web/tests/test_api.py
When eager mode is on, an entity will be executed once it is created, so we should use `kernel_mode` to decorate the function `build_graph` to avoid execution. 
fixes #522
=> Fix bug that redundant graphs are submitted unexpectedly when eager mode is on

mars/tensor/execution/tests/test_index_execute.py, mars/tensor/expressions/indexing/setitem.py, mars/tensor/expressions/tests/test_indexing.py
Current code from the master branch suffers a trouble about `setitem` on structured arrays, that is, if we have `a = mt.ones(4, dtype=np.dtype([('a', np.int32), ('b', np.double)]))`, execute `a` is ok and the result is consistent with numpy. However, if we `setitem` to a like `a[0] = 100`, numpy will set `a[0]` to `(100, 100)`, mars raises an exception instead:
```python
~/mars/mars/tensor/execution/indexing.py in _index_set_value(ctx, chunk)
171     if hasattr(input_, 'flags') and not input_.flags.writeable:
172         input_.setflags(write=True)
--> 173     input_[tuple(indexes)] = value
174     ctx[chunk.key] = input_
175
ValueError: setting an array element with a sequence.
```
The issue is caused by
https://github.com/mars-project/mars/blob/ea2db4c2b95ad8ad97d2490edbf378c0d041618d/ma …
=> Fix assignment of structured data type arrays.

mars/tensor/execution/tests/test_arithmetic_execute.py, mars/tensor/expressions/utils.py
Fix the function `unify_nsplits` when input tensor is a scalar tensor.
This issue was undiscovered before because add a scalar should generate a constant operand, however, in this case, `out` is specified and will not convert to constant op, the scalar tensor's `nsplits` is an empty tuple which will lead to the unexpected behavior in function `unify_nsplits`.
Fixes #535
=> Fix unify chunks when add a scalar with out

mars/core.py, mars/dataframe/core.py, mars/operands.py, mars/tensor/core.py, mars/tensor/execution/tests/test_core_execute.py, mars/tensor/execution/tests/test_fft_execute.py, mars/tensor/expressions/base/__init__.py, mars/tensor/expressions/base/flatten.py, mars/tensor/expressions/base/squeeze.py, mars/tensor/expressions/base/swapaxes.py, mars/tensor/expressions/base/transpose.py, mars/tensor/expressions/indexing/getitem.py, mars/tensor/expressions/reshape/reshape.py, mars/tensor/expressions/tests/test_base.py, mars/tests/test_eager_mode.py, mars/tests/test_utils.py, mars/utils.py
Support view behavior in numpy for Mars tensor. It would also be workable for DataFrame as well. Also add `tensor.flat` property, but does not support iteration yet.
Operands that create view include:
Resolves #533 
Resolves #527 
Fixes #442
=> Support view behavior in numpy and add `tensor.view()` as well as `tensor.flat`

mars/scheduler/graph.py, mars/scheduler/tests/integrated/test_normal_execution.py, mars/utils.py, mars/worker/calc.py, mars/worker/execution.py
Fix execution error caused by fused ShuffleReduces by supporting obtaining ``shuffle_key`` from Fuse nodes.
Fixes #545
=> Fix execution error caused by fused ShuffleReduces

mars/tensor/execution/tests/test_index_execute.py, mars/tensor/expressions/utils.py
handle the negative number of integral index in `slice_split`.
Fixes #544
=> Fix wrong result of negative indexing

mars/api.py, mars/deploy/local/session.py, mars/scheduler/mutable.py, mars/scheduler/session.py, mars/session.py, mars/tensor/core.py, mars/tensor/expressions/utils.py, mars/tests/test_mutable.py, mars/utils.py, mars/web/api.py, mars/web/server.py, mars/web/session.py, mars/web/tests/test_api.py, mars/worker/seal.py, mars/worker/transfer.py, mars/worker/utils.py
Support mutable tensor in local session and web session.
+ For the `LocalSession`, we
1. maintain a map of `name -> mut tensor` in `LocalSession`, and do write to the ndarray directly.
2. when `seal`, we use the ndarray to construct a `mt.tensor` and execute it with `self._executor` know the tensor is executed.
+ For the `WebSession`, we
1. add several necessary endpoints to web api server.
2. when `write`, we forward the `index` and `value` to `MutableTensorActor`, the `MutableTensorActor` maintains the buffer, and send record chunks to corresponding workers.
3. When `seal`, do the same thing with `LocalClusterSession`.
Some design point that needs to clarify:
1. The `index` (such as `(slice(1, None, None))`) cannot be serialized to json directly, thus I add a helper class …
=> Mutable tensor for local session and web session

mars/actors/__init__.py, mars/actors/core.pyx, mars/actors/distributor.pyx, mars/actors/pool/gevent_pool.pyx, mars/actors/pool/messages.pyx, mars/actors/pool/utils.pyx
Fix error in importing new_client in Python 2.7 by adding absolute_import options and importing ``gipc`` in advance.
Fixes #557
=> Fix error in importing new_client in Python 2.7

mars/resource.py
Allow specifying different calculation methods for CPU and memory by setting ```MARS_CPU_USE_PROCESS_STAT``` and ```MARS_MEM_USE_PROCESS_STAT```.
Fixes #559
=> Allow specifying different calculation methods for CPU and memory

bin/travis-build-wheels.sh, requirements-dev.txt, requirements-wheel.txt, requirements.txt
Fix build error for abi cp27-cp27m-manylinux1 by changing installation sequence when building wheels under Linux, as when numpy headers are absent, pandas will look for master branch of numpy which is not compatible with Python<3.5.
NA
=> Fix build issue under cp27-cp27m-manylinux1

mars/compat.py, mars/serialize/dataserializer.py, mars/serialize/tests/test_serialize.py, mars/tests/test_mutable.py
Backport upstream patch from pyarrow (apache/arrow#4953), which has already been merged. And we don't need the workaround in `test_mutable.py` anymore.
Fixes #586
=> Backport patch from pyarrow.

mars/serialize/pbserializer.pyx, mars/serialize/tests/test_serialize.py
=> Fix proto-serialization for certain dtypes.

mars/deploy/local/core.py
For the parameter `open_browser`, we should use the value from `options` only when the given parameter is `None`. Otherwise `open_browser=False` won't take effect.
Fixes #604
=> Fix the default value parsing of `open_browser`

mars/serialize/pbserializer.pyx, mars/serialize/tests/test_serialize.py
=> [BACKPORT] Fix proto-serialization for certain dtypes

mars/deploy/local/core.py
=> [BACKPORT] Fix the default value parsing of `open_browser`

mars/api.py, mars/deploy/local/session.py, mars/deploy/local/tests/test_cluster.py, mars/scheduler/session.py, mars/session.py, mars/web/api.py, mars/web/session.py
Support create mars session on the fly using given `session_id`, and do necessary checks. Available for `LocalClusterSession` and `WebSession`.
resolve #605
=> Support create mars session with given session_id.

mars/scheduler/analyzer.py, mars/scheduler/graph.py, mars/scheduler/operands/base.py, mars/scheduler/operands/shuffle.py, mars/scheduler/tests/integrated/base.py, mars/worker/execution.py
Fix errors when running integrated failover cases of Mars scheduler by inferring states of virtual nodes and removing dead workers from metas maintained by ShuffleActor.
Fixes #612
=> Fix shuffle failover error in cases

mars/dataframe/arithmetic/core.py, mars/dataframe/arithmetic/tests/test_utils.py, mars/dataframe/arithmetic/utils.py
Use `pd.RangeIndex(0)` to infer the out index if one of the input indexes is `RangeIndex`
Fixes #621
=> Fix `infer_index_value` when one of input indexes is `RangeIndex`

mars/dataframe/arithmetic/core.py, mars/dataframe/arithmetic/tests/test_utils.py, mars/dataframe/arithmetic/utils.py
=> [BACKPORT] Fix `infer_index_value` when one of input indexes is `RangeIndex` (#624)

mars/deploy/kubernetes/docker/Dockerfile, mars/deploy/kubernetes/docker/Dockerfile.base, mars/resource.py, mars/tests/test_resource.py
Use memory.stat in containers to obtain more accurate memory stats, given https://www.kernel.org/doc/Documentation/cgroup-v1/memory.txt. This option can be used by setting env ``MARS_MEM_USE_CGROUP_STAT=1``.
Fixes #631
=> Get more accurate memory stats from cgroup memory.stat in containers

mars/resource.py, mars/tests/test_resource.py
=> [BACKPORT] Get more accurate memory stats from cgroup memory.stat in containers (#632)

mars/utils.py
Use  float division in `readable_size`.
Fixes #576 , the issue about used memory is fixed in #632.
=> Fix `readable_size` accuracy issue under python2

mars/tensor/fft/core.py
Nowadays, `numpy.fft` is way more faster than `scipy.fftpack`, thus in this PR, I remove the part that trying to use `scipy.fftpack` to calculate fft.
Resolves #645 .
=> Use numpy only to calculate fft

mars/tensor/linalg/core.py, mars/tensor/linalg/svd.py, mars/tensor/linalg/tests/test_linalg.py, mars/tensor/linalg/utils.py
Add a util `calc_svd_shapes` to calculate the shapes of singular value decomposition.
Fixes #655
=> Fix the wrong shape of chunks in SVD

mars/scheduler/analyzer.py, mars/scheduler/operands/common.py, mars/scheduler/operands/shuffle.py, mars/worker/spill.py
Try creating spill directories and test file creation before adding directories as spill targets. This excludes malfunctioning disks from the cluster.
Fixes #653
=> Check disks before adding into spill targets

mars/tensor/utils.py, mars/tests/test_mutable.py
As described in #659, we need to generate unique keys for mutable tensor chunks. This pr add a test that can reproduce the problem.
Fixes #659
=> Generate unique key for chunks of mutable tensors which have identical properties

mars/utils.py
=> [BACKPORT] Fix `readable_size` accuracy with Python 2 (#641)

mars/web/__init__.py, mars/web/apihandlers.py, mars/web/session.py, mars/web/tests/test_api.py, mars/worker/tests/base.py, mars/worker/tests/test_transfer.py, mars/worker/utils.py
When creating web sessions, we validate ``pyver`` arg. If the major version is different, the server side returns 400.
Fixes #337
=> Raise an error when Python version between client and server is different

mars/core.py, mars/tensor/tests/test_core_execute.py
Fix bug that set value to copied tensor still changed the original one.
Fixes #674 .
=> Fix bug that set value to copied tensor still changed the original one

mars/executor.py, mars/tensor/linalg/tensordot.py, mars/tensor/linalg/tests/test_linalg_execute.py
Add ``_tensordot_estimate_size`` back and add test cases.
Fixes #676
=> Add missing size estimation function for TensorDot

mars/executor.py, mars/tensor/linalg/tensordot.py, mars/tensor/linalg/tests/test_linalg_execute.py
=> [BACKPORT] Add missing size estimation function for TensorDot (#677)

mars/web/server.py
The default `max_buffer_size` of the tornado HTTP server is 100M, when constructing dataframes from large pandas dataframes, it will raise `Content-Length too long` error.
This pr enlarge the `max_buffer_size` to 4G.
Fixes #680.
=> Extend the max_buffer_size of tornado server to 4G.

mars/api.py, mars/deploy/local/session.py, mars/scheduler/graph.py, mars/scheduler/operands/common.py, mars/scheduler/operands/shuffle.py, mars/tensor/__init__.py, mars/web/apihandlers.py, mars/web/session.py, mars/web/task_pages.py, mars/web/tests/test_api.py, mars/worker/execution.py
Ensure remaining data removed on session delete by waiting all data removed before destroying GraphActor.
Fixes #689
=> Ensure remaining data removed on session close

mars/scheduler/mutable.py
Avoid creating and destroying `SealerActor` on the same endpoint when sealing mutable tensor. This optimization is quite useful when processing mutable tensors that have a large number of chunks.
N/A
=> Reuse sealer actor on the same worker.

docs/source/install.rst, docs/source/locale/zh_CN/LC_MESSAGES/install.po, mars/worker/__main__.py, mars/worker/service.py
Add a ``--plasma-dir`` option to specify ``plasma_directory`` when calling ``start_plasma_store``. The size of plasma store will be ignored when this option is specified.
Fixes #698
=> Add option for plasma path

.gitignore, mars/actors/pool/gevent_pool.pyx, mars/api.py, mars/deploy/local/core.py, mars/deploy/local/session.py, mars/scheduler/graph.py, mars/tensor/__init__.py, mars/web/apihandlers.py, mars/web/session.py, mars/web/tests/test_api.py
A GraphWaitActor is created after graph creation. It holds an event object which can be triggered by GraphMetaActor.
Fixes #700
=> Wait for graph to finish instead of querying with fixed intervals

mars/actors/pool/messages.pyx, mars/lib/gipc.pyx, mars/scheduler/graph.py, mars/scheduler/operands/__init__.py, mars/scheduler/operands/base.py, mars/scheduler/operands/common.py, mars/scheduler/operands/core.py, mars/scheduler/tests/integrated/op_delayer.py
Use ``is_terminal`` and ``is_initial`` instead of ``OperandPosition`` enum type, as an operand can be both initial and terminal.
Fixes #702
=> Separate flags for initials and terminals for operands

mars/api.py, mars/cluster_info.py, mars/deploy/local/session.py, mars/scheduler/graph.py, mars/scheduler/operands/base.py, mars/scheduler/operands/common.py, mars/utils.py, mars/web/apihandlers.py, mars/web/server.py, mars/worker/storage/tests/test_sharedstore.py, mars/worker/tests/base.py
This PR reduces RPC calls for schedulers in three occasions:
1. When session_manager is not needed, we do not create reference for it.
2. Cache schedulers as static variable for Web APIs.
3. Pass schedulers to operands and avoid massive queries for schedulers.
Fixes #704
=> Remove redundant RPC calls for schedulers

mars/dataframe/core.py, mars/dataframe/indexing/tests/test_indexing_execution.py
This PR is the subsequent work for #682, which implements the `__getitem__` for `DataFrame`. Pandas also support accessing columns using the column names, and this PR fills the missing part.
Test cases are also added to ensure column names don't overwrite existing `DataFrame` attributes.
Improve #625.
=> Access column using __getattr__ syntax for DataFrame.

mars/base_app.py, mars/config.py, mars/deploy/local/session.py, mars/promise.py, mars/resource.py, mars/scheduler/assigner.py, mars/scheduler/chunkmeta.py, mars/scheduler/graph.py, mars/scheduler/operands/base.py, mars/scheduler/operands/common.py, mars/scheduler/tests/test_assigner.py, mars/scheduler/tests/test_graph.py, mars/scheduler/utils.py, mars/tests/test_resource.py, mars/web/apihandlers.py, mars/web/session.py, mars/worker/calc.py, mars/worker/execution.py
Collect initial operands and submit them to AssignerActor in a batch when starting graphs.
Fixes #710
=> Submit initial operands together in one RPC call

mars/tensor/linalg/core.py, mars/tensor/linalg/tests/test_linalg.py
Fix incorrect chunk shape in QR decomposition.
Fixes #714
=> Fix incorrect chunk shape in QR decomposition

mars/config.py, mars/worker/__main__.py, mars/worker/service.py, mars/worker/storage/iorunner.py, mars/worker/storage/tests/test_client.py
Allow running workers without locks on file systems, useful when the path is a distributed FS.
Fixes #715
=> Add lock free option for workers

mars/tensor/base/tests/test_base.py, mars/tensor/indexing/setitem.py, mars/tensor/reshape/reshape.py, mars/tensor/tests/test_core_execute.py
Add `view` behavior to the result of `TensorIndexSetValue` op.
Fixes #732
=> __setitem__ on a view should be still a view.

mars/core.py, mars/tests/test_utils.py
An often-used access pattern for `.cix[]` may look like "access the first chunk of every rows" or "access the first chunks of every columns". In the previous solution we need to construct a series of indices like `[0, x]` or `[x, 0]` and `.cix[]` one by one, which is a bit boilerplate.
This pr ralex the constraint and enable the `.cix[]` for `slice()` indices, and return the chunks in a list. Note that we still require the indices has the same length with `chunk_shape` and don't do broadcasting. It is enough for nearly all use cases and can help avoid unintended bugs and errors.
No new test case is added since the correctness of `.cix[]` has been guaranteed by nearly all existing test cases (since nearly all ops use `.cix` in `tile()`). 
N/A
=> Implements more flexible `.cix[]`.

mars/scheduler/assigner.py, mars/scheduler/operands/common.py, mars/scheduler/operands/tests/test_common_ut.py, mars/worker/calc.py, mars/worker/execution.py, mars/worker/tests/test_execution.py
Pass input metas from schedulers to workers to reduce worker RPC latency.
Fixes #726
=> Submit metas obtained from schedulers

mars/dataframe/indexing/tests/test_indexing_execution.py, mars/promise.py, mars/scheduler/operands/common.py, mars/tests/test_promise.py, mars/web/apihandlers.py, mars/worker/execution.py, mars/worker/tests/test_quota.py, mars/worker/tests/test_transfer.py
Spawn remote promise calls with gevent to facilitate async operations.
Fixes #724
=> Spawn promise to utilize async network libs

mars/dataframe/core.py, mars/dataframe/datasource/from_tensor.py, mars/dataframe/datasource/tests/test_datasource.py, mars/dataframe/datasource/tests/test_datasource_execution.py
When constructing `DataFrame` from `Tensor`, the `index` and `columns` argument should be processed separately. When user feed a custom `index` argument we need to store the underlying value and when the argument is not `pd.Index` we should perform a conversion.
This pr also fixes a bug in `IndexValue.has_value`.
Fixes #718
=> Processing `index` and `columns` seperately (and correctly) in `from_tensor`

mars/scheduler/chunkmeta.py, mars/scheduler/operands/common.py, mars/worker/execution.py, mars/worker/tests/test_execution.py, mars/worker/tests/test_transfer.py, mars/worker/transfer.py
Simplify transfer RPC calls to 2 calls (``create_data_writer`` and ``receive_data_part``).
Fixes #724
=> Simplify data transfer protocol

mars/deploy/kubernetes/config.py, mars/resource.py, mars/tests/test_resource.py
Use cpuacct.stat to calculate cpu usage in Docker containers when enabling MARS_USE_CGROUP_STAT according to https://www.kernel.org/doc/Documentation/cgroup-v1/cpuacct.txt
Fixes #739
=> Add a config to use cpuacct.stat to calculate cpu usage

mars/dataframe/core.py, mars/dataframe/datasource/from_tensor.py, mars/dataframe/datasource/tests/test_datasource.py, mars/dataframe/datasource/tests/test_datasource_execution.py, mars/serialize/protos/operand_pb2.py
=> [BACKPORT] Processing `index` and `columns` seperately (and correctly) in `from_tensor`

bin/ci/travis-install-minikube.sh, mars/deploy/kubernetes/client.py, mars/deploy/kubernetes/tests/test_kubernetes.py, mars/scheduler/operands/common.py, mars/worker/calc.py, mars/worker/execution.py, mars/worker/quota.py, mars/worker/tests/test_calc.py, mars/worker/tests/test_execution.py
Add finish callback when running ``execute_graph``. This resolves potential race condition when executing graphs.
Fixes #753
=> Fix race condition when starting tasks and adding callbacks

.travis.yml
Fix version of certifi after installing tiledb. This will fix errors when uploading packages.
=> Fix certifi version after installing tiledb

mars/worker/service.py, mars/worker/storage/client.py, mars/worker/storage/core.py, mars/worker/storage/diskhandler.py, mars/worker/storage/iorunner.py, mars/worker/storage/objectholder.py, mars/worker/storage/procmemhandler.py, mars/worker/storage/sharedhandler.py, mars/worker/storage/tests/test_client.py, mars/worker/storage/tests/test_disk_io.py, mars/worker/storage/tests/test_objectholder.py, mars/worker/storage/tests/test_procmem_io.py, mars/worker/storage/tests/test_shared_io.py, mars/worker/tests/test_calc.py
Add support for controlling data copy across processes by declaring proc_id explicitly in handlers and adding IORunnerActor for every calculation actor holding local data.
Fixes #765
=> Add support for controlling data copy across processes

mars/tensor/arithmetic/core.py, mars/tensor/arithmetic/tests/test_arithmetic_execution.py
Fix arithmetic execution on GPU, mainly about  the`order` parameter.
Fixes #728
=> Fix execution of arithmetic on GPU

.travis.yml
Skip install tiledb on MacOS to reduce CI time.
=> Skip installing tiledb on MacOS in travis

.travis.yml
=> [BACKPORT] Skip installing tiledb on MacOS in travis (#784)

mars/executor.py, mars/tiles.py, mars/web/session.py
Use a DAG to express tileable objects' dependencies and tile them in a topological ordering.
=> Simplify tiles logic to improve its performance

mars/dataframe/arithmetic/add.py, mars/dataframe/arithmetic/core.py, mars/dataframe/arithmetic/floordiv.py, mars/dataframe/arithmetic/subtract.py, mars/dataframe/arithmetic/truediv.py, mars/dataframe/operands.py, mars/dataframe/reduction/__init__.py, mars/dataframe/reduction/core.py, mars/dataframe/reduction/max.py, mars/dataframe/reduction/min.py, mars/dataframe/reduction/prod.py, mars/dataframe/reduction/sum.py, mars/dataframe/reduction/tests/test_reduction.py, mars/dataframe/reduction/tests/test_reduction_execute.py
Refactor `DataFrame.reduction.core` that use the same mixin class `DataFrameReductionMixin` to handle both DataFrame and Series.
Add `max`, `min`, `prod` support.
=> Refactor of DataFrame reduction and support more reduction operands

mars/tensor/random/permutation.py, mars/tensor/random/shuffle.py, mars/tensor/random/tests/test_random.py, mars/tensor/random/tests/test_random_execute.py
This PR adds `axis` argument to `mt.random.permutation` and `mt.random.shuffle`.
Resolves #802 .
=> Support `axis` argument for `permutation` and `shuffle`

.github/workflows/run-tests.sh, mars/dataframe/core.py, mars/dataframe/initializer.py, mars/learn/__init__.py, mars/learn/contrib/xgboost/dmatrix.py, mars/learn/datasets/__init__.py, mars/learn/datasets/samples_generator.py, mars/learn/datasets/tests/test_samples_generator.py, mars/learn/operands.py, mars/learn/utils/__init__.py, mars/learn/utils/core.py, mars/learn/utils/shuffle.py, mars/learn/utils/tests/test_shuffle.py, mars/tensor/__init__.py, mars/tensor/random/permutation.py, mars/tensor/rechunk/rechunk.py, mars/tensor/reduction/__init__.py
This PR aims to add two APIs.
This PR requires #805 and #813 being merged first.
NA
=> Add `mars.learn.utils.shuffle` to support shuffling multiple tileable objects in a consistent way

mars/dataframe/arithmetic/core.py, mars/dataframe/arithmetic/tests/test_arithmetic.py, mars/dataframe/arithmetic/tests/test_arithmetic_execution.py
When add a DataFrame with a tensor, we don't need to converse tensor to DataFrame or Series, otherwise, it will generate RangeIndex during the conversion which leads to the wrong results.
Fixes #836
=> Fix incorrect behavior of dataframe arithmetic

.github/workflows/upload-packages.sh, mars/utils.py, mars/worker/calc.py, mars/worker/execution.py, mars/worker/quota.py, mars/worker/seal.py, mars/worker/service.py, mars/worker/storage/client.py, mars/worker/storage/core.py, mars/worker/storage/cudahandler.py, mars/worker/storage/diskhandler.py, mars/worker/storage/objectholder.py, mars/worker/storage/procmemhandler.py, mars/worker/storage/sharedhandler.py, mars/worker/storage/tests/test_client.py, mars/worker/storage/tests/test_cuda_io.py, mars/worker/storage/tests/test_objectholder.py, mars/worker/storage/tests/test_procmem_io.py, mars/worker/storage/tests/test_shared_io.py, mars/worker/tests/test_calc.py, mars/worker/tests/test_quota.py, mars/worker/tests/test_transfer.py, mars/worker/transfer.py
ReceiverStatusActor is added for receiving end to listen to data transfer statuses for keys. Add pin options for object holders also.
Fixes #830
Fixes #831
=> Add ReceiverStatusActor to help listening at receiver end

mars/worker/execution.py, mars/worker/quota.py, mars/worker/tests/test_quota.py
Add an option ``process_quota`` to resource requests. Once the request is allocated and ``process_quota`` is True, the resource will be marked as processing.
Fixes #847
=> Mark resource as processing once allocated

.github/workflows/ci.yml, .github/workflows/reload-env.sh, mars/actors/pool/messages.pyx, mars/deploy/kubernetes/tests/Dockerfile.test, mars/lib/gipc.pyx, mars/lib/tblib/__init__.py, mars/lib/tblib/pickling_support.py, mars/tensor/base/sort.py
Add CI/CD for Python 3.8. Several points to notice:
1. As TensorFlow wheels are not supported yet in Python 3.8, we ignore TensorFlow in tests for Python 3.8.
2. tblib will add compatibility for Python 3.8 in 1.5, and gevent will embed this version in the next release, we have to patch gevent package to make sure cases run correctly.
Code changes, not CI/CD configurations. are to be backported to make sure v0.2.x works correctly in Python 3.8 with source code.
NA
=> Add CI/CD for Python 3.8

mars/dataframe/datasource/read_csv.py, mars/dataframe/datasource/tests/test_datasource_execution.py, mars/dataframe/groupby/aggregation.py, mars/dataframe/groupby/core.py, mars/dataframe/merge/concat.py
We passed specific dtypes when call `cudf.read_csv`, as object type is unsupported in cuDF, we treat it as string type as default.
Fixes #852
=> Fix `read_csv` execution on GPU

mars/_utils.pxd, mars/_utils.pyx, mars/config.py, mars/scheduler/assigner.py, mars/scheduler/chunkmeta.py, mars/scheduler/graph.py, mars/scheduler/operands/base.py, mars/scheduler/operands/common.py, mars/scheduler/tests/integrated/base.py, mars/scheduler/tests/integrated/test_normal_execution.py, mars/tests/test_utils.py, mars/utils.py, mars/worker/calc.py, mars/worker/daemon.py, mars/worker/execution.py, mars/worker/service.py, mars/worker/status.py, mars/worker/storage/client.py, mars/worker/storage/cudahandler.py, mars/worker/storage/manager.py, mars/worker/storage/objectholder.py, mars/worker/storage/sharedhandler.py, mars/worker/storage/sharedstore.py, mars/worker/tests/test_calc.py, mars/worker/utils.py
Assign enqueued operands immediately when no descendants are ready. This behavior is disabled by default, and can be enabled with ``options.scheduler.aggressive_assign``.
Fixes #853
=> Assign enqueued operands immediately when no descendants are ready

.github/workflows/install-hdfs.sh, .github/workflows/install-minikube.sh, mars/api.py, mars/errors.py, mars/promise.py, mars/scheduler/mutable.py, mars/web/static/js/mars.js, mars/worker/__init__.py, mars/worker/calc.py, mars/worker/execution.py, mars/worker/service.py, mars/worker/storage/client.py, mars/worker/storage/core.py, mars/worker/storage/cudahandler.py, mars/worker/storage/diskhandler.py, mars/worker/storage/iorunner.py, mars/worker/storage/manager.py, mars/worker/storage/objectholder.py, mars/worker/storage/procmemhandler.py, mars/worker/storage/sharedhandler.py, mars/worker/storage/tests/test_client.py, mars/worker/tests/base.py, mars/worker/tests/test_calc.py, mars/worker/tests/test_execution.py, mars/worker/tests/test_transfer.py, mars/worker/transfer.py
In this PR, several designs in transfer.py is changed.
1. Receiver meta is now shared by both ``ReceiverManagerActor`` and ``ReceiverWorkerActor`` (previously ``ReceiverActor``) to make sure that transfer meta does not conflict between different worker actors.
2. ``create_data_writers`` now accepts batch interface.
3. ``receive_data_part`` now supports transferring multiple data chunks at one time. whether the part of data is a terminating data piece of a chunk is determined by argument ``end_marks``.
4. ``send_data`` now accepts multiple chunk keys. data pieces are dispatched to different receivers.
Fixes #832
=> Support transferring multiple chunks at one time

.github/workflows/ci.yml, requirements-wheel.txt
Python 3.8 uses new abi called ``cp38-cp38``, hence we need to change the definition in ci.yml. Build logs can be seen at https://github.com/wjsi/mars/commit/66e8581c0c81a1d506419e7a41174788482f2a0d/checks?check_suite_id=359196592.
NA
=> Fix distribute error under Py38

mars/operands.py, mars/scheduler/graph.py, mars/worker/execution.py
Skip preparing chunks specified in ``chunk.prepare_inputs`` when preparing for execution
Fixes #890
=> Skip preparing specified chunks when preparing for execution

mars/scheduler/graph.py, mars/scheduler/tests/integrated/test_normal_execution.py
This PR tries to fix possible failure of `testIterativeTilingWithoutEtcd` for Python 3.5 in CI.
The reason is that some value stored in a dict value is bind into a weakref.WeakKeyDIctionary, and the same key may be overwritten and gc may collect the old value, thus it's gone in the weak key dict either.
Fixes #895 .
=> Fix possible failure of `testIterativeTilingWithoutEtcd` for Python 3.5 in CI

mars/tensor/linalg/lu.py
As described in #904 , when input has one chunk, execution of `LU` is super slow. This PR accelerated the process.
Because `LU` is used in randomized_svd, and the latter one is widely used in `PCA` and `TruncatedSVD`, I test the unittests in `test_pca`, the running time reduced from 5min 14s to 1min 35s on my laptop. I think this PR can accelerate the CI as well.
Fixes #904 .
=> Accelerate `LU` when input has one chunk

mars/dataframe/reduction/__init__.py, mars/dataframe/reduction/core.py, mars/dataframe/reduction/mean.py, mars/dataframe/reduction/tests/test_reduction.py, mars/dataframe/reduction/tests/test_reduction_execute.py
Add `Mean` implementation in DataFrame reduction module.
Resolves #883.
=> Implement `mean` operator for DataFrame and Series

mars/core.py, mars/dataframe/arithmetic/__init__.py, mars/dataframe/arithmetic/core.py, mars/dataframe/arithmetic/equal.py, mars/dataframe/arithmetic/greater.py, mars/dataframe/arithmetic/greater_equal.py, mars/dataframe/arithmetic/less.py, mars/dataframe/arithmetic/less_equal.py, mars/dataframe/arithmetic/not_equal.py, mars/dataframe/arithmetic/tests/test_arithmetic.py, mars/dataframe/arithmetic/tests/test_arithmetic_execution.py, mars/dataframe/arithmetic/tests/test_comparison.py, mars/dataframe/core.py, mars/tensor/core.py, mars/utils.py
This PR added comparison functions including `eq`, `ne`, `gt`, `ge`, `lt`, `le`.
Resolves #837 .
=> Add comparison functions for DataFrame

mars/lib/sparse/__init__.py, mars/lib/sparse/matrix.py, mars/tensor/reduction/core.py, mars/tensor/reduction/max.py, mars/tensor/reduction/min.py, mars/tensor/reduction/tests/test_reduction_execute.py
If a tensor(ndim > 1) is sparse, tensor.min(axis=0) and tensor.max(axis=0) would be sparse as well. The past behavior is wrong, fix it in this PR.
NA
=> Fix sparse behavior for tensor.min and tensor.max

mars/tensor/indexing/nonzero.py, mars/tensor/indexing/tests/test_indexing_execute.py
This PR fixes bug described in #953 .
In the `tile` of nonzero, `op.input` is a `TensorData` instead of `Tensor` which would cause potential failure for tensor manipulation.
Fixes #953 .
=> Fix tile in nonzero that tensor instead of tensor data should be used during the process

mars/tensor/indexing/nonzero.py, mars/tensor/indexing/tests/test_indexing_execute.py
=> [BACKPORT] Fix tile in nonzero that tensor instead of tensor data should be used during the process (#954)

mars/lib/sparse/tests/test_sparse.py, mars/tensor/spatial/distance/cdist.py, mars/tensor/spatial/distance/tests/test_distance.py
Fixes `cdist(x, y)` that creates tensor with wrong nsplits.
Fixes #959 .
=> Fixes `cdist(x, y)` that creates tensor with wrong nsplits

mars/learn/metrics/pairwise/euclidean.py, mars/learn/metrics/pairwise/tests/test_euclidean_distances.py, mars/serialize/protos/operand.proto, mars/tensor/__init__.py, mars/tensor/base/__init__.py, mars/tensor/base/argpartition.py, mars/tensor/base/argsort.py, mars/tensor/base/argtopk.py, mars/tensor/base/partition.py, mars/tensor/base/psrs.py, mars/tensor/base/sort.py, mars/tensor/base/tests/test_base.py, mars/tensor/base/tests/test_base_execute.py, mars/tensor/base/topk.py, mars/utils.py
This PR introduces `topk` which described in #943 . 
PSRS has been refactored to support return indices, thus `argsort`, `argpartition`, `argtopk` are added as well.
Resolves #943 .
=> Implements mt.{topk, argsort, argpartition, argtopk}

mars/dataframe/__init__.py, mars/dataframe/datastore/__init__.py, mars/dataframe/datastore/tests/__init__.py, mars/dataframe/datastore/tests/test_datastore.py, mars/dataframe/datastore/tests/test_datastore_execute.py, mars/dataframe/datastore/to_csv.py, mars/dataframe/operands.py, mars/filesystem.py, mars/serialize/protos/operand.proto
This PR implements `DataFrame.to_csv`.
* If path is a string with wildcard e.g. '/to/path/out-*.csv', `to_csv` will try to write multiple files, for instance, chunk (0, 0) will write data into '/to/path/out-0.csv'.
* If path is a string without wildcard, it's a bit more complicated. To summarize it, each `chunk.to_csv` will write data into a StringIO, then collect all sizes of them, generate a file filled with '\x00', then tell each chunk where to seek, the data will be written accordingly.
Resolves #950 .
=> Implements `DataFrame.to_csv`

mars/dataframe/base/reset_index.py, mars/dataframe/base/standardize_range_index.py, mars/dataframe/base/tests/test_base_execution.py, mars/dataframe/datasource/read_csv.py, mars/dataframe/datasource/tests/test_datasource_execution.py, mars/dataframe/utils.py, mars/scheduler/tests/integrated/no_prepare_op.py, mars/scheduler/tests/integrated/test_normal_execution.py, mars/serialize/protos/operand.proto
Provides a util `standardize_range_index` to set correct `RangeIndex` to each chunk for operands like `read_csv`, their chunk shape is unknown before execution, we need this util to calculate the right start position and end position of `RangeIndex`.
Fixes #928.
=> Fix the wrong `RangeIndex` in read_csv

mars/context.py, mars/learn/contrib/pytorch/__init__.py, mars/learn/contrib/pytorch/dataset.py, mars/learn/contrib/pytorch/sampler.py, mars/learn/contrib/pytorch/tests/dataset_sample.py, mars/learn/contrib/pytorch/tests/integrated/test_distributed_dataset.py, mars/scheduler/tests/integrated/test_normal_execution.py, mars/tensor/indexing/tests/test_indexing_execute.py
- Implement PyTorch sampler and prefetch batch data to reduce rpc call.
- Fix `context. get_tileable_data` when select order is not ascending or descending.
Resolves #969.
=> Implement PyTorch sampler to improve dataset performance

mars/learn/metrics/pairwise/__init__.py, mars/learn/neighbors/__init__.py, mars/learn/neighbors/ball_tree.py, mars/learn/neighbors/base.py, mars/learn/neighbors/kd_tree.py, mars/learn/neighbors/tests/__init__.py, mars/learn/neighbors/tests/test_nearest_neighbors.py, mars/learn/neighbors/tree.py, mars/learn/neighbors/unsupervised.py, mars/learn/utils/validation.py, mars/serialize/protos/operand.proto, mars/tensor/base/psrs.py, mars/tensor/base/sort.py, mars/tensor/base/tests/test_base.py, mars/tensor/base/topk.py, mars/tensor/reshape/reshape.py
This PR adds support for `mars.learn.neighbors.NearestNeighbors` which is the counterpart of `sklearn.neighbors.NearestNeighbors`.
sklearn provides three algorithms including `brute`, `ball_tree` and `kd_tree`, the next PR'd like to introduce [faiss](https://github.com/facebookresearch/faiss) as well. Faiss is quite friendly for large dataset and distributed setting.
Tasks:
Resolves #949 .
=> Support `mars.learn.neighbors.NearestNeighbors`

mars/tensor/random/choice.py, mars/tensor/random/tests/test_random.py, mars/tensor/random/tests/test_random_execute.py
In the past, `mt.random.choice` just rechunk input into one chunk, and then perform computation, but when it has multiple chunks and `replace=False`, the consequence may be wrong.
This PR fixes the problem, and tries to solve `choice` in a parallel fashion when the data is huge. 
1. If a is an integer, and replace=True, it's equivalent to `mt.random.randint(a, size=size)`.
2. If a is a tensor, and replace=True, equivalent to `a[mt.random.randint(a.size, size=size)]`.
3. If replace=False, try to solve the problem via parallel Reservoir Sampling .
Fixes #974 .
Resolves #799 .
=> Fix wrong behavior of `mt.random.choice`

mars/dataframe/base/__init__.py, mars/dataframe/base/map.py, mars/dataframe/base/tests/test_base_execution.py, mars/serialize/protos/operand.proto, requirements-dev.txt, requirements.txt
This PR added support for `Series.map()`.
The key issue is how to infer the dtype given the arg which could be a dict, Series(both pd and md), or a function. Below is what has been done in this PR:
1. If arg is a function, try to get the return type which given in type hint.
2. If arg is a dict or Series, convert to Series always, and get the dtype of it, if it's a number as well as np.inexact, for instance, np.float, it's legal; if it's int for instance, we cannot make sure if it's legal, because np.nan may exist always, and the real dtype could be float instead of int.
NA
=> Implements `Series.map`

mars/dataframe/base/__init__.py, mars/dataframe/base/describe.py, mars/dataframe/base/tests/test_base_execution.py, mars/dataframe/initializer.py, mars/dataframe/reduction/core.py, mars/dataframe/reduction/count.py, mars/dataframe/reduction/max.py, mars/dataframe/reduction/mean.py, mars/dataframe/reduction/min.py, mars/dataframe/reduction/prod.py, mars/dataframe/reduction/sum.py, mars/dataframe/reduction/tests/test_reduction.py, mars/dataframe/reduction/var.py, mars/serialize/protos/operand.proto
This PR adds support for `DataFrame.describe` and `Series.describe` when describing on numeric data.
NA
=> Implements `describe` for DataFrame

conda-spec.txt, mars/tensor/arithmetic/tests/test_arithmetic.py, mars/tensor/utils.py
Make sure all kwargs are numpy types when inferring dtypes.
Fixes #551
=> Make sure all kwargs are numpy types when inferring dtypes

mars/serialize/protos/operand.proto, mars/tensor/images/__init__.py, mars/tensor/images/imread.py, mars/tensor/images/tests/__init__.py, mars/tensor/images/tests/test_images.py, mars/tensor/images/tests/test_images_execute.py
Use `imread` to read single image or images to Mars tensor.
Resolve #978.
=> Implement `imread` to read from images

conda-spec.txt, mars/tensor/arithmetic/tests/test_arithmetic.py, mars/tensor/utils.py
=> [BACKPORT] Make sure all kwargs are numpy types when inferring dtypes (#987)

mars/_version.py, mars/dataframe/datasource/read_sql_table.py, mars/dataframe/datasource/tests/test_datasource_execution.py
This PR fixes error when chunk_size not provided for `md.read_sql_table`. And for the execution of `read_sql_table`, explicit `order_by` is specified.
Fixes #989 .
=> Fix error when chunk_size not provided for `md.read_sql_table`

mars/tensor/reduction/core.py, mars/tensor/reduction/count_nonzero.py, mars/tensor/reduction/tests/test_reduction_execute.py
`count_nonzero` produces wrong result when tensor has only one chunk, this PR will fix this issue.
Fixes #999
=> Fix wrong result of count_nonzero

mars/context.py, mars/learn/contrib/pytorch/dataset.py, mars/scheduler/tests/integrated/test_normal_execution.py, mars/tensor/__init__.py, mars/tensor/einsum/core.py, mars/tensor/images/imread.py, mars/tensor/images/tests/test_images.py
Add `dtype` property for `TensorImread`.
=> Add `dtype` property for `TensorImread`

mars/tensor/__init__.py, mars/tensor/einsum/core.py, mars/tensor/images/imread.py, mars/tensor/images/tests/test_images.py
=> [BACKPORT] Add `dtype` property for `TensorImread` (#1004)

.github/workflows/install-conda.sh, requirements-extra.txt
Detect installation of VS2015 and fix missing RC compiler.
Fixes #1013
=> Fix tests under Python 3.6 as VS2015 is preinstalled

mars/dataframe/datasource/read_csv.py, mars/dataframe/datasource/tests/test_datasource_execution.py, mars/dataframe/merge/merge.py
We introduce `standardize_range_index` in #930 to fix wrong index when read csv files, it will cost  much time, so we add `sort_range_index` parameter in `read_csv` and set False as default, users can set `sort_range_index=True` if care about the index.
=> Add `sort_range_index` parameter in `read_csv`

mars/dataframe/base/__init__.py, mars/dataframe/base/fillna.py, mars/dataframe/base/tests/test_base.py, mars/dataframe/base/tests/test_base_execution.py, mars/dataframe/reduction/core.py, mars/deploy/kubernetes/tests/test_kubernetes.py, mars/serialize/protos/operand.proto
Add support for ``md.fillna``. Some hints about the implementation:
When filling with scalars, a one-to-one tiling will be performed.
When filling with Mars DataFrames / Scalars, Mars will first align these objects and then perform a one-to-one tiling.
When performing forward / backward tiling without limits, filling will be performed with a map stage and a combine stage. In the map stage, tiling will be performed and the last series along the specified axis is collected into the combine stage, where these series are concatenated with the input data, and fillna is performed again.
When performing forward / backward tiling with limits, besides generating last series in the map stage, lengths of limits left for following chunks are computed and passed to the combine stage as well. In the …
=> Add support for md.fillna

mars/dataframe/core.py, mars/dataframe/groupby/__init__.py, mars/dataframe/groupby/aggregation.py, mars/dataframe/groupby/tests/test_groupby.py, mars/dataframe/groupby/tests/test_groupby_execution.py, mars/deploy/kubernetes/tests/test_kubernetes.py
This PR supports:
1. List of aggregation functions, e.g. `df.groupby('a').agg(['min', 'mean'])` and `df.groupby('a').agg({'b': ['count', 'std'], 'c': 'var'})`
2. More aggregation functions were added for `DataFrameGroupBy.agg` include `count`, `mean`, `var` and `std`.
Since cloudpickle was used in this PR, thus it will not be backported.
Resolves #1027 .
=> Support `groupby.agg` with list of functions

mars/dataframe/__init__.py, mars/dataframe/base/standardize_range_index.py, mars/dataframe/sort/__init__.py, mars/dataframe/sort/psrs.py, mars/dataframe/sort/sort_values.py, mars/dataframe/sort/tests/__init__.py, mars/dataframe/sort/tests/test_sort.py, mars/dataframe/sort/tests/test_sort_execute.py, mars/dataframe/utils.py, mars/serialize/protos/operand.proto, mars/tensor/base/partition.py, mars/tensor/base/psrs.py, mars/tensor/base/sort.py
Support `DataFrame.sort_values` by a parallel sorting algorithm PSRS, the logic is similar to `mt.sort`.
Solve part of #1037.
=> Add support for DataFrame.sort_values

mars/core.py, mars/dataframe/base/apply.py, mars/dataframe/base/fillna.py, mars/dataframe/groupby/aggregation.py, mars/dataframe/groupby/tests/test_groupby_execution.py, mars/dataframe/merge/concat.py, mars/dataframe/reduction/__init__.py, mars/dataframe/reduction/aggregation.py, mars/dataframe/reduction/core.py, mars/dataframe/reduction/tests/test_reduction.py, mars/dataframe/reduction/tests/test_reduction_execute.py, mars/dataframe/reduction/var.py, mars/dataframe/utils.py, mars/operands.py, mars/serialize/protos/operand.proto, mars/web/tests/test_api.py, requirements.txt
This PR adds support for aggregation on data frames and series. We describe the method we use below.
Given that every aggregation function used in tree reduction can be put in three stages: map, combine and agg, which can be illustrated below:
```
map1 - combine1
map2 - combine2  > agg
...
mapx - combinex
```
We first group data by functions used in the map stage and create u separated map groups, one for every distinct map function. Then for every map group, we divide then further by combine functions accepting the results of the map group into map-combine groups. Therefore every map-combine group has one corresponding map group, but the reversed conclusion does not hold. Then all related columns in map-combine groups for every aggregation is collected, and aggregation result is …
=> Add support for {DataFrame,Series}.agg

mars/dataframe/core.py, mars/dataframe/datasource/tests/test_datasource.py, mars/serialize/jsonserializer.pyx, mars/serialize/pbserializer.pyx, mars/serialize/protos/indexvalue.proto
This PR adds support for serializing `pd.Timestamp` and `pd.Timedelta`.
Fixes #1064 .
=> Support serializing `pd.Timestamp` and `pd.Timedelta`

mars/dataframe/base/__init__.py, mars/dataframe/base/accessor.py, mars/dataframe/base/datetimes.py, mars/dataframe/base/string_.py, mars/dataframe/base/tests/test_base.py, mars/dataframe/base/tests/test_base_execution.py, mars/dataframe/core.py, mars/serialize/protos/operand.proto
This PR implements string and datetime methods via `Series.str` and `Series.dt` accessor.
Resolves #1051 .
Resolves #1052 .
=> Support string and datetime methods via `Series.str` and `Series.dt` accessor

mars/dataframe/groupby/__init__.py, mars/dataframe/groupby/apply.py, mars/dataframe/groupby/cum.py, mars/dataframe/groupby/tests/test_groupby.py, mars/dataframe/groupby/tests/test_groupby_execution.py, mars/operands.py, mars/serialize/protos/operand.proto
Add support for GroupBy.{cumcount,cummin,cummax,cumprod,cumsum}
Fixes #1068
=> Add support for GroupBy.{cumcount,cummin,cummax,cumprod,cumsum}

mars/dataframe/groupby/__init__.py, mars/dataframe/groupby/cum.py, mars/dataframe/groupby/tests/test_groupby.py, mars/dataframe/groupby/tests/test_groupby_execution.py, mars/operands.py, mars/serialize/protos/operand.proto
Backport of #1069. SeriesGroupBy tests are removed as corresponding groupby not supported in v0.3.
NA
=> [BACKPORT] Add support for GroupBy.{cumcount,cummin,cummax,cumprod,cumsum} (#1069)

mars/_version.py, mars/dataframe/sort/__init__.py, mars/dataframe/sort/core.py, mars/dataframe/sort/psrs.py, mars/dataframe/sort/sort_index.py, mars/dataframe/sort/sort_values.py, mars/dataframe/sort/tests/test_sort.py, mars/dataframe/sort/tests/test_sort_execute.py, mars/dataframe/utils.py, mars/serialize/protos/operand.proto
Add support for `sort_index`.
Resolves #1037.
=> Support sort_index for DataFrame and Series

mars/dataframe/base/rechunk.py, mars/dataframe/base/tests/test_base.py
Fix chunk's dtypes in `DataFrame.rechunk`.
Fixes #1077.
=> Fix wrong dtypes in df.rechunk

mars/dataframe/indexing/__init__.py, mars/dataframe/indexing/getitem.py, mars/dataframe/indexing/iloc.py, mars/dataframe/indexing/tests/test_indexing_execution.py
Implemnts head/tail using `DataFrame.iloc`, and fixes bug in `getitem` (when the `dtype` cannot be infered or shuffle happends in `getitem`).
Test is coming.
N/A
=> Implements head/tail based on iloc, and fixes bug in `getitem`.

mars/dataframe/indexing/__init__.py, mars/dataframe/indexing/getitem.py, mars/dataframe/indexing/iloc.py, mars/dataframe/indexing/tests/test_indexing_execution.py
=> [BACKPORT] Implements head/tail based on iloc, and fixes bug in `getitem`. (#1057)

mars/dataframe/tests/test_utils.py, mars/dataframe/utils.py, mars/tensor/base/psrs.py
When input tileable e.g. DataFrame has unknown shape, `validate_axis` would fail which illustrated in #1090 .
Fixes #1090 .
=> Fix `validate_axis` when input tileable has unknown shape

mars/dataframe/tests/test_utils.py, mars/dataframe/utils.py, mars/tensor/base/psrs.py
=> [BACKPORT] Fix validate_axis when input tileable has unknown shape (#1091)

.github/workflows/install-minikube.sh, mars/_version.py, mars/dataframe/datasource/dataframe.py, mars/dataframe/datasource/read_csv.py, mars/dataframe/groupby/aggregation.py, mars/dataframe/merge/concat.py, mars/executor.py, mars/tests/test_executor.py, requirements-dev.txt, requirements-extra.txt, requirements.txt
When running ops less than the number of parallelism a.k.a `n_parallel`, the performance of executor will become terrible.
Master branch, the file is around 500M, default `chunk_bytes` is 128M, and automatic `n_parallel` is 8.
```
In [1]: %%time 
...: import mars.dataframe as md 
...: df = md.read_csv('Downloads/ratings.csv') 
...: df.groupby('movieId').agg({'rating': ['max', 'min']}).execute() 
...:  
...:                                                                         
CPU times: user 14.4 s, sys: 2.49 s, total: 16.9 s
Wall time: 8.9 s
Out[1]: 
rating     
max  min
movieId            
1          5.0  0.5
2          5.0  0.5
3          5.0  0.5
4          5.0  0.5
5          5.0  0.5
...        ...  ...
131254     4.0  4.0
131256     4.0  4.0
131258     2.5  2.5
131260     3.0 …
```
=> Optimize performance of executor when running ops less than number of parallelism

mars/dataframe/groupby/tests/test_groupby_execution.py, mars/dataframe/indexing/__init__.py, mars/dataframe/indexing/at.py, mars/dataframe/indexing/iat.py, mars/dataframe/indexing/index_lib.py, mars/dataframe/indexing/tests/test_indexing_execution.py
This PR added support for `at` and `iat`.
Resolves #1100 .
=> Implements `at` and `iat` for DataFrame

mars/dataframe/base/__init__.py, mars/dataframe/base/isin.py, mars/dataframe/base/tests/test_base.py, mars/dataframe/base/tests/test_base_execution.py
Implements DataFrame/Series.isin. At current stage only the `Series` part has been implemented, the `DataFrame.isin` part, as well as the test cases, will coming soon.
Partially resolves #756
=> Implements Series.isin (for Series type).

mars/dataframe/__init__.py, mars/dataframe/indexing/getitem.py, mars/dataframe/indexing/index_lib.py, mars/dataframe/indexing/loc.py, mars/dataframe/indexing/tests/test_indexing_execution.py, mars/tests/test_session.py, mars/utils.py
As mentioned in #1102 , when input DataFrame's index is not int64 index e.g. RangeIndex, the slice is very flexible that it can be integer which could act same as `iloc`, or can be other types which act same as `loc`.
Fixes #1102 .
=> Support slice that can be integer or other types on non-int64 index

mars/dataframe/__init__.py, mars/dataframe/base/__init__.py, mars/dataframe/base/checkna.py, mars/dataframe/base/tests/test_base_execution.py, mars/dataframe/core.py, mars/dataframe/tests/test_utils.py, mars/serialize/protos/operand.proto
Support ``DataFrame.__dir__``, ``isna()`` and ``notna()``.
Fixes #1111 
Fixes #1117
=> Add support for isna, notna and __dir__

.github/workflows/ci.yml, mars/dataframe/base/__init__.py, mars/dataframe/base/dropna.py, mars/dataframe/base/fillna.py, mars/dataframe/base/tests/test_base.py, mars/dataframe/base/tests/test_base_execution.py, mars/dataframe/reduction/aggregation.py, mars/dataframe/reduction/count.py, mars/dataframe/reduction/tests/test_reduction.py
Add support for ``md.dropna``. When handling multiple chunks in columns, we first call ``agg('count', axis=1)`` to generate stats for non-nans and then filter out rows.
Fixes #1116
=> Add support for md.dropna

mars/dataframe/merge/merge.py, mars/dataframe/merge/tests/test_merge_execution.py, mars/dataframe/utils.py
Support situation that `on` column is in df.index for `md.merge`.
Fixes #1110 .
=> Support `md.merge` when `on` column is in df.index

.github/workflows/install-conda.sh, docs/source/dataframe/reference/api/mars.dataframe.DataFrame.iloc.rst, docs/source/dataframe/reference/api/mars.dataframe.DataFrame.loc.rst, docs/source/dataframe/reference/api/mars.dataframe.DataFrame.nunique.rst, docs/source/dataframe/reference/api/mars.dataframe.DataFrame.rst, docs/source/dataframe/reference/api/mars.dataframe.Series.dt.rst, docs/source/dataframe/reference/api/mars.dataframe.Series.nunique.rst, docs/source/dataframe/reference/api/mars.dataframe.Series.rst, docs/source/dataframe/reference/api/mars.dataframe.Series.str.rst, docs/source/dataframe/reference/frame.rst, docs/source/dataframe/reference/series.rst, docs/source/dataframe/user_guide/10min.rst, docs/source/tensor/generated/mars.tensor.core.Tensor.T.rst, docs/source/tensor/generated/mars.tensor.random.RandomState.rst, mars/dataframe/merge/merge.py, mars/dataframe/reduction/__init__.py, mars/dataframe/reduction/core.py, mars/dataframe/reduction/nunique.py, mars/dataframe/reduction/tests/test_reduction.py, mars/dataframe/reduction/tests/test_reduction_execute.py, mars/dataframe/utils.py, mars/serialize/protos/operand.proto
This PR implements df.unique, it's now a simple way that record all unique values and count them at the aggregation stage, it should be optimized if the amount of unique values are too large.
Resolves #1124 .
=> Implement DataFrame nunique

mars/_utils.pyx, mars/tests/test_utils.py
Fix tokenizing partial function by extracting dict items directly.
Fixes #1148
=> Fix tokenizing partial function

mars/lib/groupby_wrapper.py, mars/lib/tests/test_lib.py
Add size property for GroupByWrapper to make sure ``_update_tileable_and_chunk_shape`` works.
Fixes #1154
=> Allow retrieving shape of a groupby object

docs/requirements-doc.txt, mars/learn/metrics/pairwise/__init__.py, mars/learn/metrics/pairwise/rbf_kernel.py, mars/learn/metrics/pairwise/tests/test_rbf_kernel.py
This PR added support for `mars.learn.metrics.pairwise.rbf_kernel`.
NA
=> Implements `mars.learn.metrics.pairwise.rbf_kernel`

.github/workflows/install-conda.sh, mars/dataframe/merge/merge.py, mars/dataframe/merge/tests/test_merge_execution.py, mars/dataframe/utils.py
=> [BACKPORT] Support `md.merge` when `on` column is in df.index (#1132)

docs/source/dataframe/reference/api/mars.dataframe.Series.append.rst, docs/source/dataframe/reference/api/mars.dataframe.Series.value_counts.rst, docs/source/dataframe/reference/series.rst, mars/dataframe/arithmetic/core.py, mars/dataframe/base/__init__.py, mars/dataframe/base/tests/test_base_execution.py, mars/dataframe/base/value_counts.py, mars/dataframe/groupby/aggregation.py, mars/dataframe/groupby/core.py, mars/dataframe/groupby/tests/test_groupby_execution.py, mars/dataframe/merge/concat.py, mars/dataframe/operands.py, mars/dataframe/utils.py, mars/executor.py, mars/serialize/protos/operand.proto
This PR introduced:
1. Support `Series.value_counts()`.
2. Support `{DataFrame, Series}.groupby(by=series)`.
Resolves #1119 .
Partially implement #1036 .
=> Add `Series.value_counts()` support

mars/learn/utils/shuffle.py, mars/learn/utils/tests/test_shuffle.py, mars/serialize/pbserializer.pyx
This PR fixes serialization issue for `mars.learn.utils.shuffle`, and `ExecutorForTest` is introduced to test shuffle execution.
Fixes #1184 .
=> Fix serialization for `mars.learn.utils.shuffle`

mars/learn/utils/shuffle.py, mars/learn/utils/tests/test_shuffle.py, mars/serialize/pbserializer.pyx
=> [BACKPORT] Fix serialization for mars.learn.utils.shuffle (#1192)

docs/source/dataframe/reference/api/mars.dataframe.to_datetime.rst, docs/source/dataframe/reference/general_functions.rst, mars/dataframe/__init__.py, mars/dataframe/indexing/__init__.py, mars/dataframe/indexing/setitem.py, mars/dataframe/indexing/tests/test_indexing_execution.py, mars/dataframe/tseries/__init__.py, mars/dataframe/tseries/tests/__init__.py, mars/dataframe/tseries/tests/test_tseries.py, mars/dataframe/tseries/tests/test_tseries_execution.py, mars/dataframe/tseries/to_datetime.py, mars/serialize/protos/operand.proto
This PR contributed two changes:
1. Implementation of `md.to_datetime`.
2. Support `__setitem__` for DataFrame.
Support part of #1121 .
=> Implements `md.to_datetime`, support `__setitem__` for DataFrame as well

docs/source/dataframe/reference/api/mars.dataframe.Series.rst, docs/source/learn/generated/mars.learn.metrics.auc.rst, docs/source/learn/generated/mars.learn.metrics.roc_curve.rst, docs/source/learn/reference.rst, docs/source/tensor/generated/mars.tensor.c_.rst, docs/source/tensor/generated/mars.tensor.r_.rst, docs/source/tensor/indexing.rst, mars/core.py, mars/executor.py, mars/learn/base.py, mars/learn/metrics/__init__.py, mars/learn/metrics/_classification.py, mars/learn/metrics/_ranking.py, mars/learn/metrics/tests/test_ranking.py, mars/serialize/protos/operand.proto, mars/session.py, mars/tensor/__init__.py, mars/tensor/base/__init__.py, mars/tensor/base/shape.py, mars/tensor/base/tests/test_base_execute.py, mars/tensor/datasource/array.py, mars/tensor/lib/index_tricks.py, mars/tensor/lib/tests/test_index_tricks.py, mars/tensor/operands.py, mars/tensor/utils.py, mars/tests/test_session.py
This PR introduced:
1. `mars.learn.metrics.roc_curve` as well as `mars.learn.metrics.auc`.
2. `mars.tenosr.shape` which returns a `ExcutableTuple`, if the shape is unknown, `.execute()` will return the actual shape.
3. `mars.tensor.r_` and `mars.tensor.c_` shortcuts.
Resolves #1196 .
=> Implements `mars.learn.metrics.{roc_curve, auc}` 

.dockerignore, mars/deploy/kubernetes/docker/Dockerfile.base, mars/operands.py, mars/scheduler/graph.py, mars/scheduler/operands/common.py, mars/web/apihandlers.py, mars/web/session.py, mars/web/tests/test_api.py
This PR does the things below:
1. Allow some operands to fail fast by adding ``retryable`` property to operands
2. Warns when pyarrow version between host and service does not agree
3. Fixes ``.dockerignore`` which ignores building protobuf files
4. Return errors in graph preparation to the client
Fixes #1221
=> Allow some operands to fail fast

.github/workflows/ci.yml, .github/workflows/install-conda.sh, mars/deploy/local/core.py, mars/deploy/local/tests/test_cluster.py, mars/utils.py, mars/web/__main__.py
Use multiprocessing with spawn method instead of gipc to fix errors caused by monkey patching after fork in IPython.
This PR also deal with failures of Mars Web with recent gevent versions (>=1.5), which is described in #1228.
Fixes #1231
=> Fix error in starting local cluster with IPython

mars/dataframe/base/__init__.py, mars/dataframe/base/astype.py, mars/dataframe/base/tests/test_base.py, mars/dataframe/base/tests/test_base_execution.py, mars/serialize/jsonserializer.pyx, mars/serialize/pbserializer.pyx, mars/tests/core.py, mars/web/apihandlers.py
Support `astype` for both Series and DataFrame, if specific dtype is 'category', it will call `unique` method to get all unique values firstly.
Resolves #1222.
=> Add support for Series.astype and DataFrame.astype

mars/context.py, mars/dataframe/base/transform.py, mars/dataframe/groupby/transform.py, mars/deploy/local/tests/test_cluster.py, mars/executor.py, mars/operands.py, mars/remote/__init__.py, mars/remote/core.py, mars/remote/tests/__init__.py, mars/remote/tests/test_remote_function.py, mars/remote/utils.py, mars/serialize/jsonserializer.pyx, mars/serialize/pbserializer.pyx, mars/serialize/protos/operand.proto, mars/session.py, mars/utils.py
This PR added preliminary remote function support. Sample code:
```python
import mars.remote as mr
def f(x):
return x + 1
def g(x, y):
return x * y
a = mr.spawn(f, 3)
b = mr.spawn(f, 4)
c = mr.spawn(g, (a, b))
print(c.execute().fetch())  # print 20
```
Finish part of #1227 .
=> Add preliminary remote function support

mars/executor.py, mars/optimizes/tileable_graph/core.py, mars/optimizes/tileable_graph/tests/test_column_pruning.py, mars/tests/test_session.py, mars/utils.py, requirements-extra.txt
As reported in #1242 , performance declined since #1201 merged.
After investigation, I found that the reason is that `.fetch()` may cause some op executed again.
Now, for local execution, `.fetch()` will just submit the tilables to executor for running, in the executor, after tiling, the executed op will be replaced with fetch op. 
Consider the situation below:
```
chunk_a -> chunk_b
```
Since `chunk_b` has been executed, it will be replace by fetch_chunk_b, but chunk_a exists still, this graph will be
```
chunk_a
fetch_chunk_b
```
Thus we need to remove all the predecessors of the tileables that has been executed before execution.
Fixes #1242 .
=> Fix `.fetch()` that may cause some op executed again

mars/dataframe/base/describe.py, mars/dataframe/base/tests/test_base_execution.py, mars/dataframe/utils.py
This PR fixed `df.describe()` that failed when df has unknown shape and chunk size > 1
Fixes #1247 .
=> Fix `df.describe()` that failed when df has unknown shape and chunk size > 1

mars/dataframe/base/describe.py, mars/dataframe/base/tests/test_base_execution.py, mars/dataframe/utils.py
=> [BACKPORT] Fix `df.describe()` that failed when df has unknown shape and chunk size > 1 (#1249)

docs/source/dataframe/reference/api/mars.dataframe.DataFrame.astype.rst, docs/source/dataframe/reference/api/mars.dataframe.DataFrame.iterrows.rst, docs/source/dataframe/reference/api/mars.dataframe.DataFrame.itertuples.rst, docs/source/dataframe/reference/api/mars.dataframe.Series.astype.rst, docs/source/dataframe/reference/frame.rst, docs/source/dataframe/reference/series.rst, docs/source/locale/zh_CN/LC_MESSAGES/dataframe/reference/api/mars.dataframe.DataFrame.astype.po, docs/source/locale/zh_CN/LC_MESSAGES/dataframe/reference/api/mars.dataframe.DataFrame.iterrows.po, docs/source/locale/zh_CN/LC_MESSAGES/dataframe/reference/api/mars.dataframe.DataFrame.itertuples.po, docs/source/locale/zh_CN/LC_MESSAGES/dataframe/reference/api/mars.dataframe.Series.astype.po, docs/source/locale/zh_CN/LC_MESSAGES/dataframe/reference/frame.po, docs/source/locale/zh_CN/LC_MESSAGES/dataframe/reference/series.po, mars/dataframe/core.py, mars/tests/test_session.py
This PR implements `DataFrame.iterrows` as well as `DataFrame.itertuples`.
`df.execute()` will be triggered first internally.
Resolves #1251 .
=> Implements DataFrame.{iterrows, itertuples}

mars/deploy/local/tests/test_cluster.py, mars/scheduler/graph.py
Resolve the issue that `Object` type can't be serialized correctly in cluster mode.
Fixes #1260.
=> Fix `NearestNeighbors` that run failed in cluster mode

docs/source/dataframe/reference/api/mars.dataframe.DataFrame.drop.rst, docs/source/dataframe/reference/api/mars.dataframe.DataFrame.pop.rst, docs/source/dataframe/reference/api/mars.dataframe.Series.drop.rst, docs/source/dataframe/reference/frame.rst, docs/source/dataframe/reference/series.rst, docs/source/locale/zh_CN/LC_MESSAGES/dataframe/reference/api/mars.dataframe.DataFrame.drop.po, docs/source/locale/zh_CN/LC_MESSAGES/dataframe/reference/api/mars.dataframe.DataFrame.pop.po, docs/source/locale/zh_CN/LC_MESSAGES/dataframe/reference/api/mars.dataframe.Series.drop.po, mars/dataframe/base/__init__.py, mars/dataframe/base/drop.py, mars/dataframe/base/tests/test_base.py, mars/dataframe/base/tests/test_base_execution.py, mars/dataframe/datasource/index.py, mars/serialize/protos/operand.proto, mars/tests/core.py
Add support for {DataFrame,Series,Index}.drop().
Fix drop() part of #1241.
=> Add support for {DataFrame,Series,Index}.drop

mars/scheduler/tests/integrated/test_normal_execution.py, mars/web/server.py, mars/worker/service.py, mars/worker/storage/client.py
Fix failure when executing None-result functions in distributed environment. Add tests as well.
Fixes #1270
=> Fix failure when executing None-result spawn functions

mars/tensor/indexing/getitem.py
In `tensor.__setitem__`, it will just leverage `TensorIndex` for index preprocess, but for `setitem`, if multiple bool indexes or bool + fancy indexes exist, the bool index will not be converted to fancy index for the convenience of calculating setitem, thus the shape will be wrong for `TensorIndex`.
Thus in this case, we will convert to fancy index only for shape calculation.
Fixes #1282 .
=> Fix shape calculation in TensorIndex for tensor.__setitem__

mars/api.py, mars/config.py, mars/dataframe/datasource/read_csv.py, mars/dataframe/datasource/tests/test_hdfs.py, mars/deploy/local/tests/test_cluster.py, mars/filesystem.py, mars/graph.pyx, mars/serialize/core.pxd, mars/serialize/core.pyx, mars/serialize/dataserializer.py, mars/serialize/jsonserializer.pyx, mars/serialize/pbserializer.pyx, mars/serialize/tests/test_serialize.py, mars/session.py, mars/utils.py, mars/web/apihandlers.py, mars/web/server.py, mars/web/session.py, mars/web/tests/test_api.py, mars/worker/dataio.py, mars/worker/storage/diskhandler.py, mars/worker/storage/sharedhandler.py, mars/worker/storage/tests/test_disk_io.py, mars/worker/storage/tests/test_shared_io.py, mars/worker/tests/test_dataio.py, mars/worker/transfer.py, requirements-extra.txt, requirements.txt
This PR allows clients to use pickle to serialize / deserialize data and communicate with servers under two scenarios:
1. pyarrow is absent
2. the version of pyarrow is not consistent with the version at server side
Fixes #1288
=> [ENH] Allow client-side to use pickle to serialize / deserialize tensor data

mars/_utils.pyx, mars/context.py, mars/deploy/local/tests/test_cluster.py, mars/executor.py, mars/remote/core.py, mars/remote/tests/test_remote_function.py, mars/remote/utils.py, mars/session.py, mars/utils.py
This PR added support for possibility that tileables now  can be arguments for spawned functions.
```
In [1]: import mars.dataframe as md                                             
In [2]: df = md.DataFrame({'a': [1, 2, 3], 'b': [4, 5, 6]})                                                                             
In [4]: import mars.remote as mr 
In [6]: def h(f): 
...:     return f[:2].to_pandas() 
...:                                                                         
In [7]: mr.spawn(h, args=(df,)).execute().fetch()                               
Out[7]: 
a  b
0  1  4
1  2  5
```
Support part of #1227 .
=> Support tileables as arguments for spawned functions

mars/tensor/linalg/norm.py, mars/tensor/linalg/tests/test_linalg_execute.py
This PR fixes `mt.linalg.norm` when chunk shape on axis > 1.
Fixes #1301 .
=> Fix `mt.linalg.norm` when chunk shape on axis > 1

mars/tensor/linalg/norm.py, mars/tensor/linalg/tests/test_linalg_execute.py
=> [BACKPORT] Fix `mt.linalg.norm` when chunk shape on axis > 1 (#1302)

mars/lib/groupby_wrapper.py, mars/lib/tests/test_lib.py, mars/utils.py, mars/worker/execution.py
Fix error in calc_data_size() for GroupByWrapper and allow executing groupby() with distributed sessions.
Fixes #1306
=> Fix error in calc_data_size() for GroupByWrapper

mars/learn/utils/tests/test_validation.py, mars/learn/utils/validation.py
This PR fixes `check_consistent_length` that when arrays has unknown shape, trigger execution.
Fixes #1318 .
=> Trigger execution in `check_consistent_length` when arrays has unknown shape

mars/dataframe/arithmetic/core.py, mars/dataframe/arithmetic/tests/test_comparison.py, mars/dataframe/base/reset_index.py, mars/dataframe/base/tests/test_base.py, mars/dataframe/base/tests/test_base_execution.py
- Fix wrong columns value in `reset_index`.
- Use `pd.api.types.is_scalar` instead of `np.isscalar` in DataFrame.arithmetic.
Fixes #1313.
Fixes #1286.
=> Fix wrong columns value in `reset_index`

mars/dataframe/merge/tests/test_merge_execution.py, mars/dataframe/utils.py
This PR fixes `build_df` when input DataFrame has duplicate columns.
Fixes #1312 .
=> Fix `build_df` when input DataFrame has duplicate columns

mars/learn/utils/tests/test_validation.py, mars/learn/utils/validation.py
=> [BACKPORT] Trigger execution in `check_consistent_length` when arrays have unknown shape (#1321)

mars/dataframe/merge/tests/test_merge_execution.py, mars/dataframe/utils.py
=> [BACKPORT] Fix `build_df` when input DataFrame has duplicate columns (#1319)

docs/source/reference/dataframe/api/mars.dataframe.Series.rst, docs/source/reference/learn/generated/mars.learn.model_selection.train_test_split.rst, docs/source/reference/learn/reference.rst, mars/dataframe/indexing/getitem.py, mars/learn/model_selection/__init__.py, mars/learn/model_selection/_split.py, mars/learn/model_selection/tests/__init__.py, mars/learn/model_selection/tests/test_split.py, mars/learn/utils/shuffle.py, mars/learn/utils/validation.py, mars/lib/sparse/array.py
Thit PR implements `mars.learn.model_selection.train_test_split`.
Resolves #1188 .
=> Implements `mars.learn.model_selection.train_test_split`

.github/workflows/run-tests.sh, mars/dataframe/datasource/read_csv.py, mars/filesystem.py, mars/tests/test_filesystem.py
If PyArrow is not installed, we copy code from pyarrow.filesystem to make it work.
Fixes #1354.
=> Make local filesystem work when PyArrow not installed

docs/source/dataframe/reference/api/mars.dataframe.Series.rst, docs/source/learn/generated/mars.learn.model_selection.train_test_split.rst, docs/source/learn/reference.rst, mars/dataframe/indexing/getitem.py, mars/learn/model_selection/__init__.py, mars/learn/model_selection/_split.py, mars/learn/model_selection/tests/__init__.py, mars/learn/model_selection/tests/test_split.py, mars/learn/utils/shuffle.py, mars/learn/utils/validation.py, mars/lib/sparse/array.py
=> [BACKPORT] Implements `mars.learn.model_selection.train_test_split` (#1352)

mars/dataframe/datasource/read_csv.py, mars/dataframe/indexing/getitem.py, mars/dataframe/indexing/iloc.py, mars/dataframe/indexing/tests/test_indexing.py, mars/dataframe/indexing/tests/test_indexing_execution.py, mars/executor.py, mars/graph.pyx, mars/optimizes/chunk_graph/fuse.py, mars/optimizes/runtime/optimizers/core.py, mars/optimizes/runtime/optimizers/cp.py, mars/optimizes/runtime/optimizers/dataframe.py, mars/optimizes/runtime/optimizers/ne.py, mars/optimizes/runtime/optimizers/tests/test_compose.py, mars/tensor/base/partition.py, mars/tensor/fuse/tests/test_cupy_execute.py, mars/tensor/indexing/index_lib.py, mars/tensor/statistics/histogram.py, mars/tests/core.py, mars/tests/test_utils.py, mars/utils.py, setup.py
Before this PR, if DataFrame has unknown chunk shape, for instance, DataFrame created from `md.read_csv()`, `df.head()` will trigger iterative tiling, thus the entire data will be read, then get the head data, it's a huge waste, and may cause bad experience.
This PR tries to address the problem. The main point is that for this sort of `head`, try to fetch head data of each chunk, and do tree reduction to get the final head. The runtime optimization is used as well, the iloc[:n] will be `nrows`  for `read_csv`.
I did some tests on my laptop, the input csv file is around 700M.
|   | Master | This PR |
| ------------- | ------------- | ------------- |
| Memory Usage | 2548.06M  | 67.62M |
| Time  | 1.71s | 0.51s |
Detail code:
This PR:
```
In [1]: import mars.dataframe as md …
```
=> Optimize DataFrame.{head, tail} when DataFrame has unknown chunk shape

mars/dataframe/datasource/read_sql.py, mars/dataframe/datasource/tests/test_datasource_execution.py, mars/scheduler/graph.py, mars/scheduler/tests/integrated/test_normal_execution.py, mars/scheduler/tests/test_graph.py
This PR fixes `md.read_sql` when no data is selected, error is refined as well when no worker attached.
Fixes #1368 .
=> Fix read_sql when no data selected & refine error when no worker attached

mars/dataframe/datasource/read_csv.py, mars/dataframe/datasource/read_sql.py, mars/dataframe/datasource/tests/test_datasource_execution.py, mars/dataframe/indexing/iloc.py, mars/dataframe/indexing/loc.py, mars/dataframe/indexing/tests/test_indexing.py, mars/dataframe/indexing/tests/test_indexing_execution.py, mars/optimizes/runtime/optimizers/dataframe.py, mars/tensor/stats/entropy.py
This PR optimized `read_sql` and `head`. 
What's more, if input DataFrame's index is RangeIndex started with 0, `df.loc[:n]` will be rewritten with `df.iloc[:n]`, so that it can leverage the universal optimization about head, and ensure correctness when input DataFrame does not ensure index incremental.
|   | Master | This PR |
| ------------- | ------------- | ------------- |
| Memory Usage | 191.38M  | 61.73M |
| Time  | 12.2s | 9.5s |
NA
=> Optimize `read_sql` + `head`

.github/workflows/install-minikube.sh, mars/dataframe/fetch/core.py, mars/deploy/local/tests/test_cluster.py
Set object_type as a `AnyField` in  `DataFrameFetchMixin`.
Fixes #1385
=> Fix serialize failed when FetchDataFrame's object_type is a list

mars/dataframe/datasource/read_csv.py, mars/dataframe/indexing/getitem.py, mars/dataframe/indexing/iloc.py, mars/dataframe/indexing/index_lib.py, mars/dataframe/indexing/tests/test_indexing_execution.py, mars/deploy/local/tests/test_cluster.py, mars/optimizes/runtime/dataframe.py
`md.read_csv('xx.csv')[['col1', 'col2']]` will read the entire data and select columns then, in this PR, `usecols` will be set if `read_csv` is followed by `getitem`, the expression will be like `md.read_csv('xx.csv', usecols=['col1', 'col2'])`, the optimization will reduce the memory usage greatly if the the number of DataFrame columns is large.
Fixes #1384
=> Optimize `read_csv` if followed by `DataFrame.getitem`

mars/learn/contrib/lightgbm/tests/integrated/test_distributed_lightgbm.py, mars/learn/contrib/lightgbm/train.py
Fix worker assign when no evaluation sets specified in LGBM training.
Fixes #1404
=> Fix worker assign when no evaluation sets specified in LGBM training

mars/learn/contrib/lightgbm/tests/integrated/test_distributed_lightgbm.py, mars/learn/contrib/lightgbm/train.py
=> [BACKPORT] Fix worker assign when no evaluation sets specified in LGBM training (#1405)

mars/api.py, mars/context.py, mars/scheduler/graph.py, mars/scheduler/tests/integrated/base.py, mars/scheduler/tests/integrated/test_normal_execution.py, mars/scheduler/tests/integrated/test_worker_failover.py, mars/session.py, mars/worker/calc.py, mars/worker/daemon.py, mars/worker/dispatcher.py, mars/worker/execution.py, mars/worker/tests/base.py, mars/worker/tests/test_calc.py, mars/worker/tests/test_dispatcher.py, mars/worker/tests/test_transfer.py
We create backup CalcActor when spawning a new graph in mars.remote. This will make the worker process blocked by waiting calls continues running.
Fixes #1407
=> Create backup CalcActor when spawning a new graph in mars.remote

mars/dataframe/datasource/read_sql.py, mars/operands.py, mars/utils.py, mars/worker/execution.py
Fix aliases for ``read_sql_query`` and add estimation for object sizes to reduce possibility of OOM.
Fixes #1415
=> Fix query alias & add estimation for object types

mars/learn/contrib/lightgbm/tests/test_ranker.py, mars/learn/contrib/lightgbm/tests/test_regressor.py, mars/learn/contrib/lightgbm/train.py
If the model is type of regressor or ranker, we specify the dtype to float.
Fixes #1418.
=> Fix the dtype of LightGBM model's predicted results.

mars/context.py, mars/dataframe/base/__init__.py, mars/dataframe/core.py, mars/dataframe/datasource/tests/test_datasource_execution.py, mars/dataframe/groupby/aggregation.py, mars/dataframe/groupby/tests/test_groupby.py, mars/dataframe/groupby/tests/test_groupby_execution.py, mars/dataframe/sort/psrs.py, mars/dataframe/sort/tests/test_sort_execute.py, mars/dataframe/utils.py, mars/deploy/local/tests/test_cluster.py, mars/operands.py, mars/remote/core.py, mars/remote/tests/test_remote_function.py, mars/scheduler/tests/integrated/no_prepare_op.py, mars/tensor/base/psrs.py, mars/tensor/rechunk/core.py, mars/tests/test_session.py, mars/utils.py, mars/worker/calc.py, mars/worker/tests/test_dispatcher.py
`sort_values` will rechunk tileable in tiles, which will trigger iterative tiling when tileable has unknown shape, in this PR, we skip rechunk to avoid iterative tiling.
Fixes #1413.
=> Skip rechunk when DataFrame has unknown shape in `sort_values`.

mars/context.py, mars/dataframe/base/__init__.py, mars/dataframe/core.py, mars/dataframe/groupby/aggregation.py, mars/dataframe/groupby/tests/test_groupby.py, mars/dataframe/groupby/tests/test_groupby_execution.py, mars/dataframe/sort/psrs.py, mars/dataframe/sort/tests/test_sort_execute.py, mars/dataframe/utils.py, mars/deploy/local/tests/test_cluster.py, mars/operands.py, mars/remote/core.py, mars/remote/tests/test_remote_function.py, mars/scheduler/tests/integrated/no_prepare_op.py, mars/tensor/base/psrs.py, mars/tensor/rechunk/core.py, mars/tests/test_session.py, mars/utils.py, mars/worker/calc.py, mars/worker/tests/test_dispatcher.py
=> [BACKPORT] Skip rechunk when DataFrame has unknown shape in `sort_values` (#1414)

mars/dataframe/base/tests/test_base_execution.py, mars/dataframe/base/transform.py
Catch error if infer dtype failed in DataFrame.transform.
Fixes #1423.
=> Fix the error raised when inferring dtype in DataFrame.transform

.github/workflows/ci.yml, .github/workflows/reload-env.sh, mars/errors.py, mars/lib/nvutils.py, mars/serialize/dataserializer.py, mars/serialize/tests/test_serialize.py, mars/session.py, mars/worker/service.py, mars/worker/storage/manager.py, mars/worker/storage/sharedstore.py
Support returning complex scalars when pyarrow does not support. Now code like
```python
mt.zeros([2, 2], dtype=mt.complex128).sum().execute()
```
can work as expected.
Fixes #552
=> Support serializing complex scalars

mars/_utils.pyx, mars/dataframe/arrays.py, mars/dataframe/base/tests/test_base_execution.py, mars/dataframe/tests/test_arrays.py
Support tokenize `ExtensionDtype` to support `ExtensionDtype ` in `df.astype`.
Fixes #1460.
=> Support `ExtensionDtype ` in `df.astype`

mars/dataframe/base/drop.py, mars/dataframe/base/tests/test_base.py
Fix incorrect `index_value` in `df.drop()`.
Fixes #1463.
=> Fix incorrect `index_value` in `df.drop()`

mars/base_app.py, mars/dataframe/arrays.py, mars/deploy/local/tests/test_cluster.py, mars/lib/mkl_interface.py, mars/scheduler/__main__.py, mars/serialize/dataserializer.py, mars/tests/test_base_app.py, mars/web/__main__.py, mars/web/session.py, mars/web/tests/test_api.py, mars/worker/__main__.py, mars/worker/calc.py, mars/worker/execution.py, mars/worker/prochelper.py, mars/worker/quota.py, mars/worker/storage/client.py, mars/worker/storage/core.py, mars/worker/storage/cudahandler.py, mars/worker/storage/procmemhandler.py, mars/worker/storage/sharedhandler.py, mars/worker/storage/vineyardhandler.py, mars/worker/tests/test_calc.py, requirements-dev.txt
Serialize results in worker before storing into shared storages. This will provide more accurate memory sizes as well as reducing memory usage. Support passing cluster info json data as an environment variable as well.
Fixes #1458
=> Serialize results in worker before storing into shared storages

mars/actors/core.pxd, mars/actors/core.pyx, mars/actors/pool/gevent_pool.pyx, mars/base_app.py, mars/config.py, mars/scheduler/assigner.py, mars/scheduler/graph.py, mars/scheduler/resource.py, mars/scheduler/tests/integrated/test_worker_failover.py, mars/scheduler/tests/test_assigner.py, mars/worker/__main__.py, mars/worker/daemon.py, mars/worker/execution.py, mars/worker/service.py, mars/worker/status.py
This PR implements several things.
1. Raise timeout when assigning failed for a long time
2. Check error raises when fail-over is disabled
3. Allow plugin ActorPool
4. Use mem_quota instead of memory when allocating resources. This will help reusing memory not released by pymalloc.
Fixes #1472
=> Raise timeout when assigning failed for a long time

mars/api.py, mars/base_app.py, mars/config.py, mars/deploy/kubernetes/client.py, mars/scheduler/__main__.py, mars/scheduler/service.py, mars/scheduler/tests/integrated/base.py, mars/scheduler/tests/integrated/test_normal_execution.py, mars/scheduler/tests/integrated/test_worker_failover.py, mars/utils.py, mars/web/tests/test_api.py, mars/worker/__main__.py, mars/worker/service.py, mars/worker/storage/iorunner.py, mars/worker/storage/tests/test_client.py
This PR does the following changes:
1. Convert ``ArrowStringArray`` to numpy array when using pickle to fetch data to client;
2. Allow specifying parallel num in ``IORunnerActor``. This allows ``IORunnerActor`` to behave like a semaphore limiting total IO operations;
3. Warn when encountering failed PODs when starting Mars cluster.  
Fixes #1479
=> Fix pickling arrow types & allow specifying parallel number in IO runners

mars/_version.py, mars/config.py, mars/dataframe/__init__.py, mars/dataframe/arrays.py, mars/dataframe/reduction/nunique.py, mars/dataframe/reduction/tests/test_reduction_execute.py, mars/dataframe/tests/test_arrays.py, mars/dataframe/utils.py, mars/serialize/dataserializer.py, mars/serialize/tests/test_serialize.py, mars/utils.py
This PR added support for `ArrowListDtype` as well as `ArrowListArray`.
I did some experiments.
```python
In[9]: import pandas as pd
In[10]: s = pd.Series(lst)
In [11]: s
Out[11]: 
0                            [Kurt Olsen, Carlos Monroe]
1                          [Scott Weeks, Ashley Swanson]
2      [Anna Campbell, Tony Scott, Lawrence Clark, Mi...
3                          [Sandra Meyers, Kevin Arnold]
4      [Vanessa Garcia, Jonathan Carlson, John Nichol...
...                        
995     [Dawn Salazar, Joel Garcia Jr., Rodney Anderson]
996                    [David Sanchez, James Richardson]
997    [Amanda Spears, Stephanie Mccormick, Deborah G...
998    [Katie Myers, Corey Williamson, Jonathan Pittman]
999                     [Jean Schneider, Caleb Stafford]
Length: 1000, dtype: …
```
=> Add support for `ArrowListDtype` as well as `ArrowListArray`

mars/dataframe/base/drop.py, mars/dataframe/base/tests/test_base.py
=> [BACKPORT] Fix incorrect `index_value` in `df.drop()` (#1466)

mars/lib/gipc.pyx, mars/serialize/core.pyx, mars/serialize/jsonserializer.pyx, mars/serialize/pbserializer.pyx, mars/serialize/tests/test_serialize.py, mars/utils.py, mars/web/session.py, requirements-extra.txt
Fix incompatibility for gevent>=20.5.1. The compatibility break was caused by gevent/gevent#1632 which raises an GreenletExit on forked processes when calling ``Hub.destroy()`` and makes subprocesses failed to start after gevent hub creation on the main process.
Fixes #1489
=> Fix compatibility for gevent>=20.5.1

mars/_version.py, mars/dataframe/datasource/read_csv.py, mars/dataframe/datasource/read_sql.py, mars/dataframe/datasource/tests/test_datasource_execution.py, mars/dataframe/utils.py
This PR added `use_arrow_dtype` argument for `md.read_csv` and `md.read_sql`.
Resolves #1465 .
=> Support `use_arrow_dtype` for `md.read_csv` and `md.read_sql`

mars/_version.py, mars/dataframe/datasource/read_csv.py, mars/dataframe/datasource/read_sql.py, mars/dataframe/datasource/tests/test_datasource_execution.py, mars/dataframe/utils.py
=> [BACKPORT] Support `use_arrow_dtype` for `md.read_csv` and `md.read_sql` (#1491)

mars/_version.py, mars/utils.py, mars/web/tests/test_api.py
This PR fixes `arrow_array_to_objects` when input is a Series whose index is not RangeIndex(n)
NA
=> Fix `arrow_array_to_objects` when input is a Series whose index is not RangeIndex(n)

mars/tensor/linalg/norm.py, mars/tensor/linalg/tests/test_linalg_execute.py
fix a bug that derived shape is incorrect when negative axis is assign to `linalg.norm` function.
add some tests
Fixes #1492
=> Fix `mt.linalg.norm` when axis is negative

mars/tensor/arithmetic/isclose.py, mars/tensor/arithmetic/tests/test_arithmetic_execution.py, mars/utils.py, mars/web/tests/test_api.py
This PR fixed `mt.isclose` when some of the arguments is scalar.
Fixes #1497 .
=> Fix `mt.isclose` when some of the arguments is scalar

mars/scheduler/graph.py, mars/scheduler/session.py, mars/web/apihandlers.py, mars/web/server.py, mars/web/tests/test_api.py
Graph information (size, start time, end time and status) are now sent into SessionActor for batch retrieval.
Fixes #1478
=> Store and query graph information in batch

mars/tensor/arithmetic/arctan2.py, mars/tensor/arithmetic/tests/test_arithmetic_execution.py
This PR fixes `mt.arctan2` when arguments contains scalar.
Fixes #1500 .
=> Fix `mt.arctan2` when arguments contain scalar

mars/tensor/base/split.py, mars/tensor/base/tests/test_base.py, mars/tensor/base/tests/test_base_execute.py
update `mt.split` to support list and tuple as first argument
Fixes #1506
=> Update `mt.split` to support list and tuple

README.rst, mars/tensor/base/split.py, mars/tensor/base/tests/test_base.py, mars/tensor/base/tests/test_base_execute.py
=> [BACKPORT] Update `mt.split` to support list and tuple (#1507)

mars/tensor/arithmetic/isclose.py, mars/tensor/arithmetic/tests/test_arithmetic_execution.py, mars/utils.py, mars/web/tests/test_api.py
=> [BACKPORT] Fix `mt.isclose` when some of the arguments is scalar (#1498)

mars/tensor/linalg/norm.py, mars/tensor/linalg/tests/test_linalg_execute.py
=> [BACKPORT] Fix `mt.linalg.norm` when axis is negative (#1499)

mars/dataframe/datasource/tests/test_datasource_execution.py, mars/dataframe/utils.py, mars/tensor/utils.py
Fix `decide_dataframe_chunk_sizes` to make it works when input DataFrame is empty.
Fixes #1521.
=> Fix creating Mars DataFrame from an empty pandas DataFrame

mars/cluster_info.py, mars/dataframe/arrays.py, mars/scheduler/assigner.py, mars/scheduler/graph.py, mars/scheduler/mutable.py, mars/scheduler/operands/base.py, mars/scheduler/operands/tests/test_common_exec.py, mars/scheduler/resource.py, mars/scheduler/session.py, mars/worker/dispatcher.py, mars/worker/execution.py, mars/worker/utils.py
Allow unregistering scheduler observers when destroying actors. This will stop ActorNotExist errors after spawning graphs in mars.remote.
Fixes #1524
=> Unregister scheduler observer when destroying actors

mars/_utils.pyx, mars/core.py, mars/dataframe/arithmetic/__init__.py, mars/dataframe/arithmetic/tests/test_comparison.py, mars/dataframe/arrays.py, mars/dataframe/core.py, mars/dataframe/tests/test_arrays.py, mars/executor.py, mars/graph_builder.py, mars/optimizes/tileable_graph/core.py, mars/scheduler/graph.py, mars/tensor/arithmetic/__init__.py, mars/tensor/arithmetic/tests/test_arithmetic.py, mars/tensor/core.py, mars/tensor/datasource/tests/test_datasource.py, mars/tests/test_utils.py, mars/tiles.py, mars/utils.py
This PR unified all modes including eager, kernel and build. Use enter_mode(kernel=None, build=None) as a unified way.
Resolves #1529 .
=> Unifiy logics of modes including `eager`, `kernel` and `build`

mars/config.py, mars/dataframe/arrays.py, mars/dataframe/base/apply.py, mars/dataframe/base/tests/test_base_execution.py, mars/dataframe/base/transform.py, mars/dataframe/core.py, mars/dataframe/datasource/tests/test_datasource_execution.py, mars/dataframe/groupby/apply.py, mars/dataframe/groupby/core.py, mars/dataframe/groupby/tests/test_groupby_execution.py, mars/dataframe/indexing/rename.py, mars/dataframe/reduction/aggregation.py, mars/dataframe/reduction/tests/test_reduction.py, mars/dataframe/reduction/tests/test_reduction_execute.py, mars/dataframe/tests/test_arrays.py, mars/dataframe/utils.py, mars/dataframe/window/aggregation.py, mars/operands.py, mars/serialize/protos/indexvalue.proto, mars/tests/test_session.py
This PR mainly introduced:
1. Support `df.groupby().count()` for arrow dtype with and without pyarrow installed
2. Make `ArrowArray` work even when pyarrow not installed and not in kernel mode. If pyarrow not installed and in kernel mode(for instance, inside tile or execute), an ImportError will be raised.
Fixes #1514 .
=> Support `df.groupby().count()` for arrow dtype with and without pyarrow installed

mars/config.py, mars/dataframe/arrays.py, mars/dataframe/base/apply.py, mars/dataframe/base/tests/test_base_execution.py, mars/dataframe/base/transform.py, mars/dataframe/core.py, mars/dataframe/datasource/tests/test_datasource_execution.py, mars/dataframe/groupby/apply.py, mars/dataframe/groupby/core.py, mars/dataframe/groupby/tests/test_groupby_execution.py, mars/dataframe/indexing/rename.py, mars/dataframe/reduction/aggregation.py, mars/dataframe/reduction/tests/test_reduction.py, mars/dataframe/reduction/tests/test_reduction_execute.py, mars/dataframe/tests/test_arrays.py, mars/dataframe/utils.py, mars/dataframe/window/aggregation.py, mars/operands.py, mars/serialize/protos/indexvalue.proto, mars/tests/test_session.py
=> [BACKPORT] Support df.groupby().count() for arrow dtype with and without pyarrow installed (#1523)

.github/workflows/ci.yml, mars/learn/cluster/_k_means_init.py, mars/learn/cluster/_kmeans.py, mars/learn/cluster/tests/test_k_means.py, mars/learn/metrics/pairwise/euclidean.py, mars/learn/metrics/pairwise/tests/test_euclidean_distances.py, mars/serialize/dataserializer.py, mars/serialize/tests/test_serialize.py, mars/worker/calc.py, mars/worker/quota.py
This PR did two things to optimize `mars.learn.cluster.KMeans` when `n_clusters` is relatively large.
1. Do rechunk in `euclidean_distances` to prevent from potential large chunks.
2. Cut k-means++ iterations into pieces and trigger execution to reduce size of chunk graph.
Resolves #1510 .
=> Optimize `mars.learn.cluster.KMeans` when `n_clusters` is relatively large

mars/dataframe/core.py, mars/deploy/local/tests/test_cluster.py, mars/executor.py, mars/ray/core.py, mars/ray/tests/test_ray_execution.py, mars/session.py, mars/tensor/fuse/core.py, setup.py
This PR did a few things.
1. Fix `md.read_csv` for Ray executor.
2. Disable numexpr fuse for Ray executor.
3. Optimize performance of RayStorage.
Fixes #1542 .
=> Fix `md.read_csv` for Ray executor

mars/context.py, mars/dataframe/base/apply.py, mars/dataframe/groupby/apply.py, mars/dataframe/groupby/tests/test_groupby_execution.py, mars/dataframe/utils.py, mars/deploy/local/tests/test_cluster.py
Support executing ``df.groupby(xxx).apply(fun)`` where ``fun`` returns nothing.
Fixes #1543
=> Allow returning None when using groupby.apply

mars/tensor/base/swapaxes.py, mars/tensor/base/tests/test_base_execute.py
Fix cannot pass numpy array into mt.swapaxes
Fixes #1552
=> Fix bug that cannot pass numpy array to `mt.swapaxes`

mars/tensor/base/swapaxes.py, mars/tensor/base/tests/test_base_execute.py
=> [BACKPORT] Fix bug that cannot pass numpy array to `mt.swapaxes` (#1553)

docs/source/reference/dataframe/api/mars.dataframe.DataFrame.mask.rst, docs/source/reference/dataframe/api/mars.dataframe.DataFrame.rst, docs/source/reference/dataframe/api/mars.dataframe.DataFrame.where.rst, docs/source/reference/dataframe/api/mars.dataframe.Series.mask.rst, docs/source/reference/dataframe/api/mars.dataframe.Series.rst, docs/source/reference/dataframe/api/mars.dataframe.Series.where.rst, docs/source/reference/dataframe/frame.rst, docs/source/reference/dataframe/series.rst, mars/dataframe/core.py, mars/dataframe/indexing/__init__.py, mars/dataframe/indexing/tests/test_indexing_execution.py, mars/dataframe/indexing/where.py, mars/deploy/kubernetes/tests/test_kubernetes.py
Add support for {DataFrame,Series}.{where,mask}. Alignment between DataFrames and Series not supported.
Fixes #1338
=> Add support for {DataFrame,Series}.{where,mask}

.github/workflows/ci.yml, mars/dataframe/__init__.py, mars/dataframe/datasource/read_csv.py, mars/dataframe/datasource/read_parquet.py, mars/dataframe/datasource/tests/test_datasource_execution.py, mars/dataframe/utils.py
Read a parquet file into DataFrame.
Closes #1578.
=> Add `read_parquet` support

mars/dataframe/arithmetic/core.py, mars/dataframe/arithmetic/tests/test_arithmetic.py, mars/dataframe/datasource/read_parquet.py, mars/dataframe/reduction/tests/test_reduction_execute.py, mars/dataframe/utils.py
When the one of the input chunk's columns is empty, reduction operations will raise a ValueError. Small fixes in function `build_df` will resolve it.
Fixes #1586.
Fixes #1590.
=> Fix the failure of DataFrame reduction operators

mars/graph.pyx, mars/learn/contrib/lightgbm/tests/integrated/test_distributed_lightgbm.py, mars/learn/contrib/lightgbm/train.py, mars/learn/tests/integrated/base.py
Clear ``out_dtype_`` argument when fitting models. This will fix ValueError when a LGBMModel is fitted again.
Fixes #1597
=> Fix error on fitting LGBMModel twice

mars/deploy/kubernetes/config.py, mars/learn/model_selection/tests/test_split.py, mars/learn/utils/validation.py
This PR fixed `train_test_split` when some input is Series.
Fixes #1603 .
=> Fix `train_test_split` when some input is Series

.github/workflows/ci.yml, mars/learn/neighbors/_faiss.py, mars/learn/neighbors/tests/test_faiss.py
This PR fixes `build_faiss_index` when some index type cannot be merged.
Fixes #1608 .
=> Fix `build_faiss_index` when some index type cannot be merged

mars/learn/contrib/lightgbm/core.py, mars/learn/contrib/lightgbm/regressor.py, mars/learn/contrib/lightgbm/tests/test_regressor.py, mars/utils.py, mars/worker/storage/objectholder.py, mars/worker/storage/tests/test_objectholder.py
Convert all inputs into Mars tileables before running LightGBM wrapper.
Fixes #1605
=> Allow LightGBM wrapper to use numpy arrays

mars/dataframe/sort/psrs.py, mars/dataframe/sort/sort_values.py, mars/dataframe/sort/tests/test_sort_execute.py, mars/scheduler/tests/integrated/test_normal_execution.py, mars/worker/prochelper.py, mars/worker/quota.py
Add (chunk_key, row_id) as an extra sort key to resolve value bias in PSRS sort algorithm.
Fixes #1611
=> Add an extra sort key in PSRS to make distinct pivot

mars/dataframe/datasource/read_csv.py, mars/dataframe/datasource/tests/test_datasource_execution.py, mars/dataframe/groupby/aggregation.py, mars/dataframe/sort/sort_values.py, mars/tensor/einsum/core.py
If inferred dtype is wrong due to the NAN value, `read_csv` will fail in execution, in this PR we will not passing `dtype` argument when call `pd.read_csv` to fix the behavior.
Fixes #1604.
=> Fixes `md.read_csv` when `dtypes` is not inferred correctly

mars/dataframe/datasource/read_csv.py, mars/dataframe/datasource/tests/test_datasource_execution.py, mars/dataframe/groupby/aggregation.py, mars/dataframe/sort/sort_values.py, mars/tensor/einsum/core.py
=> [BACKPORT] Fixes `md.read_csv` when `dtypes` is not inferred correctly (#1606)

mars/ray/core.py
Release of v0.6.0a3 is broken due to release of Ray 1.0.0, see https://github.com/mars-project/mars/actions/runs/280830850.
This PR fixes the compatibility.
NA
=> Fix Ray 1.0 compatibility

.github/workflows/ci.yml, mars/dataframe/indexing/setitem.py, mars/dataframe/indexing/tests/test_indexing.py
Fix the wrong dtypes of `DataFrameSetitem`'s inputs.
Fixes #1622.
=> Fix the wrong dtypes of `DataFrameSetitem`'s inputs

.github/workflows/ci.yml, mars/dataframe/indexing/setitem.py, mars/dataframe/indexing/tests/test_indexing.py
=> [BACKPORT] Fix the wrong dtypes of `DataFrameSetitem`'s inputs (#1623)

mars/dataframe/base/apply.py, mars/dataframe/base/map_chunk.py, mars/dataframe/base/tests/test_base.py, mars/dataframe/base/tests/test_base_execution.py
This PR fixes issue that `output_type` does not take effect for `df.apply`.
Fixes #1625 .
=> Fix issue that `output_type` does not take effect for `df.apply`

mars/dataframe/base/apply.py, mars/dataframe/base/map_chunk.py, mars/dataframe/base/tests/test_base.py, mars/dataframe/base/tests/test_base_execution.py
=> [BACKPORT] Fix issue that `output_type` does not take effect for `df.apply` (#1626)

.github/workflows/install-minikube.sh, mars/scheduler/assigner.py, mars/scheduler/graph.py
Eliminate TimeoutError when there are running nodes. This resolves the issue when the job is constructed with time-consuming nodes.
Fixes #1636
=> Eliminate TimeoutError when there are running nodes

mars/config.py, mars/dataframe/statistics/quantile.py, mars/learn/metrics/__init__.py, mars/learn/metrics/pairwise/__init__.py, mars/learn/metrics/pairwise/core.py, mars/learn/metrics/pairwise/euclidean.py, mars/learn/metrics/pairwise/pairwise_distances_topk.py, mars/learn/metrics/pairwise/tests/test_pariwise_distances.py, mars/learn/neighbors/base.py, mars/learn/utils/__init__.py, mars/learn/utils/core.py, mars/serialize/protos/operand.proto
This PR introduced an internal function `pairwise_distances_topk` to reduce the memory cost for `NearestNeighbors`.
Resolves #1621 .
=> Optimize memory usage for brute-force algorithm in `NearestNeighbors`

mars/custom_log.py, mars/scheduler/tests/integrated/test_normal_execution.py
This PR added `flush` method to `_LogWrapper`, this prevents from AttributeError when users call `sys.stdout.flush()`.
Fixes #1645 .
=> Add `flush` method to `_LogWrapper`

mars/_version.py, mars/dataframe/merge/concat.py, mars/dataframe/merge/tests/test_merge.py
This PR fixes `md.concat` which may occupy huge amount of memory on client when all of DataFrames own large RangeIndex.
Master branch:
```python
In [1]: import mars.tensor as mt                                                                                                                                                                            
In [2]: import mars.dataframe as md                                                                                                                                                                         
In [3]: df = md.DataFrame(mt.random.rand(1000_0000, 10))                                                                                                                                                    
In [4]: df2 = …
```
=> Fix `md.concat` which may occupy huge amount of memory on client when all of DataFrames own large RangeIndex

mars/_version.py, mars/dataframe/merge/concat.py, mars/dataframe/merge/tests/test_merge.py
=> [BACKPORT] Fix `md.concat` which may occupy huge amount of memory on client when all of DataFrames own large RangeIndex (#1649)

mars/base_app.py, mars/dataframe/indexing/reset_index.py, mars/dataframe/indexing/tests/test_indexing.py, mars/dataframe/indexing/tests/test_indexing_execution.py
Add support for `reset_index(inplace=True)`.
Fixes #1659
=> Support `inplace` parameter in `reset_index` method

mars/base_app.py, mars/dataframe/indexing/reset_index.py, mars/dataframe/indexing/tests/test_indexing.py, mars/dataframe/indexing/tests/test_indexing_execution.py
=> [BACKPORT] Support `inplace` parameter in `reset_index` method (#1662)

mars/core.py, mars/dataframe/fetch/core.py, mars/dataframe/operands.py, mars/deploy/local/tests/test_cluster.py, mars/learn/operands.py, mars/operands.py, mars/tensor/fetch/core.py, mars/tensor/operands.py
Create Fetch operands given output types, not operand types. This resolves errors caused by fetching tensors generated by DataFrame operands with DataFrameFetch.
Fixes #1664
=> Create Fetch operands given output types

mars/deploy/local/tests/test_cluster.py, mars/scheduler/operands/shuffle.py
When `ShuffleProxyActor` is reused, `io_meta` should be updated when append new graphs.
Fixes #1661.
=> Fix hang for rerun `DataFrame.groupby` in distributed mode

mars/deploy/local/tests/test_cluster.py, mars/scheduler/operands/shuffle.py
=> [BACKPORT] Fix hang for rerun `DataFrame.groupby` in distributed mode (#1667)

mars/config.py, mars/dataframe/indexing/iloc.py, mars/dataframe/indexing/tests/test_indexing_execution.py, mars/optimizes/runtime/dataframe.py
Expressions like `df.head(n)` will be optimized to reduce the memory usage, however, the strategy will even requires more memory when `n` is large, in this PR, we set a threshold 1000, if `n` greater than it, the optimization will be disabled.
Fixes #1658.
=> Add a threshold for `DataFrame.head` optimization

mars/core.py, mars/tests/test_session.py
=> [BACKPORT] Modify `df.copy()` so that it generates the identical key (#1671)

mars/config.py, mars/deploy/kubernetes/client.py, mars/deploy/kubernetes/config.py, mars/deploy/kubernetes/tests/test_config.py, mars/lib/gipc.pyx, mars/resource.py, mars/worker/__main__.py, mars/worker/calc.py, mars/worker/execution.py, mars/worker/service.py, mars/worker/tests/test_calc.py, mars/worker/tests/test_service.py, mars/worker/utils.py
Mount `/dev/shm` on host to pods when starting Mars workers in kubernetes. This will effectively fix SIGBUS issue. Add lower bound for shared memory also.
Fixes #1676
=> Mount /dev/shm on host to pods when starting Mars workers in Kubernetes

mars/config.py, mars/deploy/kubernetes/client.py, mars/deploy/kubernetes/config.py, mars/deploy/kubernetes/tests/test_config.py, mars/lib/gipc.pyx, mars/resource.py, mars/worker/__main__.py, mars/worker/calc.py, mars/worker/execution.py, mars/worker/service.py, mars/worker/tests/test_calc.py, mars/worker/tests/test_service.py, mars/worker/utils.py
=> [BACKPORT] Mount /dev/shm on host to pods when starting Mars workers in Kubernetes (#1677)

mars/dataframe/indexing/setitem.py, mars/dataframe/indexing/tests/test_indexing.py
Changes in #1623 only fixed tileable's dtypes, fix wrong dtypes of chunks in this PR.
Fixes #1622.
=> Fix wrong dtypes of DataFrame setitem chunks

mars/_version.py, mars/dataframe/indexing/setitem.py, mars/dataframe/indexing/tests/test_indexing.py
=> [BACKPORT] Fix wrong dtypes of DataFrame setitem chunks (#1690)

mars/deploy/kubernetes/config.py, mars/scheduler/graph.py, mars/worker/__main__.py, mars/worker/service.py, mars/worker/tests/test_main.py
Add timeout for SharedHolderActor creation.
Fixes #1683
=> Add timeout for SharedHolderActor creation

mars/deploy/local/tests/test_cluster.py, mars/tensor/fuse/core.py
It has been fixed in master in #1541, this PR picks the related commit(https://github.com/mars-project/mars/pull/1541/commits/66be75170184919935ca06ceed2c526d30553bda) to backport to branch v0.5.
Fixes #1698.
=> Fix the KeyError in `estimate_fuse_size`

mars/operands.py, mars/remote/core.py, mars/scheduler/graph.py, mars/scheduler/tests/integrated/no_prepare_op.py, mars/scheduler/tests/integrated/test_normal_execution.py, mars/tensor/base/shape.py, mars/tensor/datastore/to_hdf5.py, mars/worker/calc.py, mars/worker/execution.py
As all usages of `prepare_inputs` can be replaced with `pure_depends` without pains, the former property can be replaced.
=> Remove `prepare_inputs` property on operands

mars/ray/core.py, mars/ray/tests/test_ray_execution.py
- Problem
- mars on ray raises an exception when load code from local.
- Solution
- Move nested type `RemoteMetaStore` outside the `RayStorage` class.
Fixes #1711
=> Fix mars not working on ray cluster

docs/source/reference/dataframe/frame.rst, docs/source/reference/dataframe/series.rst, mars/_version.py, mars/dataframe/base/__init__.py, mars/dataframe/base/explode.py, mars/dataframe/base/tests/test_base_execution.py, mars/serialize/dataserializer.py, mars/serialize/protos/operand.proto
Implements {DataFrame,Series}.explode. Also fix pandas objects serialized from old versions.
Fixes #1704
Fixes #1713
=> Implements {DataFrame,Series}.explode

mars/dataframe/base/map.py, mars/dataframe/base/tests/test_base_execution.py, mars/dataframe/base/value_counts.py, mars/dataframe/groupby/core.py, mars/dataframe/indexing/getitem.py, mars/dataframe/indexing/set_index.py, mars/dataframe/indexing/tests/test_indexing.py, mars/dataframe/indexing/tests/test_indexing_execution.py, mars/dataframe/utils.py
This PR fixes:
1. Infer dtype correctly for `series.map`.
2. Pass index name for bool indexing.
3. Eliminate index name for `series.value_counts` which is consistent to pandas.
4. Fix `build_mock_groupby` which may raise error `ValueError: cannot reindex from a duplicate axis`.
Fixes #1717 .
Fixes #1718 .
=> Fix inferring dtype for `series.map`

mars/dataframe/sort/core.py, mars/dataframe/sort/psrs.py, mars/dataframe/sort/sort_index.py, mars/dataframe/sort/sort_values.py, mars/dataframe/sort/tests/test_sort_execute.py
Fix `sort_index` and `sort_values` of DataFrames on CUDA. cuDF 0.16 is needed.
Fixes #1720
=> Fix sort functions of DataFrames on CUDA

mars/config.py, mars/worker/dataio.py, mars/worker/service.py, mars/worker/storage/__init__.py, mars/worker/storage/diskhandler.py, mars/worker/storage/diskmerge.py, mars/worker/storage/tests/test_disk_io.py
Write into  and read from merged files when data sizes are small. This reduces the number of inodes when using external storages.
=> Write into and read from merged files when data sizes are small

mars/dataframe/base/__init__.py, mars/dataframe/base/apply.py, mars/dataframe/base/map.py, mars/dataframe/base/rebalance.py, mars/dataframe/base/rechunk.py, mars/dataframe/base/tests/test_base_execution.py, mars/dataframe/base/transform.py, mars/dataframe/datasource/from_tensor.py, mars/dataframe/groupby/apply.py, mars/dataframe/groupby/transform.py, mars/dataframe/initializer.py, mars/dataframe/tests/test_initializer.py, mars/dataframe/tests/test_utils.py, mars/dataframe/utils.py
1. Support `num_partitions` argument for DataFrame initializers
2. Fixes column order when creating DataFrames from dicts
3. Allow creating Series from Index
4. Suspend standard outputs when inferring output dtypes
Fixes #1314 
Fixes #1726
Fixes #1728
=> Support `num_partitions` argument for DataFrame initializers

mars/dataframe/datasource/read_csv.py, mars/dataframe/datasource/tests/test_datasource_execution.py
This PR fixes `md.read_csv` when names and usecols specified.
Fixes #1736 .
=> Fix `md.read_csv` when names and usecols specified

.github/workflows/ci.yml, docs/source/reference/learn/reference.rst, docs/source/user_guide/learn/index.rst, docs/source/user_guide/learn/statsmodels.rst, mars/learn/contrib/statsmodels/__init__.py, mars/learn/contrib/statsmodels/api.py, mars/learn/contrib/statsmodels/predict.py, mars/learn/contrib/statsmodels/tests/__init__.py, mars/learn/contrib/statsmodels/tests/integrated/__init__.py, mars/learn/contrib/statsmodels/tests/integrated/test_distributed_statsmodels.py, mars/learn/contrib/statsmodels/tests/test_statsmodels.py, mars/learn/contrib/statsmodels/train.py, mars/scheduler/analyzer.py, mars/serialize/protos/operand.proto
Add distributed model for statsmodels library. As statsmodels does not support model analysis for `RegularizedResults` generated from `DistributedModel`, it is not implemented either.
Fixes #1734
=> Add preliminary statsmodels support

docs/source/reference/dataframe/api/mars.dataframe.groupby.GroupBy.kurt.rst, docs/source/reference/dataframe/api/mars.dataframe.groupby.GroupBy.kurtosis.rst, docs/source/reference/dataframe/api/mars.dataframe.groupby.GroupBy.sem.rst, docs/source/reference/dataframe/api/mars.dataframe.groupby.GroupBy.skew.rst, docs/source/reference/dataframe/groupby.rst, mars/dataframe/groupby/__init__.py, mars/dataframe/groupby/aggregation.py, mars/dataframe/groupby/core.py, mars/dataframe/groupby/tests/test_groupby_execution.py, mars/dataframe/reduction/nunique.py
This PR is a followup of #1705 by replacing implements of ``groupby.agg`` with newly-implemented ``ReductionCompiler``. ``skew``, ``kurt`` and ``CustomReduction`` are added, and those issues can be closed now.
Under Intel 10700K with test data
```python
import numpy as np
import pandas as pd
raw = pd.DataFrame(np.random.rand(1000, 10))
raw[0] = raw[0].map(lambda x: 'ABC'[int(x * 3)])
df = md.DataFrame(raw, chunk_size=20)
```
Tests with this PR patched:
```python
In[3]: %timeit df.groupby(0).sum()
6.74 ms ± 42.7 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
In[4]: %timeit df.groupby(0).var()
6.65 ms ± 7.27 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
In[5]: %timeit df.groupby(0).agg(['sum', 'var'])
15 ms ± 17.1 µs per loop (mean ± std. …
```
=> Unify groupby.agg() using ReductionCompiler

mars/dataframe/datasource/read_csv.py, mars/dataframe/datasource/tests/test_datasource_execution.py
=> [BACKPORT] Fix `md.read_csv` when names and usecols specified (#1737)

mars/tensor/reduction/all.py, mars/tensor/reduction/any.py, mars/tensor/reduction/core.py, mars/tensor/reduction/sum.py, mars/tensor/reduction/tests/test_reduction_execute.py
This PR added string dtype support for tensor reductions.
Fixes #1743 .
=> Support string dtype for tensor reductions

mars/dataframe/initializer.py, mars/dataframe/merge/concat.py, mars/dataframe/operands.py, mars/dataframe/tests/test_initializer.py, mars/learn/contrib/lightgbm/tests/integrated/test_distributed_lightgbm.py, mars/learn/contrib/xgboost/tests/integrated/test_distributed_xgboost.py, mars/scheduler/__main__.py, mars/scheduler/operands/shuffle.py, mars/scheduler/tests/integrated/test_normal_execution.py
Allow non-consecutive indices when concatenating df objects. This resolves training issues for xgboost and lightgbm.
Fixes #1740
=> Fix xgboost and lightgbm on DataFrames

mars/_utils.pyx, mars/dataframe/groupby/aggregation.py, mars/dataframe/groupby/core.py, mars/dataframe/groupby/tests/test_groupby_execution.py, mars/dataframe/indexing/iloc.py, mars/scheduler/graph.py, mars/scheduler/operands/common.py, mars/scheduler/tests/integrated/test_normal_execution.py, mars/tests/test_utils.py, mars/worker/storage/client.py
Fix the case running in distributed mode:
```python
grouped = mdf.groupby('col2', as_index=False)['col2'].agg({"cnt":'count'}).execute()
grouped.sort_values(by='cnt').head().execute()
mdf.groupby('col2', as_index=False)['col2'].agg({"cnt":'count'}).sort_values(by='cnt').head().execute()
```
Fixes #1741
Fixes #1752
=> Fix repeated execution of same code in distributed mode

mars/dataframe/base/apply.py, mars/dataframe/base/tests/test_base.py, mars/dataframe/base/transform.py, mars/dataframe/groupby/apply.py, mars/dataframe/groupby/core.py, mars/dataframe/groupby/cum.py, mars/dataframe/groupby/tests/test_groupby.py, mars/dataframe/groupby/tests/test_groupby_execution.py, mars/dataframe/groupby/transform.py, mars/dataframe/tests/test_utils.py, mars/dataframe/utils.py, mars/deploy/local/tests/test_cluster.py, mars/operands.py
Add documentation for apply and transform on DataFrames. Also fix type infer issue for groupby.apply.
Fixes #1763
=> Fill docs for apply and transform

mars/dataframe/base/apply.py, mars/dataframe/base/tests/test_base.py, mars/dataframe/base/transform.py, mars/dataframe/groupby/apply.py, mars/dataframe/groupby/core.py, mars/dataframe/groupby/cum.py, mars/dataframe/groupby/tests/test_groupby.py, mars/dataframe/groupby/tests/test_groupby_execution.py, mars/dataframe/groupby/transform.py, mars/dataframe/tests/test_utils.py, mars/dataframe/utils.py, mars/deploy/local/tests/test_cluster.py, mars/operands.py
=> [BACKPORT] Fill docs for apply and transform (#1764)

mars/dataframe/reduction/aggregation.py, mars/dataframe/reduction/core.py, mars/deploy/local/tests/test_cluster.py, mars/scheduler/graph.py, mars/scheduler/operands/base.py
Spawn serialization of executable graphs so that web pages does hot get stuck.
=> Spawn serialization of executable graphs

mars/dataframe/base/string_.py, mars/dataframe/groupby/aggregation.py, mars/dataframe/groupby/tests/test_groupby_execution.py, mars/dataframe/reduction/__init__.py, mars/dataframe/reduction/aggregation.py, mars/dataframe/reduction/core.py, mars/dataframe/reduction/str_concat.py, mars/dataframe/reduction/tests/test_reduction_execute.py, mars/serialize/protos/operand.proto
Add ``str.cat`` as base aggregation method. Now users can call ``df.groupby('col').agg(lambda x: x.str.cat(sep='+')``.
Fixes #1775
=> Integrate `str.cat` into reduction and groupby-aggregation

mars/dataframe/base/string_.py, mars/dataframe/groupby/aggregation.py, mars/dataframe/groupby/tests/test_groupby_execution.py, mars/dataframe/reduction/__init__.py, mars/dataframe/reduction/aggregation.py, mars/dataframe/reduction/core.py, mars/dataframe/reduction/str_concat.py, mars/dataframe/reduction/tests/test_reduction_execute.py, mars/serialize/protos/operand.proto
=> [BACKPORT] Integrate `str.cat` into reduction and groupby-aggregation (#1776)

docs/source/installation/index.rst, docs/source/installation/kubernetes.rst, docs/source/installation/yarn.rst, mars/dataframe/datasource/read_csv.py, mars/dataframe/datasource/read_parquet.py, mars/dataframe/datasource/tests/test_datasource_execution.py, mars/dataframe/datasource/tests/test_hdfs.py, mars/dataframe/datastore/tests/test_datastore_execute.py
Fix reading partitioned parquet files in HDFS by using ``mars.filesystem`` methods instead of built-in ``os`` package.
Fixes #1780
=> Fix reading partitioned parquet files in HDFS

mars/dataframe/arithmetic/core.py, mars/dataframe/groupby/aggregation.py, mars/dataframe/reduction/core.py, mars/dataframe/reduction/tests/test_reduction.py, mars/dataframe/reduction/tests/test_reduction_execute.py
Implements reductions like `df.sum(level=1)` using groupby and reduction compiler.
Deal with full groupby issue #1036.
=> Implements reduction with `level` argument

mars/dataframe/arithmetic/core.py, mars/dataframe/groupby/aggregation.py, mars/dataframe/reduction/core.py, mars/dataframe/reduction/tests/test_reduction.py, mars/dataframe/reduction/tests/test_reduction_execute.py
=> [BACKPORT] Implements reduction with `level` argument (#1779)

mars/learn/contrib/lightgbm/_predict.py, mars/learn/contrib/lightgbm/_train.py, mars/learn/contrib/lightgbm/tests/test_classifier.py, mars/learn/contrib/xgboost/dmatrix.py, mars/learn/contrib/xgboost/predict.py, mars/learn/contrib/xgboost/tests/test_predict.py, mars/learn/contrib/xgboost/tests/test_train.py, mars/tensor/core.py, mars/tensor/datasource/from_dense.py, mars/tensor/datasource/from_sparse.py, mars/tensor/datasource/tests/test_datasource_execute.py
This PR support `missing` argument for `tensor.tosparse()` and `fill_value` argument for `sparse_tensor.todense()`.
Resolves #1795 .
=> Support `missing` argument for `tensor.tosparse()` and `fill_value` argument for `sparse_tensor.todense()`

docs/source/reference/dataframe/api/mars.dataframe.CustomReduction.rst, docs/source/reference/dataframe/api/mars.dataframe.DataFrame.backfill.rst, docs/source/reference/dataframe/api/mars.dataframe.DataFrame.bfill.rst, docs/source/reference/dataframe/api/mars.dataframe.DataFrame.explode.rst, docs/source/reference/dataframe/api/mars.dataframe.DataFrame.ffill.rst, docs/source/reference/dataframe/api/mars.dataframe.DataFrame.isnull.rst, docs/source/reference/dataframe/api/mars.dataframe.DataFrame.notnull.rst, docs/source/reference/dataframe/api/mars.dataframe.DataFrame.pad.rst, docs/source/reference/dataframe/api/mars.dataframe.DataFrame.replace.rst, docs/source/reference/dataframe/api/mars.dataframe.DataFrame.rst, docs/source/reference/dataframe/api/mars.dataframe.Series.explode.rst, docs/source/reference/dataframe/api/mars.dataframe.Series.rst, docs/source/reference/learn/generated/mars.learn.contrib.statsmodels.MarsDistributedModel.rst, docs/source/reference/learn/generated/mars.learn.contrib.statsmodels.MarsResults.rst, mars/dataframe/datastore/tests/test_datastore_execute.py, mars/dataframe/datastore/to_parquet.py, mars/learn/contrib/xgboost/predict.py, mars/learn/contrib/xgboost/tests/test_classifier.py
This PR fixes bug that explicit execute may be required for to_parquet and XGB predict.
Fixes #1792 .
=> Fix bug that explicit execute may be required for to_parquet and XGB predict

mars/learn/contrib/lightgbm/_predict.py, mars/learn/contrib/lightgbm/_train.py, mars/learn/contrib/lightgbm/tests/test_classifier.py, mars/learn/contrib/xgboost/dmatrix.py, mars/learn/contrib/xgboost/predict.py, mars/learn/contrib/xgboost/tests/test_predict.py, mars/learn/contrib/xgboost/tests/test_train.py, mars/tensor/core.py, mars/tensor/datasource/from_dense.py, mars/tensor/datasource/from_sparse.py, mars/tensor/datasource/tests/test_datasource_execute.py
=> [BACKPORT] Support `missing` argument for `tensor.tosparse()` and `fill_value` argument for `sparse_tensor.todense()` (#1797)

mars/dataframe/datasource/read_csv.py, mars/dataframe/datasource/read_parquet.py, mars/dataframe/datasource/tests/test_datasource_execution.py, mars/utils.py
This PR added memory estimation for `read_parquet` as well as `read_csv`.
Resolves #1809 .
=> Add memory estimation for `read_parquet` as well as `read_csv`

.github/workflows/cd.yml, .github/workflows/core-ci.yml, .github/workflows/os-compat-ci.yml, mars/dataframe/groupby/aggregation.py, mars/dataframe/reduction/aggregation.py, mars/dataframe/reduction/all.py, mars/dataframe/reduction/any.py, mars/dataframe/reduction/core.py, mars/dataframe/reduction/count.py, mars/dataframe/reduction/custom_reduction.py, mars/dataframe/reduction/kurtosis.py, mars/dataframe/reduction/max.py, mars/dataframe/reduction/mean.py, mars/dataframe/reduction/min.py, mars/dataframe/reduction/nunique.py, mars/dataframe/reduction/prod.py, mars/dataframe/reduction/reduction_size.py, mars/dataframe/reduction/sem.py, mars/dataframe/reduction/skew.py, mars/dataframe/reduction/str_concat.py, mars/dataframe/reduction/sum.py, mars/dataframe/reduction/unique.py, mars/dataframe/reduction/var.py, mars/deploy/kubernetes/core.py, mars/learn/cluster/_k_means_init.py, mars/operands.py, mars/tests/test_session.py, requirements-extra.txt
Allow calling compound aggregation functions, such as ``df.agg(lambda x: x.mean() + x.skew())`` in df.agg(). Also simplify definitions of builtin functions.
=> Support using compound agg function in lambda

.github/workflows/platform-ci.yml, mars/dataframe/datasource/from_tensor.py, mars/dataframe/datasource/read_parquet.py, mars/dataframe/datasource/tests/test_datasource_hdfs.py, mars/dataframe/datastore/tests/test_datastore_hdfs.py, mars/dataframe/datastore/to_parquet.py, mars/dataframe/indexing/set_index.py, mars/dataframe/indexing/tests/test_indexing_execution.py, mars/dataframe/initializer.py, mars/dataframe/tests/test_initializer.py, mars/deploy/yarn/tests/test_yarn.py, mars/learn/contrib/lightgbm/core.py, mars/learn/contrib/lightgbm/tests/test_classifier.py, mars/learn/contrib/xgboost/classifier.py, mars/learn/contrib/xgboost/predict.py, mars/learn/contrib/xgboost/tests/test_classifier.py, mars/tests/core.py
=> [BACKPORT] Remove unnecessary iterative tiling when predicting via XGBoost and data from/to parquet (#1818)

mars/dataframe/indexing/reset_index.py, mars/dataframe/indexing/tests/test_indexing_execution.py, mars/dataframe/merge/concat.py, mars/tensor/datasource/from_dense.py
This PR added `incremental_index` argument which by default is False to `reset_index`.
**Remember that this is a break change**.
Resolves #1822 .
=> Add `incremental_index` argument to `reset_index` which by default is False

mars/tensor/core.py
There is a small typo in mars/tensor/core.py.
Should read `partitioned` rather than `parititioned`.
Semi-automated pull request generated by
https://github.com/timgates42/meticulous/blob/master/docs/NOTE.md
=> docs: fix simple typo, parititioned -> partitioned

mars/deploy/kubedl/config.py
1. set worker cache by memoryTuningPolicy instead of directly environments.
=> Set marsjob worker cache by memoryTuningPolicy.

.github/workflows/platform-ci.yml, mars/dataframe/arithmetic/bitwise_and.py, mars/dataframe/arithmetic/bitwise_or.py, mars/dataframe/arithmetic/bitwise_xor.py, mars/dataframe/arithmetic/core.py, mars/dataframe/arithmetic/tests/test_arithmetic_execution.py, mars/dataframe/arrays.py, mars/dataframe/base/transform.py, mars/dataframe/groupby/core.py, mars/dataframe/reduction/aggregation.py, mars/dataframe/reduction/core.py, mars/dataframe/reduction/tests/test_reduction.py, mars/dataframe/reduction/tests/test_reduction_execute.py, mars/dataframe/tests/test_arrays.py, mars/dataframe/utils.py, mars/dataframe/window/rolling/aggregation.py, mars/dataframe/window/rolling/tests/test_rolling_execute.py, mars/utils.py, requirements-dev.txt, requirements.txt
Fixes some compatibility issues for pandas v1.2.0
Fixes #1845.
=> Fix compatibility for pandas 1.2.0

docs/source/locale/zh_CN/LC_MESSAGES/reference/dataframe/indexing.po, docs/source/reference/dataframe/index.rst, docs/source/reference/dataframe/indexing.rst, mars/dataframe/arithmetic/core.py, mars/dataframe/arithmetic/is_ufuncs.py, mars/dataframe/base/__init__.py, mars/dataframe/base/astype.py, mars/dataframe/base/cartesian_chunk.py, mars/dataframe/base/map.py, mars/dataframe/base/tests/test_base_execution.py, mars/dataframe/base/transform.py, mars/dataframe/core.py, mars/dataframe/datasource/index.py, mars/dataframe/missing/__init__.py, mars/dataframe/missing/checkna.py, mars/dataframe/missing/dropna.py, mars/dataframe/missing/fillna.py, mars/dataframe/missing/tests/test_missing_execute.py, mars/dataframe/reduction/__init__.py, mars/dataframe/reduction/aggregation.py, mars/dataframe/reduction/all.py, mars/dataframe/reduction/any.py, mars/dataframe/reduction/max.py, mars/dataframe/reduction/min.py, mars/dataframe/reduction/nunique.py, mars/dataframe/reduction/tests/test_reduction_execute.py, mars/dataframe/tests/test_utils.py, mars/operands.py, mars/tests/test_session.py
Add missing values methods for md.Index. Also add documentations for Mars index.
Fixes #1832
Part of #1840 is done (``iteritems()`` and ``items()``)
=> Add more functionalities for `md.Index`

docs/source/locale/zh_CN/LC_MESSAGES/reference/dataframe/indexing.po, docs/source/reference/dataframe/frame.rst, docs/source/reference/dataframe/indexing.rst, docs/source/reference/dataframe/series.rst, mars/dataframe/core.py, mars/dataframe/indexing/__init__.py, mars/dataframe/indexing/rename.py, mars/dataframe/indexing/rename_axis.py, mars/dataframe/indexing/tests/test_indexing_execution.py, mars/serialize/protos/operand.proto, mars/tests/test_session.py
Implements `{DataFrame,Series}.rename_axis`. Also allows setting names of columns or indexes.
Fixes #1665 
Part of #1840 is done (iteritems() and items() on series)
=> Implements `{DataFrame,Series}.rename_axis`

CODEOWNERS, mars/dataframe/base/cartesian_chunk.py, mars/dataframe/datasource/from_tensor.py, mars/dataframe/datasource/tests/test_datasource_execution.py, mars/ray/tests/test_ray_execution.py, mars/tensor/reshape/reshape.py, mars/tensor/reshape/tests/test_reshape.py, mars/tensor/reshape/tests/test_reshape_execute.py, mars/tensor/statistics/histogram.py, mars/tensor/statistics/tests/test_statistics_execute.py
This PR added support for mt.reshape, mt.histogram and md.DataFrame when input tileable has unknown shape.
Fixes #1868 
Fixes #1843
=> Support unknown shape for mt.reshape, mt.histogram and md.DataFrame

mars/dataframe/core.py, mars/tests/test_session.py
This PR fixes wrongly raised error: Tileable object must be executed first before being fetched
Fixes #1871 .
=> Fix wrongly raised error: Tileable object must be executed first before being fetched

mars/dataframe/core.py, mars/tensor/base/flatten.py, mars/tensor/reshape/reshape.py, mars/tensor/reshape/tests/test_reshape_execute.py, mars/tests/test_session.py
This PR fixes reshape when input tensor has unknown shape and 1 chunk.
This is a followed fix of #1869 .
Fixes #1873 .
=> Fix reshape when input tensor has unknown shape and 1 chunk

mars/dataframe/core.py, mars/tests/test_session.py
=> [BACKPORT] Fix wrongly raised error: Tileable object must be executed first before being fetched (#1872)

mars/actors/pool/gevent_pool.pyx, requirements-extra.txt
Use cross-thread semaphores (gevent>20.5.1 required) to resolve stuck of threaded actor operations in gevent==20.12.0.
Fixes #1816
=> Fix stuck of threaded actor operations in gevent==20.12.0

mars/config.py, mars/scheduler/tests/test_graph.py, mars/utils.py, mars/worker/execution.py
As it is quite slow to construct protobuf objects in Python due to type checks, we change serialization method into JSON and make serialization methods configurable.
=> Allow internal serialization to use JSON

mars/dataframe/core.py, mars/dataframe/datasource/index.py, mars/dataframe/initializer.py, mars/dataframe/sort/psrs.py, mars/dataframe/sort/tests/test_sort_execute.py, mars/tensor/base/tests/test_base_execute.py
This PR fixes two issues:
1. Fixes sorting string columns with None values with a largest object to make None comparable with strings.
2. Fixes sorting when there are empty chunks in data sources.
Similar bugs may exist in tensor sort and this PR does not fix them.
Fixes #1885
Fixes #1890
=> Fix sorting string columns with None value & sorting with empty chunks

.github/workflows/platform-ci.yml, mars/config.py, mars/context.py, mars/dataframe/datastore/to_vineyard.py, mars/deploy/local/tests/test_cluster.py, mars/tensor/datastore/to_vineyard.py, mars/worker/storage/vineyardhandler.py
+ Avoid copy chunks again when they are already in vineyard.
+ Use latest released vineyard in CI, rather than a hacked one.
N/A
=> To vineyard: avoid copy when chunks are already in vineyard (vineyard is the backend).

mars/dataframe/base/rechunk.py, mars/dataframe/datastore/tests/test_datastore_execute.py, mars/dataframe/datastore/to_csv.py, mars/learn/contrib/xgboost/tests/test_classifier.py, mars/tensor/rechunk/rechunk.py
This PR fixes rechunk when input tileable has unknown shape.
Fixes #1901 
Fixes #1910
=> Fix rechunk when input tileable has unknown shape

mars/deploy/kubedl/client.py, mars/deploy/kubernetes/core.py
Add `KUBE_VERIFY_SSL` environment in kubernetes to ignore the certificate when connect to api server.
NA
=> Allow set verify_ssl to False for kubernetes configuration

mars/dataframe/reduction/core.py, mars/dataframe/utils.py
Optimize generating mock DataFrames when num of columns is large.
Test results:
```python
import mars.tensor as mt, mars.dataframe as md
a = mt.random.randint(low=1, high=1000, size=(20000, 40000))
```
```python
%%time
df = md.DataFrame(a)
_ = df.min()
```
```
Before:
CPU times: user 28.2 s, sys: 302 ms, total: 28.5 s
Wall time: 28.5 s
After: 
CPU times: user 4.44 s, sys: 55.4 ms, total: 4.5 s
Wall time: 4.52 s
```
```python
from mars.dataframe.utils import build_empty_df
%time _ = build_empty_df(df.dtypes)
```
```
Before:
CPU times: user 28.4 s, sys: 297 ms, total: 28.7 s
Wall time: 28.7 s
After:
CPU times: user 4.36 s, sys: 39 ms, total: 4.4 s
Wall time: 4.4 s
```
=> Optimize generating mock DataFrames

CODEOWNERS, mars/dataframe/arithmetic/core.py, mars/dataframe/groupby/aggregation.py, mars/dataframe/groupby/cum.py, mars/dataframe/groupby/tests/test_groupby_execution.py, mars/dataframe/groupby/transform.py, mars/dataframe/missing/replace.py, mars/dataframe/statistics/quantile.py, mars/deploy/local/tests/test_cluster.py, mars/learn/neighbors/tree.py, mars/tensor/statistics/histogram.py, mars/tests/core.py, mars/utils.py
1. Fix KeyError when comparing series. This is caused by fusing inputs of DataFrameBinOp and lhs / rhs not updated. Code base scanned manually and similar errors may not occur again.
2. Fix selecting column 0 after groupby and do aggregation. The cause is that value 0 is treated as None.
Fixes #1918 
Fixes #1919
=> Fix KeyError when comparing series

CODEOWNERS, mars/_version.py, mars/dataframe/base/rechunk.py, mars/dataframe/base/tests/test_base_execution.py, mars/dataframe/utils.py, mars/tensor/rechunk/rechunk.py
This PR fixes rechunk when chunks have different dtypes that cannot compare
Fixes #1908 .
=> Fix rechunk when chunks have different dtypes that cannot compare

mars/optimizes/tileable_graph/core.py, mars/optimizes/tileable_graph/tests/test_head.py
Fix KeyError when column pruning is applied, we need replace the inputs of optimized node.
Fixes #1923
=> Fix KeyError when column pruning is applied

mars/learn/model_selection/tests/integrated/__init__.py, mars/learn/model_selection/tests/integrated/test_distributed_split.py, mars/learn/utils/shuffle.py
``mars.learn.shuffle`` fails to set output type for ``LearnShuffleProxy``. When executed distributedly, Mars cannot generate proper FetchShuffle object, and execution fails.
Fixes #1930
=> Fix shuffling data in mars.learn module

mars/learn/contrib/xgboost/start_tracker.py, mars/learn/contrib/xgboost/tests/integrated/test_distributed_xgboost.py, mars/learn/contrib/xgboost/train.py, mars/tests/integrated/base.py
This PR fixes memory estimation of StartTracker for XGBoost
Fixes #1932
=> Fix memory estimation of StartTracker for XGBoost

mars/dataframe/base/describe.py, mars/dataframe/base/rechunk.py, mars/dataframe/base/tests/test_base_execution.py
For now, users cannot skip calculating percentiles, because it's very time-consuming.  Now we can specify `percentiles=False` which is illegal for pandas, but used to skip percentiles computation for Mars.
Besides, this PR used `DataFrame.agg` to perform aggregation computation instead of doing reduction for each column.
Fixes #1942 .
=> Optimize performance of `DataFrame.describe()`

mars/dataframe/base/rechunk.py, mars/dataframe/base/tests/test_base.py, mars/learn/contrib/xgboost/classifier.py, mars/learn/contrib/xgboost/predict.py, mars/learn/contrib/xgboost/regressor.py, mars/learn/contrib/xgboost/tests/test_train.py, mars/tensor/rechunk/rechunk.py
This PR fixes `MarsDMatrix` when input tensor has unknown chunk shape. Extra arguments for predict are support as well.
Fixes #1963 
Fixes #1965
=> Fix `MarsDMatrix` when input tensor has unknown chunk shape

mars/serialization/core.py, mars/serialization/numpy.py, mars/serialization/tests/test_serial.py, mars/storage/core.py, mars/storage/plasma.py, mars/storage/shared_memory.py, mars/storage/tests/test_libs.py, mars/storage/vineyard.py
This PR added storage backend of `multiprocessing.shared_memory`. `shared_memory` is introduced in Python 3.8, its advantage is that it supports windows, until we decided to backport shared_memory module for older version of Python, we can only support it for Python 3.8+ for now.
NA
=> [storage][shared_memory] Add storage backend of `multiprocessing.shared_memory`

.github/workflows/platform-ci.yml, mars/dataframe/datasource/from_vineyard.py, mars/dataframe/datastore/tests/test_datastore_execute.py, mars/dataframe/datastore/to_vineyard.py, mars/deploy/local/tests/test_cluster.py, mars/tensor/datasource/from_vineyard.py, mars/tensor/datastore/tests/test_datastore_execute.py, mars/tensor/datastore/to_vineyard.py, requirements-vineyard.txt, setup.py
This pull request fixes the diff coverage problem imposed by #1952 as well.
N/A
=> Re-enable the from/to vineyard test cases, and set meta for tensor/dataframe properly.

mars/lib/sparse/matrix.py, mars/tensor/reduction/core.py, mars/tensor/reduction/tests/test_reduction_execute.py, mars/tensor/statistics/tests/test_statistics_execute.py
Return the chunk itself when there is no content inside, and `keepdims` is True. This will stop `ValueError` being raised when some chunk is empty.
Fixes #1977
=> Fix ValueError when reducing tensors with empty chunks

mars/lib/sparse/matrix.py, mars/tensor/reduction/core.py, mars/tensor/reduction/tests/test_reduction_execute.py, mars/tensor/statistics/tests/test_statistics_execute.py
=> [BACKPORT] Fix ValueError when reducing tensors with empty chunks (#1978)

mars/deploy/local/tests/test_cluster.py, mars/tensor/statistics/histogram.py, mars/worker/calc.py
Fix job hang when error message can't be pickled.
Fixes #1959
=> Fix job hang when error message can't be pickled

mars/dataframe/sort/psrs.py, mars/dataframe/sort/tests/test_sort_execute.py
Fix `IndexError` for sorting empty series.
=> Fix `sort_values` for empty series

mars/dataframe/sort/psrs.py, mars/dataframe/sort/tests/test_sort_execute.py
=> [BACKPORT] Fix IndexError in `Series.sort_values` when some chunk is empty (#1999)

mars/dataframe/groupby/sample.py, mars/dataframe/groupby/tests/test_groupby_execution.py, mars/deploy/kubernetes/client.py, mars/deploy/kubernetes/core.py, mars/lib/groupby_wrapper.py
Add `errors` argument for groupby.sample to ignore errors when group size less than `n`. This also adapts logic from pandas groupby.sample and then bugs of weighted sampling in pandas will not affect Mars.
Fixes #2000
=> Add `errors` argument for groupby.sample to ignore errors when group size less than `n`

mars/_version.py, mars/dataframe/groupby/sample.py, mars/dataframe/groupby/tests/test_groupby_execution.py, mars/deploy/kubernetes/client.py, mars/deploy/kubernetes/core.py, mars/lib/groupby_wrapper.py
=> [BACKPORT] Add `errors` argument for groupby.sample to ignore errors when group size less than `n` (#2002)

mars/deploy/kubernetes/config.py, mars/deploy/kubernetes/core.py, mars/tensor/arithmetic/core.py, mars/tensor/base/copyto.py, mars/tensor/base/tests/test_base_execute.py, mars/tensor/base/where.py, mars/utils.py
This PR does things below:
1. Fix TypeError caused by `None`s in shapes
2. Fix shape inconsistency when x and y in `where` are all scalars
3. Fix CI failure for kubernetes
Fixes #2009
=> Fix errors when calling where() on reshape results

mars/oscar/backends/mars/tests/test_mars_actor_context.py, mars/oscar/backends/mars/tests/test_pool.py, mars/oscar/core.pyx, mars/tests/test_utils.py, mars/utils.py
Add support for batch interfaces for actors. Actor writers can define actors as
```python
class TestActor(mo.Actor):
@extensible
def method(self, arg1, arg2):
@method.batch
def method(self, args_list, kwargs_list):
```
and invoke as
```python
ref = await mp.actor_ref('TestActor', address='address')
await ref.batch(
ref.method(val1_1, val2_1),
ref.method(val1_2, val2_2),
)
```
=> Add support for batch interfaces for actors

mars/dataframe/arithmetic/tests/test_arithmetic.py, mars/optimizes/runtime/tests/test_compose.py, mars/scheduler/tests/test_analyzer.py, mars/tensor/__init__.py, mars/tensor/arithmetic/__init__.py, mars/tensor/arithmetic/add.py, mars/tensor/arithmetic/core.py, mars/tensor/arithmetic/multiply.py, mars/tensor/arithmetic/tests/test_arithmetic.py, mars/tensor/arithmetic/tests/test_arithmetic_execution.py, mars/tensor/arithmetic/utils.py, mars/tensor/einsum/core.py, mars/tensor/linalg/lu.py, mars/tensor/linalg/matmul.py, mars/tensor/linalg/solve_triangular.py, mars/tensor/linalg/tensordot.py, mars/tensor/reduction/core.py, mars/tensor/special/core.py, mars/tensor/statistics/histogram.py, mars/tests/test_executor.py, mars/worker/tests/test_calc.py
Implements tree arithmetic for tensor add and multiplication to make operand tree of consecutive arithmetic operations shallower. Most of the codes moved from `mars.tensor.special.core`.
Deal with #2023
=> Implements tree arithmetic for tensor add and multiplication

mars/lib/gipc.pyx, mars/oscar/__init__.py, mars/oscar/api.py, mars/oscar/backends/mars/allocate_strategy.py, mars/oscar/backends/mars/communication/__init__.py, mars/oscar/backends/mars/communication/core.py, mars/oscar/backends/mars/communication/dummy.py, mars/oscar/backends/mars/communication/socket.py, mars/oscar/backends/mars/communication/tests/test_comm.py, mars/oscar/backends/mars/config.py, mars/oscar/backends/mars/context.py, mars/oscar/backends/mars/core.py, mars/oscar/backends/mars/message.py, mars/oscar/backends/mars/pool.py, mars/oscar/backends/mars/router.py, mars/oscar/backends/mars/tests/test_pool.py, mars/oscar/backends/ray/context.pyx, mars/oscar/context.pyx, mars/oscar/errors.py
This PR did a few things:
1. Add cancel support, now an actor operation can be cancelled. 
2. Error handling is optimized.
3. Actor pool now can auto recovering when process is done, if `auto_recover` is specified as True or 'actor', the actors created on the process will be created automatically.
4. `kill_actor` API is added to make sure an Actor can be destroyed even if it's blocked, but remember this is a dangerous operation that it actually did it by killing a process, make sure the actors that created in the same process are stateless.
5. Now more than 1 pools can be created.
NA
=> [oscar] Add cancel support, optimize error handling, add `kill_actor` API

.github/workflows/platform-ci.yml, mars/dataframe/datasource/from_vineyard.py, mars/dataframe/datastore/tests/test_datastore_execute.py, mars/dataframe/datastore/to_vineyard.py, mars/deploy/local/tests/test_cluster.py, mars/tensor/datasource/from_vineyard.py, mars/tensor/datastore/tests/test_datastore_execute.py, mars/tensor/datastore/to_vineyard.py, requirements-vineyard.txt, setup.py
=> [BACKPORT] Re-enable the from/to vineyard test cases, and set meta for tensor/dataframe properly(#1967)

mars/oscar/api.py, mars/oscar/backends/mars/pool.py, mars/oscar/backends/mars/tests/test_mars_actor_context.py, mars/oscar/core.pyx
Fix call `__pre_destroy__` when actors are in main pool.
Fixes #2044
=> Fix __pre_destroy__ not called when actors are in main pool

mars/tensor/base/insert.py, mars/tensor/base/tests/test_base_execute.py
`mt.insert` doesn't work if index object is the last position in the specific axis, the PR fixes this bug and add test cases.
Fixes #2043
=> Fix the wrong results of `mt.insert`

mars/serialization/tests/test_serial.py, mars/services/scheduling/__init__.py, mars/services/scheduling/api.py, mars/services/task/api.py, mars/tests/test_utils.py, mars/utils.py
Allow sync actor methods to be extensible. Scheduling APIs also added.
=> Allow sync actor methods to be extensible

mars/oscar/backends/mars/core.py, mars/oscar/backends/mars/message.py, mars/serialization/arrow.py, mars/serialization/core.py, mars/serialization/cuda.py, mars/serialization/mars_objects.py, mars/serialization/numpy.py, mars/serialization/scipy.py, mars/serialization/tests/test_serial.py, requirements-dev.txt, requirements-wheel.txt, requirements.txt
Allow serializer ro serialize recursive objects. Duplicated objects will be serialized only once.
=> Allow serializer to serialize recursive objects

.github/workflows/cd.yml, .github/workflows/core-ci.yml, .github/workflows/install-minikube.sh, .github/workflows/platform-ci.yml, mars/learn/neighbors/tests/test_faiss.py, mars/lib/gipc.pyx, mars/tensor/base/tests/test_base_execute.py, mars/tensor/base/unique.py
Fix `mt.unique` on empty arrays for numpy 1.18.x.
Deal with #2059 on v0.6.
=> Fix `mt.unique` on empty arrays

mars/oscar/backends/mars/pool.py, mars/oscar/backends/mars/tests/test_mars_actor_context.py
This PR fixes main pool that creating servers only when sub pools finished creation.
Before, because creating servers is quicker than forking sub processes, so the servers on main pool will be forked.
=> Fix main pool that creating servers only when sub pools finished creation

.github/workflows/platform-ci.yml, mars/deploy/local/core.py, mars/tensor/datasource/from_vineyard.py, mars/worker/service.py, mars/worker/storage/objectholder.py, mars/worker/storage/vineyardhandler.py, mars/worker/utils.py
+ Fixes the bug in batch get/delete vineyard object ID
+ Don't launch plasma if vineyard is enabled.
This pull request may could fixes recent random failures in CI.
=> Fix batch get / delete object id and stop launching plasma when working on vineyard

.github/workflows/install-hadoop.sh, mars/learn/contrib/lightgbm/__init__.py, mars/learn/contrib/lightgbm/_predict.py, mars/learn/contrib/lightgbm/classifier.py, mars/learn/contrib/lightgbm/core.py, mars/learn/contrib/lightgbm/ranker.py, mars/learn/contrib/lightgbm/regressor.py, mars/learn/contrib/utils.py, mars/learn/contrib/xgboost/__init__.py, mars/learn/contrib/xgboost/predict.py, mars/serialization/core.py
Use module-level `__getattr__` to load lightgbm and xgboost lazily. This prevents loading CUDA modules before fork.
=> Make import of LightGBM and XGBoost lazy

mars/dataframe/datasource/core.py, mars/dataframe/datasource/read_csv.py, mars/dataframe/datasource/read_parquet.py, mars/dataframe/datasource/read_sql.py, mars/learn/datasets/tests/integrated/__init__.py, mars/learn/datasets/tests/integrated/test_distributed_samples_generator.py, mars/learn/decomposition/_pca.py, mars/learn/utils/shuffle.py, mars/optimizes/runtime/dataframe.py, mars/optimizes/tileable_graph/tests/test_column_pruning.py
This PR fixes two issues.
1. Distributed `make_blobs` caused by missing `dtype` in learn shuffle.
2. `read_sql` followed by column selection when optimization is valid.
Fixes #2091 
Fixes #2074
=> Fix distributed `make_blobs` and column pruning in `read_sql`

mars/oscar/backends/context.py, mars/oscar/backends/mars/pool.py, mars/oscar/backends/mars/tests/test_mars_actor_context.py, mars/oscar/backends/pool.py, mars/oscar/backends/ray/pool.py, mars/services/task/supervisor/tests/test_task_manager.py
Shutdown subprocesses gracefully to let coverage data being recorded.
=> Fix coverage result on SubActorPool

mars/oscar/backends/mars/tests/test_mars_actor_context.py, mars/oscar/core.pyx, mars/serialization/core.py
Fix result error when yield after exceptions.
=> Fix result error when yield after exceptions

mars/storage/ray.py
- Fix put_file_like_object for ray >= 1.3.0
Fixes #2105 .
=> Fix put_file_like_object for ray >= 1.3.0

docs/source/reference/dataframe/frame.rst, docs/source/reference/dataframe/series.rst, mars/dataframe/indexing/__init__.py, mars/dataframe/indexing/add_preifx.py, mars/dataframe/indexing/tests/test_indexing_execution.py
This PR adds `{DataFrame,Series}.add_prefix` support.
Fixes #1825
=> Add add_prefix support

.gitignore, mars/services/scheduling/supervisor/globalslot.py, mars/services/scheduling/worker/execution.py, mars/services/scheduling/worker/tests/test_execution.py, mars/services/scheduling/worker/workerslot.py, mars/tensor/arithmetic/tests/test_arithmetic_execution.py, mars/tensor/random/tests/test_random_execute.py
Make sure slot usages are updated when some task ends. This may reduce the ratio when heavy-loaded jobs are loaded onto the same worker.
=> Make sure slot usages updated when some task ends

.github/workflows/platform-ci.yml, mars/deploy/oscar/tests/local_test_with_vineyard_config.yml, mars/deploy/oscar/tests/test_local.py, mars/services/storage/transfer.py, mars/storage/core.py, mars/storage/tests/test_libs.py, mars/storage/vineyard.py, setup.cfg
This pull request brings back the vineyard support, more specifically,
1. Overhual the vineyard storage implementation.
2. Support (put + open_reader) and (open_writer + get) operations on vineayrd storage.
3. A bugfix in `BufferWrappedFileObject.close()`
4. Split the "test_reader_and_writer" test case to verify the roundtrip property of storage backend.
The code has been tested with `test_lib.py` and `test_local.py` with vineyard storage backend, and all cases are green. Note this pull request also bumps up the dependency version of vineyard package to v0.2.4, which, will be uploaded to pypi and dockerhub later today.
N/A.
=> Enable mars (oscar) runs on vineyard.

mars/deploy/kubernetes/config.yml, mars/deploy/kubernetes/tests/test_kube_config.yml, mars/deploy/oscar/base_config.yml, mars/deploy/oscar/config.yml, mars/deploy/oscar/rayconfig.yml, mars/deploy/oscar/tests/check_enabled_config.yml, mars/deploy/oscar/tests/fault_injection_config.yml, mars/deploy/oscar/tests/local_test_config.yml, mars/deploy/oscar/tests/local_test_with_vineyard_config.yml, mars/deploy/tests/base_test_cfg.yml, mars/deploy/tests/inherit_test_cfg1.yml, mars/deploy/tests/inherit_test_cfg2.yml, mars/deploy/tests/test_utils.py, mars/deploy/utils.py, mars/deploy/yarn/config.yml, mars/deploy/yarn/tests/test_yarn_config.yml, mars/tests/test_session.py
Allow configuring overriding fields for config sections. Add `@` as prefix for meta configs also.
=> Support configuring overriding fields

mars/dataframe/groupby/aggregation.py, mars/dataframe/groupby/tests/test_groupby_execution.py, mars/dataframe/reduction/core.py, mars/dataframe/reduction/tests/test_reduction.py, setup.cfg
Fix unexpected NaNs in groupby-agg discovered in two scenarios:
1. multiple group keys with `as_index == False`
2. aggregation with same function on different rows
Fixes #2175 
Fixes #2176
=> Fix unexpected NaNs in groupby-agg

mars/dataframe/base/drop_duplicates.py, mars/dataframe/base/duplicated.py, mars/dataframe/groupby/core.py, mars/dataframe/groupby/tests/test_groupby_execution.py, mars/dataframe/merge/merge.py, mars/dataframe/utils.py
Fix groupby on indexes with duplicate items by filtering DataFrames with `iloc`.
Fixes #2185
=> Fix groupby on indexes with duplicate items

mars/deploy/oscar/tests/test_cmdline.py, mars/oscar/backends/pool.py, mars/services/scheduling/supervisor/globalslot.py, mars/services/scheduling/supervisor/queueing.py, mars/services/scheduling/worker/workerslot.py, mars/services/subtask/api.py, mars/services/subtask/worker/runner.py
Fix starting multiple workers in shared file system by allocating different process indexes. Also fixes missing slots when running jobs immediately after worker start.
Fixes #2180
Fixes #2188
=> Fix starting multiple workers in shared file system

.github/workflows/core-ci.yml, azure-pipelines.yml, mars/dataframe/arrays.py, mars/dataframe/base/astype.py, mars/dataframe/base/shift.py, mars/dataframe/base/value_counts.py, mars/dataframe/groupby/aggregation.py, mars/dataframe/indexing/loc.py, mars/dataframe/reduction/aggregation.py, mars/dataframe/reduction/tests/test_reduction_execute.py, mars/dataframe/statistics/quantile.py, mars/dataframe/tests/test_arrays.py, mars/dataframe/window/ewm/core.py, mars/dataframe/window/expanding/core.py, mars/dataframe/window/rolling/core.py, setup.py
Fix compatibility issue for pandas 1.3, including
1. initialize binary class for `PandasArray`
2. copy non-contiguous data before astype (see pandas-dev/pandas#42396)
3. consolidate data before shift to workaround (see pandas-dev/pandas#42401)
4. change input type of find_common_type into lists
5. window function reprs
6. keep original order when calculating `value_counts`.
Fixes #2191
=> Fix compatibility issue for pandas 1.3

mars/_version.py, mars/deploy/oscar/tests/test_cmdline.py, mars/deploy/oscar/worker.py, mars/oscar/backends/mars/backend.py, mars/oscar/backends/test/backend.py, mars/services/scheduling/worker/tests/test_execution.py, mars/services/storage/api/oscar.py, mars/services/storage/core.py, mars/services/storage/spill.py, mars/services/storage/transfer.py, mars/services/subtask/worker/processor.py, mars/services/task/api/web.py, mars/storage/filesystem.py, mars/storage/plasma.py, setup.py
Make all storage API like `put`, `get`, `fetch` methods call `StorageHandlerActor` directly.
=> Move `fetch` method from `StorageManagerActor` to `StorageHandlerActor`

mars/deploy/oscar/tests/modules/replace_op.py, mars/oscar/backends/mars/tests/test_pool.py, mars/services/scheduling/worker/quota.py, mars/services/scheduling/worker/service.py, mars/services/scheduling/worker/tests/test_quota.py, mars/services/scheduling/worker/tests/test_workerslot.py, mars/services/scheduling/worker/workerslot.py
Restart idle slots when hard memory limit is encountered. This will relieve task stuck when too much memory used by small allocations caused by `PyAlloc`.
=> Restart idle slots when hard memory limit is encountered

mars/dataframe/tests/test_utils.py, mars/dataframe/utils.py, setup.py
This PR fixes merge_index_value when index_values come from multi range indexes.
Fixes #2206 .
=> Fix merge_index_value when index_values come from multi range indexes

mars/oscar/__init__.py, mars/oscar/api.py, mars/oscar/backends/context.py, mars/oscar/backends/mars/tests/test_mars_actor_context.py, mars/oscar/backends/mars/tests/test_pool.py, mars/oscar/backends/message.py, mars/oscar/backends/pool.py, mars/oscar/context.pyx, mars/oscar/core.pxd, mars/oscar/core.pyx, mars/services/cluster/api/oscar.py, mars/services/cluster/tests/test_uploader.py, mars/services/cluster/uploader.py, mars/services/scheduling/worker/workerslot.py, mars/tests/test_session.py
Add support for stateless actors. Also add method `wait_actor_pool_recovered` for oscar. Calling the method will wait till a sub pool is recovered.
=> Add support for stateless actors

mars/services/scheduling/worker/tests/test_execution.py, mars/services/storage/api/oscar.py, mars/services/storage/core.py, mars/services/storage/errors.py, mars/services/storage/handler.py, mars/services/storage/spill.py, mars/services/storage/tests/test_spill.py, mars/services/storage/tests/test_transfer.py, mars/services/storage/transfer.py, mars/services/subtask/worker/processor.py, mars/storage/core.py
We catch `NoDataToSpill` and create an asyncio event, when put or unpin finishes, we will check spillable size, if size is enough for spilling, call event.set() to wake up spilling task.
=> Fix `NoDataToSpill` when multiple storage quota requests happen simultaneously

azure-pipelines.yml, mars/dataframe/groupby/aggregation.py, mars/dataframe/groupby/tests/test_groupby_execution.py, mars/deploy/oscar/cmdline.py, mars/deploy/oscar/supervisor.py, mars/deploy/oscar/worker.py, mars/oscar/backends/config.py, mars/oscar/backends/mars/pool.py, mars/oscar/backends/mars/tests/test-logging.conf, mars/oscar/backends/mars/tests/test_pool.py, mars/oscar/backends/pool.py, mars/tests/core.py
Pass logging config file name into sub pools to let sub pools print logs as configured. Also fixes aggregation issue.
Fixes #2212
=> Pass logging config file name into sub pools

mars/deploy/oscar/local.py, mars/deploy/oscar/session.py, mars/deploy/oscar/tests/test_local.py
Add methods to sessions to get web endpoint. Also print web endpoint when starting local clusters with web.
=> Add methods to sessions to get web endpoint

mars/core/context.py, mars/core/entity/executable.py, mars/core/entity/tileables.py, mars/core/operand/base.py, mars/core/operand/core.py, mars/dataframe/datasource/core.py, mars/dataframe/datasource/read_csv.py, mars/dataframe/datasource/read_parquet.py, mars/dataframe/datasource/read_sql.py, mars/dataframe/datasource/tests/test_datasource_execution.py, mars/deploy/oscar/tests/test_local.py, mars/learn/utils/collect_ports.py, mars/learn/utils/tests/test_collect_ports.py, mars/services/context.py, mars/services/core.py, mars/services/scheduling/api.py, mars/services/scheduling/tests/test_service.py, mars/services/session/supervisor/core.py, mars/services/subtask/core.py, mars/services/subtask/worker/processor.py, mars/services/task/analyzer/analyzer.py, mars/services/task/analyzer/assigner.py, mars/services/task/analyzer/fusion.py, mars/services/task/supervisor/stage.py, mars/tensor/datastore/to_hdf5.py, mars/typing.py
Before, for op like `md.read_csv`, index is not guaranteed to be incremental, instead, each chunk's index is from 0 to length. User can add an argument `incremental_index=True` to the function to ensure it, however, this will decrease performance badly, because in that case, each chunk needs to wait for the finish of previous ones.
Now with implementation of this branch, incremental index will be guaranteed by default, and without much decreasing performance.
**This branch:**
```
In [1]: import mars
In [2]: mars.new_session(default=True)
WARNING:bokeh.server.util:Host wildcard '*' will allow connections originating from multiple (or possibly all) hostnames or IPs. Use non-wildcard values to restrict access explicitly
Out[2]: <mars.deploy.oscar.session.SyncSession at 0x7fefb91746d0>
In …
```
=> Ensure range index incremental for data source op like `md.read_csv`

mars/deploy/oscar/tests/test_local.py, mars/services/meta/api/oscar.py, mars/services/subtask/worker/processor.py, mars/services/task/supervisor/processor.py
Subtask that contains mapper operand will generate multiple data whose key is consist of main and sub keys, before, only main key is recorded in meta, this will cause potential data leak, what's more, when auto scaling triggered, the data will be not aware of, so data may be lost. This PR tries to record their meta.
=> Record mapper meta for shuffle task

mars/dataframe/groupby/tests/test_groupby_execution.py, mars/deploy/oscar/tests/local_test_with_ray_config.yml, mars/deploy/oscar/tests/test_local.py, mars/deploy/oscar/tests/test_ray.py, mars/services/session/api/core.py, mars/services/session/api/web.py
For oscar, `fetch_log` support is absent for web session, this PR added it.
=> Support `fetch_log` for web session

mars/oscar/backends/mars/pool.py, mars/services/meta/api/oscar.py, mars/services/scheduling/worker/tests/test_execution.py, mars/services/storage/api/oscar.py, mars/services/storage/core.py, mars/services/storage/handler.py, mars/services/storage/spill.py, mars/services/storage/tests/test_api.py, mars/services/storage/tests/test_spill.py, mars/services/storage/tests/test_transfer.py, mars/services/storage/transfer.py, mars/tensor/base/tests/test_base_execute.py
Implements `batch_fetch` to reduce rpc call when fetch a large number of small objects.
=> Use batch method to reduce transferring cost for shuffle tasks

mars/deploy/oscar/tests/test_ray_fault_injection.py, mars/oscar/api.py, mars/oscar/backends/context.py, mars/oscar/backends/mars/pool.py, mars/oscar/backends/pool.py, mars/oscar/backends/ray/communication.py, mars/oscar/backends/ray/driver.py, mars/oscar/backends/ray/pool.py, mars/oscar/backends/ray/tests/test_ray_pool.py, mars/oscar/context.pyx, mars/services/scheduling/worker/execution.py, mars/services/scheduling/worker/workerslot.py
This PR generally adds support of basic rerun subtask for ray backend, and is basically the subsequent work for #2198. The details are as follows.
* Fix the hanging problem when recovering ray sub pool.
* Raise a ServerClosed when sub pool dies, which is the same as the original backend.
* Fix the wait_actor_pool_recovered logic.
* Fix coverage of some ray subprocesses.
**Note**: This PR changes back to one way channel for ray backend communication, which can have some side effects. If there are better ways to achieve the ServerClosed support, it's ok to change this.
=> [Ray] Rerun subtask for ray backend

mars/services/web/ui/.eslintrc.yml, mars/services/web/ui/src/Utils.js, mars/services/web/ui/src/node_info/NodeEnvTab.js, mars/services/web/ui/src/node_info/NodeListPage.js, mars/services/web/ui/src/node_info/NodeResourceTab.js, mars/services/web/ui/src/node_info/SupervisorDetailPage.js, mars/services/web/ui/src/node_info/TabPanel.js, mars/services/web/ui/src/node_info/WorkerDetailPage.js, mars/services/web/ui/src/task_info/TaskDetail.js, mars/services/web/ui/src/task_info/TaskListPage.js, mars/services/web/ui/src/task_info/TaskTileableGraph.js, mars/services/web/ui/src/task_info/TileableDetail.js
This PR makes changes below:
1. Remove `OptionalElement`;
2. Extract `TaskTileableGraph` and `TileableDetail` to separate pane layout from component rendering;
3. Minor style fixes.
=> Refactor tileable visualization classes

mars/oscar/backends/communication/socket.py, mars/oscar/backends/message.py, mars/services/meta/api/oscar.py, mars/services/meta/store/dictionary.py, mars/services/storage/core.py, mars/services/storage/spill.py, mars/services/storage/tests/test_transfer.py, mars/services/storage/transfer.py
When multiple subtasks fetch the same key at the same time, the transfer task may fails. In this PR, `ReceiverManagerActor` holds a dict to record the data keys being fetched and create events to mark if transfer tasks are finished, `SenderManagerActor` will wait those events to make sure all data keys are sent.
Fixes #2321
=> Fix the error when multiple subtasks fetch the same data

mars/deploy/oscar/tests/test_cmdline.py, mars/deploy/oscar/worker.py, mars/services/cluster/api/oscar.py, mars/services/storage/core.py, mars/services/storage/tests/test_api.py, mars/services/storage/transfer.py, mars/services/web/ui/src/Utils.js, mars/services/web/ui/src/node_info/NodeListPage.js, mars/services/web/ui/src/node_info/NodeResourceTab.js, mars/storage/filesystem.py, mars/storage/tests/test_libs.py
=> [BACKPORT] Add storage infos in web (#2317)

mars/dataframe/__init__.py, mars/dataframe/base/tests/test_base.py, mars/dataframe/base/tests/test_base_execution.py, mars/dataframe/base/to_numeric.py
=> [BACKPORT] Support `md.to_numeric` (#2290)

mars/oscar/backends/pool.py, mars/oscar/backends/ray/pool.py, mars/oscar/backends/ray/tests/test_ray_pool.py
This PR enhances reliability of wait_actor_pool_recovered and avoid waiting forever. The changes are small and the ideas are below:
1. The message handler creates the event and waits for it, so it can always retrieve the event (will not get None).
2. The monitor pops and sets the recover event at every end of iterations, so the message handler will not wait forever.
3. The monitor checks the existence at the start of iteration, to ensure the event will not be set too early.
This PR also adds tests for auto-recover and server-closed for ray as mars pool does.
Resolve #2320
=> Improve wait_actor_pool_recovered

mars/oscar/backends/communication/socket.py, mars/services/meta/api/oscar.py, mars/services/meta/store/dictionary.py, mars/services/storage/core.py, mars/services/storage/spill.py, mars/services/storage/tests/test_transfer.py, mars/services/storage/transfer.py
=> [BACKPORT] Fix the error when multiple subtasks fetch the same data (#2322)

mars/services/lifecycle/supervisor/tracker.py, mars/services/task/analyzer/analyzer.py, mars/services/task/analyzer/assigner.py, mars/services/task/supervisor/preprocessor.py, mars/services/task/supervisor/processor.py
Fix supervisor hang:
* Before this pr, if we have 1000 chunks need to `set_subtask_result` and each take 1 second, we'll need to wait 1000 seconds before we can schedule next subtask graph.
* Big sutask graph generation may take more than 3 minutes, this will block event loop 3 minutes. This PR moved the graph preparation into another thread to avoid event loop hang.
=> Optimize mars supervisor scheduling

mars/deploy/oscar/ray.py, mars/deploy/oscar/tests/test_ray.py, mars/services/core.py
1. Clear the instances when stopping services. It guarantees to create new instances in the subsequent test case.
2. Eliminate the different behavior of ray backend.
3. Parametrize test_load_third_party_modules for better setup and teardown.
=> [Ray] Fix ray ci

mars/contrib/dask/converter.py, mars/contrib/dask/scheduler.py, mars/contrib/dask/tests/test_dask.py, mars/contrib/dask/utils.py
Fix error in Dask-on-Mars when compute multiple objects
Fixes #2345
=> Fix error in Dask-on-Mars when compute multiple objects

mars/oscar/backends/context.py, mars/oscar/backends/mars/pool.py, mars/oscar/backends/pool.py, mars/oscar/backends/ray/communication.py, mars/oscar/backends/ray/driver.py, mars/oscar/backends/ray/pool.py, mars/oscar/backends/ray/tests/test_ray_pool.py, mars/oscar/context.pyx
Backport of #2328  and part from #2288 .
=> [BACKPORT] Improve wait_actor_pool_recovered (#2328)

README.rst, docs/requirements-doc.txt, docs/source/getting_started/learn.rst, docs/source/reference/contrib/reference.rst, docs/source/user_guide/contrib/dask.rst, docs/source/user_guide/contrib/index.rst, docs/source/user_guide/learn/joblib.rst, docs/source/user_guide/learn/lightgbm.rst, docs/source/user_guide/learn/statsmodels.rst, docs/source/user_guide/learn/tensorflow.rst, docs/source/user_guide/learn/xgboost.rst, mars/core/operand/core.py, mars/core/operand/tests/test_core.py, mars/tensor/stats/tests/test_stats_execute.py
This PR enables ability that gives an error when input DataFrame has unknown dtypes.
Fixes #2354 .
=> Gives an error when input DataFrame has unknown dtypes

.github/workflows/core-ci.yml, mars/services/subtask/worker/processor.py, mars/services/task/api/oscar.py, mars/services/task/api/web.py, mars/services/task/supervisor/manager.py, mars/services/task/supervisor/processor.py, mars/services/task/supervisor/stage.py, mars/services/task/tests/test_service.py, mars/services/web/ui/src/task_info/TaskTileableGraph.js, mars/services/web/ui/src/task_info/TileableDetail.js, mars/tensor/stats/tests/test_stats_execute.py
Add API support for #2342. Subtasks are binded to tileables to get progresses. If chunks of a tileable is fused with chunks of another tileable, progresses are shared between different tileables.
Deal with API part of #2342.
=> Add API to retrieve progress and status of tileables

mars/dataframe/core.py, mars/dataframe/tests/test_core.py
Added assign to DataFrame Class (Corrected the issues in the previous PR)
This will enable the **assign** function to the DataFrame Class. This fix has been referenced the Pandas DataFrame.assign() function found here https://github.com/pandas-dev/pandas/blob/v1.3.2/pandas/core/frame.py#L4416-L4482
Fixes #1336 .
=> Added assign to DataFrame

mars/services/task/supervisor/processor.py, mars/services/web/ui/src/task_info/TaskTileableGraph.js
Now the tileables will be colored based on their status:
- white = pending
- yellow = running
- green = finished
- gray = cancelled
- red = failed
and the tileables will be colored based on the percentage of subtasks they have finished. A sample graph may look like this:
Lastly, the dependency between two tileables will be dashed if the dependency has a linkType of 1.
Resolves #2342
=> Display tileable progress, status and dependency link type on task detail page

.gitattributes, .github/workflows/checks.yml, ci/importcheck.py, ci/modecheck.sh, mars/deploy/oscar/session.py, mars/deploy/utils.py, mars/learn/proxima/simple_index/recall.py, mars/oscar/backends/ray/communication.py, mars/oscar/errors.py, mars/services/lifecycle/api/oscar.py, mars/services/scheduling/supervisor/autoscale.py
Add checks below:
1. File mode changes. This forces commiters to ignore fileMode in Windows.
2. Absolute imports in non-test source code.
Also add a `.gitattributes` to avoid CRLF line endings in Windows.
=> Add checks for file mode changes and absolute imports

.github/workflows/platform-ci.yml
Ray master version is not stable, which makes mars on ray test unstable too. The PR fix the version to a specified commit and will change it to ray>=1.7.0 when it got released.
=> [Ray] Fix ray version

ci/importcheck.py, mars/oscar/backends/core.py, mars/oscar/tests/test_actorcaller.py
ActorCaller._listen is at risk and will not remake related futures after the client closed. It will happen when the `client.recv` got successfully returned with the client closed.   
Fixes #2405
=> [Oscar] Fix possible `ActorCaller.call` hang

docs/source/locale/zh_CN/LC_MESSAGES/reference/learn/reference.po, docs/source/reference/learn/reference.rst, mars/learn/contrib/tensorflow/dataset.py, mars/learn/preprocessing/__init__.py, mars/learn/preprocessing/_label.py, mars/learn/preprocessing/tests/test_label.py, mars/tensor/base/map_chunk.py, mars/tensor/datasource/array.py
=> [BACKPORT] Implements `mars.learn.preprocessing.{LabelBinarizer, label_binarize}` (#2415)

docs/source/reference/learn/reference.rst, mars/learn/metrics/__init__.py, mars/learn/metrics/_classification.py, mars/learn/metrics/tests/test_classification.py
This PR implements `mars.learn.metrics.log_loss`.
This can be merged after #2415 and #2417 got merged.
Resolves #2266 .
=> Implements `mars.learn.metrics.log_loss`

mars/dataframe/base/apply.py, mars/dataframe/base/map_chunk.py, mars/dataframe/tests/test_core.py
=> [BACKPORT] Fix df/series.{apply, map_chunk} when some chunk output empty data (#2434)

mars/services/web/ui/src/task_info/TaskTileableGraph.js, mars/services/web/ui/src/task_info/TileableDetail.js, mars/services/web/ui/src/task_info/charts/DAGChart.js, mars/services/web/ui/src/task_info/charts/DAGPropTypes.js
The current tileable graph compares prevProp's tileables and dependencies with the current tileables and dependencies, and only if they are different, the dag will be rendered. However, there is also a check that states that the length of tileable details must match the length of tileables, and if the React setState for tileable detail takes some time and finishes setting the state after the tileables and dependencies have been passed to the graph component, the prevProp's tileables and dependencies have already become the new tileables and dependencies. As such, the dag will never be rendered. 
This PR removed the length check for tileable details. Instead, if the rendered tileable's detail is not in the passed nodesStatus prop, the tileable will just be rendered as a pending tileable. …
=> Fix missing DAGs when initializing with empty API results

.github/workflows/docker-cd.yml, mars/_version.py, mars/dataframe/reduction/aggregation.py, mars/dataframe/reduction/kurtosis.py, mars/dataframe/reduction/skew.py, mars/services/subtask/core.py, mars/services/subtask/worker/processor.py, mars/services/task/supervisor/processor.py, mars/services/task/supervisor/stage.py, mars/services/web/ui/src/Utils.js, mars/tests/test_session.py
Fix AttributeError in MacOS under latest pandas versions when executing `skew` and `kurt`.
=> Fix skew and kurt errors under MacOS

mars/services/task/supervisor/processor.py
Log the error message raised in `TaskProcessor`.
Fixes #2455.
=> Print the error message when error happens in `TaskProcessor`

.github/workflows/docker-cd.yml, ci/reload-env.sh, docs/source/installation/kubernetes.rst, docs/source/installation/yarn.rst, docs/source/locale/zh_CN/LC_MESSAGES/installation/kubernetes.po, docs/source/locale/zh_CN/LC_MESSAGES/installation/yarn.po, mars/deploy/kubernetes/client.py, mars/deploy/kubernetes/config.py, mars/deploy/kubernetes/core.py, mars/deploy/kubernetes/tests/test_kubernetes.py, mars/deploy/yarn/client.py, mars/deploy/yarn/tests/test_yarn.py, mars/resource.py, mars/utils.py
Add nightly builds for docker images. This applies on `master` branch as well as `vx.y` branches.
=> Add nightly builds for docker images

mars/dataframe/align.py, mars/tests/test_session.py
Before fixed, if we run this test case, the error will occur.
```
def test_dataframe(setup):
t = np.random.rand(10, 3)
pdf = pd.DataFrame(t)
df = md.DataFrame(pdf, chunk_size=(5, 3))
r = df[0] != df.sort_index()[0].shift(-1)
expected = pdf[0] != pdf.sort_index()[0].shift(-1)
pd.testing.assert_series_equal(r.execute().fetch(), expected)
```
Run this test case, an error will occur.
`TypeError: Cannot interpret '0' as a data type`
Only need to change this code:
` if kw.get('name', None) is None and getattr(inputs[0], 'name', None) is not None:
kw['name'] = inputs[0].name`
in align.py,we can fix this bug
Fixes #2459 .
=> Fix misuse of `name` parameter in DataFrame align

mars/oscar/backends/mars/pool.py, mars/oscar/backends/mars/tests/test_pool.py, mars/oscar/backends/pool.py, mars/oscar/backends/ray/pool.py, mars/oscar/backends/test/pool.py
Check the status of subprocess to avoid hang during the create pools.
Resolves #2464
=> Fix hang when start sub pool fails

mars/dataframe/align.py, mars/tests/test_session.py
=> [BACKPORT] Fix misuse of `name` parameter in DataFrame align (#2469)

mars/services/web/ui/src/task_info/TileableDetail.js
=> [BACKPORT] Split tileable information and subtask graph into two tabs (#2480)

mars/services/storage/tests/test_api.py, mars/storage/tests/test_libs.py, mars/storage/vineyard.py
The vineyardd might be prelaunched in a `DaemonSet` and shared with other compute engines.
N/A
=> Support specified vineyard socket and skip the launching vineyardd process

mars/deploy/oscar/tests/fault_injection_config_with_rerun.yml, mars/deploy/oscar/tests/test_fault_injection.py, mars/deploy/oscar/tests/test_local.py, mars/deploy/oscar/tests/test_ray_fault_injection.py, mars/services/scheduling/supervisor/manager.py, mars/services/scheduling/supervisor/service.py, mars/services/scheduling/supervisor/tests/test_manager.py, mars/services/scheduling/utils.py, mars/services/scheduling/worker/execution.py, mars/services/scheduling/worker/tests/test_execution.py, mars/services/subtask/core.py, mars/services/task/analyzer/analyzer.py
- Handle subtask result in one place, the `SubtaskManagerActor`.
- before
- The `SubtaskExecutionActor` calls `TaskAPI.set_subtask_result` to set the subtask result.
- The `SubtaskManagerActor` handles `run_subtask` exceptions.
- after
- The `SubtaskManagerActor` gets and sets the subtask result, also handles the `run_subtask` exceptions.
- Acquire and release global slots in supervisor.
- before
- The `SubtaskExecutionActor` releases global slots.
- after
- The `SubtaskManagerActor` releases global slots.
- Add an option `subtask_max_reschedules` to reschedule failed subtask. _(This PR can't handle worker main pool crash)_
N/A
=> Basic reschedule subtask

mars/learn/metrics/pairwise/tests/test_manhattan_distances.py, mars/lib/sparse/array.py, mars/lib/sparse/tests/test_sparse.py
Fix compatibility issues for scikit-learn 1.0. 
Including two cases, `test_elkan_results_sparse` and `test_manhattan_distances_execution`.
Resolves #2485.
=> Compatible with scikit-learn 1.0

mars/learn/metrics/pairwise/tests/test_manhattan_distances.py, mars/lib/sparse/array.py, mars/lib/sparse/tests/test_sparse.py
=> [BACKPORT] Compatible with scikit-learn 1.0 (#2486)

docs/source/reference/dataframe/series.rst, mars/dataframe/core.py, mars/dataframe/tests/test_core.py
Support Series.median() plus testings
Resolves #1345
---
Series.median() is mainly supported by ```tensor.statistics.median``` based on ```tensor.statistics.quantile```
In addition to the parameters  from ```tensor.statistics.median```, I also added ```skipna``` for handling nan values just like [pandas series()](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.Series.median.html?highlight=median#pandas.Series.median)
4 test cases work fine.
However, I had trouble when Building Documentations. 
I ran
```make html```
then 
It seems my VM ubuntu suffers from its 8 GB memory. Is there a good way to solve this?
=> Support Series.median()

.github/PULL_REQUEST_TEMPLATE.md, docs/source/reference/learn/reference.rst, mars/learn/metrics/__init__.py, mars/learn/metrics/_classification.py, mars/learn/metrics/tests/test_classification.py, mars/learn/preprocessing/_label.py, mars/learn/utils/sparsefuncs.py, mars/learn/utils/tests/test_sparsefuncs.py
Add `mars.learn.metrics.multilabel_confusion_matrix` and derivative metrics, including `precision_score`, `recall_score`, `f1_score` and `fbeta_score`.
Fixes #2553
=> Add `mars.learn.metrics.multilabel_confusion_matrix` and derivative metrics

.github/PULL_REQUEST_TEMPLATE.md, docs/source/development/contributing.rst, docs/source/development/index.rst, docs/source/development/operand.rst, docs/source/locale/zh_CN/LC_MESSAGES/development/operand.po, docs/source/reference/learn/reference.rst, mars/learn/metrics/__init__.py, mars/learn/metrics/_classification.py, mars/learn/metrics/tests/test_classification.py, mars/learn/preprocessing/_label.py, mars/learn/utils/sparsefuncs.py, mars/learn/utils/tests/test_sparsefuncs.py
=> [BACKPORT] Add `mars.learn.metrics.multilabel_confusion_matrix` and derivative metrics (#2554)

mars/dataframe/reduction/aggregation.py, mars/serialization/cuda.py, mars/serialization/tests/test_serial.py
Fix tests under cudf 21.10.
Fixes #2573
=> Fix tests under cudf 21.10

mars/core/operand/core.py, mars/lib/groupby_wrapper.py, mars/lib/tests/test_lib.py, mars/services/scheduling/worker/execution.py, mars/services/scheduling/worker/tests/test_execution.py, mars/tests/test_utils.py, mars/utils.py
Reduce time cost of size estimation when running `sys.getsizeof` of a DataFrame object by sampling.
Fixes #2565
=> Reduce estimation time cost

mars/dataframe/indexing/getitem.py, mars/dataframe/indexing/tests/test_indexing_execution.py, mars/dataframe/indexing/utils.py
This PR fixes the `TypeError` when select data from a DataFrame that has duplicate columns/
Fixes #2578
=> Fix DataFrame getitem when exists duplicate columns

README.rst, docs/source/index.rst, docs/source/installation/index.rst, docs/source/installation/ray.rst, docs/source/locale/zh_CN/LC_MESSAGES/index.po, docs/source/locale/zh_CN/LC_MESSAGES/installation/ray.po, mars/__init__.py, mars/conftest.py, mars/deploy/oscar/__init__.py, mars/deploy/oscar/ray.py, mars/deploy/oscar/tests/test_ray.py, mars/oscar/backends/ray/driver.py
Refine mars on ray usability and documents.
```python
import mars
import mars.tensor as mt
session = mars.new_ray_session(cluster_name='abc', worker_num=2)
mt.random.RandomState(0).rand(1000_0000, 5, chunk_size=100_0000).sum().execute()
df = md.DataFrame(
mt.random.rand(1000_0000, 4, chunk_size=500_0000),
columns=list('abcd'))
print(df.sum().execute())
```
Create a mars cluster:
```python
import mars.tensor as mt
from mars.deploy.oscar import new_cluster_in_ray, new_ray_session
cluster = new_cluster_in_ray(cluster_name='test', worker_num=2)
```
then connect it in the client:
```python
session = new_ray_session(address = cluster.address)
```
#2112
=> [ray] refine mars on ray usability

mars/_utils.pyx, mars/core/base.py, mars/core/entity/tileables.py, mars/core/mode.py, mars/core/operand/base.py, mars/core/operand/core.py, mars/dataframe/__init__.py, mars/dataframe/arithmetic/core.py, mars/dataframe/arithmetic/equal.py, mars/dataframe/arithmetic/greater.py, mars/dataframe/arithmetic/greater_equal.py, mars/dataframe/arithmetic/less.py, mars/dataframe/arithmetic/less_equal.py, mars/dataframe/arithmetic/not_equal.py, mars/dataframe/arrays.py, mars/dataframe/base/map_chunk.py, mars/dataframe/core.py, mars/dataframe/datasource/dataframe.py, mars/dataframe/datasource/from_tensor.py, mars/dataframe/indexing/getitem.py, mars/dataframe/reduction/core.py, mars/dataframe/utils.py, mars/serialization/serializables/core.py, mars/serialization/serializables/field.py, mars/serialization/serializables/tests/test_serializable.py, mars/services/task/analyzer/fusion.py, mars/services/task/supervisor/processor.py, mars/services/task/tests/test_service.py, mars/tensor/datasource/core.py, mars/tests/test_utils.py
This PR did things below:
1. Put dicts of attribute names directly instead of tags
2. Use dtype of arithmetic operands if specified
3. Optimize obtaining dtypes of aggregation
4. Reduce costs of tokenize by using output indices for tileable objects
=> Optimize tileable graph construction

mars/deploy/oscar/session.py, mars/deploy/oscar/tests/test_local.py, mars/services/task/api/web.py
The web session use same timeout for client and server. Server timeout + RPC cost > client timeout, so the client call will always timeout, then the progress will not be updated.
- Always get progress even the previous call timeout.
- Set max(timeout / 2.0, timeout -1) for server.
Fixes https://github.com/mars-project/mars/issues/2590
=> Fix progress always is 0 or 100%

mars/dataframe/base/map_chunk.py, mars/dataframe/base/tests/test_base_execution.py
Stop calling user funcs when dtypes is specified to avoid unnecessary delay.
Fixes #xxxx
=> Stop calling user funcs when dtypes is specified

mars/_utils.pyx, mars/deploy/oscar/session.py, mars/deploy/oscar/tests/test_local.py, mars/deploy/oscar/tests/test_ray.py, mars/oscar/backends/communication/socket.py, mars/oscar/backends/context.py, mars/oscar/backends/message.py, mars/oscar/backends/pool.py, mars/oscar/backends/ray/communication.py, mars/oscar/context.pyx, mars/oscar/core.pxd, mars/oscar/core.pyx, mars/oscar/profiling.py, mars/oscar/tests/test_profiling_data.py, mars/services/scheduling/supervisor/manager.py, mars/services/subtask/api.py, mars/services/task/api/web.py, mars/services/task/core.py, mars/services/task/supervisor/processor.py, mars/tests/core.py, mars/tests/test_utils.py, mars/utils.py
- Add a `enable_profiling` extra config, default is False. e.g. `a.execute(show_progress=False, extra_config={"enable_profiling": True})`
- Fix `extra_config` for web session.
- Sample profile result for supervisor.
``` python
WARNING  mars.deploy.oscar.session:session.py:861 Profile task PO1e7wSe4DFpxzoFk5IKYiey execution result:
{
"supervisor": {
"general": {
"optimize": 0.002045869827270508,
"incref_fetch_tileables": 0.003548145294189453,
"stage_g9ovAV2iVQQS20b2ym8lbrMt": {
"tile": 0.02925896644592285,
"gen_subtask_graph": 0.05370688438415527,
"run": 0.19794082641601562,
"total": 0.29035496711730957
},
"total": 0.299562931060791
},
"serialization": {
"serialize": 0.014928340911865234,
"deserialize": 0.0011813640594482422,
"total": 0.016109704971313477
}
}
}
```
N/A
=> Add basic profiling support for supervisor

mars/core/entrypoints.py, mars/core/tests/test_entrypoints.py, mars/deploy/oscar/local.py, mars/deploy/oscar/ray.py, mars/deploy/oscar/session.py, mars/oscar/backends/pool.py
This PR defines an entrypoint for mars extensions. So, some packages can implement the entrypoint to make mars auto load the package as extension. Just the same as SDC is an extension of numba. Please refer to SDC for more details: https://github.com/IntelPython/sdc/blob/master/setup.py#L440
There are 4 load points:
- LocalCluster
- RayCluster
- AbstractActorPool
- new_session
The entrypoints will be loaded only once in a process.
- Entrypoints may import mars for extension, this will cause recursive import error.
N/A
=> Supports adding Mars extensions via setup entrypoints

mars/learn/proxima/core.py, mars/services/task/analyzer/analyzer.py
* The first arg of `TensorSlice` should be a set instead of a list;
* Most chunks in `ProximaBuilder` are bundled to specified workers, but only start-OPs are assigned during analyzing. I assign other chunks;
=> Make Proxima work with latest Mars

mars/services/meta/api/oscar.py, mars/services/subtask/worker/processor.py
Skip details of shuffled chunks in meta to jmprove performance.
Fixes #xxxx
=> Skip details of shuffled chunks in meta

mars/core/operand/core.py, mars/lib/groupby_wrapper.py, mars/lib/tests/test_lib.py, mars/services/scheduling/worker/execution.py, mars/services/scheduling/worker/tests/test_execution.py, mars/tests/test_utils.py, mars/utils.py
=> [BACKPORT] Reduce estimation time cost (#2577)

mars/services/task/supervisor/processor.py, mars/services/task/supervisor/stage.py
* fix decrease subtask input chunk
This is a race condition.
Let us suppose stage A have two Subtask S1 and S2, and they have the same input chunk C
1. S1 got an error, and stage_processor.done has been set.
2. S2 call set_subtask_result, it already reduces reference count of C  but not set `stage_processor.results[C.key]`
3. `TaskProcessorActor` find `stage_processor` got an error and call `self._cur_processor.incref_stage(stage_processor)` in function `TaskProcessorActor.start`, it will also reduce the reference count of C which is input of S2.
Fixes #2610
=> Fix duplicate decref of subtask input chunk

mars/dataframe/contrib/raydataset/dataset.py, mars/dataframe/contrib/raydataset/mldataset.py, mars/services/scheduling/supervisor/globalslot.py, mars/services/scheduling/supervisor/queueing.py, mars/services/scheduling/supervisor/tests/test_queue_balance.py, mars/services/scheduling/supervisor/tests/test_queueing.py, mars/storage/shared_memory.py
Request global slots in batches. This reduces potential time cost when a number of slots are to be allocated.
Fixes #xxxx
=> Use batched request to apply for slots

mars/deploy/oscar/session.py, mars/deploy/oscar/tests/test_local.py, mars/oscar/backends/context.py, mars/oscar/backends/mars/pool.py, mars/oscar/backends/pool.py, mars/oscar/backends/ray/communication.py, mars/oscar/batch.py, mars/oscar/core.pyx, mars/services/scheduling/supervisor/assigner.py, mars/services/task/supervisor/processor.py
Reduce RPC cost of oscar by removing unnecessary tasks. Now Oscar can handle 4500 calls pser sec instead of 2500 before optimization.
Fixes #xxxx
=> Reduce RPC cost of oscar by removing unnecessary tasks

.github/workflows/core-ci.yml, .github/workflows/platform-ci.yml, .github/workflows/pypi-cd.yml, ci/install-conda.sh, ci/requirements-wheel.txt
Add wheel support for Python 3.10 and drop Python 3.6. Build results see https://github.com/wjsi/mars/runs/4548270645?check_suite_focus=true.
Fixes #xxxx
=> Add wheel support for Python 3.10 and drop Python 3.6

.github/workflows/install-hadoop.sh, mars/deploy/oscar/local.py, mars/deploy/oscar/ray.py, mars/deploy/oscar/session.py, mars/deploy/oscar/supervisor.py, mars/deploy/oscar/tests/test_cmdline.py, mars/oscar/backends/core.py, mars/oscar/backends/mars/tests/test_pool.py, mars/oscar/backends/message.py, mars/oscar/backends/pool.py, mars/oscar/core.pyx, mars/services/cluster/api/oscar.py, mars/services/lifecycle/api/web.py, mars/services/meta/api/web.py, mars/services/session/api/web.py, mars/services/session/supervisor/core.py, mars/services/storage/api/web.py, mars/services/subtask/worker/runner.py, mars/services/task/api/web.py, mars/services/web/core.py, mars/services/web/ui/package-lock.json
As loops of supervisors may be blocked by GIL, it is possible to use another process to handle sessions in separate processes. As it may bring serialization overhead, we offer it as an option.
Fixes #2451
(though as a partial solution)
=> Allow specifying multiple supervisor processes

azure-pipelines.yml, mars/conftest.py, mars/core/graph/builder/chunk.py, mars/core/graph/core.pyx, mars/core/mode.py, mars/dataframe/arrays.py, mars/dataframe/base/astype.py, mars/dataframe/base/duplicated.py, mars/dataframe/base/tests/test_base_execution.py, mars/dataframe/base/transform.py, mars/dataframe/base/value_counts.py, mars/dataframe/groupby/aggregation.py, mars/dataframe/groupby/tests/test_groupby_execution.py, mars/dataframe/indexing/getitem.py, mars/dataframe/indexing/reindex.py, mars/dataframe/indexing/setitem.py, mars/dataframe/indexing/tests/test_indexing_execution.py, mars/dataframe/reduction/aggregation.py, mars/dataframe/reduction/core.py, mars/dataframe/reduction/tests/test_reduction.py, mars/dataframe/reduction/tests/test_reduction_execution.py, mars/dataframe/tests/test_core.py, mars/dataframe/utils.py, mars/dataframe/window/ewm/core.py, mars/dataframe/window/expanding/core.py, mars/dataframe/window/rolling/aggregation.py, mars/dataframe/window/rolling/core.py, mars/lib/groupby_wrapper.py, mars/utils.py, setup.cfg
Fix backward compatibility for pandas 1.0 and add tests for backward compatibility.
Fixes #2623
=> Fix backward compatibility for pandas 1.0

azure-pipelines.yml, mars/conftest.py, mars/core/graph/builder/chunk.py, mars/core/graph/core.pyx, mars/core/mode.py, mars/dataframe/arrays.py, mars/dataframe/base/astype.py, mars/dataframe/base/duplicated.py, mars/dataframe/base/tests/test_base_execution.py, mars/dataframe/base/transform.py, mars/dataframe/base/value_counts.py, mars/dataframe/groupby/aggregation.py, mars/dataframe/groupby/tests/test_groupby_execution.py, mars/dataframe/indexing/getitem.py, mars/dataframe/indexing/reindex.py, mars/dataframe/indexing/setitem.py, mars/dataframe/indexing/tests/test_indexing_execution.py, mars/dataframe/reduction/aggregation.py, mars/dataframe/reduction/tests/test_reduction.py, mars/dataframe/reduction/tests/test_reduction_execution.py, mars/dataframe/tests/test_core.py, mars/dataframe/utils.py, mars/dataframe/window/ewm/core.py, mars/dataframe/window/expanding/core.py, mars/dataframe/window/rolling/aggregation.py, mars/dataframe/window/rolling/core.py, mars/lib/groupby_wrapper.py, mars/utils.py, setup.cfg
=> [BACKPORT] Fix backward compatibility for pandas 1.0 (#2628)

.github/workflows/core-ci.yml, .github/workflows/os-compat-ci.yml, .github/workflows/platform-ci.yml, mars/oscar/batch.py, mars/oscar/tests/test_batch.py
Fix error for `mo.batch` when single call not implemented. Also remove forked `pytest-asyncio` as bug already been fixed.
Fixes #2634
=> Fix `NotImplementedError` for `mo.batch` when single call not implemented

mars/dataframe/groupby/aggregation.py, mars/dataframe/groupby/tests/test_groupby_execution.py
As pandas DataFrame will raise `IndexError` for code like `df.groupby(['A'])[['B','C']]['B']`, remove the repeated getitem to solve it.
Fixes #2640
=> Fix `IndexError` raise by aggregation of DataFrameGroupBy

mars/dataframe/base/rechunk.py, mars/dataframe/indexing/loc.py, mars/dataframe/indexing/tests/test_indexing.py, mars/dataframe/utils.py, mars/utils.py
This PR fixes df.loc[:] to make sure same index_value key generated
Fixes #2642
=> Fix df.loc[:] to make sure same index_value key generated

mars/dataframe/groupby/aggregation.py, mars/dataframe/groupby/tests/test_groupby_execution.py, mars/dataframe/indexing/reset_index.py, mars/dataframe/reduction/aggregation.py, mars/dataframe/reduction/core.py, mars/dataframe/reduction/tests/test_reduction.py
Fix aggregation with comparison, for inst., 
```python
df.groupby('b', as_index=False)['a'].agg(lambda x: (x == "1").sum())
```
Fix aggregation over multi-level group-bys.
Fixes #2646
Fixes #2648
=> Fix aggregation with comparison

mars/dataframe/indexing/index_lib.py, mars/dataframe/indexing/tests/test_indexing.py
This PR fixes the wrong index_value generated by df.loc[:].
Fixes #2656
=> Fix the wrong index_value generated by df.loc[:]

mars/deploy/oscar/session.py, mars/deploy/oscar/tests/test_local.py, mars/services/cluster/api/web.py, mars/services/lifecycle/api/web.py, mars/services/meta/api/web.py, mars/services/mutable/api/web.py, mars/services/scheduling/api/web.py, mars/services/session/api/web.py, mars/services/storage/api/web.py, mars/services/task/api/web.py, mars/services/web/core.py, mars/services/web/tests/test_core.py
Add an argument for HTTP request rewriter which accepts an argument representing the request object.
Fixes #2663
=> Add support for HTTP request rewriter

mars/optimization/logical/tileable/arithmetic_query.py, mars/optimization/logical/tileable/tests/test_arithmetic_query.py
Fix query optimization bug when applying conditions with `pd.Timestamp`.
Fixes #2670
=> Fix optimizing DataFrame query with timestamp in conditions

MANIFEST.in, docs/source/development/contributing.rst, pyproject.toml
Add pyproject.toml to config build packages. Now these packages are not need when calling `pip install` from a new pyenv.
Fixes #2673
=> Add pyproject.toml to config build packages

mars/dataframe/groupby/aggregation.py, mars/dataframe/groupby/tests/test_groupby_execution.py, mars/dataframe/reduction/core.py
Fix as_index settings when calling agg on SeriesGroupBy object. This fixes missing indexes for aggregation results.
Fixes #2675
=> Fix `as_index` when calling agg on SeriesGroupBy

mars/dataframe/datasource/core.py, mars/dataframe/sort/sort_values.py, mars/dataframe/sort/tests/test_sort_execution.py, mars/learn/metrics/pairwise/tests/test_pariwise_distances.py, mars/tensor/datasource/from_zarr.py, mars/tensor/random/tests/test_random_execution.py, mars/tensor/spatial/distance/cdist.py, mars/tensor/spatial/distance/pdist.py, mars/tensor/spatial/distance/tests/test_distance_execution.py
This PR fixes the failure for `sort_values` when input DataFrame/Series is empty.
Fixes #2649
=> Fix `sort_values` for empty DataFrame or Series

mars/dataframe/datasource/core.py, mars/dataframe/sort/sort_values.py, mars/dataframe/sort/tests/test_sort_execution.py, mars/learn/metrics/pairwise/tests/test_pariwise_distances.py, mars/tensor/datasource/from_zarr.py, mars/tensor/random/tests/test_random_execution.py, mars/tensor/spatial/distance/cdist.py, mars/tensor/spatial/distance/pdist.py, mars/tensor/spatial/distance/tests/test_distance_execution.py
=> [BACKPORT] Fix `sort_values` for empty DataFrame or Series (#2681)

mars/optimization/logical/core.py, mars/optimization/logical/tileable/tests/test_arithmetic_query.py
Fix redundant evaluation node when result of `__bool__` of predecessor node is False.
Fixes #2682
=> Eliminate redundant eval node in optimization

mars/dataframe/indexing/index_lib.py, mars/dataframe/indexing/tests/test_indexing.py, mars/dataframe/indexing/tests/test_indexing_execution.py
After this PR, iterative tiling is avoided for df.loc[:, fields].
Fixes #2684 .
=> Avoid iterative tiling for `df.loc[:, fields]`

mars/optimization/logical/core.py, mars/optimization/logical/tileable/tests/test_arithmetic_query.py
=> [BACKPORT] Eliminate redundant eval node in optimization (#2683)

.github/workflows/platform-ci.yml, mars/deploy/oscar/tests/test_fault_injection.py, mars/deploy/oscar/tests/test_ray_fault_injection.py, mars/services/scheduling/worker/execution.py, mars/services/task/tests/test_service.py
The  logs and exceptions of failure recovery are not clear enough, this PR is to refine them.
Fixes #xxxx
=> Refine failure recovery log and exception

mars/dataframe/indexing/index_lib.py, mars/dataframe/indexing/tests/test_indexing.py, mars/dataframe/indexing/tests/test_indexing_execution.py
=> [BACKPORT] Avoid iterative tiling for df.loc[:, fields] (#2685)

mars/dataframe/indexing/setitem.py, mars/optimization/logical/tileable/arithmetic_query.py, mars/optimization/logical/tileable/tests/test_arithmetic_query.py
Optimize eval-setitem expressions as single eval expressions to reduce tileables.
Fixes #2694
=> Optimize eval-setitem expressions as single eval expressions

.github/workflows/platform-ci.yml
Ray dataset in ray 1.10.0 has an incompatible change and it's not easy to fix unless we rewrite the dataset integration using datasource api of ray dataset. So we downgrade ray version to 1.9 and will relax version when we finished the rewrite.
=> [hotfix][ray] fix ray dataset compatibility

mars/dataframe/datasource/read_parquet.py, mars/dataframe/datasource/tests/test_datasource_execution.py
=> [BACKPORT] Fix `use_arrow_dtype` parameter for `read_parquet` (#2698)

mars/_version.py, mars/tests/test_utils.py, mars/utils.py
This PR solves the error when estimating the size of `pd.MultiIndex`.
Fixes #2706
=> Fix `estimate_pandas_size` for `pd.MultiIndex`

mars/dataframe/arithmetic/tests/test_arithmetic.py, mars/dataframe/core.py, mars/dataframe/datasource/date_range.py, mars/dataframe/datasource/tests/test_datasource_execution.py, mars/dataframe/indexing/set_index.py, mars/dataframe/sort/psrs.py, mars/dataframe/sort/sort_values.py, mars/dataframe/tests/test_utils.py, mars/dataframe/utils.py, mars/learn/ensemble/_bagging.py, mars/services/scheduling/worker/tests/test_execution.py, mars/tensor/statistics/bincount.py
Support `inclusive` argument for `pd.date_range`. Also replace all `pd.Int64Index` calls with `pd.Index`.
Fixes #2717
Fixes #2651
=> Support `inclusive` argument for `pd.date_range`

mars/deploy/oscar/tests/test_local.py, mars/deploy/oscar/tests/test_ray.py, mars/oscar/backends/core.py, mars/oscar/profiling.py, mars/oscar/tests/test_profiling.py, mars/oscar/tests/test_profiling_data.py, mars/services/scheduling/supervisor/manager.py, mars/services/subtask/api.py, mars/services/task/supervisor/processor.py, mars/tests/core.py
- New most_calls _(top 10)_ / slow_calls _(top 10, default >= 1s)_ / band_subtasks _(most 5 + least 5)_ / slow_subtasks _(top 10, default >= 10s)_ in profile result.
- Read environment var `MARS_ENABLE_PROFILING` to enable / disable profiling.
- Read environment var `MARS_PROFILING_DEBUG_INTERVAL_SECONDS` to log profiling when executing task.
- Read environment var `MARS_PROFILING_SLOW_CALLS_DURATION_THRESHOLD` to change the default threshold of slow calls in seconds.
- Read environment var `MARS_PROFILING_SLOW_SUBTASKS_DURATION_THRESHOLD` to change the default threshold of slow subtasks in seconds.
- The value of `enable_profiling` extra config can be `True`, `False` and a dict of profiling options, e.g.
```python
df.execute(extra_config={"enable_profiling": True})  # It's OK, enable …
```
=> Improve profiling

mars/learn/utils/shuffle.py, mars/learn/utils/tests/test_shuffle.py
This PR fixed shuffle when ndim of input tensors are different.
Fixes #2720 .
=> Fix shuffle when ndim of input tensors are different

azure-pipelines.yml, mars/dataframe/datasource/read_parquet.py, mars/dataframe/datasource/tests/test_datasource_execution.py
Add implementation for reading partitioned parquet for `fastparquet`.
Fixes #2713
=> Add support for reading partitioned parquet for fastparquet

mars/services/task/supervisor/processor.py
Since the `report progress` will also set the subtask result, when the supervisor load is relatively high, the arrival time of the two set subtask results will be longer, resulting in the object ref being decremented one more time
Fixes #xxxx
=> [Bug] Fix duplicate dec object ref

mars/deploy/oscar/tests/test_fault_injection.py, mars/deploy/oscar/tests/test_ray_fault_injection.py, mars/oscar/backends/context.py, mars/oscar/backends/message.py, mars/oscar/backends/pool.py, mars/oscar/backends/test/tests/test_message.py, mars/oscar/core.pyx, mars/services/scheduling/worker/execution.py, mars/utils.py
Developers need the address and pid for debug in a large distributed cluster, so this PR,
An example exception,
``` python
File "mars/oscar/core.pyx", line 226, in _handle_actor_result
result = await result
File "/Users/admin/mars/services/tests/fault_injection_patch.py", line 86, in run
return await super().run()
File "/Users/admin/mars/services/subtask/worker/processor.py", line 457, in run
await self._execute_graph(chunk_graph)
File "/Users/admin/mars/services/subtask/worker/processor.py", line 195, in _execute_graph
await self._async_execute_operand(self._datastore, chunk.op)
File "/Users/admin/mars/services/tests/fault_injection_patch.py", line 94, in _async_execute_operand
handle_fault(fault)
File "/Users/admin/mars/services/tests/fault_injection_manager.py", line 50, in …
```
=> Add address and pid prefix to the mars exception message

mars/oscar/backends/core.py, mars/oscar/backends/mars/tests/test_mars_actor_context.py
Long exception will be raised when all the following conditions are met,
- asyncio.gather
- all the gathering coroutines / tasks are set to the same exception instance.
```python
import asyncio
futures = [asyncio.Future() for x in range(10)]
async def foo(i):
await futures[i]
async def bar(i):
await foo(i)
async def set_exception_loop():
try:
raise Exception("Got Exception!!!")
except Exception as e:
for fut in futures:
fut.set_exception(e)
async def wait_in_loop():
tasks = []
for _ in range(10):
task = asyncio.create_task(bar(_))
tasks.append(task)
asyncio.create_task(set_exception_loop())
await asyncio.gather(*tasks)
loop = asyncio.get_event_loop()
loop.run_until_complete(wait_in_loop())
```
output of long exception
``` python
Traceback (most recent call last):
File …
```
=> Fix long exception of asyncio.gather

.github/workflows/run-tests.sh, mars/metric/__init__.py, mars/metric/api.py, mars/metric/backends/__init__.py, mars/metric/backends/console/__init__.py, mars/metric/backends/console/console_metric.py, mars/metric/backends/console/tests/__init__.py, mars/metric/backends/console/tests/pytest.ini, mars/metric/backends/console/tests/test_console_metric.py, mars/metric/backends/metric.py, mars/metric/backends/tests/__init__.py, mars/metric/backends/tests/test_metric.py, mars/metric/tests/__init__.py, mars/metric/tests/test_metric_api.py
There is no metrics in mars and it's useful and necessary to add a simple and convenient metric framework.
Issuse #2743
=> Add metric framework

mars/dataframe/datasource/read_parquet.py
Fix NameError: name 'pq' is not defined if pyarrow is not installed
Fixes https://github.com/mars-project/mars/issues/2746
=> Fix NameError: name 'pq' is not defined if pyarrow is not installed

mars/core/operand/core.py, mars/dataframe/base/rechunk.py, mars/lib/sparse/__init__.py, mars/lib/sparse/matrix.py, mars/lib/sparse/tests/test_sparse.py, mars/tensor/indexing/tests/test_indexing.py, mars/tensor/rechunk/core.py, mars/tensor/rechunk/rechunk.py, mars/tensor/rechunk/tests/test_rechunk.py, mars/tensor/utils.py
This PR simplifies the `rechunk` implementation while the older version is really complicated and hard to understand.
Master branch:
```
In [1]: import numpy as np; import mars; import mars.tensor as mt
In [2]: mars.new_session()
Web service started at http://0.0.0.0:30452
Out[2]: <mars.deploy.oscar.session.SyncSession at 0x7f8441101250>
In [3]: r = np.random.RandomState(0).rand(12000, 12000)
In [4]: a = mt.array(r, chunk_size=1680).execute()
100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 100.0/100 [00:04<00:00, 23.39it/s]
In [5]: %time a.rechunk(2111).execute()
100%|███████████████████████████████████████████████████████████████████████████████████████████████████████ …
```
=> Simplify rechunk implementation

mars/dataframe/datasource/read_parquet.py, mars/oscar/backends/core.py, mars/oscar/backends/mars/tests/test_mars_actor_context.py
=> [BACKPORT] Fix long exception of asyncio.gather (#2748)

mars/dataframe/datasource/read_parquet.py, mars/deploy/oscar/tests/test_local.py, mars/deploy/oscar/tests/test_ray.py, mars/oscar/profiling.py, mars/tests/core.py
- Fix band_subtasks and most_calls are empty if the slow duration is large
Fixes #xxxx
=> Fix profiling band_subtasks and most_calls are empty if the slow duration is large

mars/dataframe/base/apply.py, mars/dataframe/base/tests/test_base.py, mars/dataframe/groupby/apply.py, mars/dataframe/groupby/tests/test_groupby.py, mars/deploy/oscar/tests/test_fault_injection.py, mars/utils.py
Stop inferring outputs when args provided
Fixes #2758
=> Stop inferring outputs when args provided

mars/dataframe/base/apply.py, mars/dataframe/base/tests/test_base.py, mars/dataframe/groupby/apply.py, mars/dataframe/groupby/tests/test_groupby.py
=> [BACKPORT] Stop inferring outputs when args provided (#2759)

mars/metric/api.py, mars/metric/backends/ray/__init__.py, mars/metric/backends/ray/ray_metric.py, mars/metric/backends/ray/tests/__init__.py, mars/metric/backends/ray/tests/test_ray_metric.py, mars/metric/tests/test_metric_api.py
This pr adds ray metrics implementation which can be used when mars on ray. And we can use ray's metric backend to record and report metrics data to external system in this scenario.
We can use ray metrics as follows:
```
from mars.metric.api import init_metrics, Metrics
init_metrics({"metric": {"backend": "ray"}})
c = Metrics.counter("test_counter", "A test counter", ("service", "tenant"))
c.record(1)
g = Metrics.gauge("test_gauge", "A test gauge")
g.record(1)
m = Metrics.meter("test_meter")
m.record(1)
h = Metrics.histogram("test_histogram")
h.record(1)
```
Issue #2743
=> [Metric]Add ray metrics implementation

mars/dataframe/merge/merge.py, mars/dataframe/merge/tests/test_merge_execution.py
For left join, if left DataFrame has only one chunk, shuffle is still necessary, otherwise it will produce wrong results.
Fixes #2107
=> Fix the wrong result of df.merge

mars/_version.py, mars/dataframe/arithmetic/dot.py, mars/dataframe/datasource/dataframe.py, mars/dataframe/datasource/from_tensor.py, mars/dataframe/datasource/tests/test_datasource.py, mars/dataframe/datasource/tests/test_datasource_execution.py, mars/dataframe/initializer.py, mars/dataframe/merge/concat.py, mars/dataframe/statistics/quantile.py, mars/dataframe/tests/test_initializer.py, mars/services/task/analyzer/analyzer.py, mars/storage/filesystem.py, mars/storage/plasma.py, mars/storage/shared_memory.py, mars/storage/vineyard.py, mars/tensor/datasource/array.py, mars/tensor/datasource/core.py, mars/tensor/datasource/diag.py, mars/tensor/datasource/ones.py, mars/tensor/datasource/tests/test_datasource.py, mars/tensor/datasource/tri.py, mars/tensor/datasource/zeros.py, mars/tensor/linalg/cholesky.py, mars/tensor/linalg/lu.py
This PR fixes DataFrame initializer when Mars object exists in list
Fixes #2769
=> Fix DataFrame initializer when Mars object exists in list

mars/dataframe/merge/merge.py, mars/dataframe/merge/tests/test_merge_execution.py
=> [BACKPORT] Fix wrong result of `df.merge` (#2774)

docs/source/reference/dataframe/general_functions.rst, mars/conftest.py, mars/deploy/oscar/tests/test_cmdline.py, mars/oscar/backends/message.py, mars/oscar/backends/ray/tests/test_ray_pool.py, mars/oscar/profiling.py, mars/services/subtask/core.py, mars/services/subtask/worker/tests/test_subtask.py, mars/services/task/supervisor/processor.py, mars/services/task/supervisor/stage.py, mars/tensor/__init__.py, mars/utils.py
Remove deprecate warnings when import mars.tensor. Also do other minor fixes.
Fixes #xxxx
=> Remove deprecate warnings when import mars.tensor

mars/deploy/oscar/session.py, mars/deploy/oscar/tests/test_fault_injection.py, mars/oscar/__init__.py, mars/oscar/backends/context.py, mars/oscar/backends/mars/tests/test_debug.py, mars/oscar/backends/mars/tests/test_mars_actor_context.py, mars/oscar/backends/pool.py, mars/oscar/context.pxd, mars/oscar/context.pyx, mars/oscar/core.pxd, mars/oscar/core.pyx, mars/oscar/utils.pyx, mars/services/cluster/tests/test_locator.py, mars/services/scheduling/supervisor/manager.py
Mars in-process actor call will go through the communication logic:
```txt
actor_ref.foo()                                           actor.foo()                 
\                                                  -/                                  
-\                                               /                                    
ActorCaller                              pool.process_message    
-\                                      -                                         
-                                   -/                                          
Client.send                  Server.on_connected   
-\                         -                                                
-                      -/                                                 
Channel.send --- …
```
=> Optimize in-process actor calls

.github/workflows/platform-ci.yml, mars/deploy/oscar/ray.py, mars/deploy/oscar/tests/test_ray.py, mars/oscar/backends/ray/communication.py, mars/oscar/backends/ray/driver.py, mars/oscar/backends/ray/pool.py
=> [BACKPORT][Ray] Support Ray client mode (#2773)

mars/dataframe/utils.py, mars/oscar/profiling.py, mars/services/lifecycle/supervisor/tracker.py, mars/services/task/supervisor/graph_visualizer.py, mars/services/task/supervisor/processor.py, mars/services/task/supervisor/tests/test_task_manager.py
Add an optional config `dump_subtask_graph` when submitting graphs, it will generate the complete chunk graph, those chunks be colored with same color will be united as a subgraph in DOT, and then connect subgraphs according to the subtask dependences. Specially, if one task has multiple stages, the edge's style will be "dotted" if the connected subtasks belong to different stages.
Here are some examples:
- Example1
```
In [12]: a = mt.random.rand(10, 10, chunk_size=3)
In [13]: b = a + 1 - 2
In [14]: c = b.sum(axis=1)
In [15]: c.execute(extra_config={"dump_subtask_graph": True})
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 100.0/100 [00:00<00:00, 360.90it/s]
Out[15]:
array([-4.79605122, -4.17584986, -3.62345371, …
```
=> Support generating a DOT file for subtask graph

mars/dataframe/datasource/dataframe.py, mars/dataframe/datasource/from_records.py, mars/dataframe/datasource/from_vineyard.py, mars/dataframe/datasource/index.py, mars/dataframe/datasource/series.py, mars/dataframe/indexing/iloc.py, mars/dataframe/indexing/loc.py, mars/dataframe/reduction/core.py, mars/dataframe/sort/core.py, mars/learn/neighbors/_faiss.py, mars/services/task/analyzer/tests/test_fusion.py, mars/tensor/arithmetic/tests/test_arithmetic.py, mars/tensor/datasource/array.py, mars/tensor/datasource/diag.py, mars/tensor/datasource/diagflat.py, mars/tensor/datasource/empty.py, mars/tensor/datasource/eye.py, mars/tensor/datasource/from_tiledb.py, mars/tensor/datasource/from_vineyard.py, mars/tensor/datasource/full.py, mars/tensor/datasource/identity.py, mars/tensor/datasource/linspace.py, mars/tensor/datasource/ones.py, mars/tensor/datasource/scalar.py, mars/tensor/datasource/tests/test_datasource.py, mars/tensor/datasource/zeros.py, mars/tensor/fft/fftfreq.py, mars/tensor/fft/rfftfreq.py
For some operands, `gpu` property is set to `False` as default, it's all changed to `None` in this PR.
Fixes #2809
=> Fix default value of `gpu` property for some operands

mars/tensor/datastore/to_vineyard.py
Here the tensor mighe be some subclass of numpy's `np.ndarray`.
Found during debugging CI failure in #2576
=> Fixes the failure on Vineyard CI by ensure the input tensor chunk is a numpy's ndarray

mars/services/scheduling/worker/workerslot.py, mars/services/task/supervisor/processor.py, mars/services/task/supervisor/stage.py
* Fix set_subtask_result race condition since we  release lock when `_decref_input_subtasks`.
* Fix duplicate subtasks submit.
Closes #2814
=> Fix race condition of `set_subtask_result`

mars/services/scheduling/worker/workerslot.py, mars/services/task/supervisor/processor.py, mars/services/task/supervisor/stage.py, mars/tensor/datastore/to_vineyard.py
Backport of #2784, #2814 and #2817
=> [BACKPORT] Fix race condition of set_subtask_result (#2784)

docs/source/reference/tensor/set.rst, mars/tensor/__init__.py, mars/tensor/base/__init__.py, mars/tensor/base/setdiff1d.py, mars/tensor/base/tests/test_base_execution.py
This PR implements `mars.tensor.setdiff1d`
Fixes #2822 .
=> Implements `mars.tensor.setdiff1d`

mars/core/graph/tests/test_graph.py, mars/dataframe/datastore/tests/test_datastore_execution.py, mars/services/lifecycle/supervisor/tracker.py, mars/services/storage/handler.py, mars/services/task/supervisor/processor.py
`StorageHandlerActor` is stateless before, it leads to potential race condition, change to stateful instead.
Fixes #2800
=> Change `StorageHandlerActor` to stateful

mars/deploy/oscar/rayconfig.yml, mars/deploy/oscar/tests/local_test_with_ray_config.yml, mars/services/scheduling/worker/workerslot.py
The worker fault tolerance is well tested in ray, it can be enabled by default.
Fixes #xxxx
=> [ray] Default enable fault tolerance for ray

mars/core/context.py, mars/core/custom_log.py, mars/learn/contrib/pytorch/run_script.py, mars/learn/contrib/tensorflow/run_script.py, mars/learn/contrib/xgboost/start_tracker.py, mars/learn/contrib/xgboost/tests/test_train.py, mars/services/context.py, mars/utils.py
Add `get_current_host_ip` method for `Context` to get host ip instead of using `ctx.current_address` directly, current_address will return address like "ray://xx" which is invalid for xgboost.
Fixes #2816
=> Fix running xgboost on Ray cluster

mars/core/graph/entity.py, mars/lib/filesystem/oss.py, mars/optimization/logical/common/column_pruning.py, mars/optimization/logical/core.py, mars/optimization/logical/tileable/arithmetic_query.py, mars/services/task/supervisor/stage.py
- Fix `FileSystem.ls` for OSS 
- Rename some variables in `OptimizationRule`
Fixes #2835
=> Fix `FileSystem.ls` for OSS 

mars/services/scheduling/supervisor/queueing.py, mars/services/scheduling/worker/execution.py, mars/services/scheduling/worker/service.py, mars/services/subtask/core.py, mars/services/subtask/tests/test_service.py, mars/services/subtask/worker/processor.py
Add subtask details when handling in subtasks and workers. `repr(subtask)` will look like
```
<Subtask id=C2Yl0r1tAIAA1RIdwCfA5ANN results=[TensorAdd(e2e822e32d0931a0be7c1646fe873dde_0)]>
```
Fixes #xxxx
=> Improve subtask details in logs

docs/source/reference/learn/reference.rst, mars/learn/metrics/__init__.py, mars/learn/metrics/_base.py, mars/learn/metrics/_ranking.py, mars/learn/metrics/tests/test_ranking.py, mars/learn/preprocessing/_label.py, mars/learn/utils/_encode.py, mars/learn/utils/multiclass.py, mars/services/lifecycle/supervisor/tracker.py, mars/services/task/supervisor/processor.py, mars/tensor/base/map_chunk.py
=> [BACKPORT] Added support for `mars.learn.metrics.roc_auc_score` (#2832)

mars/services/subtask/worker/processor.py, mars/services/subtask/worker/tests/subtask_processor.py
There are duplicated data puts (same data key multiple puts),
1.  among different subtasks. _`A & B > 0`_
2. in one subtask. _`len(A) > len(set(A))`_
Mars put duplicate data due to duplicated result chunks. This PR dedup the result chunks by chunk key before put, so the  `#2` can be fixed.
The example code,
```python
import numpy as np
import pandas as pd
import mars
if __name__ == "__main__":
with mars.new_session():
s = np.random.RandomState(0)
raw = pd.DataFrame(s.rand(100, 4), columns=list("abcd"))
df = md.DataFrame(raw, chunk_size=1)
r = df.describe().execute(extra_config={"enable_profiling": True})
print(r)
```
This PR can reduce,
- Data put count from 3070 to 2532.
Fixes #xxxx
=> Fix store duplicate chunk and meta per subtask

.github/workflows/pypi-cd.yml, .gitignore
Fix dirty version when building with CIBW. We need to make sure branches are clean before every build.
Fixes #xxxx
=> Fix dirty version when building with CIBW

mars/learn/contrib/xgboost/start_tracker.py, mars/learn/contrib/xgboost/tests/test_train.py, mars/learn/contrib/xgboost/tracker.py, mars/learn/contrib/xgboost/train.py
For now, if `evals` is specified for xgb train, assume `dtrain` data spans over 3 workers, but `evals` data only exist on 2 workers, the xgb train would become very slow, and cpu usage will be low, that is, at most 1 cpu can be leveraged, this PR fixed this issue.
Besides, this PR copied the newest tracker.py from xgboost official repo.
Fixes #2860 .
=> Fix XGBoost when some workers do not have `evals` data

.gitignore, mars/deploy/kubernetes/tests/test_kubernetes.py, mars/services/cluster/api/oscar.py, mars/services/cluster/backends/fixed.py, mars/services/cluster/locator.py, mars/services/cluster/tests/test_api.py, mars/services/scheduling/worker/tests/test_execution.py, mars/services/scheduling/worker/workerslot.py, mars/services/session/supervisor/core.py, mars/services/session/tests/test_service.py
When no supervisors available, the API `ClusterAPI.get_supervisor_refs` should return None instead of raising ValueError.
Fixes #2858
=> Raise ActorNotExist when no supervisors available

mars/oscar/backends/context.py, mars/oscar/backends/pool.py, mars/oscar/backends/ray/communication.py, mars/oscar/core.pyx
=> Avoid printing too many messages in Oscar

mars/core/graph/tests/test_graph.py, mars/dataframe/arithmetic/tests/test_arithmetic.py, mars/services/scheduling/worker/quota.py, mars/utils.py
Return correct dtype for datetime types when inferring dtypes in datetime arithmetic.
Fixes #2865
=> Fix dtype infer in DataFrame arithmetic on datetime consts

mars/oscar/__init__.py, mars/oscar/api.py, mars/oscar/backends/context.py, mars/oscar/backends/core.py, mars/oscar/backends/pool.py, mars/oscar/context.pyx, mars/services/cluster/api/core.py, mars/services/cluster/api/oscar.py, mars/services/cluster/api/web.py, mars/services/cluster/procinfo.py, mars/services/cluster/supervisor/service.py, mars/services/cluster/tests/test_api.py, mars/services/cluster/tests/test_procinfo.py, mars/services/cluster/worker/service.py, mars/services/web/ui/package-lock.json, mars/services/web/ui/src/node_info/NodeResourceTab.js, mars/services/web/ui/src/node_info/NodeStackTab.js, mars/services/web/ui/src/node_info/SupervisorDetailPage.js, mars/services/web/ui/src/node_info/WorkerDetailPage.js
Add a web page to display stack for each process of Mars services. Also add required APIs. The page will look like
Fixes #2875
=> Add stack display page on Mars Web

.github/workflows/docker-cd.yml, azure-pipelines.yml, mars/core/entity/executable.py, mars/core/graph/tests/test_graph.py, mars/deploy/oscar/session.py, mars/oscar/batch.py, mars/services/cluster/api/oscar.py, mars/services/scheduling/supervisor/manager.py, mars/services/scheduling/utils.py, mars/services/subtask/worker/processor.py, mars/services/subtask/worker/tests/test_subtask.py, mars/services/task/supervisor/processor.py
=> [BACKPORT] Upgrade azure-pipelines to Python 3.9 (#2862)

mars/services/task/api/web.py, mars/services/task/supervisor/manager.py, mars/services/task/supervisor/processor.py, mars/services/task/supervisor/service.py, mars/services/task/tests/test_service.py
Use `tornado.gen.with_timeout` to fix request timeout.
Fixes #2882
=> Fix timeout for `wait_task`

mars/core/entity/executable.py, mars/deploy/oscar/local.py, mars/oscar/backends/mars/tests/test_mars_actor_context.py, mars/oscar/backends/pool.py, mars/services/session/api/core.py, mars/services/session/api/oscar.py, mars/services/session/api/web.py, mars/services/session/supervisor/core.py, mars/services/session/tests/test_service.py, mars/services/subtask/worker/runner.py, mars/storage/shared_memory.py
This PR Add ability to make sure error can be raised in `Actor.__pre_destroy__`.
Fixes #2885 .
=> Make sure error can be raised in `Actor.__pre_destroy__`

mars/services/storage/core.py, mars/services/storage/worker/service.py
Use worker main pool as owner when autoscale disabled to avoid too much assign rpc.
#2877
=> [Ray] Use main pool as owner when autoscale disabled

mars/_utils.pyx, mars/core/graph/tests/test_graph.py, mars/oscar/__init__.py, mars/oscar/backends/mars/tests/test_pool.py, mars/oscar/backends/pool.py, mars/oscar/errors.py, mars/remote/tests/test_remote_function.py
Fix task hang when error object cannot be pickled.
Fixes #1959
=> Fix task hang when error object cannot be pickled

mars/deploy/oscar/ray.py, mars/deploy/oscar/tests/test_ray.py
There is  no `metrics` parameter passed in `create_worker_actor_pool` of `mars/deploy/oscar/ray.py` which leads to metrics backend not work in worker pool.
Fixes #xxxx
=> Fix paramter issue of worker actor pool

.gitignore, mars/_utils.pyx, mars/core/graph/tests/test_graph.py, mars/oscar/__init__.py, mars/oscar/backends/mars/tests/test_pool.py, mars/oscar/backends/pool.py, mars/oscar/errors.py, mars/remote/tests/test_remote_function.py
=> [BACKPORT] Fix task hang when error object cannot be pickled (#2910)

mars/services/scheduling/worker/execution.py, mars/services/storage/handler.py
Skip adding band in meta when fetch shuffle data as shuffle produce fragmented data.
Fixes #xxxx
=> Skip adding band in meta when fetch shuffle data

mars/dataframe/base/_duplicate.py, mars/dataframe/base/drop_duplicates.py, mars/dataframe/base/explode.py, mars/dataframe/base/melt.py, mars/dataframe/base/standardize_range_index.py, mars/dataframe/indexing/reset_index.py, mars/dataframe/merge/append.py, mars/dataframe/merge/concat.py, mars/dataframe/merge/tests/test_merge.py, mars/dataframe/sort/psrs.py, mars/dataframe/sort/sort_index.py, mars/dataframe/utils.py, mars/dataframe/window/rolling/aggregation.py, mars/services/context.py, mars/services/meta/__init__.py, mars/services/meta/api/__init__.py, mars/services/meta/api/oscar.py, mars/services/scheduling/worker/tests/test_execution.py, mars/services/subtask/core.py, mars/services/subtask/worker/processor.py, mars/services/subtask/worker/tests/test_subtask.py, mars/services/task/analyzer/analyzer.py, mars/services/task/execution/mars/stage.py, mars/services/task/supervisor/preprocessor.py, mars/services/task/supervisor/processor.py, mars/services/task/supervisor/tests/task_preprocessor.py, mars/services/task/supervisor/tests/test_task_manager.py, mars/tensor/base/shape.py
This PR support storing complete meta on worker and update supervisor meta via fetching from workers.
Fixes #2908 
#2791
=> Store complete meta on worker and update supervisor meta via fetching from workers

.gitignore, docs/source/reference/tensor/special.rst, mars/lib/sparse/__init__.py, mars/tensor/special/__init__.py, mars/tensor/special/core.py, mars/tensor/special/ellip_harm.py, mars/tensor/special/tests/test_special_execution.py, setup.cfg
=> [BACKPORT] Implementing Ellipsoidal Harmonics Functions (#2891)

.github/workflows/benchmark-ci.yml, docs/source/reference/tensor/special.rst, mars/services/task/analyzer/analyzer.py, mars/services/task/analyzer/tests/test_assigner.py, mars/services/task/api/web.py, mars/services/task/execution/api.py, mars/services/task/execution/mars/executor.py, mars/services/task/execution/mars/stage.py, mars/services/task/supervisor/preprocessor.py, mars/services/task/supervisor/processor.py, mars/services/task/supervisor/tests/task_preprocessor.py
When trigger iterative tiling, subtask's graph may has fetch operand, and we treat them as initial nodes and assign them in `GraphAnalyzer`, it will result in losing locality and bad performance. This PR try to solve this issue by ignoring fetch chunks when assign chunk graph.
Fixes #xxxx
=> Ignore fetch operands when assign initial nodes

LICENSE, mars/config.yml, mars/deploy/oscar/cmdline.py, mars/deploy/oscar/supervisor.py, mars/oscar/backends/mars/pool.py, mars/oscar/backends/ray/pool.py, mars/oscar/backends/ray/tests/test_communication.py, mars/serialization/aio.py, mars/services/web/core.py, mars/supervisor.py, mars/tests/test_cluster.py, mars/utils.py, mars/worker.py, setup.cfg
This PR did a few things:
1. Fix default config to ensure storage backends configured.
2. Add shortcuts of supervisor and worker, like starting supervisor with `python -m mars.supervisor`.
3. Optimize assertion error's message to tell that maybe wrong web port is provided.
4. Do not close http client if web client is gc because http client will close when itself gc collected.
Fixes #2931 
Fixes #2933
=> Fix default config to ensure storage backends configured

mars/core/entity/chunks.py, mars/dataframe/base/bloom_filter.py, mars/dataframe/merge/merge.py, mars/services/scheduling/supervisor/assigner.py, mars/services/scheduling/supervisor/tests/test_assigner.py, mars/services/scheduling/worker/execution.py, mars/utils.py
Add `is_broadcaster` property in ChunkData and avoid scheduling all broadcaster's downstream nodes to one worker. 
Fixes #2941
=> Ignore broadcaster's locality when assign subtasks

mars/dataframe/arithmetic/core.py, mars/dataframe/arithmetic/tests/test_arithmetic.py, mars/dataframe/arithmetic/tests/test_arithmetic_execution.py, mars/dataframe/core.py, mars/dataframe/groupby/aggregation.py, mars/dataframe/groupby/tests/test_groupby_execution.py, mars/dataframe/merge/concat.py, mars/deploy/oscar/session.py, mars/services/task/supervisor/tests/test_task_manager.py, mars/utils.py
Remove `should_be_monotonic` property in `IndexValue`, it may cause incompatible results for some operands.
Fixes #2939
=> Remove `should_be_monotonic` property

mars/core/operand/core.py, mars/metrics/backends/metric.py, mars/metrics/backends/tests/test_metric.py, mars/services/scheduling/supervisor/manager.py, mars/services/scheduling/supervisor/queueing.py, mars/services/scheduling/worker/execution.py
* Add scheduling, band and op metrics
```
mars.scheduling.submitted_subtask_count: The count of submitted subtasks to all bands.
mars.scheduling.finished_subtask_count: The count of finished subtasks of all bands.
mars.scheduling.canceled_subtask_count: The count of canceled subtasks of all bands.
mars.band.submitted_subtask_number: The number of submitted subtask to a band.
mars.band.unsubmitted_subtask_number: The number of unsubmitted subtask to a band.
mars.operand.executed_number: The number of executed operands.
```
* Optimize metrics arguments check
Fixes #xxxx
=> [Metrics] Add metrics for scheduling

mars/services/task/execution/ray/fetcher.py
=> [Ray] optimize ray fetcher by query in remote node

mars/core/graph/tests/test_graph.py, mars/deploy/kubernetes/config.py, mars/deploy/oscar/supervisor.py, mars/oscar/backends/context.py, mars/oscar/backends/mars/pool.py, mars/oscar/backends/mars/tests/test_mars_actor_context.py, mars/oscar/backends/pool.py, mars/oscar/context.pxd, mars/oscar/context.pyx, mars/tests/core.py, mars/tests/test_cluster.py, mars/utils.py
Config multiple processes for supervisors by default.
Fixes #xxxx
=> Fix potential KeyError in actor_ref calls when running with multiple processes

mars/core/graph/tests/test_graph.py, mars/deploy/kubernetes/config.py, mars/deploy/oscar/supervisor.py, mars/oscar/backends/context.py, mars/oscar/backends/mars/pool.py, mars/oscar/backends/mars/tests/test_mars_actor_context.py, mars/oscar/backends/pool.py, mars/oscar/context.pxd, mars/oscar/context.pyx, mars/utils.py
=> [BACKPORT] Fix potential KeyError in actor_ref calls when running with multiple processes (#2950)

mars/core/__init__.py, mars/core/base.py, mars/dataframe/groupby/aggregation.py, mars/lib/cython/__init__.py, mars/lib/cython/libcpp.pxd, mars/oscar/backends/mars/pool.py, mars/oscar/backends/message.pyi, mars/oscar/backends/message.pyx, mars/oscar/backends/ray/communication.py, mars/oscar/context.pyx, mars/oscar/utils.pyx, mars/serialization/core.pyx, mars/services/scheduling/tests/test_service.py, mars/services/scheduling/worker/execution.py, mars/services/subtask/worker/processor.py, mars/services/subtask/worker/tests/test_subtask.py, mars/tests/test_cluster.py, mars/utils.py
Wrap errors in operand execution to protect scheduling service with an `ExecutionError`. When building `ErrorMessage` real errors are extracted and stored in the message from the wrapper.
Fixes #2963
=> Wrap errors in operand execution to protect scheduling service

mars/core/__init__.py, mars/core/base.py, mars/core/entity/utils.py, mars/core/graph/__init__.py, mars/core/graph/builder/__init__.py, mars/core/graph/builder/chunk.py, mars/dataframe/merge/merge.py, mars/dataframe/merge/tests/test_merge_execution.py, mars/optimization/logical/chunk/tests/test_column_pruning.py, mars/optimization/logical/chunk/tests/test_head.py, mars/optimization/physical/tests/test_cupy.py, mars/oscar/backends/pool.py, mars/services/task/analyzer/analyzer.py, mars/services/task/analyzer/tests/test_assigner.py, mars/services/task/execution/api.py, mars/services/task/execution/mars/executor.py, mars/services/task/execution/ray/executor.py, mars/services/task/supervisor/manager.py, mars/services/task/supervisor/preprocessor.py, mars/services/task/supervisor/processor.py, mars/services/task/supervisor/task.py, mars/services/task/supervisor/tests/task_preprocessor.py, mars/services/task/tests/test_service.py
This PR enables ability to report tile progress, now a TileStatus object can be yielded to tell the progress of tile, if not provided, the progress will be by default 0.4 * reset progress. 
Now the task progress is updated, now each stage's progress will have be tile_progress * subtask_progress.
Besides, progress of tileable graph is refined too, now the progress is more accurate, and enabled cache-based optimization.
Fixes #xxxx
=> Support reporting tile progress

mars/core/graph/entity.py, mars/core/graph/tests/test_graph.py
Logic key is a unique and deterministic key for `TileableGraph`. For multiple runs the logic key will remain same if the computational logic doesn't change. And it can be used to some optimization when running a same `execute`, like HBO.
#2787
=> Add logic key for tileable graph

mars/deploy/oscar/session.py, mars/deploy/oscar/tests/test_local.py, mars/deploy/oscar/tests/test_ray_dag.py, mars/services/task/execution/ray/context.py, mars/services/task/execution/ray/executor.py, mars/services/task/supervisor/processor.py, mars/services/task/supervisor/tests/test_task_manager.py, mars/services/task/supervisor/tests/test_task_manager_on_ray_dag.py
This PR makes the Ray executor able to load the subtask inputs from meta, so Ray backend can run the task which inputs are the executed tasks.
=> [Ray] Loads the subtask inputs from meta

mars/deploy/oscar/session.py, mars/deploy/oscar/tests/test_local.py, mars/services/lifecycle/supervisor/tracker.py, mars/services/storage/api/oscar.py, mars/services/storage/transfer.py, mars/services/task/execution/mars/executor.py
This PR fixes data leak during shuffle tasks.
Fixes #2974
=> Fix potential data leak for shuffle tasks

mars/dataframe/datasource/dataframe.py, mars/dataframe/datasource/tests/test_datasource.py, mars/dataframe/utils.py
This PR fixed potential empty chunks when creating DataFrame from pandas.
Fixes #2985 .
=> Fix potential empty chunks when creating DataFrame from pandas

mars/deploy/oscar/base_config.yml, mars/deploy/oscar/tests/test_local.py, mars/deploy/oscar/tests/test_ray_scheduling.py, mars/deploy/utils.py
This pr fixed speculative execution compatibility with coloring by set `initial_same_color_num` to 1 to ensure enough homogeneous subtasks. If `initial_same_color_num` > 1, coloring based fusion will make subtask too heterogeneous such that the speculative scheduler can't get enough homogeneous subtasks to calculate statistics
Fixes #xxxx
=> Fix speculative execution compatibility with coloring

mars/deploy/oscar/tests/test_local.py, mars/services/lifecycle/supervisor/tracker.py
This PR made functions that may take long run in thread for lifecycle tracker.
Fixes #xxxx
=> Make functions that may take long run in thread for lifecycle tracker

mars/deploy/oscar/base_config.yml, mars/deploy/oscar/ray.py, mars/metrics/api.py, mars/metrics/tests/test_metric_api.py, mars/oscar/backends/pool.py
The arguments  of `init_metrics(backend, port)` method are inappropriate. Because port is a configuration of prometheus. It is not necessary for `console` and `ray`. It's better to change it to `config` and in this way we could easily add new metric backend.
Fixes #xxxx
=> [Metrics] Optimize metric configs

mars/core/operand/base.py, mars/core/operand/tests/test_core.py
Fix missing extra_params when constructing operands
Fixes https://github.com/mars-project/mars/issues/2998
=> Fix missing extra_params when constructing operands

mars/oscar/backends/ray/communication.py, mars/oscar/backends/ray/tests/test_communication.py
This PR fix `msg_to_simple_str` error introduced in #2936 when truth value for some object is ambiguous.
#2936
Fixes #xxxx
=> Fix `msg_to_simple_str` in Ray backend and add tests

mars/services/task/analyzer/analyzer.py
If `start ops` is huge, `chunk not in start_ops` will take `O(n)` complexties, which will be very time comsuing. This PR optimize gen subtask graph by using `set` instead of `list` for `start ops`
Fixes #xxxx
=> Optimize gen subtask graph

mars/dataframe/sort/psrs.py, mars/dataframe/sort/sort_values.py, mars/dataframe/sort/tests/test_sort_execution.py
Before we didn't consider the `ascending` parameter would be a list, the behavior in `DataFramePSRSShuffle._calc_poses` simply take it as a bool value and leads to incorrect result. This PR converts value as `ReversedValue` for those columns with `ascending=False` to work correctly with `np.searchsorted`.
Fixes #2980
=> Fix incorrect result for `df.sort_values` when specifying multiple ascending

mars/dataframe/datasource/core.py, mars/deploy/oscar/tests/test_local.py, mars/deploy/oscar/tests/test_ray_dag.py, mars/oscar/backends/pool.py, mars/services/task/execution/mars/executor.py, mars/services/task/execution/ray/context.py, mars/services/task/execution/ray/executor.py, mars/services/task/execution/ray/tests/test_ray_execution_backend.py, mars/services/task/supervisor/manager.py, mars/services/task/supervisor/tests/test_task_manager.py, mars/services/task/supervisor/tests/test_task_manager_on_ray_dag.py
Mars execution context provides remote object to sync states between multiple running operands. Ray execution backends use a task state actor for this feature.
With this PR, ray backend supports incremental index.
The drawback is that,
- Poor performance to sync states among operands, maybe we can avoid using remote object when executing operands in the future.
- Hard to fault tolerance because the remote object makes the operands stateful.
=> [Ray] Ray execution state

.github/workflows/pypi-cd.yml, setup.cfg
Build web code before CIBW when deploying to PyPI in Linux. Also remove benchmarks in wheels.
Fixes #xxxx
=> Build web code before CIBW when deploying to PyPI

mars/core/entity/tests/test_utils.py, mars/core/entity/utils.py, mars/services/task/supervisor/tests/task_preprocessor.py
This PR fixed recursive_tile that it may cause duplicated tile for one tileable.
Fixes #3010
=> Fix recursive_tile that it may cause duplicated tile for one tileable

mars/lib/tbcode.py, mars/lib/tblib/__init__.py, mars/lib/tblib/cpython.py, mars/lib/tblib/decorators.py, mars/lib/tblib/pickling_support.py, mars/lib/tests/test_lib.py, mars/services/task/api/web.py, pyproject.toml
Dump remote tracebacks to make local ones more friendly. Also upgrade bundled tblib to 1.7.0.
Fixes #xxxx
=> Dump remote tracebacks to make local ones more friendly

mars/lib/tbcode.py, mars/services/scheduling/worker/execution.py, mars/services/storage/transfer.py, mars/services/task/api/web.py, pyproject.toml
Use tell when remove mapper data after execution to reduce time cost.
Fixes #xxxx
=> Use tell when remove mapper data after execution

CODEOWNERS
This PR changed code owners to Mars PMC maintainers.
Fixes #xxxx
=> Change code owners to Mars PMC maintainers

benchmarks/tpch/run_queries.py, mars/dataframe/groupby/aggregation.py, mars/dataframe/groupby/sort.py, mars/dataframe/groupby/tests/test_groupby_execution.py
This PR optimized tile of groupby to stop aggressively choosing tree method for distributed setting.
Fixes #xxxx
=> Do not aggressively choose tree method in tile of groupby for distributed setting

mars/conftest.py, mars/deploy/oscar/tests/test_local.py, mars/deploy/oscar/tests/test_ray_dag.py
Ray executor progress test does not run due to lack of await. This pr fixed it.
Fixes #xxxx
=> [Ray] Fix ray executor progress test

mars/conftest.py, mars/dataframe/base/standardize_range_index.py, mars/dataframe/utils.py, mars/remote/core.py, mars/tensor/base/shape.py, mars/tensor/base/tests/test_base_execution.py
Some operands call `ThreadedServiceContext.get_chunks_meta` when executing, which is unnecessary because the iterative tiling updates the meta to the chunks. The operands have enough meta for executing.
- TensorGetShape
- `yield a.chunks` before the operand is constructed.
- ChunkStandardizeRangeIndex
- yield the input chunks of `standardize_range_index` before the operand is constructed.
- RemoteFunction
- yield the tileable inputs before the operand is executed.
=> Refine ThreadedServiceContext.get_chunks_meta usage

mars/lib/sparse/array.py, mars/lib/sparse/tests/test_sparse.py, mars/tensor/base/tests/test_base_execution.py
Makes `SparseNDArray` object pickleable.
Fixes https://github.com/mars-project/mars/issues/3045
=> Fix error message when sparse data format not supported

mars/dataframe/merge/merge.py, mars/dataframe/merge/tests/test_merge.py
For now, we shuffle left and right separately and make reducer data locate in different workers, this leads to additional transfer when execute merge operand. This PR only shuffles once for both left and right, so that reducer data locate in same worker and no transfer for following execution.
Fixes #xxxx
=> Shuffle both sides at the same time for `md.merge`

benchmarks/tpch/run_queries.py, mars/core/operand/shuffle.py, mars/dataframe/groupby/aggregation.py, mars/services/task/analyzer/analyzer.py, mars/services/task/analyzer/assigner.py, mars/services/task/analyzer/tests/test_assigner.py
=> Assign reducer ops in task assigner to make them more balanced across cluster

mars/services/task/execution/api.py, mars/services/task/execution/ray/executor.py, mars/services/task/execution/ray/tests/test_ray_execution_backend.py, mars/services/task/supervisor/processor.py
Mars tests share one same session in CI, but all the `TaskProcessorActor`, `TaskProcessor` and `TaskExecuter` are not destroyed. So, this PR
=> [Ray] Destroy Ray executor when the task finish

mars/dataframe/base/tests/test_base_execution.py, mars/services/task/execution/ray/context.py, mars/services/task/execution/ray/executor.py, mars/services/task/execution/ray/fetcher.py, mars/services/task/execution/ray/tests/test_ray_execution_backend.py, mars/tensor/base/tests/test_base_execution.py
- new_custom_log_dir
- register_custom_log_path
- set_progress
- set_running_operand_key
- get_storage_info
=> [Ray] Implements get_chunks_meta for Ray execution context

mars/conftest.py, mars/dataframe/contrib/raydataset/dataset.py, mars/dataframe/contrib/raydataset/mldataset.py, mars/dataframe/contrib/raydataset/tests/test_raydataset.py, mars/deploy/oscar/rayconfig.yml, mars/deploy/oscar/session.py, mars/deploy/oscar/tests/test_local.py, mars/deploy/oscar/tests/test_ray.py, mars/deploy/oscar/tests/test_ray_dag_failover.py, mars/deploy/utils.py, mars/services/task/execution/ray/config.py, mars/services/task/execution/ray/executor.py
This PR implements basic subtask retry and reconstruction based on ray object lineage reconstruction.
With this PR, if task lineage are not evicted, the mars tasks will succeed even some ray nodes has failed.
Closes #3029
#2972
=> [Ray] Support basic subtask retry and lineage reconstruction

mars/dataframe/tests/test_utils.py, mars/dataframe/utils.py
if a single chunk remains to merge in auto_merge_chunks, current code tries not to create a new concat OP and just use the last chunk. But the index of last chunk should be changed after merging.
This PR fixes this issue.
Fixes #3056
=> Fix chunk index error in auto_merge_chunks

docs/source/reference/tensor/special.rst, mars/lib/sparse/__init__.py, mars/lib/sparse/array.py, mars/tensor/special/__init__.py, mars/tensor/special/err_fresnel.py, mars/tensor/special/tests/test_special.py, mars/tensor/special/tests/test_special_execution.py
Integrate special error functions (erfc, erfcx, erfi, erfinv, erfcinv) following the erf function example
#757 (error functions part)
=> Integrate special error functions

mars/dataframe/groupby/aggregation.py, mars/dataframe/groupby/core.py, mars/dataframe/groupby/tests/test_groupby.py, mars/dataframe/groupby/tests/test_groupby_execution.py, mars/services/subtask/worker/processor.py
This PR applies both tree and shuffle methods for `DataFrameGroupBy.agg`'s auto method. First, combine map chunks into larger chunks according to sample chunk's size, then shuffle those combined chunks. It brings improvements when executing groupby on cluster.
Fixes #xxxx
=> Combine tree and shuffle methods in `DataFrameGroupBy.agg` tile

mars/dataframe/base/tests/test_base_execution.py, mars/services/task/execution/api.py, mars/services/task/execution/mars/config.py, mars/services/task/execution/mars/executor.py, mars/services/task/execution/ray/config.py, mars/services/task/execution/ray/context.py, mars/services/task/execution/ray/executor.py, mars/services/task/execution/ray/tests/test_ray_execution_backend.py, mars/services/task/execution/utils.py, mars/tensor/base/tests/test_base_execution.py
=> [Ray] Implements get_total_n_cpu for Ray execution context

mars/conftest.py, mars/deploy/oscar/tests/test_local.py, mars/deploy/oscar/tests/test_ray_dag.py, mars/services/task/execution/ray/executor.py
=> [BACKPORT][Ray] Implement ray task executor progress (#3008)

mars/dataframe/merge/merge.py, mars/dataframe/merge/tests/test_merge.py
=> [BACKPORT] Shuffle both sides at the same time for `md.merge` (#3041)

benchmarks/tpch/run_queries.py, mars/dataframe/groupby/aggregation.py, mars/dataframe/groupby/sort.py, mars/dataframe/groupby/tests/test_groupby_execution.py
=> [BACKPORT] Do not aggressively choose tree method in tile of groupby for distributed setting (#3032)

mars/dataframe/groupby/aggregation.py, mars/dataframe/groupby/core.py, mars/dataframe/groupby/tests/test_groupby.py, mars/dataframe/groupby/tests/test_groupby_execution.py, mars/services/subtask/worker/processor.py
=> [BACKPORT] Combine tree and shuffle methods in `DataFrameGroupBy.agg` tile (#3051)

mars/dataframe/groupby/aggregation.py, mars/dataframe/groupby/tests/test_groupby.py
In #3051, we introduce a new tile strategy for DataFrameGroupByAgg if method is "auto" , it only works for cluster mode. However, it also brings improvements when executing on local, so we remove branch for local and unify them in this PR.
Fixes #xxxx
=> Unify DataFrameGroupByAgg's tile logic for auto method

mars/services/cluster/api/web.py, mars/services/task/api/web.py, mars/services/web/core.py, mars/services/web/tests/test_core.py
Call immutable web API only once when previous call does not return. This reduces potential call flood for services.
Fixes #xxxx
=> Call immutable web API only once when previous call blocks

.github/workflows/platform-ci.yml, mars/deploy/oscar/ray.py, mars/deploy/oscar/tests/test_ray.py, mars/oscar/backends/ray/pool.py, mars/oscar/backends/ray/utils.py, mars/tests/test_utils.py, mars/utils.py
In ray master, If a actor created with `max_restarts=-1` is restarting, call actor method will raise exception instead of pending in caller. This PR fix it by specifing `max_retries=-1` when querying actor state.
Fixes #3079
=> [Ray] Fix ray worker failover

mars/dataframe/groupby/aggregation.py, mars/dataframe/groupby/tests/test_groupby.py
=> [BACKPORT] Unify DataFrameGroupByAgg's tile logic for auto method (#3084)

mars/_resource.pyx, mars/learn/metrics/pairwise/tests/test_haversine_distances.py, mars/oscar/batch.py, mars/oscar/core.pyx, mars/serialization/core.pxd, mars/serialization/core.pyx, mars/serialization/tests/test_serial.py, mars/services/web/ui/src/node_info/NodeEnvTab.js, mars/services/web/ui/src/node_info/NodeResourceTab.js
Simplify batch call in actors by adding a `call_with_lists` method. Batch calls are now executed without having to convert to `DelayedArguments` and converted back again.
Fixes #xxxx
=> Simplify argument passing in actor batch calls

.github/workflows/platform-ci.yml, mars/conftest.py, mars/deploy/oscar/tests/test_ray.py, mars/deploy/oscar/tests/test_ray_client.py, mars/deploy/oscar/tests/test_ray_dag.py, mars/deploy/oscar/tests/test_ray_dag_failover.py, mars/deploy/oscar/tests/test_ray_fault_injection.py, mars/deploy/oscar/tests/test_ray_scheduling.py, mars/oscar/backends/ray/driver.py
This PR optimizes Ray CI execution time and stability by :
- Making ray/deploy as a separate CI pipeline. The `ray/deploy` tests cases took at least 20~40 minutes to finish, which is long enough for a separate CI pipeline. A faster and small CI is more friendly to retry and more stable
- Move all scheduling tests from `test_ray.py` into `test_ray_scheduling.py`
- Using shared ray cluster for `test_ray.py` and `test_ray_fault_injection.py`
- Reduce created workers for some tests
- Split pytest into multiple pytest cases
With this PR, the longest Ray Deploy CI only took 19 minutes, which speed up development efficiency notably:
Ray CI took 17 minutes:
Ray DAG CI took 3 minutes:
And Ray CI is more stable. Timeout doesn't happen again.
Closes #3101
=> [Ray] Optimize Ray CI execution time and stability

mars/core/operand/shuffle.py, mars/core/operand/tests/test_core.py, mars/dataframe/align.py, mars/dataframe/base/_duplicate.py, mars/dataframe/groupby/aggregation.py, mars/dataframe/groupby/core.py, mars/dataframe/groupby/sample.py, mars/dataframe/merge/merge.py, mars/dataframe/sort/psrs.py, mars/learn/ensemble/_bagging.py, mars/learn/utils/shuffle.py, mars/services/task/execution/mars/executor.py, mars/services/task/supervisor/tests/task_preprocessor.py, mars/tensor/base/psrs.py, mars/tensor/base/unique.py, mars/tensor/indexing/index_lib.py, mars/tensor/indexing/setitem.py, mars/tensor/random/permutation.py, mars/tensor/reshape/reshape.py, mars/tensor/spatial/distance/pdist.py, mars/tensor/spatial/distance/squareform.py, mars/tensor/statistics/bincount.py
This PR add `n_reducers` and `reducer_ordinal` to all shuffle operands, which enable further meta and scheduling optimization for shuffle in future.
https://github.com/mars-project/meps/pull/2
#3054 
#3040
#2916
=> Add `n_reducers` and `reducer_ordinal` to shuffle operands

mars/deploy/oscar/tests/test_local.py, mars/deploy/oscar/tests/test_ray_dag.py
Fix `test_session_set_progress` when running on backend ray.
Fixes #xxxx
=> Make `test_session_set_progress` more stable under Ray tests

mars/core/operand/shuffle.py, mars/core/operand/tests/test_core.py, mars/dataframe/align.py, mars/dataframe/base/_duplicate.py, mars/dataframe/groupby/aggregation.py, mars/dataframe/groupby/core.py, mars/dataframe/groupby/sample.py, mars/dataframe/merge/merge.py, mars/dataframe/sort/psrs.py, mars/deploy/oscar/tests/test_local.py, mars/deploy/oscar/tests/test_ray_dag.py, mars/learn/ensemble/_bagging.py, mars/learn/utils/shuffle.py, mars/services/task/execution/mars/executor.py, mars/services/task/supervisor/tests/task_preprocessor.py, mars/tensor/base/psrs.py, mars/tensor/base/unique.py, mars/tensor/indexing/index_lib.py, mars/tensor/indexing/setitem.py, mars/tensor/random/permutation.py, mars/tensor/reshape/reshape.py, mars/tensor/spatial/distance/pdist.py, mars/tensor/spatial/distance/squareform.py, mars/tensor/statistics/bincount.py
=> [BACKPORT] Add `n_reducers` and `reducer_ordinal` to shuffle operands (#3055)

docs/source/reference/tensor/special.rst, mars/lib/sparse/__init__.py, mars/lib/sparse/array.py, mars/tensor/special/__init__.py, mars/tensor/special/ellip_func_integrals.py, mars/tensor/special/tests/test_special.py, mars/tensor/special/tests/test_special_execution.py
Integrate scipy elliptic functions and integrals except ellipj which returns multiple outputs. Some functions are within a try except block because they were not implemented in scipy v1.7, so spspecial.func may throw an AttributeError if the scipy version is low.
#751 (except ellipj)
=> Integrate part of scipy elliptic functions and integrals

.github/workflows/benchmark-ci.yml, benchmarks/asv_bench/benchmarks/storage.py, mars/deploy/oscar/tests/test_local.py, mars/oscar/backends/mars/pool.py, mars/oscar/debug.py, mars/tests/test_utils.py
`multiprocessing` module fixes importing `__main__` when starting subprocesses with `forkserver` or `spawn`. This stops running Mars local clusters without wrapping code with `if __name__ == "__main__"` block. This can be fixed by suspending this import behavior when starting subprocesses with Mars actor pools.
Also fixes benchmark errors for storage mod.
Fixes #3108
=> Stop importing main module when starting Mars local cluster

benchmarks/asv_bench/benchmarks/graph_assigner.py, benchmarks/asv_bench/benchmarks/serialize.py, mars/core/base.py, mars/dataframe/arithmetic/tests/test_arithmetic.py, mars/dataframe/core.py, mars/dataframe/indexing/tests/test_indexing.py, mars/serialization/serializables/core.py, mars/serialization/serializables/field.py, mars/serialization/serializables/tests/test_serializable.py, mars/services/task/execution/ray/executor.py
This PR implements the serializable fields by slots instead of a value dict, 
- Reduces **~25%** memory usage / peaks of constructing graph (in the supervisor).
- Reduces **~40%** memory footprint of serializables (most of them are chunks). 
- About **~12%** faster when serialize / deserialize the serializables.
Test code 
``` python
import time
import tracemalloc
import mars.tensor as mt
from mars.core.graph import TileableGraph, TileableGraphBuilder, ChunkGraphBuilder
from asv.extern import asizeof
tracemalloc.start()
start_time = time.time()
num_rows = 10000
df1 = md.DataFrame(
mt.random.rand(num_rows, 4, chunk_size=10), columns=list("abcd")
)
df2 = md.DataFrame(
mt.random.rand(num_rows, 4, chunk_size=10), columns=list("abcd")
)
merged_df = df1.merge(
df2, …
```
=> Optimize serializable memory

docs/source/development/metrics.rst, docs/source/locale/zh_CN/LC_MESSAGES/development/metrics.po, mars/metrics/__init__.py, mars/metrics/api.py, mars/metrics/backends/prometheus/prometheus_metric.py, mars/metrics/backends/prometheus/tests/test_prometheus_metric.py, mars/metrics/tests/test_metric_api.py
* Fix an error when executing a task with Prometheus metric backend
* Add details docs for Prometheus metric backend
Fixes #3123 
We can use Prometheus metric backend as follows:
* Download Prometheus, details see https://prometheus.io/docs/prometheus/latest/getting_started/
1. New a Mars session
```python
In [1]: import numpy as np
...:
...: import mars
...: import mars.dataframe as md
...:
...: session = mars.new_session(n_worker=1, n_cpu=2, web=True, config={"metrics.backend": "prometheus"})
...:
Finished startup prometheus http server and port is 46137
Finished startup prometheus http server and port is 32280
Finished startup prometheus http server and port is 39947
Finished startup prometheus http server and port is 25067
Web service started at http://0.0.0.0:11244
```
2. Config and …
=> [Metric] Fix prometheus metric backend

benchmarks/asv_bench/benchmarks/graph_assigner.py, benchmarks/asv_bench/benchmarks/serialize.py, mars/core/base.py, mars/dataframe/arithmetic/tests/test_arithmetic.py, mars/dataframe/core.py, mars/dataframe/indexing/tests/test_indexing.py, mars/serialization/serializables/core.py, mars/serialization/serializables/field.py, mars/serialization/serializables/tests/test_serializable.py, mars/services/task/execution/ray/executor.py
=> [BACKPORT] Optimize serializable memory (#3120)

mars/tensor/special/__init__.py, mars/tensor/special/ellip_func_integrals.py, mars/tensor/special/tests/test_special.py
Currently, the file tries to import certain elliptic functions and integrals such as elliprc from both scipy and err_func_integrals.py. However, these functions don't exist in scipy nor err_func_integrals.py if the scipy version is low. So directly importing them causes import errors. We can move these imports to within the test functions, so only if we have correct dependencies then we import them. 
Fixes #3128
=> Update pytest imports for test_special.py

mars/deploy/oscar/tests/test_ray.py, mars/deploy/oscar/tests/test_ray_cluster_standalone.py
`test_optional_supervisor_node` use same actor name for different run which is flaky because ray kill actor async. This PR fix it by using a standalone ray cluster
Fixes #xxxx
=> [Ray] Fix flaky test `test_optional_supervisor_node`

mars/tensor/arithmetic/add.py, mars/tensor/arithmetic/multiply.py, mars/tensor/reduction/core.py, mars/tensor/reduction/tests/test_reduction_execution.py, mars/tensor/reshape/reshape.py
This PR fixed mt.{cumsum, cumprod} when the first chunk is empty.
Fixes #3132
=> Fix mt.{cumsum, cumprod} when the first chunk is empty

benchmarks/asv_bench/benchmarks/graph_builder.py, benchmarks/tpch/run_queries.py, mars/dataframe/align.py, mars/dataframe/indexing/setitem.py, mars/dataframe/utils.py
This PR optimized tile of DataFrame.__setitem__ by reducing time of generating chunk meta.
Fixes #xxxx
=> Optimize tile of DataFrame.__setitem__ by reducing time of generating chunk meta

mars/lib/aio/lru.py, mars/services/meta/api/oscar.py
The default value of alru cache is 128 which is small. Like `WorkerMetaAPI.create`, there will be lots of duplicate creations if number of workers is greater than 128. 
In my job there are 3639 chunk results and 200 workers and it costs 1414s to create worker meta apis. After caching the created meta apis, it only takes 156s by accelerating 9x speed.
We should increase the default value of alru_cache like 1024.
Fixes #3143
=> Increase the default value of alru cache max size

docs/source/reference/tensor/special.rst, mars/tensor/array_utils.py, mars/tensor/special/__init__.py, mars/tensor/special/core.py, mars/tensor/special/err_fresnel.py, mars/tensor/special/tests/test_special.py, mars/tensor/special/tests/test_special_execution.py, mars/tensor/utils.py
We can use ExecutableTuple and TensorTupleElementOp to support mars execution of scipy special functions with tuple returns. Specifically, the following syntaxes can be supported:
```python
from mars.tensor import special
import mars.tensor as mt
x = mt.linspace(-3, 3)
S, C = special.fresnel(x)
S.execute()
C.execute()
special.fresnel(x).execute()
(S + C).execute()
```
Also since we invoke scipy.special.fresnel during tensor executions, a cache is added in core.py so if we execute multiple elements of the same function during one execute() call, we don't need to do the scipy computation for each element. Later executes can just use the cached scipy outputs.
=> Support scipy special function with tuple output

mars/core/graph/core.pyx
This PR fix graph.to_dot when reducer has multiple outputs
Fixes #xxxx
=> Fix `DAG.to_dot` when reducers have multiple outputs

mars/dataframe/arithmetic/__init__.py, mars/dataframe/arithmetic/core.py, mars/dataframe/arithmetic/dot.py, mars/dataframe/arithmetic/tests/test_arithmetic_execution.py, mars/dataframe/arithmetic/tests/test_comparison.py, mars/dataframe/arithmetic/tests/test_dot.py, mars/dataframe/base/accessor.py, mars/dataframe/base/tests/test_base.py, mars/dataframe/operands.py, mars/dataframe/tseries/to_datetime.py, mars/typing.py
Patch pandas magic functions to allow handling Mars objects.
Fixes #3154
=> Patch pandas magic functions to allow reverse operands

.github/workflows/platform-ci.yml, mars/deploy/oscar/tests/test_ray.py, mars/deploy/oscar/tests/test_ray_load_modules.py
This PR fix ray load_modules flaky by moving it to a standalone module and use standalone ray cluster. If reusing exsiting cluster, the clsuter stop may hang at pytest cleanup:
Fixes #xxxx
=> Run flaky test `test_load_third_party_modules` separately

benchmarks/asv_bench/benchmarks/execution.py, mars/optimization/physical/numexpr.py, mars/optimization/physical/tests/test_numexpr.py, mars/services/task/execution/ray/tests/test_ray_execution_backend.py, mars/tensor/fuse/numexpr.py, mars/tensor/fuse/tests/test_numexpr_execution.py
graph(@: node, S: Slice Chunk, #: fused_node): fuse stopped at S, because numexpr don't support Slice op
- before
```python
@                   @              @             @
\               /                  \         /
@ --> @ --> S      ========>       # --> S
/               \                  /         \
@                   @              @             @
```
- after
```python
@                   @                          @
\               /                          /
@ --> @ --> S      ========>     # --> S
/               \                          \
@                   @                          @
```
Update Mars fuse logic to support new operands:
- TensorFloor
- TensorCeil
- TensorAnd
- TensorOr
- TensorNot
- before
`((V_7db74de3f328b72d4e13457955bf5289_0+V_5b589bdfffe813d3d0414 …
=> Improve numexpr fusion

mars/_utils.pyx, mars/core/operand/tests/test_core.py, mars/deploy/oscar/tests/session.py, mars/lib/mmh3_src/mmh3module.cpp, mars/services/subtask/worker/tests/subtask_processor.py, mars/services/task/execution/ray/executor.py, mars/services/task/execution/ray/fetcher.py, mars/services/task/execution/ray/tests/test_ray_execution_backend.py, mars/tensor/datastore/tests/test_datastore_execution.py, mars/tests/test_eager_mode.py, mars/tests/test_session.py, mars/utils.py, setup.py
This PR masks the first two bits of mumur hash result to ensure the result hex string has a letter prefix. So, all the keys will be valid Python identifiers.
BTW, it fixes some minor bugs of Ray executor.
Fixes #3189 
Fixes #3188 
Fixes #3182 
Fixes #3187 
Fixes #3191
=> Ensure key is a valid Python identifier

docs/source/reference/tensor/special.rst, mars/lib/sparse/__init__.py, mars/lib/sparse/array.py, mars/tensor/special/__init__.py, mars/tensor/special/airy.py, mars/tensor/special/tests/test_special.py, mars/tensor/special/tests/test_special_execution.py
The PR is implements all airy functions except for ai_zeros and bi_zeros.
Attempts to fixes #750
=> Implement airy functions (except the `ai_zeros` and `bi_zeros` functions)

.github/dependabot.yml
Disable version updates for dependabot, given docs at https://docs.github.com/cn/code-security/dependabot/dependabot-security-updates/configuring-dependabot-security-updates .
Fixes #xxxx
=> Disable version updates for dependabot

azure-pipelines.yml, mars/deploy/oscar/ray.py, mars/oscar/backends/core.py, mars/oscar/backends/ray/backend.py
The memory leak is because when starting session by the `new_ray_session`, the global router is not set. There is a `_set_global_router` in ActorPoolBase::create, but the `new_ray_session` calls the create method in Ray actor. So, driver still has empty global router.
The memory leak details:
1. `new_ray_session` has not called the `Router.set_instance`.
2. Each Mars actor call invokes `Router.get_instance_or_empty()`, a new Router instance will be created.
3. The Router instance is always a new one, then `router.get_client(...)` creates a new client instance in `ActorCaller`.
4. The `asyncio.create_task(self._listen(client))` creates a new coroutine `_listen`.
5. The `_listen` coroutine captures the returned `ResultMessage` in  frame.
Before
```
[ Top 10 differences ] …
```
=> [Ray] Fix ray memory leak

mars/services/task/execution/ray/executor.py, mars/tensor/indexing/tests/test_indexing_execution.py
This PR add ray shuffle support for operands whose reducers has inputs which are not mapper outputs such as `TensorIndexSetValue`:
Fixes #3185
#2916
=> [Ray] Support reducer has inputs which isn't mapper

mars/services/task/supervisor/task.py
This PR make `set_subtask_result` concurrent by releasing actor lock when `set_subtask_result`
Fixes #xxxx
=> release actor lock when set_subtask_result

mars/dataframe/base/apply.py, mars/dataframe/groupby/apply.py, mars/services/task/execution/ray/executor.py, mars/tests/test_utils.py, mars/utils.py
This PR add func key cache to avoid duplicate func serialization when generate apply key which will be costly when func capture some big objects 
Fixes #xxxx
=> Refine apply key generation

mars/services/task/execution/mars/executor.py, mars/services/task/execution/ray/config.py, mars/services/task/execution/ray/executor.py, mars/services/task/execution/ray/tests/test_ray_execution_backend.py
Mars does not set the `num_cpus` for subtask execution, so it uses the Ray cluster's default `num_cpus` of normal task. The `num_cpus` affects Ray scheduling, so we should provide an option to set the `num_cpus`.
Fixes #xxxx
=> [Ray] Configurable subtask num_cpus

LICENSE, benchmarks/asv_bench/benchmarks/serialize.py, docs/source/locale/zh_CN/LC_MESSAGES/reference/tensor/generated/mars.tensor.array.po, docs/source/locale/zh_CN/LC_MESSAGES/user_guide/tensor/generated/mars.tensor.array.po, mars/core/entity/chunks.py, mars/learn/linear_model/tests/test_base.py, mars/services/task/execution/ray/executor.py, mars/tensor/base/tests/test_base_execution.py, mars/tensor/base/unique.py, mars/tensor/datasource/array.py
This PR add shuffle support for operands whose mapper produce outputs which isn't shuffle blocks. In traditional map-reduce paradigm, all outputs of a mapper operand will be shuffle blocks, and used by downstream reducers. But in mars , operands such as `TensorUnique` will produce final results such as `unique index` in mapper stage too, those results are not mapper blocks, which need special handling in ray-task based shuffle.
Fixes #3221
=> [Shuffle] Support shuffle operands mapper whose outputs aren't mapper blocks

mars/dataframe/sort/psrs.py, mars/dataframe/sort/tests/test_sort_execution.py
The numpy array is immutable if it is got from shared memory. But, pandas < 1.4 has item setting bugs: https://github.com/pandas-dev/pandas/pull/43406.
pandas >= 1.4.x has fixed this bug. So, this PR is to make the Ray backend works with pandas < 1.4
``` python
import pandas as pd
import numpy as np
a = np.arange(2)
a.setflags(write=False)
df = pd.DataFrame(a, columns=["a"])
df["a"] = -df["a"]
assert a[1] > 0  # The original array is immutable.
assert df.iloc[1]["a"] < 0  # The df column is a copy one.
```
This code raises a ValueError in pandas < 1.4, but works in pandas >= 1.4
``` python
Traceback (most recent call last):
File "/home/admin/Work/mars/t2.py", line 9, in <module>
df["a"] = -df["a"]
File "/home/admin/.pyenv/versions/3.8.13/lib/python3.8/site-packages/pandas/core/frame.py", …
```
=> Fix dataframe sort_values with multiple ascendings bug in pandas < 1.4

.github/workflows/benchmark-ci.yml, mars/deploy/oscar/session.py, mars/deploy/oscar/tests/check_enabled_config.yml, mars/deploy/oscar/tests/test_local.py, mars/serialization/serializables/core.py, mars/serialization/serializables/field.py, mars/services/lifecycle/supervisor/tests/test_tracker.py, mars/services/lifecycle/supervisor/tracker.py, mars/services/task/api/core.py, mars/services/task/api/oscar.py, mars/services/task/api/web.py, mars/services/task/config.py, mars/services/task/core.py, mars/services/task/supervisor/manager.py, mars/services/task/supervisor/service.py, mars/services/task/supervisor/task.py, mars/services/task/supervisor/tests/test_task_manager.py, mars/utils.py, setup.cfg
All the TaskProcessorActors, TaskProcessors and related contexts, graphs are not GC.  This PR is to GC the task services by lifecycle.
- New config `task.default_config.reserved_finish_tasks`, default value is 10.
https://github.com/mars-project/mars/issues/3192
https://github.com/mars-project/mars/issues/3236
=> Lifecycle gc task service

mars/dataframe/indexing/loc.py, mars/dataframe/indexing/tests/test_indexing_execution.py
Mars loc will use iloc for some slice inputs, but the loc and iloc bounds are different,
- loc[m:n], m and n are included
- iloc[m:n], m is included, n is excluded
Fixes https://github.com/mars-project/mars/issues/2584
=> Fix dataframe loc with slice returns incorrect results

mars/dataframe/indexing/setitem.py, mars/dataframe/indexing/tests/test_indexing_execution.py
The dataframe setitem may get incorrect results, the columns value are mismatch the column names. The bug is highly reproduced when all the conditions are met:
- set item with multiple columns
- some columns are exist in the target dataframe
- target dataframe has multiple chunks
Fixes https://github.com/mars-project/mars/issues/3235
=> Fix dataframe setitem bugs when partial indexes exist in target dataframe

mars/dataframe/indexing/tests/test_indexing_execution.py, mars/services/task/analyzer/analyzer.py, mars/services/task/analyzer/fusion.py
Mars coloring-based fusion algorithm may fuse multiple mapper subtasks of different shuffles into one subtask, which conflict with `ShuffleFetchType.FETCH_BY_INDEX` shuffle block resolution mode.  In `ShuffleFetchType.FETCH_BY_INDEX` shuffle block resolution mode, shuffle data is resolved by index. If one subtask contains shuffle mapper of different shuffle, current resolution mode won't work.
One solution is adding second-level index to `ShuffleManager` to work around this. It's complicated and not compatible with push-based shuffle and other shuffle system such as [CloudShuffleService](https://github.com/bytedance/CloudShuffleService)、[alibaba/RemoteShuffleService](https://github.com/alibaba/RemoteShuffleService)、[Firestorm](https://github.com/Tencent/Firestorm). 
Considering very …
=> [Shuffle] isolate mappers in different subtasks for fetch_by_index mode

mars/_utils.pxd, mars/_utils.pyx, mars/conftest.py, mars/deploy/oscar/tests/test_ray.py, mars/deploy/oscar/tests/test_ray_dag_failover.py, mars/oscar/backends/ray/communication.py, mars/oscar/backends/ray/driver.py, mars/oscar/backends/ray/pool.py, mars/oscar/backends/ray/tests/test_ray_actor_context.py, mars/serialization/core.pyx, mars/serialization/ray.py, mars/serialization/tests/test_serial.py, mars/tests/test_utils.py, mars/utils.py
Mars serializers are not compatible with Ray serializers because Ray needs to dispatch `ActorHandle` and `ObjectRef` to Ray's serializer for reference counting. But, some `ActorHandle` and `ObjectRef` are nested in objects, then we needs to register object type to RaySerializer which is not compatible with Mars object type serializer.
This PR allows Mars to register multile serializers to one type, then Ray serializers are compatible with Mars serializers. We don't needs to `register_ray_serializers` and `unregister_ray_serializers`.
Fixes #xxxx
=> TypeDispatcher support one type multiple serializers

ci/reload-env.sh, mars/deploy/oscar/tests/test_ray_scheduling.py, mars/services/scheduling/api/oscar.py, mars/services/scheduling/supervisor/autoscale.py, mars/services/scheduling/supervisor/service.py, mars/services/subtask/core.py, mars/services/subtask/worker/processor.py, mars/services/task/analyzer/analyzer.py, mars/services/task/analyzer/tests/test_analyzer.py, mars/services/task/execution/mars/stage.py, mars/services/task/execution/ray/shuffle.py
This PR skip store shuffle object refs to reduce meta overhead and supervisor serialization bottleneck by disable autoscale-in when shuffle is executing.
#2916
=> [Shuffle] Skip store shuffle object refs to reduce meta overhead

mars/services/task/supervisor/graph_visualizer.py, mars/services/task/supervisor/processor.py, mars/services/task/supervisor/tests/test_task_manager.py
Currently, dump_subtask_graph feature is only available for mars backend. This PR makes it work for all backends.
Fixes #xxxx
=> Dump subtask graph for all backends

mars/optimization/logical/common/column_pruning.py, mars/optimization/logical/common/head.py, mars/optimization/logical/core.py
OptimizationRule has a cache that referenced optimized graphs. This PR removes the global cache.
Fixes https://github.com/mars-project/mars/issues/3192
=> Fix optimization rule memory leak

mars/dataframe/datasource/read_csv.py, mars/lib/filesystem/__init__.py, mars/lib/filesystem/core.py, mars/lib/filesystem/s3.py
- Add S3 support _(The `s3fs` and `fsspec` Python packages are required)_.
An example to read csv from s3.
```python
import mars
mars.new_session()
mdf = md.read_csv("s3://bucket/example.csv", index_col=0, storage_options={
"client_kwargs": {
"endpoint_url": "http://192.168.1.12:9000",
"aws_access_key_id": "RwDeqMoctbLG3yly",
"aws_secret_access_key": "uwinWm1hTAGJ6Wnipa4tbE4SwO3Mx6Ek",
}})
mdf = md.read_csv("s3://bucket/example.csv", index_col=0)
r = mdf.head(1000).execute()
print(r)
```
Fixes #xxxx
=> Add S3 support

mars/tensor/arithmetic/frexp.py, mars/tensor/arithmetic/tests/test_arithmetic_execution.py
The `numpy.frexp` writes to the `out1`, `out2` if `out1`, `out2` are passed as input args. e.g. `numpy.frexp(x, out1, out2)`. But, almost all the cases that the `out1` and `out2` are got from the shared memory, then the `out1` and `out2` are immutable. So, this PR uses `out1, out2 = numpy.frexp(x)` instead of `numpy.frexp(x, out1, out2)`.
Fixes https://github.com/mars-project/mars/issues/3257
=> Fix tensor frexp

mars/deploy/oscar/session.py, mars/oscar/backends/ray/communication.py, setup.cfg
1. Optimize the display of task process bar
With the optimization of task process bar, it will print as follows when running the codes:
```python
import mars
import mars.tensor as mt
mars.new_session()
df = md.DataFrame(
mt.random.randint(1, 100, size=(1000, 10), chunk_size=(130, 5)),
columns=list("ABCDEFGHIJ"),
)
df.describe().execute()
```
```
6%|████▎                                                                    |   5.92/100 [00:02<00:15,  5.91it/s]
21%|███████████████▍                                                         |  21.07/100 [00:03<00:06, 11.34it/s]
33%|███████████████████████▉                                                 |  32.76/100 [00:04<00:05, 11.49it/s]
58%|██████████████████████████████████████████                               | …
```
=> Optimize the display of task process bar

mars/dataframe/utils.py, mars/deploy/oscar/local.py, mars/deploy/oscar/ray.py, mars/deploy/oscar/tests/modules/check_ray_remote_function_options.py, mars/deploy/oscar/tests/test_ray_client.py, mars/deploy/oscar/tests/test_ray_cluster_standalone.py, mars/lib/aio/isolation.py, mars/oscar/backends/ray/communication.py, mars/services/task/execution/ray/config.py, mars/services/task/execution/ray/executor.py
- Spread scheduling subtasks with empty dependencies.
- `mars.new_ray_session` support `supervisor_cpu`.
- `mars.new_ray_session(backend="ray", worker_cpu=n)` can specify subtask num_cpus to n.
- Log large messages (serialized bytes > 1GB).
- Refine logs of clean func / restore func.
- Fix new_ray_session bugs.
Fixes https://github.com/mars-project/mars/issues/3279 https://github.com/mars-project/mars/issues/3280
=> [Ray] Spread scheduling subtasks with empty dependencies

mars/core/base.py, mars/deploy/oscar/tests/test_local.py, mars/utils.py
There is a GraphContainsCycleError when concatenating two DataFrame in which there are same fetch chunks.
Fixes #3284
=> Fix `md.concat` error when there are same fetch chunk data

.github/workflows/os-compat-ci.yml, azure-pipelines.yml, mars/dataframe/reduction/tests/test_reduction_execution.py, mars/deploy/oscar/tests/test_ray_dag.py, mars/services/task/execution/ray/config.py, mars/services/task/execution/ray/executor.py, mars/services/task/execution/ray/shuffle.py, mars/services/task/execution/ray/tests/test_ray_execution_backend.py, mars/services/task/supervisor/tests/test_task_manager.py
Ray executor submits subtasks do not suspend current aio task even await for loading subtask inputs. This could cause the GC is delayed to the submitting finish. This PR makes the executor switches the event loop to the GC aio task when submitting subtasks, reduces the load of object store. 
Fixes https://github.com/mars-project/mars/issues/3216, Fixes https://github.com/mars-project/mars/issues/3290
=> [Ray] Improve Ray executor GC

azure-pipelines.yml, mars/services/task/execution/ray/executor.py, mars/services/task/execution/ray/tests/test_ray_execution_backend.py, mars/services/task/supervisor/manager.py
Ray executor does not gc the input data and the intermediate data of subtask, then the memory usage of worker may be very high. This PR gc the chunk data after every operand finish.
- The input data are referenced by Ray core worker in _raylet.pyx, we can't gc them. 
Fixes #xxxx
=> [Ray] Implement Ray executor subtask GC

mars/deploy/oscar/ray.py, mars/services/task/execution/ray/config.py, mars/services/task/execution/ray/executor.py, mars/services/task/execution/ray/tests/test_ray_execution_backend.py
- Support `worker_mem` for ray executor.
```python
mars.new_ray_session(supervisor_cpu=16, worker_cpu=4, worker_mem=6 * 1024**3)
```
- Reduce CPU cost of supervisor GC.
- Use set + list instead of OrderedSet. The OrderedSet may be hangs at accessing by index sometimes.
- Remove `subtask_id` tag of ray executor metrics to reduce the agg results.
Fixes #xxxx
=> [Ray] Support worker_mem for ray executor

mars/core/graph/builder/chunk.py, mars/dataframe/base/rechunk.py, mars/dataframe/base/tests/test_base_execution.py, mars/dataframe/sort/core.py, mars/dataframe/utils.py, mars/services/task/supervisor/preprocessor.py
Some chunks are copied when tiling (e.g. copied chunks with new chunk index), these copied chunks can't be treated as executed, so they will be regenerated. This PR use chunk key instead of chunk object to check whether it is executed.
Fixes https://github.com/mars-project/mars/issues/3299
=> Fix duplicate execution

mars/contrib/dask/tests/test_dask.py, mars/learn/cluster/tests/test_k_means.py, mars/learn/metrics/pairwise/tests/test_pariwise_distances.py, mars/learn/metrics/tests/test_ranking.py, mars/learn/neighbors/tests/test_nearest_neighbors.py, mars/learn/semi_supervised/tests/test_label_propagation.py, mars/services/subtask/core.py, mars/services/task/core.py, mars/services/task/execution/ray/config.py, mars/services/task/execution/ray/executor.py, mars/services/task/execution/ray/tests/test_ray_execution_backend.py
- Detect slow subtasks for Ray executor.
- The unready subtasks will be checked by the historical durations in the same logic key. So, if a slow task has an unique logic key, then it can't be detected. 
- Fix scikit-learn 1.2.0 compatibility issue.
Fixes #xxxx
=> [Ray] Basic slow subtask detection

mars/lib/filesystem/base.py, mars/lib/filesystem/core.py, mars/lib/filesystem/s3.py, mars/lib/filesystem/tests/test_s3.py
Fix "client_kwargs" not works for s3 storage options.
Fixes #xxxx
=> Fix s3 client kwargs

mars/dataframe/datasource/read_raydataset.py, mars/dataframe/datasource/tests/test_datasource.py
Fix read_ray_dataset is not compatible with the latest Ray
Fixes https://github.com/mars-project/mars/issues/3317
=> Fix read_ray_dataset is not compatible with the latest Ray

.github/workflows/platform-ci.yml, mars/dataframe/contrib/raydataset/tests/test_mldataset.py, mars/dataframe/datasource/tests/test_datasource.py, mars/dataframe/datasource/tests/test_datasource_execution.py, mars/dataframe/utils.py
- Unpin xgboost_ray version when CI
- Use latest ray when CI
#3318 Fix read_ray_dataset is not compatible with the latest Ray
=> Unpin version of xgboost_ray and use latest ray when CI

mars/dataframe/datasource/from_vineyard.py, mars/tensor/datasource/from_vineyard.py
Fixes bugs in processing chunk index of vineyard's global dataframe.
The global dataframe may be generated by upstream systems and is row-splitted without a valid global chunk_index value.
N/A
=> Vineyard: from unordered chunks.

.github/workflows/platform-ci.yml, mars/dataframe/datasource/read_sql.py
The `xgboost_ray==0.1.14` has compatibility issue with the latest Ray. This PR
- Pin `xgboost_ray<0.1.14`.
- DataFrameReadSQL compatible with `SQLAlchemy>2`.
Fixes #xxxx
=> Pin xgboost_ray<0.1.14

mars/tensor/linalg/norm.py
In `tile()` of `TensorNorm`, input chunk will be copied before recursively tiling, which leads to unnecessary re-execution of historical DAG nodes or crashing when encountering `Fetch` OP.
This commit prevents the input chunk from copying.
=> fix tiling of norm

mars/lib/nvutils.py, mars/services/task/execution/ray/executor.py
Fixes the long standing error, i.e., `ValueError: bytes is not a 16-char string`, during gpu/cuda init. 
Probably:
Fixes: https://github.com/mars-project/mars/issues/3176.
Fixes: https://github.com/mars-project/mars/issues/3231.
Fixes: https://github.com/mars-project/mars/issues/3325.
Coping from https://github.com/xprobe-inc/xorbits/pull/242. All credits belong to them.
Since Mars hasn't public GPU CI, I would test it on our internal GPU cluster later.
DON'T MERGE it temporarily, since I have to rebase it after https://github.com/mars-project/mars/pull/3336 is merged.
=> [BUG] Fix the long standing `ValueError` during the GPU/CUDA initialization

mars/dataframe/core.py, mars/dataframe/datasource/index.py, mars/dataframe/datasource/tests/test_datasource.py
The `names` field in a `MultiIndexValue` is None, but it should be equal with the passed ones of `MultiIndex`
=> Fix incorrect 'names' field of MultiIndexValue of DataFrameSource
