requirements-dev.txt

add requirements-dev.txt including cython(#6)

---

mars/web/session.py
mars/web/tests/test_api.py

Fix TimeoutError when it is not specified

Fix TimeoutError when it is not specified

---

mars/tensor/execution/tests/test_linalg_execute.py
mars/tensor/execution/tests/test_reduction_execute.py

Fix test case.
resolve #10  #13  #12

fix test case

---

mars/tensor/execution/tests/test_reduction_execute.py

Fix arg reduction. 
resolve #12

Fix arg reduction test

---

mars/web/dashboard.py
mars/web/tests/test_api.py

Fix UI dashboard and check UI requests in test_api.

Fix web UI dashboard

---

.coveragerc-tensor
.travis.yml
README.rst
bin/travis-upload.sh
mars/distributor.py
mars/lib/gipc.pyx
mars/lib/sparse/coo.py
mars/node_info.py
mars/utils.py

Fix mars/tensor coverage issue by applying different configurations
N/A

fix mars/tensor coverage issue by applying different configurations

---

README.rst
docs/source/install.rst

Add installation, instructions and getting involved in README, add local cluster docs

Add installation, instructions and getting involved in README, add local cluster docs

---

mars/compat/__init__.py
mars/lib/futures/_base.py
mars/lib/lib_utils.py
mars/utils.py
mars/worker/tests/test_transfer.py

Remove redundant code to increase coverage, including PlasmaProcessHelper and code implemented both in .py and .pyx.
N/A

Remove redundant code to increase coverage

---

mars/fuse.pyx
mars/graph.pyx
setup.py

Separate the fuse logic from graph into a single fuse.pyx file on the top directory.
This is the first step for a better fuse, we separate the code first.
Resolve #39

Make fuse logic out of graph

---

mars/scheduler/graph.py
mars/scheduler/resource.py
mars/web/server.py
mars/web/templates/task_list.html
mars/web/templates/worker_detail.html
mars/web/templates/worker_list.html
mars/worker/status.py

Pass timestamp instead of formatted date time string.
Fixes https://github.com/mars-project/mars/issues/67.

Pass timestamps as status

---

mars/scheduler/chunkmeta.py

Fix repeated deletion of kv-store item in chunk meta management
Fixes #72

Fix repeat deletion of kv item

---

.travis.yml
bin/download-etcd.sh
mars/api.py
mars/base_app.py
mars/kvstore.py
mars/lib/gipc.pyx
mars/node_info.py
mars/resource.py
mars/scheduler/kvstore.py
mars/scheduler/tests/test_kvstore.py
mars/serialize/__init__.py
mars/serialize/dataserializer.py
mars/session.py
mars/tests/core.py
mars/tests/test_kvstore.py
mars/tests/test_resource.py
mars/web/__init__.py
mars/web/api.py
mars/web/server.py
mars/web/session.py
mars/web/tests/test_api.py
mars/worker/status.py

This pr adds cases for kvstore on etcd and task web page. Happy new yr, Mars.
NA

Add test cases for etcd and tasks web page

---

mars/worker/execution.py

Fix AttributeError on distributed environment for multiple workers.
NA

Fix AttributeError on get_workers

---

mars/scheduler/graph.py
mars/scheduler/tests/test_graph.py
mars/scheduler/tests/test_main.py

Fix IndexError on summation of sliced array with same index range by using tensor id as keys as unique keys on tiling.
Fixes #99

Fix summation on slicing on an array with same range

---

mars/scheduler/graph.py
mars/scheduler/tests/test_graph.py
mars/scheduler/tests/test_main.py

[BACKPORT] Fix summation on slicing on an array with same range

---

mars/deploy/local/tests/test_cluster.py
mars/tensor/expressions/indexing/getitem.py
mars/tensor/expressions/indexing/setitem.py
mars/tensor/expressions/tests/test_indexing.py

[BACKPORT] Fix setitem and getitem generate same operand key (#101)

---

mars/graph.pyx
mars/tensor/core.py

[BACKPORT] Use property instead of weak-key dict to store cix (#107)

---

mars/scheduler/graph.py
mars/scheduler/tests/test_graph.py

Fix compose failure after #103 as code in it mistakenly recognize every node as target. A test case also added.
NA

Fix compose failure after #103

---

mars/scheduler/graph.py
mars/scheduler/tests/test_graph.py

[BACKPORT] Fix compose failure after #103 (#111)

---

.coveragerc
.coveragerc-tensor
.travis.yml
bin/fix-gevent-cov.sh
mars/actors/core.pyx
mars/actors/pool/gevent_pool.pyx
mars/actors/pool/messages.pyx
mars/graph.pyx
mars/tests/test_graph.py
mars/tests/test_utils.py
mars/utils_c.pyx
setup.py

Add coverage for *.pyx. Given that https://github.com/cython/cython/pull/2784 has not been merged by Cython, we use a temporarily solution by removing *.c under gevent path (fix-gevent-cov.sh). What's more, ``binding`` is configured to increase the coverage of ``cpdef``s, as is referred to in https://github.com/cython/cython/issues/1461. These shall be removed once Cython resolves the issues.
N/A.

Add cython coverage

---

mars/tensor/core.py
mars/tests/test_session.py

[BACKPORT] Implement __array__ protocol for Tensor (#126)

---

mars/scheduler/tests/test_main.py
mars/worker/execution.py

Fixes attribute error on v0.1.
Fixes #129.

Fix worker meta error on v0.1

---

mars/actors/pool/tests/test_gevent_pool.py
mars/graph.pyx
mars/scheduler/graph.py
mars/scheduler/operand.py
mars/scheduler/tests/test_graph.py
mars/scheduler/tests/test_main.py
mars/serialize/tests/test_serialize.py
mars/serialize/tests/testser.proto
mars/serialize/tests/testser_pb2.py

Add test cases for multiple workers & improve pyx coverage.
Fixes #131

Add test cases for multiple workers

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/feature_request.md
.github/ISSUE_TEMPLATE/other.md
CONTRIBUTING.rst

Contributing rules should be seen on every issue templates.
NA

Refine contributing rules and show that on every issue template

---

.travis.yml
MANIFEST.in
requirements-extra.txt

Include requirements-extra.txt and requirements-dev.txt in MANIFEST.in. Global include pyx and pxd, exclude c file in MANIFEST.in.
Fix file not found mentioned in #152

Include requirements-*.txt, pyx and pxd, exclude c file in MANIFEST.in

---

mars/compat/__init__.py
mars/worker/__main__.py
mars/worker/service.py

[BACKPORT] Fix --phy-mem arg error and BrokenPipeErrors under Python 2.7 (#159)

---

.travis.yml

[BACKPORT] Fix CI failure under python 2.7 in osx

---

mars/core.py
mars/dataframe/core.py
mars/dataframe/expressions/tests/test_datasource.py
mars/tensor/core.py
mars/tensor/expressions/tests/test_core.py

Fix bug when serializing a graph with a tiled tensor.
Fixes #190

Fix serializing graph with a tiled tensor

---

mars/base_app.py
mars/cluster_info.py
mars/core.py
mars/lib/gipc.pyx
mars/operands/random.py
mars/scheduler/service.py
mars/scheduler/tests/test_kvstore.py
mars/scheduler/tests/test_main.py
mars/tensor/core.py
mars/worker/execution.py
mars/worker/service.py

[BACKPORT] Fix starting with multiple schedulers with --schedulers (#202)

---

mars/base_app.py
mars/deploy/local/core.py
mars/deploy/local/tests/test_cluster.py
mars/lib/gipc.pyx
mars/scheduler/chunkmeta.py
mars/tensor/expressions/base/expand_dims.py
mars/tensor/expressions/random/dirichlet.py
mars/worker/service.py

[BACKPORT] Fix process clean up when local cluster terminates (#206)

---

README.rst
docs/source/index.rst
docs/source/tensor/eager-mode.rst
docs/source/tensor/index.rst
mars/config.py
mars/core.py
mars/deploy/local/tests/test_cluster.py
mars/executor.py
mars/session.py
mars/tensor/core.py
mars/tensor/execution/tests/test_arithmetic_execute.py
mars/tensor/execution/tests/test_numexpr_execute.py
mars/tensor/expressions/arithmetic/clip.py
mars/tensor/expressions/arithmetic/core.py
mars/tensor/expressions/base/split.py
mars/tensor/expressions/core.py
mars/tensor/expressions/indexing/getitem.py
mars/tensor/expressions/indexing/nonzero.py
mars/tensor/expressions/indexing/setitem.py
mars/tensor/expressions/indexing/unravel_index.py
mars/tensor/expressions/linalg/lu.py
mars/tensor/expressions/linalg/qr.py
mars/tensor/expressions/linalg/svd.py
mars/tensor/expressions/random/core.py
mars/tensor/expressions/reduction/core.py
mars/tensor/expressions/utils.py
mars/tests/test_eager_mode.py
mars/tests/test_utils.py
mars/tiles.py
mars/utils.py

Support eager mode for `mars.tensor`. Trigger execution after `new_tensors` when create tensors.
resolve #194

Support eager mode

---

mars/actors/pool/gevent_pool.pyx
mars/actors/pool/messages.pyx
mars/actors/pool/tests/test_gevent_pool.py
mars/errors.py
mars/graph.pyx
mars/scheduler/analyzer.py
mars/scheduler/graph.py
mars/scheduler/kvstore.py
mars/scheduler/operand.py
mars/scheduler/tests/test_analyzer.py
mars/scheduler/tests/test_graph.py
mars/scheduler/tests/test_kvstore.py
mars/scheduler/tests/test_operand_exec.py
mars/scheduler/tests/test_operand_ut.py
mars/tests/test_graph.py
mars/worker/tests/test_execution.py

Separate graph analytics from GraphActor into a separate GraphAnalyzer (this is not an actor). This facilitates further optimization and also paves way for worker-level failover (#5).
Fixes #196

Separate graph analyzer from graph and add test cases

---

mars/scheduler/tests/test_kvstore.py
mars/scheduler/tests/test_main.py
mars/tensor/core.py
mars/tensor/expressions/tests/test_base.py

Back port part of #226 to resolve #233 in v0.1
Fixes #233

[BACKPORT] Add stub for execute() and __dir__ support in Tensor to facilitate code completion

---

mars/lib/sparse/__init__.py
mars/lib/sparse/array.py
mars/lib/sparse/core.py
mars/lib/sparse/matrix.py
mars/lib/sparse/tests/test_sparse.py
mars/lib/sparse/vector.py
mars/operands/linalg.py
mars/serialize/dataserializer.py
mars/serialize/tests/test_serialize.py
mars/tensor/execution/linalg.py
mars/tensor/execution/tests/test_linalg_execute.py
mars/tensor/expressions/arithmetic/core.py
mars/tensor/expressions/arithmetic/utils.py
mars/tensor/expressions/linalg/inv.py
mars/tensor/expressions/linalg/lu.py
mars/tensor/expressions/linalg/solve_triangular.py
mars/tensor/expressions/tests/test_linalg.py

[BACKPORT] Support sparse for part of linalg operands.

---

mars/tensor/execution/tests/test_linalg_execute.py
mars/tensor/expressions/linalg/inv.py

[BACKPORT] Fix TensorInv tiles for input tensor with one chunk

---

mars/lib/sparse/__init__.py
mars/lib/sparse/matrix.py
mars/tensor/execution/datasource.py
mars/tensor/execution/tests/test_datasource_execute.py
mars/tensor/expressions/datasource/array.py
mars/tensor/expressions/datasource/diag.py
mars/tensor/expressions/tests/test_core.py

Support `mt.diag` on sparse 2d tensor.
Resolves #252

Support mt.diag on sparse 2d tensor

---

mars/executor.py
mars/scheduler/graph.py
mars/tensor/execution/core.py
mars/tensor/execution/datasource.py
mars/tensor/execution/fetch.py
mars/tensor/expressions/datasource/__init__.py
mars/tensor/expressions/datasource/core.py
mars/tensor/expressions/fetch/__init__.py
mars/tensor/expressions/fetch/core.py
mars/tensor/expressions/tests/test_arithmetic.py
mars/tensor/expressions/utils.py
mars/tests/test_utils.py
mars/utils.py
mars/worker/calc.py
mars/worker/execution.py
mars/worker/tests/test_execution.py
mars/worker/utils.py

Move FETCH into standalone package, allowing ``TensorFetch`` being a superclass of ``Fetch``.
Fixes #244

Move fetch into standalone package

---

mars/actors/pool/gevent_pool.pyx
mars/actors/pool/tests/test_gevent_pool.py
mars/lib/sparse/__init__.py
mars/lib/sparse/matrix.py
mars/tensor/execution/datasource.py
mars/tensor/execution/tests/test_datasource_execute.py
mars/tensor/expressions/datasource/array.py
mars/tensor/expressions/datasource/diag.py
mars/tensor/expressions/tests/test_core.py

[BACKPORT] Support mt.diag on sparse 2d tensor

---

mars/scheduler/assigner.py
mars/scheduler/graph.py
mars/scheduler/tests/test_assigner.py
mars/scheduler/tests/test_graph.py
mars/tensor/core.py
mars/tensor/execution/arithmetic.py
mars/tensor/execution/core.py
mars/tensor/execution/cp.py
mars/tensor/execution/indexing.py
mars/tensor/execution/ne.py
mars/tensor/execution/tests/test_index_execute.py
mars/tensor/execution/tests/test_linalg_execute.py
mars/tensor/execution/tests/test_numexpr_execute.py
mars/tensor/execution/utils.py
mars/tensor/expressions/base/argwhere.py
mars/tensor/expressions/base/repeat.py
mars/tensor/expressions/fuse/core.py
mars/tensor/expressions/indexing/getitem.py
mars/tensor/expressions/indexing/nonzero.py
mars/tensor/expressions/tests/test_base.py
mars/tensor/expressions/tests/test_indexing.py
mars/tensor/expressions/utils.py
mars/worker/chunkstore.py
mars/worker/execution.py

Backport of #266 (rough_size part)
NA

[BACKPORT] Remove rough_size from tensor (#266)

---

mars/deploy/local/tests/test_cluster.py
mars/scheduler/graph.py
mars/tensor/execution/core.py
mars/tensor/expressions/datasource/core.py
mars/utils.py

[BACKPORT]  Add sparse property for fetch operand (#279)

---

mars/fuse.pyx
mars/tensor/expressions/fuse/core.py
mars/tensor/expressions/tests/test_fuse.py

Add sparse property for fuse operand and add some tests for fuse.
fixes #263

Add sparse property for fuse operand

---

mars/api.py
mars/deploy/local/session.py
mars/deploy/local/tests/test_cluster.py
mars/scheduler/graph.py
mars/scheduler/session.py
mars/tensor/execution/core.py
mars/tests/test_session.py
mars/web/api.py
mars/web/session.py

[BACKPORT] Support execute graph without fusion

---

mars/tensor/execution/tests/test_linalg_execute.py
mars/tensor/expressions/linalg/lu.py
mars/tensor/expressions/tests/test_linalg.py

[BACKPORT] Remove chunk square limitation in lu decomposition

---

.travis.yml
mars/scheduler/analyzer.py
mars/scheduler/graph.py
mars/scheduler/operands/base.py
mars/scheduler/operands/common.py
mars/scheduler/tests/test_analyzer.py
mars/scheduler/tests/test_graph.py
mars/utils.py
mars/worker/chunkholder.py
mars/worker/execution.py
mars/worker/utils.py

1. Fix long latency caused by synchronous ``has_actor``
2. Simplify operand creation by passing enum values directly
3. Allow specifying node keys to assign workers
4. Fix conflict of ``handle_process_down`` method between ``WorkerActor`` and ``WorkerDaemonActor``
Fixes #300

Fix long latency caused by synchronous has_actor

---

mars/tensor/expressions/reduction/core.py
mars/tensor/expressions/tests/test_reduction.py
mars/tensor/expressions/utils.py

The old version fails to handle negative axis, fixed it.
Fixes #303

Validate axis for reduction

---

.travis.yml
mars/tensor/expressions/reduction/core.py
mars/tensor/expressions/tests/test_reduction.py
mars/tensor/expressions/utils.py

[BACKPORT] Validate axis for reduction

---

mars/tensor/execution/core.py
mars/tensor/execution/tests/test_core_execute.py

Manual back-port of #309 (review needed)
NA

[BACKPORT] Fix execution size for fuse nodes (#309)

---

mars/tensor/execution/arithmetic.py
mars/tensor/execution/tests/test_arithmetic_execute.py
mars/tensor/expressions/arithmetic/core.py

[BACKPORT] Fix arithmetic operator with `where` (#314)

---

.travis.yml
appveyor.yml
mars/tensor/core.py
mars/tensor/execution/tests/test_core_execute.py

Implement `__array_function__` protocol according to [NEP-18](https://www.numpy.org/neps/nep-0018-array-function-protocol.html).
Resolves #331

Implement __array_function__ protocol

---

.travis.yml
appveyor.yml
mars/tensor/core.py
mars/tensor/execution/tests/test_core_execute.py

[BACKPORT] Implement __array_function__ protocol

---

mars/core.py
mars/deploy/local/tests/test_cluster.py
mars/operands/random.py

Do some special handling when build coarse-grained graph.
fixes #297

Support execute tiled tensor in distributed mode

---

mars/core.py
mars/deploy/local/session.py
mars/deploy/local/tests/test_cluster.py
mars/operands/random.py
mars/tensor/core.py
mars/tensor/expressions/core.py

[BACKPORT] Support execute tiled tensor in distributed mode (#322)

---

mars/promise.py
mars/tests/test_promise.py

Sync promise.py in v0.1 with v0.2 to solve arg missing issue in test_transfer.
Related PRs: #88, #89, #119, #207, #287
NA

Sync promise.py in v0.1 with v0.2 to solve arg missing issue

---

mars/config.py
mars/deploy/local/core.py
mars/deploy/local/session.py
mars/deploy/local/tests/test_cluster.py
mars/kvstore.py
mars/lib/sparse/core.py
mars/scheduler/__main__.py
mars/tensor/execution/array.py
mars/tensor/execution/fft.py
mars/tensor/execution/linalg.py
mars/web/session.py
mars/worker/__main__.py
mars/worker/chunkstore.py
mars/worker/service.py
mars/worker/tests/test_service.py

Backport #170 while keeping ``start_service`` and ``stop_service`` to maintain compatibility.
NA

[BACKPORT] Decouple services from applications & unify worker start logic (#170)

---

mars/worker/__main__.py
mars/worker/service.py
mars/worker/status.py
mars/worker/tests/test_status.py

Worker is registered by StatusActor only when all actors started.
Fixes #342

Register worker when finish initialization

---

mars/worker/__main__.py
mars/worker/service.py
mars/worker/status.py
mars/worker/tests/test_status.py

[BACKPORT] Register worker when finish initialization (#343)

---

mars/actors/__init__.py
mars/actors/core.pxd
mars/actors/core.pyx
mars/actors/pool/gevent_pool.pyx
mars/actors/pool/tests/test_gevent_pool.py
setup.py

[BACKPORT] Support replacing actor classes given registration (#348)

---

mars/_version.py

Bump to v0.1.2

---

mars/_version.py

Bump version to 0.2.0a3

---

mars/tensor/execution/random.py
mars/tensor/execution/tests/test_random_execute.py

[BACKPORT] Add size estimator for randint (#356)

---

mars/api.py
mars/deploy/local/session.py
mars/scheduler/graph.py
mars/serialize/dataserializer.py
mars/serialize/tests/test_serialize.py
mars/session.py
mars/web/api.py
mars/web/session.py
mars/web/tests/test_api.py

Back-port #359 and also session.fetch() function in #180 to fix #361.
Fixes #361

[BACKPORT] Pass an acceptable compression list when fetching results from server

---

mars/tensor/execution/linalg.py
mars/tensor/execution/tests/test_linalg_execute.py
mars/worker/calc.py
mars/worker/quota.py
mars/worker/service.py

1. Adjust memory estimation for TensorDot: fix according to actual memory cost when inputs are dense or sparse.
2. Fix defunct hard_limit in worker by changing typo in code.
3. Simplify logging in QuotaActor.
Fixes #373 
Fixes #374

Adjust memory estimation for TensorDot & fix defunct hard_limit

---

mars/lib/mmh3_src/mmh3module.cpp
mars/worker/quota.py

Fix defunct hard_limit argument in worker, which is not fixed in #375.
Fixes #373

Fix defunct hard_limit in worker

---

mars/tensor/execution/linalg.py
mars/tensor/execution/tests/test_linalg_execute.py
mars/worker/quota.py
mars/worker/service.py

Backport of #375 (with hard_limit fixed manually)
NA

[BACKPORT] Adjust memory estimation for TensorDot % fix defunct hard_limit (#375)

---

mars/tensor/core.py
mars/tensor/execution/linalg.py
mars/tensor/execution/tests/test_linalg_execute.py
mars/tensor/expressions/core.py
mars/tensor/expressions/linalg/lu.py
mars/tensor/expressions/linalg/solve_triangular.py
mars/tensor/expressions/tests/test_linalg.py

[BACKPORT] Support non-square matrix for lu decomposition (#383)

---

mars/api.py
mars/dataframe/__init__.py
mars/dataframe/execution/tests/test_arithmetic_execution.py
mars/dataframe/expressions/__init__.py
mars/dataframe/expressions/arithmetic/core.py
mars/dataframe/expressions/utils.py
mars/dataframe/initializer.py
mars/deploy/local/session.py
mars/executor.py
mars/session.py
mars/tests/test_api.py
mars/tests/test_session.py
mars/web/api.py
mars/web/session.py

Fix bug that `min_val` of index_value or columns could be nan for chunks of DataFrame. Also add a `mars.dataframe.DataFrame` method to provide a compatible way to create a mars DataFrame, but the method does not support create from mars DataFrame or tensor yet.
Fixes #404

Fix bug that `min_val` of index_value or columns could be nan for chunks of DataFrame

---

mars/core.py
mars/deploy/local/tests/test_cluster.py
mars/scheduler/graph.py
mars/session.py
mars/utils.py

Fix errors when running dataframes with computed results by rewriting nans in nsplits with Nones.
Fixes #406

Fix executing DataFrame with Fetch operand

---

mars/deploy/local/session.py
mars/session.py

[BACKPORT] Support **kwargs in new_session (#368)

---

.gitignore
.travis.yml
mars/api.py
mars/scheduler/__init__.py
mars/scheduler/assigner.py
mars/scheduler/chunkmeta.py
mars/scheduler/graph.py
mars/scheduler/operand.py
mars/scheduler/tests/test_assigner.py
mars/scheduler/tests/test_chunkmeta.py
mars/scheduler/tests/test_operand.py
mars/scheduler/utils.py
mars/tests/test_api.py
mars/web/tests/test_api.py
mars/worker/calc.py
mars/worker/execution.py
mars/worker/transfer.py
mars/worker/utils.py

[BACKPORT] Remove central ChunkMetaActor in schedulers (#421)

---

mars/api.py
mars/config.py
mars/scheduler/tests/test_kvstore.py
mars/scheduler/tests/test_main.py
mars/serialize/dataserializer.py
mars/serialize/tests/test_serialize.py
mars/tests/core.py
mars/tests/test_kvstore.py
mars/web/api.py
mars/web/session.py
mars/web/tests/test_api.py
mars/worker/__main__.py
mars/worker/service.py
mars/worker/spill.py
mars/worker/transfer.py

[BACKPORT] Use Enum instead of numbers to specify compression types (#424)

---

mars/tensor/expressions/datasource/array.py
mars/tensor/expressions/tests/test_datasource.py

Support creating tensor from list of tensors by creating a `stack` op on those tensors.
Fixes #232

Support creating tensor from list of tensors

---

mars/_version.py

Bump version to 0.2.0b1

---

mars/tensor/expressions/datasource/array.py
mars/tensor/expressions/tests/test_datasource.py

[BACKPORT] Support creating tensor from list of tensors (#426)

---

mars/_version.py

Bump version to 0.1.3 for branch 0.1.

Bump version to 0.1.3 for branch 0.1

---

mars/dataframe/execution/arithmetic.py
mars/dataframe/execution/tests/test_arithmetic_execution.py
mars/dataframe/expressions/arithmetic/__init__.py
mars/dataframe/expressions/arithmetic/abs.py
mars/dataframe/expressions/arithmetic/add.py
mars/dataframe/expressions/arithmetic/core.py
mars/dataframe/expressions/core.py
mars/dataframe/expressions/tests/test_arithmetic.py

Support unary operations on DataFrame.
This pr is not finished yet, post it here for early feedback.
Resolves #433

Support unary ops for DataFrame.

---

mars/web/api.py
mars/web/session.py

Backport of #395, and the lost part of web session in #295

[BACKPORT] Fix defunct compose option in web session

---

mars/scheduler/graph.py
mars/scheduler/operand.py
mars/scheduler/tests/test_graph.py

[BACKPORT] Simplify building executable graph (#455)

---

.travis.yml
bin/travis-upload.sh

Build and upload wheel with `cp27-cp27m` tag in travis.
resolve #447

Build wheel for tag cp27-cp27m

---

mars/promise.py
mars/serialize/dataserializer.py
mars/serialize/tests/test_serialize.py
mars/worker/dataio.py
mars/worker/spill.py
mars/worker/tests/test_dataio.py
mars/worker/transfer.py

[BACKPORT] Fix compression types when transferring files (#459)

---

.travis.yml
bin/travis-upload.sh
mars/actors/pool/gevent_pool.pyx
mars/promise.py
mars/tests/test_promise.py

[BACKPORT] Fix promise memory issues (#474)

---

docs/source/install.rst
mars/base_app.py
mars/web/__main__.py
mars/web/tests/test_api.py

[BACKPORT] Remove --ui-port option for Mars Web (#482)

---

mars/api.py
mars/scheduler/analyzer.py
mars/scheduler/graph.py
mars/web/api.py
mars/web/server.py
mars/worker/execution.py

1. Add placement_order as a priority item.
2. Push successor into queue before releasing current task in worker.
3. Return 404 when graph actor does not exist.
Fixes #496
Fixes #497

Add placement_order as a priority item

---

mars/api.py
mars/web/api.py
mars/web/server.py

Return 404 when graph actor does not exist

---

mars/scheduler/utils.py

[BACKPORT] Specify an __order__ attribute in Enum class OperandState

---

mars/dataframe/__init__.py
mars/dataframe/core.py
mars/dataframe/execution/tests/test_arithmetic_execution.py
mars/dataframe/expressions/arithmetic/__init__.py
mars/dataframe/expressions/arithmetic/add.py

support radd for DataFrame
Resolves #507  .

Add `radd` implementation for DataFrame

---

.travis.yml
bin/travis-install-conda.sh
mars/_version.py
mars/graph.pyx
mars/scheduler/graph.py
mars/scheduler/tests/test_graph.py
mars/worker/quota.py

[BACKPORT] Callback on quota allocation failure & bump version (#516)

---

mars/config.py
mars/scheduler/operands/core.py
mars/web/server.py
mars/web/task_pages.py
mars/web/templates/worker_pages/detail.html
mars/web/templates/worker_pages/timeline.html
mars/web/tests/test_api.py
mars/web/tests/test_timeline.py
mars/web/worker_pages.py
mars/worker/__init__.py
mars/worker/calc.py
mars/worker/events.py
mars/worker/service.py
mars/worker/spill.py
mars/worker/tests/test_events.py
mars/worker/transfer.py

1. An event module is added to worker. Events can be queried by time intervals.
2. Worker timeline is added to the web based on worker events.
Fixes #528

Add support for worker timeline

---

mars/tensor/execution/tests/test_index_execute.py
mars/tensor/expressions/indexing/setitem.py
mars/tensor/expressions/tests/test_indexing.py

[BACKPORT]Fix assignment of structured data type arrays.

---

mars/executor.py

We plan to do a huge refactor described in #453 that `expressions` and `execution` directories in tensor and dataframe would be merged into one, and our execution function will apply on operand instead of chunk.
In the past, the execution registration mechanism is that:
1. If a function is registered to execute a chunk, call it.
2. If the function not found, scan all the functions, if some function is registered for a operand class, and the class is superclass of the class of destination chunk's operand, register the function for the operand's class, and then call it.
Now, the mechanism would be:
1. If a function is registered to execute an **operand**, call it.
2. If the operand has a method `execute`, call the method.
3. Same as point 2 in the past.
This PR is just a temporary PR which …

Make executor compatible with old and new execution registration mechanism

---

mars/tensor/base/broadcast_to.py
mars/tensor/datasource/array.py
mars/tensor/datasource/ones.py
mars/tensor/datasource/tests/__init__.py
mars/tensor/datasource/tests/test_array.py
mars/tensor/datasource/tests/test_array_execute.py
mars/tensor/merge/__init__.py

Add more execution function.
#453

Add more execution function

---

mars/deploy/local/tests/test_cluster.py
mars/scheduler/assigner.py
mars/scheduler/graph.py
mars/scheduler/operands/base.py
mars/scheduler/operands/common.py
mars/scheduler/operands/shuffle.py
mars/scheduler/tests/integrated/base.py
mars/scheduler/tests/integrated/op_delayer.py
mars/scheduler/tests/integrated/test_worker_failover.py
mars/tests/test_promise.py
mars/web/tests/test_api.py
mars/worker/dispatcher.py
mars/worker/execution.py

Add failover support for shuffle operands. The main changes are implementations of failover in ``ShuffleProxyActor``.
Fixes #484

Support failover for shuffle operands

---

mars/resource.py

[BACKPORT] Allow specifying different calculation methods for CPU and memory (#560)

---

mars/actors/__init__.py
mars/actors/core.pyx
mars/actors/distributor.pyx
mars/actors/pool/gevent_pool.pyx
mars/actors/pool/messages.pyx
mars/actors/pool/utils.pyx

[BACKPORT] Fix error in importing new_client in Python 2.7 (#558)

---

mars/tensor/execution/tests/test_arithmetic_execute.py
mars/tensor/expressions/utils.py

[BACKPORT] Fix unify chunks when add a scalar with out (#542)

---

mars/tensor/execution/tests/test_index_execute.py
mars/tensor/expressions/utils.py

[BACKPORT] Fix negative indexing (#547)

---

mars/_version.py

Bump version to 0.1.5

---

bin/travis-build-wheels.sh
requirements-dev.txt
requirements-wheel.txt
requirements.txt

[BACKPORT] Fix build issue under cp27-cp27m-manylinux1 (#588)

---

mars/_version.py
mars/dataframe/arithmetic/__init__.py
mars/dataframe/arithmetic/add.py
mars/dataframe/arithmetic/core.py
mars/dataframe/arithmetic/tests/test_arithmetic.py
mars/dataframe/arithmetic/tests/test_arithmetic_execution.py
mars/dataframe/utils.py
mars/tensor/arithmetic/core.py

Support add a scalar with the dataframe
#514

Support add scalar with dataframe

---

mars/_version.py
mars/dataframe/arithmetic/__init__.py
mars/dataframe/arithmetic/add.py
mars/dataframe/arithmetic/core.py
mars/dataframe/arithmetic/tests/test_arithmetic.py
mars/dataframe/arithmetic/tests/test_arithmetic_execution.py
mars/dataframe/utils.py
mars/tensor/arithmetic/core.py

Backport of #582 
(cherry picked from commit 08536cf45e750b526c4059fa87deef9f290b48aa)
NA

[BACKPORT] Support add scalar with dataframe (#582)

---

mars/compat.py
mars/serialize/dataserializer.py
mars/serialize/tests/test_serialize.py
mars/tests/test_mutable.py

[BACKPORT] Backport serialization patch from pyarrow.

---

mars/base_app.py
mars/cluster_info.py
mars/deploy/local/core.py
mars/deploy/local/tests/test_cluster.py
mars/scheduler/__main__.py
mars/scheduler/service.py
mars/tensor/reduction/tests/test_reduction_execute.py
mars/tests/core.py
mars/web/__main__.py
mars/web/server.py
mars/worker/__main__.py
mars/worker/service.py
mars/worker/tests/test_chunkholder.py
mars/worker/tests/test_execution.py
mars/worker/tests/test_main.py
mars/worker/tests/test_quota.py
mars/worker/tests/test_status.py
mars/worker/tests/test_transfer.py

Add ``StaticSchedulerDiscoverer`` and ``KVStoreSchedulerDiscoverer`` to handle initializing services with static scheduler lists and kv-store respectively.
Fixes #609

Extract scheduler discoverer from cluster_info

---

mars/scheduler/analyzer.py
mars/scheduler/graph.py
mars/scheduler/operands/base.py
mars/scheduler/operands/shuffle.py
mars/scheduler/tests/integrated/base.py
mars/worker/execution.py

[BACKPORT] Fix shuffle failover error in cases (#616)

---

mars/api.py
mars/deploy/local/session.py
mars/scheduler/mutable.py
mars/scheduler/resource.py
mars/scheduler/session.py
mars/tensor/core.py
mars/tensor/utils.py
mars/tests/test_mutable.py
mars/web/api.py
mars/web/server.py
mars/web/session.py

Fix the mutable tensor bugs and some enhancements:
+ Fix bug about worker selection for chunks
+ Support write mutable tensors using raw payload (for example, arrow tensors and arrow record batches), for better support for other languages.
+ Add an enhanced test for mutable tensor.
Fixes #603.

Fix mutable tensor related bugs and some enhancement

---

mars/executor.py
mars/fuse.pyx
mars/optimizes/tests/test_compose.py
mars/tensor/linalg/matmul.py
mars/tests/test_session.py

1. Remove inputs replacement when compose graph.
2. Do compose util all tileables are built into graph.
Fixes #642

Fix compose issues when build chunk graph

---

mars/tensor/linalg/cholesky.py

Remove conjugate in tile of Cholesky which is unnecessary and effects performance heavily.
Resolves #657 .

Remove conjugate in tile of Cholesky which effects performance heavily

---

mars/actors/core.pyx
mars/base_app.py
mars/cluster_info.py
mars/deploy/local/core.py
mars/scheduler/analyzer.py
mars/scheduler/operands/common.py
mars/scheduler/operands/shuffle.py
mars/web/session.py
mars/web/tests/test_api.py
mars/worker/service.py
mars/worker/spill.py

Backport of #654 and other minor fixes in #644 
NA

[BACKPORT] Check disks before adding into spill targets (#654)

---

mars/tensor/linalg/core.py
mars/tensor/linalg/svd.py
mars/tensor/linalg/tests/test_linalg.py
mars/tensor/linalg/utils.py

[BACKPORT] Fix chunk shape in tile of SVD (#656)

---

mars/executor.py
mars/fuse.pyx
mars/optimizes/tests/test_compose.py
mars/tensor/linalg/matmul.py
mars/tests/test_session.py

[BACKPORT] Fix compose issues when build chunk graph (#643)

---

mars/api.py
mars/deploy/local/session.py
mars/scheduler/mutable.py
mars/scheduler/resource.py
mars/scheduler/session.py
mars/serialize/protos/operand_pb2.py
mars/tensor/core.py
mars/tensor/utils.py
mars/tests/test_mutable.py
mars/web/api.py
mars/web/server.py
mars/web/session.py

[BACKPORT]  Fix mutable tensor related bugs and some enhancement

---

mars/deploy/local/session.py
mars/deploy/local/tests/test_cluster.py
mars/scheduler/session.py
mars/serialize/protos/operand_pb2.py
mars/session.py
mars/web/api.py
mars/web/session.py

[BACKPORT]  Support create mars session with given session_id. (#600)

---

mars/web/__init__.py
mars/web/apihandlers.py
mars/web/session.py
mars/web/tests/test_api.py
mars/worker/tests/base.py
mars/worker/tests/test_transfer.py
mars/worker/utils.py

[BACKPORT] Raise an error when Python version between client and server is different (#671)

---

mars/_utils.pyx
mars/tests/test_utils.py

Support tokenize nested dict in `mars.utils.tokenize` and provide class `Tokenizer ` to make code neat and achieve better performance.
Fixes #661

Support tokenize nested dict in `mars.utils.tokenize`

---

mars/_utils.pyx
mars/tests/test_utils.py
mars/web/server.py

[BACKPORT] Support tokenize nested dict in `mars.utils.tokenize` (#673)

---

mars/core.py
mars/serialize/protos/operand_pb2.py
mars/tensor/tests/test_core_execute.py

[BACKPORT] Fix bug that set value to copied tensor still changed the original one (#675)

---

mars/core.py
mars/dataframe/core.py
mars/executor.py
mars/fuse.pyx
mars/learn/decomposition/__init__.py
mars/learn/decomposition/base.py
mars/learn/decomposition/pca.py
mars/learn/decomposition/tests/__init__.py
mars/learn/decomposition/tests/test_pca.py
mars/learn/utils/__init__.py
mars/learn/utils/tests/__init__.py
mars/learn/utils/tests/test_validation.py
mars/learn/utils/validation.py
mars/tensor/__init__.py
mars/tensor/datasource/array.py
mars/tensor/datasource/core.py
mars/tensor/fuse/ne.py
mars/tensor/indexing/getitem.py
mars/tensor/indexing/tests/test_indexing_execute.py
mars/tests/test_utils.py
requirements-extra.txt

This PR adds the PCA decomposition algorithm.
TODO:
Resolves #513 .

Add PCA decomposition algorithm support

---

mars/learn/decomposition/__init__.py
mars/learn/decomposition/pca.py
mars/learn/decomposition/tests/test_truncated_svd.py
mars/learn/decomposition/truncated_svd.py
mars/utils.py

Add `TruncatedSVD` decomposition algorithm support.
Resolves #685 .

Add `TruncatedSVD` decomposition algorithm support

---

mars/core.py
mars/dataframe/core.py
mars/executor.py
mars/fuse.pyx
mars/learn/decomposition/__init__.py
mars/learn/decomposition/base.py
mars/learn/decomposition/pca.py
mars/learn/decomposition/tests/__init__.py
mars/learn/decomposition/tests/test_pca.py
mars/learn/decomposition/tests/test_truncated_svd.py
mars/learn/decomposition/truncated_svd.py
mars/learn/utils/__init__.py
mars/learn/utils/tests/__init__.py
mars/learn/utils/tests/test_validation.py
mars/learn/utils/validation.py
mars/serialize/protos/operand_pb2.py
mars/tensor/__init__.py
mars/tensor/datasource/array.py
mars/tensor/datasource/core.py
mars/tensor/fuse/ne.py
mars/tensor/indexing/getitem.py
mars/tensor/indexing/tests/test_indexing_execute.py
mars/tests/test_utils.py
mars/utils.py
requirements-extra.txt

[BACKPORT] Add PCA and TruncatedSVD decomposition algorithm support

---

mars/api.py
mars/deploy/local/session.py
mars/scheduler/graph.py
mars/scheduler/operands/common.py
mars/scheduler/operands/shuffle.py
mars/tensor/__init__.py
mars/web/apihandlers.py
mars/web/session.py
mars/web/task_pages.py
mars/web/tests/test_api.py
mars/worker/execution.py

[BACKPORT] Ensure remaining data removed on session close (#690)

---

mars/dataframe/datasource/from_tensor.py
mars/dataframe/datasource/tests/test_datasource_execution.py

Fix #694 by feeding different unique extra parameters for every chunks.
Fixes #694

Fix bug in creating dataframe from identical tensor.

---

.gitignore
docs/source/install.rst
docs/source/locale/zh_CN/LC_MESSAGES/install.po
mars/actors/pool/gevent_pool.pyx
mars/api.py
mars/deploy/local/core.py
mars/deploy/local/session.py
mars/resource.py
mars/scheduler/graph.py
mars/tensor/__init__.py
mars/tests/test_resource.py
mars/web/apihandlers.py
mars/web/session.py
mars/web/tests/test_api.py
mars/worker/__main__.py
mars/worker/service.py

[BACKPORT] Wait for graph to finish instead of querying with fixed intervals (#701)

---

mars/actors/pool/messages.pyx
mars/lib/gipc.pyx
mars/scheduler/graph.py
mars/scheduler/operands/__init__.py
mars/scheduler/operands/base.py
mars/scheduler/operands/common.py
mars/scheduler/operands/core.py
mars/scheduler/tests/integrated/op_delayer.py

[BACKPORT] Separate flags for initials and terminals (#703)

---

mars/api.py
mars/cluster_info.py
mars/deploy/local/session.py
mars/scheduler/graph.py
mars/scheduler/operands/base.py
mars/scheduler/operands/common.py
mars/tests/test_resource.py
mars/utils.py
mars/web/apihandlers.py
mars/web/server.py
mars/worker/tests/base.py

[BACKPORT] Remove redundant RPC calls for schedulers (#705)

---

mars/tensor/linalg/core.py
mars/tensor/linalg/tests/test_linalg.py

[BACKPORT] Fix incorrect chunk shape in QR (#719)

---

mars/promise.py
mars/scheduler/operands/common.py
mars/tests/test_promise.py
mars/web/apihandlers.py
mars/worker/execution.py
mars/worker/tests/test_quota.py
mars/worker/tests/test_transfer.py

[BACKPORT] Spawn promise to utilize async network libs (#725)

---

mars/scheduler/assigner.py
mars/scheduler/operands/common.py
mars/scheduler/operands/tests/test_common_ut.py
mars/worker/execution.py
mars/worker/tests/test_execution.py

[BACKPORT] Submit metas obtained from schedulers (#727)

---

mars/resource.py
mars/tests/test_resource.py

[BACKPORT] Use cpuacct.stat to calculate cpu usage in Docker containers (#740)

---

mars/dataframe/core.py
mars/dataframe/indexing/tests/test_indexing_execution.py
mars/serialize/protos/operand_pb2.py

[BACKPORT] Access column using `__getattr__` syntax for DataFrame.

---

mars/serialize/protos/operand_pb2.py
mars/tensor/base/tests/test_base.py
mars/tensor/indexing/setitem.py
mars/tensor/reshape/reshape.py
mars/tensor/tests/test_core_execute.py

[BACKPORT] `__setitem__` on a view should be still a view.

---

mars/base_app.py
mars/config.py
mars/deploy/local/session.py
mars/promise.py
mars/scheduler/assigner.py
mars/scheduler/chunkmeta.py
mars/scheduler/graph.py
mars/scheduler/operands/base.py
mars/scheduler/operands/common.py
mars/scheduler/tests/test_assigner.py
mars/scheduler/tests/test_graph.py
mars/scheduler/utils.py
mars/web/session.py
mars/worker/execution.py

[BACKPORT] Submit initial operands together in one RPC call (#711)

---

mars/scheduler/chunkmeta.py
mars/scheduler/operands/common.py
mars/worker/execution.py
mars/worker/tests/test_execution.py
mars/worker/tests/test_transfer.py
mars/worker/transfer.py

[BACKPORT] Simplify data transfer protocol (#736)

---

mars/_version.py
mars/serialize/protos/operand_pb2.py

Bump version to v0.2.1

---

mars/_version.py

Bump version to v0.3.0a2

---

.travis.yml

[BACKPORT] Fix certifi version after installing tiledb (#763)

---

mars/worker/storage/sharedstore.py

Fix relocation of ``PlasmaObjectNonexistent`` and ``PlasmaStoreFull``
Fixes #772

Fix relocation of plasma error objects

---

mars/tensor/arithmetic/core.py
mars/tensor/arithmetic/tests/test_arithmetic_execution.py
mars/tensor/array_utils.py
mars/tensor/datasource/ones.py
mars/worker/chunkstore.py
mars/worker/seal.py

[BACKPORT] Fix execution of arithmetic on GPU (#775)

---

appveyor.yml
mars/executor.py
mars/session.py
mars/tests/test_executor.py

This PR adds support for local execution that leverages multiple GPU cards.
NA

Add multiple GPU support for local execution

---

appveyor.yml
mars/executor.py
mars/session.py
mars/tests/test_executor.py

[BACKPORT] Add multiple GPU support for local execution (#779)

---

.github/workflows/download-etcd.sh
mars/tensor/arithmetic/__init__.py
mars/tensor/arithmetic/core.py
mars/tensor/tests/test_core_execute.py

This PR adds `__iadd__` and so on by wrap `add` with `out` argument. What's more, with this modification, the `iadd` would modify the data of tensor, and the view related to it may sense that which described in #812 .
Fixes #812

Support `__iadd__` etc by wrap `add` with `out` argument

---

mars/dataframe/arithmetic/add.py
mars/dataframe/arithmetic/core.py
mars/dataframe/arithmetic/floordiv.py
mars/dataframe/arithmetic/subtract.py
mars/dataframe/arithmetic/truediv.py
mars/dataframe/operands.py
mars/dataframe/reduction/__init__.py
mars/dataframe/reduction/core.py
mars/dataframe/reduction/max.py
mars/dataframe/reduction/min.py
mars/dataframe/reduction/prod.py
mars/dataframe/reduction/tests/test_reduction.py
mars/dataframe/reduction/tests/test_reduction_execute.py

[BACKPORT] Refactor of DataFrame reduction and support more reduction operands (#789)

---

.github/workflows/ci.yml
mars/api.py
mars/config.py
mars/deploy/local/session.py
mars/deploy/local/tests/test_cluster.py
mars/executor.py
mars/scheduler/graph.py
mars/scheduler/operands/common.py
mars/tests/test_api.py
mars/web/apihandlers.py
mars/web/session.py
mars/web/tests/test_api.py

[BACKPORT] Return execution exception info properly to session client. (#770)

---

mars/actors/pool/gevent_pool.pyx
mars/executor.py
mars/scheduler/operands/shuffle.py

Fix stuck issue of GeventThreadPoolExecutor in v0.2. Codes from #818
NA

Fix stuck issue of GeventThreadPoolExecutor

---

mars/_version.py

Bump version

---

.github/workflows/ci.yml
.github/workflows/install-hdfs.sh
.github/workflows/run-tests.sh
mars/dataframe/datasource/read_csv.py
mars/dataframe/datasource/tests/test_datasource_execution.py
mars/dataframe/datasource/tests/test_hdfs.py
mars/filesystem.py
mars/tests/test_filesystem.py

Add `3.7-hdfs` tag for testing HDFS in GitHub Actions.
NA

Add separate test environment for testing HDFS

---

.github/workflows/ci.yml
.github/workflows/install-hdfs.sh
.github/workflows/run-tests.sh
mars/dataframe/datasource/read_csv.py
mars/dataframe/datasource/tests/test_datasource_execution.py
mars/dataframe/datasource/tests/test_hdfs.py
mars/filesystem.py
mars/tests/test_filesystem.py

[BACKPORT] Add separate environment to test HDFS (#829)

---

.github/workflows/upload-packages.sh
mars/dataframe/arithmetic/core.py
mars/dataframe/arithmetic/tests/test_arithmetic.py
mars/dataframe/arithmetic/tests/test_arithmetic_execution.py
mars/utils.py

[BACKPORT] Fix incorrect behavior of dataframe arithmetic (#838)

---

mars/config.py
mars/dataframe/base/__init__.py
mars/dataframe/base/rechunk.py
mars/dataframe/base/tests/test_base.py
mars/dataframe/base/tests/test_base_execution.py
mars/dataframe/indexing/iloc.py
mars/dataframe/utils.py
mars/tensor/rechunk/core.py
mars/tensor/rechunk/rechunk.py

Support rechunk for DataFrame, just reuse the tensor rechunk's code.
Resolve #788 .

Support DataFrame rechunk

---

README.rst
mars/learn/datasets/__init__.py
mars/learn/datasets/samples_generator.py
mars/learn/datasets/tests/test_samples_generator.py

This PR added support for `mars.learn.datasets.samples_generator.make_blobs` which ported from sklearn. README also updated.
This PR requires #834 merged first, or the code snippet of learn in README cannot run.

Add `mars.learn.datasets.samples_generator.make_blobs` and update README

---

mars/lib/nvutils.py
mars/resource.py

Fix missing ``gpu_count`` util and make behavior of nv modules consistent between releases.
Fixes #844

[BACKPORT] Backport CUDA-related changes in utils in v0.3

---

.github/workflows/ci.yml
mars/worker/execution.py
mars/worker/quota.py
mars/worker/tests/test_quota.py

[BACKPORT] Mark resource as processing once allocated (#848)

---

.github/workflows/reload-env.sh
mars/actors/pool/messages.pyx
mars/lib/gipc.pyx
mars/lib/tblib/__init__.py
mars/lib/tblib/pickling_support.py

Backport code changes in #857 
NA

[BACKPORT] Resolve compatibility issue for Python 3.8 (#857)

---

.github/workflows/install-hdfs.sh
.github/workflows/install-minikube.sh
mars/deploy/local/core.py
mars/scheduler/tests/integrated/base.py
mars/utils.py
mars/worker/daemon.py

Kill worker process tree when terminating a calc process.
Fixes #863

Kill process tree when terminating a worker process

---

mars/deploy/local/core.py
mars/scheduler/tests/integrated/base.py
mars/utils.py
mars/worker/daemon.py

[BACKPORT] Kill process tree when terminating a worker process (#864)

---

mars/dataframe/datasource/from_tensor.py
mars/dataframe/datasource/tests/test_datasource.py
mars/dataframe/groupby/__init__.py
mars/dataframe/groupby/aggregation.py
mars/dataframe/groupby/tests/test_groupby.py
mars/dataframe/groupby/tests/test_groupby_execution.py

[BACKPORT] Add tree reduction method for DataFrame groupby aggregations (#850)

---

mars/_version.py
mars/dataframe/datasource/read_csv.py
mars/dataframe/datasource/tests/test_datasource_execution.py
mars/dataframe/groupby/aggregation.py
mars/dataframe/groupby/core.py
mars/dataframe/merge/concat.py

[BACKPORT] Fix `read_csv` execution on GPU (#859)

---

mars/core.py
mars/tensor/merge/stack.py

Add public base class, EntityData, for entity data
NA

Add public base class for entity data

---

mars/_utils.pyx
mars/deploy/kubernetes/client.py
mars/deploy/kubernetes/tests/entrypoint.sh
mars/deploy/kubernetes/tests/test_kubernetes.py
mars/scheduler/graph.py
mars/scheduler/tests/integrated/test_normal_execution.py
mars/tests/test_utils.py
requirements-dev.txt
requirements-wheel.txt
requirements.txt

Use `pickle` or `cloudpicke` to tokenize function objects. 
resolves #892

Add function objects implementation for tokenizer

---

.codecov.yml
.github/codecov-upstream.yml
.github/workflows/ci.yml
README.rst

Switch CI to codecov to avoid strange error information from coveralls.
NA

Switch coverage service to codecov

---

mars/dataframe/core.py
mars/dataframe/datasource/from_tensor.py
mars/dataframe/datasource/tests/test_datasource.py
mars/dataframe/datasource/tests/test_datasource_execution.py
mars/dataframe/initializer.py
mars/tensor/datasource/from_dataframe.py
mars/tests/test_session.py

This PR supports creating DataFrame from dict whose values are tensors.
This PR also supports creating DataFrame by specifying index with tensor type.
Resolves #902 .

Support creating DataFrame from dict whose values are tensors

---

mars/dataframe/core.py
mars/dataframe/datasource/from_tensor.py
mars/dataframe/datasource/tests/test_datasource.py
mars/dataframe/datasource/tests/test_datasource_execution.py
mars/dataframe/initializer.py
mars/tensor/datasource/from_dataframe.py
mars/tests/test_session.py

[BACKPORT] Support creating DataFrame from dict whose values are tensors (#903)

---

mars/dataframe/__init__.py
mars/dataframe/datasource/from_tensor.py
mars/dataframe/statistics/__init__.py
mars/dataframe/statistics/quantile.py
mars/dataframe/statistics/tests/__init__.py
mars/dataframe/statistics/tests/test_statistics.py
mars/dataframe/statistics/tests/test_statistics_execute.py
mars/dataframe/tests/test_utils.py
mars/dataframe/utils.py

[BACKPORT] Implements `DataFrame.quantile` and `Series.quantile` (#911)

---

mars/dataframe/datasource/tests/test_datasource_execution.py
mars/dataframe/reduction/__init__.py
mars/dataframe/reduction/core.py
mars/dataframe/reduction/count.py
mars/dataframe/reduction/tests/test_reduction.py
mars/dataframe/reduction/tests/test_reduction_execute.py
mars/serialize/protos/operand.proto

[BACKPORT] Support DataFrame and Series count (#900)

---

.codecov.yml
.coveragerc
.coveragerc-threaded
.github/codecov-upstream.yml
mars/serialize/protos/operand.proto
mars/tensor/__init__.py
mars/tensor/einsum/__init__.py
mars/tensor/einsum/core.py
mars/tensor/einsum/einsumfunc.py
mars/tensor/einsum/tests/__init__.py
mars/tensor/einsum/tests/test_einsum.py
mars/tensor/einsum/tests/test_einsum_execute.py
mars/tensor/utils.py
mars/worker/storage/tests/test_client.py

[BACKPORT] Support Einstein summation convention (#888)

---

mars/_utils.pyx
mars/lib/sparse/__init__.py
mars/lib/sparse/array.py
mars/lib/sparse/tests/test_sparse.py
mars/serialize/protos/operand.proto
mars/tensor/__init__.py
mars/tensor/indexing/__init__.py
mars/tensor/indexing/fill_diagonal.py
mars/tensor/indexing/tests/test_indexing.py
mars/tensor/indexing/tests/test_indexing_execute.py
mars/utils.py

This PR adds `mt.fill_diagonal` support, `mt.fill_diagonal`  follows [`numpy.fill_diagonal`](https://docs.scipy.org/doc/numpy/reference/generated/numpy.fill_diagonal.html)
Resolves #917 .

Add `mt.fill_diagonal` support

---

mars/serialize/jsonserializer.pyx
mars/serialize/protos/operand.proto
mars/tensor/arithmetic/__init__.py
mars/tensor/arithmetic/equal.py
mars/tensor/arithmetic/isclose.py
mars/tensor/reduction/count_nonzero.py
mars/tensor/spatial/__init__.py
mars/tensor/spatial/distance/__init__.py
mars/tensor/spatial/distance/cdist.py
mars/tensor/spatial/distance/pdist.py
mars/tensor/spatial/distance/squareform.py
mars/tensor/spatial/distance/tests/__init__.py
mars/tensor/spatial/distance/tests/test_distance.py
mars/tensor/spatial/distance/tests/test_distance_execute.py
mars/tensor/special/erf.py
mars/tensor/special/gammaln.py
mars/tests/core.py
mars/tests/test_utils.py
mars/utils.py

This PR aims to add support for `mars.tensor.spatial.distance.pdist`, `mars.tensor.spatial.distance.cdist` as well as `mars.tensor.spatial.distance.squareform`.
Tasks including:
Resolves #885 .
Resolves #886 .

Support `mars.tensor.spatial.distance.{pdist, cdist, squareform}`

---

mars/dataframe/reduction/__init__.py
mars/dataframe/reduction/core.py
mars/dataframe/reduction/mean.py
mars/dataframe/reduction/tests/test_reduction.py
mars/dataframe/reduction/tests/test_reduction_execute.py

[BACKPORT] Implement `mean` operator for DataFrame and Series (#907)

---

mars/core.py
mars/dataframe/arithmetic/__init__.py
mars/dataframe/arithmetic/core.py
mars/dataframe/arithmetic/equal.py
mars/dataframe/arithmetic/greater.py
mars/dataframe/arithmetic/greater_equal.py
mars/dataframe/arithmetic/less.py
mars/dataframe/arithmetic/less_equal.py
mars/dataframe/arithmetic/not_equal.py
mars/dataframe/arithmetic/tests/test_arithmetic.py
mars/dataframe/arithmetic/tests/test_arithmetic_execution.py
mars/dataframe/arithmetic/tests/test_comparison.py
mars/dataframe/core.py
mars/tensor/core.py
mars/utils.py

[BACKPORT] Add comparison operands for DataFrame (#921)

---

mars/_utils.pyx
mars/lib/sparse/__init__.py
mars/lib/sparse/array.py
mars/lib/sparse/tests/test_sparse.py
mars/serialize/protos/operand.proto
mars/tensor/__init__.py
mars/tensor/indexing/__init__.py
mars/tensor/indexing/fill_diagonal.py
mars/tensor/indexing/tests/test_indexing.py
mars/tensor/indexing/tests/test_indexing_execute.py
mars/utils.py

[BACKPORT] Add `mt.fill_diagonal` support (#918)

---

.github/workflows/ci.yml
.github/workflows/download-etcd.sh
.github/workflows/install-conda.sh
.github/workflows/reload-env.sh
.github/workflows/run-tests.sh
mars/tests/core.py

As Git bash for Windows change to msys instead of mingw, the uname command returns different results. Therefore we have to change our test scripts.
NA

Fix failures in Windows tests

---

.github/workflows/ci.yml
.github/workflows/download-etcd.sh
.github/workflows/install-conda.sh
.github/workflows/reload-env.sh
.github/workflows/run-tests.sh
mars/tests/core.py

[BACKPORT] Fix failures in Windows tests (#938)

---

.github/workflows/run-tests.sh
mars/actors/core.pxd
mars/actors/core.pyx
mars/actors/pool/aio_pool.pyx
mars/actors/pool/tests/test_aio_pool.py
mars/actors/pool/utils.pyx
mars/cluster_info.py
mars/kvstore.py
mars/promise.py
mars/tests/core.py
mars/tests/test_kvstore.py
mars/tests/test_promise.py
mars/worker/utils.py
setup.py

Convert KVStore and Promise code into asyncio.

Convert KVStore and Promise into asyncio

---

mars/dataframe/core.py
mars/dataframe/merge/concat.py
mars/dataframe/reduction/core.py
mars/serialize/protos/indexvalue.proto
mars/web/tests/test_timeline.py

This PR fixes failed unittests due to release of pandas 1.0.
NA

Fix failed unittests due to release of pandas 1.0

---

mars/dataframe/core.py
mars/dataframe/merge/concat.py
mars/dataframe/reduction/core.py
mars/lib/sparse/tests/test_sparse.py
mars/serialize/protos/indexvalue.proto
mars/web/tests/test_timeline.py

Backport of #964 and unittests fixes in #960 .

[BACKPORT] Fix failed unittests due to release of pandas 1.0 (#964)

---

.github/workflows/ci.yml
mars/filesystem.py
mars/serialize/protos/operand.proto
mars/tensor/__init__.py
mars/tensor/datasource/__init__.py
mars/tensor/datasource/core.py
mars/tensor/datasource/from_hdf5.py
mars/tensor/datasource/from_zarr.py
mars/tensor/datasource/tests/test_datasource_execute.py
mars/tensor/datastore/__init__.py
mars/tensor/datastore/tests/test_datastore_execute.py
mars/tensor/datastore/to_hdf5.py
mars/tensor/datastore/to_zarr.py
mars/tests/test_filesystem.py

This PR adds ability to read and write [zarr format](https://zarr.readthedocs.io/en/stable/).
Tasks include:
Resolves #948 .

Support reading and writing in zarr format

---

mars/serialize/protos/operand.proto

Hotfix opcodes that conflict

---

docs/source/contributing.rst
docs/source/install.rst
docs/source/locale/zh_CN/LC_MESSAGES/contributing.po
docs/source/locale/zh_CN/LC_MESSAGES/install.po
mars/lib/nvutils.py
mars/node_info.py
mars/scheduler/tests/integrated/base.py
mars/worker/__main__.py
mars/worker/service.py
mars/worker/status.py
mars/worker/tests/test_main.py

Pass ``with_gpu`` to StatusActor. This will inform StatusActor to detect whether GPU is enabled.
Fixes #972

Stop detecting GPU when no cuda devices are configured

---

docs/source/contributing.rst
docs/source/install.rst
docs/source/locale/zh_CN/LC_MESSAGES/contributing.po
docs/source/locale/zh_CN/LC_MESSAGES/install.po
mars/lib/nvutils.py
mars/node_info.py
mars/scheduler/tests/integrated/base.py
mars/worker/__main__.py
mars/worker/service.py
mars/worker/status.py
mars/worker/tests/test_main.py

[BACKPORT] Stop detecting GPU when no cuda devices are configured (#973)

---

mars/dataframe/arithmetic/__init__.py
mars/dataframe/arithmetic/sqrt.py
mars/dataframe/arithmetic/tests/test_arithmetic_execution.py
mars/dataframe/reduction/__init__.py
mars/dataframe/reduction/std.py
mars/dataframe/reduction/tests/test_reduction.py
mars/dataframe/reduction/tests/test_reduction_execute.py
mars/dataframe/reduction/var.py

Add DataFrame's var and std support.
Resolves #941

Implement dataframe var and std

---

mars/dataframe/arithmetic/__init__.py
mars/dataframe/arithmetic/dot.py
mars/dataframe/arithmetic/multiply.py
mars/dataframe/arithmetic/power.py
mars/dataframe/arithmetic/tests/test_arithmetic.py
mars/dataframe/arithmetic/tests/test_arithmetic_execution.py
mars/dataframe/arithmetic/tests/test_dot.py
mars/dataframe/utils.py

This PR implements `dot`, `mul` and `pow`.
NA

Implements DataFrame dot, mul and pow

---

mars/config.py
mars/dataframe/__init__.py
mars/dataframe/arithmetic/tests/test_arithmetic_execution.py
mars/dataframe/datasource/dataframe.py
mars/dataframe/datasource/read_csv.py
mars/dataframe/datasource/read_sql_table.py
mars/dataframe/datasource/series.py
mars/dataframe/datasource/tests/test_datasource.py
mars/dataframe/datasource/tests/test_datasource_execution.py
mars/serialize/protos/operand.proto
mars/tensor/arithmetic/tests/test_arithmetic_execution.py
mars/tensor/datasource/arange.py
mars/tensor/datasource/core.py
mars/tensor/datasource/eye.py
mars/tensor/datasource/linspace.py
mars/tensor/indexing/tests/test_indexing.py
mars/tensor/indexing/tests/test_indexing_execute.py
mars/tensor/random/choice.py
mars/tensor/random/core.py
mars/tensor/random/dirichlet.py
mars/tensor/random/multivariate_normal.py
mars/tensor/spatial/distance/squareform.py
mars/tensor/utils.py
requirements-dev.txt

This PR implements `mars.dataframe.read_sql_table`.
Partially implements #952 .

Implements `md.read_sql_table`

---

mars/serialize/protos/operand.proto
mars/tensor/__init__.py
mars/tensor/base/__init__.py
mars/tensor/base/argpartition.py
mars/tensor/base/argsort.py
mars/tensor/base/argtopk.py
mars/tensor/base/partition.py
mars/tensor/base/psrs.py
mars/tensor/base/sort.py
mars/tensor/base/tests/test_base.py
mars/tensor/base/tests/test_base_execute.py
mars/tensor/base/topk.py
mars/utils.py
requirements-dev.txt
requirements.txt

[BACKPORT] Implements mt.{topk, argsort, argpartition, argtopk} (#946)

---

mars/dataframe/__init__.py
mars/dataframe/datastore/__init__.py
mars/dataframe/datastore/tests/__init__.py
mars/dataframe/datastore/tests/test_datastore.py
mars/dataframe/datastore/tests/test_datastore_execute.py
mars/dataframe/datastore/to_csv.py
mars/dataframe/operands.py
mars/filesystem.py
mars/serialize/protos/operand.proto

[BACKPORT] Implements `DataFrame.to_csv` (#966)

---

mars/tensor/random/choice.py
mars/tensor/random/tests/test_random.py
mars/tensor/random/tests/test_random_execute.py

[BACKPORT] Fix wrong behavior of choice (#976)

---

mars/dataframe/arithmetic/__init__.py
mars/dataframe/arithmetic/dot.py
mars/dataframe/arithmetic/multiply.py
mars/dataframe/arithmetic/power.py
mars/dataframe/arithmetic/tests/test_arithmetic.py
mars/dataframe/arithmetic/tests/test_arithmetic_execution.py
mars/dataframe/arithmetic/tests/test_dot.py
mars/dataframe/utils.py

[BACKPORT] Implements DataFrame dot, mul and pow (#980)

---

mars/serialize/protos/operand.proto
mars/tensor/images/__init__.py
mars/tensor/images/imread.py
mars/tensor/images/tests/__init__.py
mars/tensor/images/tests/test_images.py
mars/tensor/images/tests/test_images_execute.py

[BACKPORT] Implement `imread` to read from images (#988)

---

mars/dataframe/arithmetic/__init__.py
mars/dataframe/arithmetic/sqrt.py
mars/dataframe/arithmetic/tests/test_arithmetic_execution.py
mars/dataframe/reduction/__init__.py
mars/dataframe/reduction/std.py
mars/dataframe/reduction/tests/test_reduction.py
mars/dataframe/reduction/tests/test_reduction_execute.py
mars/dataframe/reduction/var.py

[BACKPORT] Implement dataframe var and std (#977)

---

mars/dataframe/base/__init__.py
mars/dataframe/base/describe.py
mars/dataframe/base/tests/test_base_execution.py
mars/dataframe/initializer.py
mars/dataframe/reduction/core.py
mars/dataframe/reduction/count.py
mars/dataframe/reduction/max.py
mars/dataframe/reduction/mean.py
mars/dataframe/reduction/min.py
mars/dataframe/reduction/prod.py
mars/dataframe/reduction/sum.py
mars/dataframe/reduction/tests/test_reduction.py
mars/dataframe/reduction/var.py
mars/serialize/protos/operand.proto

[BACKPORT] Implements `describe` for DataFrame (#981)

---

mars/_version.py
mars/tensor/reduction/core.py
mars/tensor/reduction/count_nonzero.py
mars/tensor/reduction/tests/test_reduction_execute.py

[BACKPORT] Fix wrong result of count_nonzero (#1002)

---

mars/lib/nvutils.py

Check error number returned by CUDA libs. When the error is about no available devices, nvutils will report a warning only.
Fixes #1006

 Fix error when no device detected by CUDA driver

---

mars/lib/nvutils.py

\## What do these changes do?
Backport of #1007
NA

[BACKPORT] Fix error when no device detected by CUDA driver (#1007)

---

mars/context.py
mars/executor.py
mars/learn/contrib/pytorch/__init__.py
mars/learn/contrib/pytorch/dataset.py
mars/learn/contrib/pytorch/sampler.py
mars/learn/contrib/pytorch/tests/integrated/test_distributed_dataset.py
mars/learn/contrib/pytorch/tests/test_dataset.py

Implement `RandomSampler` and Support training `MarsDataset` locally in PyTorch.
Resolves #1009

Implement pytorch sampler for local training

---

mars/context.py
mars/tensor/base/argsort.py
mars/tensor/indexing/core.py
mars/tensor/indexing/getitem.py
mars/tensor/indexing/index_lib.py
mars/tensor/indexing/tests/test_index_lib.py
mars/tensor/indexing/tests/test_indexing_execute.py

This PR refactors the tensor indexing with a new `index_lib` to take over the tiling details.
Resolves #982 .

Refactor tensor indexing

---

.github/workflows/ci.yml
mars/tensor/base/argsort.py
mars/tensor/indexing/core.py
mars/tensor/indexing/getitem.py
mars/tensor/indexing/index_lib.py
mars/tensor/indexing/tests/test_index_lib.py
mars/tensor/indexing/tests/test_indexing_execute.py

[BACKPORT] Refactor tensor indexing (#1011)

---

.github/workflows/install-conda.sh
requirements-extra.txt

[BACKPORT] Fix tests under Python 3.6 as VS2015 is preinstalled (#1014)

---

mars/dataframe/merge/merge.py
mars/dataframe/merge/tests/test_merge.py
mars/dataframe/merge/tests/test_merge_execution.py

If one of the dataframes has only one chunk when joining, we skip the shuffle stage and just merge the single chunk for each chunk in the other dataframe, it will be more efficient in some cases.
Resolves #1020.

Use `mapjoin` to optimize df.merge

---

mars/dataframe/merge/merge.py
mars/dataframe/merge/tests/test_merge.py
mars/dataframe/merge/tests/test_merge_execution.py

[BACKPORT] Use `mapjoin` to optimize df.merge (#1021)

---

mars/dataframe/base/standardize_range_index.py
mars/dataframe/merge/__init__.py
mars/dataframe/merge/append.py
mars/dataframe/merge/tests/test_merge.py
mars/dataframe/merge/tests/test_merge_execution.py
mars/serialize/protos/operand.proto

Add support for df.append and series.append.
Resolves #1025

Implement dataframe append

---

mars/dataframe/core.py
mars/dataframe/indexing/iloc.py
mars/dataframe/indexing/index_lib.py
mars/dataframe/indexing/tests/test_indexing.py
mars/dataframe/indexing/tests/test_indexing_execution.py
mars/dataframe/operands.py
mars/dataframe/utils.py
mars/tensor/indexing/index_lib.py

This PR refactors current `DataFrame.iloc` with `index_lib` which introduced in #1011 .
Tasks
NA

Refactor tiling of `DataFrame.iloc` with `index_lib`

---

.codacy.yml
mars/dataframe/base/__init__.py
mars/dataframe/base/fillna.py
mars/dataframe/base/tests/test_base.py
mars/dataframe/base/tests/test_base_execution.py
mars/dataframe/reduction/core.py
mars/deploy/kubernetes/tests/test_kubernetes.py
mars/serialize/protos/operand.proto

[BACKPORT] Add support for md.fillna (#1029)

---

mars/core.py
mars/executor.py
mars/learn/neighbors/base.py
mars/learn/neighbors/tests/test_nearest_neighbors.py
mars/learn/utils/validation.py
mars/tensor/fuse/ne.py
mars/tensor/reduction/core.py

This PR fixes KNN so that it can accept input with unknown shape.
Fixes #1032 .

Fix KNN so that it can accept input with unknown shape

---

mars/dataframe/__init__.py
mars/dataframe/merge/__init__.py
mars/dataframe/merge/concat.py
mars/dataframe/merge/tests/test_merge.py
mars/dataframe/merge/tests/test_merge_execution.py

Add support for combining DataFrames by `concat` method.
Resolves #234.

Implement DataFrame.concat and Series.concat

---

mars/core.py
mars/dataframe/core.py
mars/dataframe/indexing/iloc.py
mars/dataframe/indexing/index_lib.py
mars/dataframe/indexing/tests/test_indexing.py
mars/dataframe/indexing/tests/test_indexing_execution.py
mars/dataframe/operands.py
mars/dataframe/utils.py
mars/executor.py
mars/learn/utils/validation.py
mars/tensor/fuse/ne.py
mars/tensor/indexing/index_lib.py
mars/tensor/reduction/core.py

Backport of #1016  and partial fixes in #1033.

[BACKPORT] Refactor tiling of `DataFrame.iloc` with `index_lib` (#1016)

---

mars/dataframe/base/apply.py
mars/dataframe/base/map.py
mars/dataframe/groupby/aggregation.py
mars/dataframe/groupby/apply.py
mars/dataframe/groupby/core.py
mars/dataframe/merge/concat.py
mars/dataframe/operands.py
mars/learn/neighbors/_ball_tree.py
mars/learn/neighbors/tree.py
mars/serialize/__init__.py
mars/serialize/core.pxd
mars/serialize/core.pyx
mars/serialize/jsonserializer.pyx
mars/serialize/pbserializer.pyx
mars/serialize/protos/value.proto
mars/serialize/tests/test_serialize.py
mars/serialize/tests/testser.proto
mars/tensor/spatial/distance/cdist.py
mars/tensor/spatial/distance/pdist.py

This PR added `FuntionField` for serialization, and functions could be included in `ListField` etc.
Resolves #1047 .

Add support for function serialization

---

mars/dataframe/__init__.py
mars/dataframe/arithmetic/core.py
mars/dataframe/arithmetic/tests/test_arithmetic.py
mars/dataframe/indexing/getitem.py
mars/dataframe/utils.py
mars/dataframe/window/__init__.py
mars/dataframe/window/rolling/__init__.py
mars/dataframe/window/rolling/aggregation.py
mars/dataframe/window/rolling/core.py
mars/dataframe/window/rolling/tests/__init__.py
mars/dataframe/window/rolling/tests/test_rolling.py
mars/dataframe/window/rolling/tests/test_rolling_execute.py
mars/serialize/jsonserializer.pyx
mars/serialize/protos/operand.proto

This PR introduced `DataFrame.rolling`.
It depends on `DataFrame.loc`.
Resolves #1044.

Add DataFrame.rolling support

---

mars/dataframe/__init__.py
mars/dataframe/arithmetic/core.py
mars/dataframe/arithmetic/tests/test_arithmetic.py
mars/dataframe/core.py
mars/dataframe/datasource/tests/test_datasource.py
mars/dataframe/indexing/getitem.py
mars/dataframe/utils.py
mars/dataframe/window/__init__.py
mars/dataframe/window/rolling/__init__.py
mars/dataframe/window/rolling/aggregation.py
mars/dataframe/window/rolling/core.py
mars/dataframe/window/rolling/tests/__init__.py
mars/dataframe/window/rolling/tests/test_rolling.py
mars/dataframe/window/rolling/tests/test_rolling_execute.py
mars/serialize/jsonserializer.pyx
mars/serialize/pbserializer.pyx
mars/serialize/protos/indexvalue.proto
mars/serialize/protos/operand.proto
mars/web/tests/test_api.py

Backport of #1045 and #1065
NA

[BACKPORT] Add DataFrame.rolling support (#1045)

---

mars/dataframe/base/reset_index.py
mars/dataframe/base/standardize_range_index.py
mars/dataframe/base/tests/test_base_execution.py
mars/dataframe/datasource/read_csv.py
mars/dataframe/datasource/tests/test_datasource_execution.py
mars/dataframe/utils.py
mars/operands.py
mars/scheduler/graph.py
mars/scheduler/tests/integrated/no_prepare_op.py
mars/scheduler/tests/integrated/test_normal_execution.py
mars/serialize/protos/operand.proto
mars/worker/calc.py
mars/worker/execution.py

[BACKPORT] Standardize RangeIndex for unknown shape DataFrame (#930)

---

mars/dataframe/datasource/read_csv.py
mars/dataframe/datasource/tests/test_datasource_execution.py
mars/dataframe/merge/merge.py

Backport of #1024, be sure that #1066 merge first
NA

[BACKPORT] Add `sort_range_index` parameter in readcsv (#1024)

---

mars/dataframe/base/__init__.py
mars/dataframe/base/accessor.py
mars/dataframe/base/datetimes.py
mars/dataframe/base/string_.py
mars/dataframe/base/tests/test_base.py
mars/dataframe/base/tests/test_base_execution.py
mars/dataframe/core.py
mars/serialize/protos/operand.proto

[BACKPORT] Support string and datetime methods via `Series.str` and `Series.dt` accessor (#1063)

---

mars/dataframe/base/standardize_range_index.py
mars/dataframe/merge/__init__.py
mars/dataframe/merge/append.py
mars/dataframe/merge/tests/test_merge.py
mars/dataframe/merge/tests/test_merge_execution.py
mars/serialize/protos/operand.proto

[BACKPORT] Implement dataframe append (#1026)

---

mars/dataframe/indexing/getitem.py
mars/dataframe/merge/merge.py
mars/deploy/local/tests/test_cluster.py
mars/scheduler/graph.py
mars/scheduler/operands/common.py
mars/serialize/protos/dataframe.proto

Some jobs will fail in distributed mode if iterative tiling is triggered, this PR fixes the error and add ut for this situation.
Fixes #1055.
Fixes #1059.

Fix failed cases in distributed mode

---

mars/dataframe/__init__.py
mars/dataframe/merge/__init__.py
mars/dataframe/merge/concat.py
mars/dataframe/merge/tests/test_merge.py
mars/dataframe/merge/tests/test_merge_execution.py

[BACKPORT] Implement DataFrame.concat and Series.concat (#1040)

---

mars/dataframe/datasource/read_csv.py
mars/dataframe/indexing/getitem.py
mars/dataframe/merge/merge.py
mars/deploy/local/tests/test_cluster.py
mars/scheduler/graph.py
mars/scheduler/operands/common.py
mars/serialize/protos/dataframe.proto

[BACKPORT] Fix failed cases in distributed mode (#1062)

---

mars/dataframe/__init__.py
mars/dataframe/base/standardize_range_index.py
mars/dataframe/sort/__init__.py
mars/dataframe/sort/psrs.py
mars/dataframe/sort/sort_values.py
mars/dataframe/sort/tests/__init__.py
mars/dataframe/sort/tests/test_sort.py
mars/dataframe/sort/tests/test_sort_execute.py
mars/dataframe/utils.py
mars/serialize/protos/operand.proto
mars/tensor/base/partition.py
mars/tensor/base/psrs.py
mars/tensor/base/sort.py

[BACKPORT] Add support for DataFrame.sort_values (#1046)

---

mars/_version.py
mars/dataframe/sort/__init__.py
mars/dataframe/sort/core.py
mars/dataframe/sort/psrs.py
mars/dataframe/sort/sort_index.py
mars/dataframe/sort/sort_values.py
mars/dataframe/sort/tests/test_sort.py
mars/dataframe/sort/tests/test_sort_execute.py
mars/dataframe/utils.py
mars/serialize/protos/operand.proto

[BACKPORT] Support sort_index for DataFrame and Series (#1053)

---

mars/dataframe/base/rechunk.py
mars/dataframe/base/tests/test_base.py

[BACKPORT] Fix wrong dtypes in df.rechunk (#1080)

---

.github/workflows/ci.yml
mars/_utils.pyx
mars/dataframe/__init__.py
mars/dataframe/arithmetic/__init__.py
mars/dataframe/base/__init__.py
mars/dataframe/base/rechunk.py
mars/dataframe/base/tests/test_base_execution.py
mars/dataframe/core.py
mars/dataframe/datasource/date_range.py
mars/dataframe/datasource/from_tensor.py
mars/dataframe/datasource/index.py
mars/dataframe/datasource/tests/test_datasource.py
mars/dataframe/datasource/tests/test_datasource_execution.py
mars/dataframe/indexing/iloc.py
mars/dataframe/merge/concat.py
mars/dataframe/operands.py
mars/serialize/__init__.py
mars/serialize/core.pxd
mars/serialize/core.pyx
mars/serialize/jsonserializer.pyx
mars/serialize/pbserializer.pyx
mars/serialize/protos/dataframe.proto
mars/serialize/protos/operand.proto
mars/serialize/protos/value.proto
mars/serialize/tests/test_serialize.py
mars/serialize/tests/testser.proto

This PR tries to add support for Index data as well as `md.date_range`.
Resolves #1076  .

Add `md.date_range` support

---

mars/dataframe/arithmetic/__init__.py
mars/dataframe/arithmetic/core.py
mars/dataframe/arithmetic/logical_and.py
mars/dataframe/arithmetic/logical_not.py
mars/dataframe/arithmetic/logical_or.py
mars/dataframe/arithmetic/logical_xor.py
mars/dataframe/arithmetic/tests/test_arithmetic.py
mars/dataframe/arithmetic/tests/test_arithmetic_execution.py

Implements logical operators(and/or/xor/not) on DataFrame and Series.
Test is coming.
N/A

Logical operators on DataFrame and Series.

---

mars/learn/neighbors/_ball_tree.py
mars/learn/neighbors/_faiss.py
mars/learn/neighbors/_kd_tree.py
mars/learn/neighbors/base.py
mars/learn/neighbors/tests/test_nearest_neighbors.py
mars/learn/neighbors/tree.py
mars/tensor/array_utils.py
mars/tensor/base/astype.py

This PR fixes failed  fit method selection for KNN when input has unknown shape, tree-based KNN has been optimized as well.
Fixes #1049

Fix failed fit method selection for KNN when input has unknown shape 

---

mars/dataframe/align.py
mars/dataframe/arithmetic/core.py
mars/dataframe/groupby/apply.py
mars/dataframe/indexing/getitem.py
mars/dataframe/indexing/index_lib.py
mars/dataframe/merge/concat.py
mars/dataframe/reduction/aggregation.py
mars/dataframe/reduction/core.py
mars/dataframe/statistics/quantile.py
mars/dataframe/window/rolling/aggregation.py
mars/executor.py
mars/lib/sparse/array.py
mars/tensor/base/partition.py
mars/tensor/base/psrs.py
mars/tensor/base/sort.py
mars/tensor/fft/irfft.py
mars/tensor/indexing/core.py
mars/tensor/indexing/index_lib.py
mars/tensor/statistics/histogram.py
mars/tensor/statistics/quantile.py
mars/tests/core.py

This PR is part of #1071 which resolves inconsistency issues in tensors and some operands on data frames, dealing (but not completely resolving) #1070.

Fix consistency between tensor metadata and real outputs

---

.github/workflows/ci.yml
mars/_utils.pyx
mars/dataframe/__init__.py
mars/dataframe/arithmetic/__init__.py
mars/dataframe/base/__init__.py
mars/dataframe/base/rechunk.py
mars/dataframe/base/tests/test_base_execution.py
mars/dataframe/core.py
mars/dataframe/datasource/date_range.py
mars/dataframe/datasource/from_tensor.py
mars/dataframe/datasource/index.py
mars/dataframe/datasource/tests/test_datasource.py
mars/dataframe/datasource/tests/test_datasource_execution.py
mars/dataframe/indexing/iloc.py
mars/dataframe/merge/concat.py
mars/dataframe/operands.py
mars/serialize/__init__.py
mars/serialize/core.pxd
mars/serialize/core.pyx
mars/serialize/jsonserializer.pyx
mars/serialize/pbserializer.pyx
mars/serialize/protos/dataframe.proto
mars/serialize/protos/operand.proto
mars/serialize/protos/value.proto
mars/serialize/tests/test_serialize.py
mars/serialize/tests/testser.proto

[BACKPORT] Add `md.date_range` support (#1073)

---

mars/dataframe/arithmetic/__init__.py
mars/dataframe/arithmetic/core.py
mars/dataframe/arithmetic/logical_and.py
mars/dataframe/arithmetic/logical_not.py
mars/dataframe/arithmetic/logical_or.py
mars/dataframe/arithmetic/logical_xor.py
mars/dataframe/arithmetic/tests/test_arithmetic.py
mars/dataframe/arithmetic/tests/test_arithmetic_execution.py

[BACKPORT] Logical operators on DataFrame and Series. (#1056)

---

mars/dataframe/align.py
mars/dataframe/arithmetic/core.py
mars/dataframe/indexing/getitem.py
mars/dataframe/indexing/index_lib.py
mars/dataframe/merge/concat.py
mars/dataframe/reduction/core.py
mars/dataframe/statistics/quantile.py
mars/dataframe/window/rolling/aggregation.py
mars/executor.py
mars/lib/sparse/array.py
mars/tensor/base/partition.py
mars/tensor/base/psrs.py
mars/tensor/base/sort.py
mars/tensor/fft/irfft.py
mars/tensor/indexing/core.py
mars/tensor/indexing/index_lib.py
mars/tensor/statistics/histogram.py
mars/tensor/statistics/quantile.py
mars/tests/core.py

Backport of #1085
Co-authored-by: 继盛 <xuye.qin@alibaba-inc.com>
Co-authored-by: hekaisheng <kaisheng.hks@alibaba-inc.com>

[BACKPORT] Fix consistency between tensor metadata and real outputs (#1085)

---

mars/dataframe/datasource/from_tensor.py
mars/dataframe/datasource/tests/test_datasource.py
mars/dataframe/datasource/tests/test_datasource_execution.py
mars/dataframe/initializer.py
mars/executor.py

This PR adds support for creating DataFrame from dict in which scalar exists
Fixes #1097 .

Support creating DataFrame from dict in which scalar exists

---

.github/workflows/ci.yml
.github/workflows/install-conda.sh
.github/workflows/install-minikube.sh
mars/_version.py
mars/dataframe/datasource/dataframe.py
mars/dataframe/datasource/read_csv.py
mars/dataframe/merge/concat.py
mars/executor.py
mars/tests/test_executor.py
requirements-dev.txt
requirements-extra.txt
requirements.txt

[BACKPORT] Optimize performance of executor when running ops less than number of parallelism (#1096)

---

mars/dataframe/indexing/__init__.py
mars/dataframe/indexing/at.py
mars/dataframe/indexing/iat.py
mars/dataframe/indexing/index_lib.py
mars/dataframe/indexing/tests/test_indexing_execution.py

[BACKPORT]Implements `at` and `iat` for DataFrame (#1101)

---

mars/dataframe/datasource/from_tensor.py
mars/dataframe/datasource/tests/test_datasource.py
mars/dataframe/datasource/tests/test_datasource_execution.py
mars/dataframe/initializer.py

[BACKPORT] Support creating DataFrame from dict in which scalar exists (#1098)

---

mars/dataframe/base/__init__.py
mars/dataframe/base/isin.py
mars/dataframe/base/tests/test_base.py
mars/dataframe/base/tests/test_base_execution.py

[BACKPORT] Implements Series.isin (for Series type). (#1058)

---

mars/dataframe/__init__.py
mars/dataframe/indexing/getitem.py
mars/dataframe/indexing/index_lib.py
mars/dataframe/indexing/loc.py
mars/dataframe/indexing/tests/test_indexing_execution.py
mars/tests/test_session.py
mars/utils.py

[BACKPORT] Support slice that can be integer or other types on non-int64 index (#1103)

---

.github/workflows/ci.yml
mars/dataframe/__init__.py
mars/dataframe/base/__init__.py
mars/dataframe/base/checkna.py
mars/dataframe/base/tests/test_base_execution.py
mars/dataframe/core.py
mars/dataframe/tests/test_utils.py
mars/serialize/protos/operand.proto

[BACKPORT] Add support for isna, notna and __dir__ (#1125)

---

mars/core.py
mars/dataframe/base/fillna.py
mars/dataframe/groupby/tests/test_groupby_execution.py
mars/dataframe/merge/concat.py
mars/dataframe/reduction/__init__.py
mars/dataframe/reduction/aggregation.py
mars/dataframe/reduction/core.py
mars/dataframe/reduction/tests/test_reduction.py
mars/dataframe/reduction/tests/test_reduction_execute.py

Backport of #1054. This is needed by dropna.

[BACKPORT] Add support for {DataFrame,Series}.agg (#1054)

---

.github/workflows/ci.yml
mars/dataframe/core.py
mars/dataframe/groupby/core.py
mars/dataframe/groupby/tests/test_groupby_execution.py
mars/dataframe/operands.py
mars/serialize/protos/dataframe.proto

Make GroupBy and GroupByData objects similar to DataFrame and DataFrameData
NA

Refactor GroupBy objects

---

mars/dataframe/base/__init__.py
mars/dataframe/base/dropna.py
mars/dataframe/base/fillna.py
mars/dataframe/base/tests/test_base.py
mars/dataframe/base/tests/test_base_execution.py
mars/dataframe/reduction/aggregation.py
mars/dataframe/reduction/count.py
mars/dataframe/reduction/tests/test_reduction.py

[BACKPORT] Add support for md.dropna (#1129)

---

docs/doc-requirements.txt
docs/requirements-doc.txt
docs/source/contributing.rst

This PR fixes requirements for doc. No code effected, thus just skip CI.
NA

[SKIP CI] Fix requirements for doc

---

.github/workflows/install-conda.sh
mars/dataframe/core.py
mars/dataframe/groupby/__init__.py
mars/dataframe/groupby/aggregation.py
mars/dataframe/groupby/apply.py
mars/dataframe/groupby/core.py
mars/dataframe/groupby/cum.py
mars/dataframe/groupby/getitem.py
mars/dataframe/groupby/tests/test_groupby.py
mars/dataframe/groupby/tests/test_groupby_execution.py
mars/dataframe/groupby/transform.py
mars/dataframe/merge/concat.py
mars/dataframe/operands.py
mars/dataframe/utils.py
mars/lib/groupby_wrapper.py
mars/lib/tests/__init__.py
mars/lib/tests/test_lib.py
mars/optimizes/tileable_graph/column_pruning.py
mars/serialize/dataserializer.py
mars/serialize/protos/dataframe.proto
mars/serialize/tests/test_serialize.py
mars/tests/core.py

Support groupby.__getitem__ and group by level

---

mars/dataframe/core.py
mars/dataframe/groupby/core.py
mars/dataframe/groupby/getitem.py
mars/dataframe/groupby/tests/test_groupby.py
mars/dataframe/groupby/transform.py
mars/dataframe/operands.py
mars/serialize/protos/dataframe.proto
mars/tests/core.py

Check output metadata check for groupby types
NA

Add meta checks for groupby

---

mars/tensor/__init__.py
mars/tensor/merge/__init__.py
mars/tensor/merge/concatenate.py
mars/tensor/merge/tests/test_merge_execute.py
mars/tensor/merge/union1d.py

This PR added support for `mt.union1d`.
Resolves #1146 .

Add support for `mt.union1d`

---

mars/learn/neighbors/_kneighbors_graph.py
mars/learn/neighbors/base.py
mars/learn/neighbors/tests/test_nearest_neighbors.py
mars/learn/utils/validation.py
mars/serialize/protos/operand.proto
mars/tensor/fuse/ne.py

This PR introduced `NearestNeighbors.kneighbors_graph`.
Resolves #1151 .

Add support for `NearestNeighbors.kneighbors_graph`

---

.gitignore
docs/source/dataframe/reference/api/mars.dataframe.DataFrame.rst
docs/source/dataframe/reference/api/mars.dataframe.DataFrame.shift.rst
docs/source/dataframe/reference/api/mars.dataframe.DataFrame.tshift.rst
docs/source/dataframe/reference/api/mars.dataframe.Series.rst
docs/source/dataframe/reference/api/mars.dataframe.Series.shift.rst
docs/source/dataframe/reference/api/mars.dataframe.Series.tshift.rst
docs/source/dataframe/reference/frame.rst
docs/source/dataframe/reference/series.rst
docs/source/dataframe/user_guide/10min.rst
docs/source/tensor/generated/mars.tensor.union1d.rst
mars/dataframe/base/__init__.py
mars/dataframe/base/shift.py
mars/dataframe/base/tests/test_base_execution.py
mars/dataframe/core.py
mars/dataframe/datasource/tests/test_datasource_execution.py
mars/dataframe/groupby/core.py
mars/dataframe/initializer.py
mars/dataframe/utils.py
mars/serialize/pbserializer.pyx
mars/serialize/protos/indexvalue.proto
mars/serialize/protos/operand.proto

This PR introduced `DataFrame.shift` and `Series.shift`.
Resolves #1118 .

Implements `{DataFrame, Series}.{shift, tshift}`

---

docs/source/dataframe/user_guide/10min.rst
mars/dataframe/base/shift.py
mars/dataframe/base/tests/test_base_execution.py
mars/dataframe/statistics/tests/test_statistics_execute.py
mars/dataframe/window/rolling/tests/test_rolling_execute.py
mars/learn/metrics/tests/test_classification.py
mars/tensor/core.py
mars/tensor/datastore/tests/test_datastore_execute.py
mars/tensor/indexing/getitem.py
mars/tensor/indexing/setitem.py
mars/tensor/indexing/tests/test_indexing.py
mars/tensor/indexing/tests/test_indexing_execute.py
mars/tensor/statistics/tests/test_statistics_execute.py
mars/tests/core.py

Support `Tensor.__setitem__` with bool indexing.
Partial fixes of #1114 .

Support `Tensor.__setitem__` with bool indexing

---

README.rst
docs/source/index.rst

This PR fixes some mistakes in examples in the doc.
N/A.

Fix some mistakes in the doc.

---

mars/dataframe/reduction/aggregation.py
mars/dataframe/window/aggregation.py
mars/dataframe/window/core.py
mars/dataframe/window/expanding/__init__.py
mars/dataframe/window/expanding/aggregation.py
mars/dataframe/window/expanding/core.py
mars/dataframe/window/expanding/tests/__init__.py
mars/dataframe/window/expanding/tests/test_expanding.py
mars/dataframe/window/expanding/tests/test_expanding_execute.py
mars/dataframe/window/rolling/aggregation.py
mars/dataframe/window/rolling/core.py
mars/serialize/protos/operand.proto

Add support of ``md.expanding``. The execution is done in two stages: the map stage and the combine stage. In the map stage, two chunks will be produced, i.e., the intermediate result chunk and the summary chunk. When producing the final result, all preceding summaries are collected together.
Part of #1138 is resolved.

Add support of `md.expanding`

---

mars/_utils.pyx
mars/compat.py
mars/dataframe/__init__.py
mars/dataframe/base/__init__.py
mars/dataframe/base/shift.py
mars/dataframe/base/tests/test_base_execution.py
mars/dataframe/core.py
mars/dataframe/datasource/tests/test_datasource_execution.py
mars/dataframe/groupby/core.py
mars/dataframe/initializer.py
mars/dataframe/utils.py
mars/serialize/pbserializer.pyx
mars/serialize/protos/indexvalue.proto
mars/serialize/protos/operand.proto

[BACKPORT] Implements `{DataFrame, Series}.{shift, tshift}` (#1157)

---

mars/tensor/__init__.py
mars/tensor/merge/__init__.py
mars/tensor/merge/concatenate.py
mars/tensor/merge/tests/test_merge_execute.py
mars/tensor/merge/union1d.py

[BACKPORT] Add support for `mt.union1d` (#1147)

---

.github/workflows/ci.yml
mars/core.py
mars/dataframe/__init__.py
mars/dataframe/core.py
mars/dataframe/plotting/__init__.py
mars/dataframe/plotting/core.py
mars/dataframe/plotting/tests/__init__.py
mars/dataframe/plotting/tests/test_plot.py

[BACKPORT] Add `plot` and relative functions for DataFrame and Series (#1143)

---

mars/dataframe/statistics/tests/test_statistics_execute.py
mars/dataframe/window/rolling/tests/test_rolling_execute.py
mars/tensor/core.py
mars/tensor/indexing/getitem.py
mars/tensor/indexing/setitem.py
mars/tensor/indexing/tests/test_indexing.py
mars/tensor/indexing/tests/test_indexing_execute.py
mars/tensor/statistics/tests/test_statistics_execute.py
mars/tests/core.py

[BACKPORT] Support `Tensor.__setitem__` with bool indexing (#1159)

---

mars/dataframe/merge/merge.py
mars/dataframe/reduction/__init__.py
mars/dataframe/reduction/core.py
mars/dataframe/reduction/nunique.py
mars/dataframe/reduction/tests/test_reduction.py
mars/dataframe/reduction/tests/test_reduction_execute.py
mars/dataframe/reduction/var.py
mars/serialize/protos/operand.proto

[BACKPORT]Implement DataFrame nunique (#1137)

---

.github/workflows/ci.yml
docs/requirements-doc.txt
mars/_version.py
mars/worker/storage/sharedstore.py
requirements-dev.txt
requirements.txt

Modify requirements to allow installing pyarrow>=0.17.0. An import issue is also fixed.
Fixes #1171 
Consider closing #1041 .

Allow using pyarrow==0.17.0

---

.github/workflows/ci.yml
docs/requirements-doc.txt
docs/source/contributing.rst
mars/_version.py
mars/worker/storage/sharedstore.py
requirements-dev.txt
requirements.txt

[BACKPORT] Allow pyarrow to use 0.17.0 (#1172)

---

docs/source/dataframe/reference/api/mars.dataframe.DataFrame.diff.rst
docs/source/dataframe/reference/api/mars.dataframe.Series.diff.rst
docs/source/dataframe/reference/frame.rst
docs/source/dataframe/reference/series.rst
mars/dataframe/base/__init__.py
mars/dataframe/base/diff.py
mars/dataframe/base/tests/test_base_execution.py
mars/serialize/protos/operand.proto

Implements {DataFrame,Series}.diff by calling shift when there are multiple chunks.
Fixes #1162

Implements {DataFrame,Series}.diff

---

mars/dataframe/base/__init__.py
mars/dataframe/base/diff.py
mars/dataframe/base/tests/test_base_execution.py
mars/serialize/protos/operand.proto

[BACKPORT] Implements {DataFrame,Series}.diff (#1174)

---

.github/workflows/ci.yml
docs/source/dataframe/reference/api/mars.dataframe.DataFrame.mod.rst
docs/source/dataframe/reference/api/mars.dataframe.DataFrame.rmod.rst
docs/source/dataframe/reference/api/mars.dataframe.Series.mod.rst
docs/source/dataframe/reference/api/mars.dataframe.Series.rmod.rst
docs/source/dataframe/reference/frame.rst
docs/source/dataframe/reference/series.rst
mars/dataframe/arithmetic/__init__.py
mars/dataframe/arithmetic/mod.py
mars/dataframe/arithmetic/tests/test_arithmetic.py
mars/dataframe/arithmetic/tests/test_arithmetic_execution.py

Add missing modulo operand for DataFrame and Series.
Fixes #1175

Support modulo operand for DataFrame

---

.gitignore
mars/dataframe/arithmetic/__init__.py
mars/dataframe/arithmetic/mod.py
mars/dataframe/arithmetic/tests/test_arithmetic.py
mars/dataframe/arithmetic/tests/test_arithmetic_execution.py

[BACKPORT] Support modulo operand for DataFrame (#1176)

---

mars/context.py
mars/dataframe/indexing/iloc.py
mars/dataframe/initializer.py
mars/learn/contrib/pytorch/dataset.py
mars/learn/contrib/pytorch/run_script.py
mars/learn/contrib/pytorch/tests/dataset_sample.py
mars/learn/contrib/pytorch/tests/integrated/test_distributed_dataset.py
mars/session.py
mars/tensor/datasource/array.py
mars/tensor/indexing/getitem.py
mars/tensor/indexing/index_lib.py
mars/web/session.py
mars/worker/transfer.py

Users can build tensor or series by names if they are named when executed, and pytorch dataset support passing both tensor or series.
Resolves #1189.

Support Mars Series in Pytorch Dataset

---

mars/context.py
mars/dataframe/indexing/iloc.py
mars/dataframe/initializer.py
mars/learn/contrib/pytorch/dataset.py
mars/learn/contrib/pytorch/run_script.py
mars/learn/contrib/pytorch/tests/dataset_sample.py
mars/learn/contrib/pytorch/tests/integrated/test_distributed_dataset.py
mars/session.py
mars/tensor/datasource/array.py
mars/tensor/indexing/getitem.py
mars/tensor/indexing/index_lib.py
mars/web/session.py
mars/worker/transfer.py

[BACKPORT] Support Mars Series in Pytorch Dataset (#1190)

---

docs/source/dataframe/reference/api/mars.dataframe.DataFrame.ewm.rst
docs/source/dataframe/reference/api/mars.dataframe.Series.ewm.rst
docs/source/dataframe/reference/frame.rst
docs/source/dataframe/reference/series.rst
docs/source/locale/zh_CN/LC_MESSAGES/dataframe/reference/api/mars.dataframe.DataFrame.ewm.po
docs/source/locale/zh_CN/LC_MESSAGES/dataframe/reference/api/mars.dataframe.DataFrame.po
docs/source/locale/zh_CN/LC_MESSAGES/dataframe/reference/api/mars.dataframe.DataFrame.round.po
docs/source/locale/zh_CN/LC_MESSAGES/dataframe/reference/api/mars.dataframe.Series.ewm.po
docs/source/locale/zh_CN/LC_MESSAGES/dataframe/reference/api/mars.dataframe.Series.po
docs/source/locale/zh_CN/LC_MESSAGES/dataframe/reference/api/mars.dataframe.Series.round.po
docs/source/locale/zh_CN/LC_MESSAGES/dataframe/reference/frame.po
docs/source/locale/zh_CN/LC_MESSAGES/dataframe/reference/general_functions.po
docs/source/locale/zh_CN/LC_MESSAGES/dataframe/reference/series.po
docs/source/locale/zh_CN/LC_MESSAGES/dataframe/user_guide/10min.po
mars/dataframe/window/aggregation.py
mars/dataframe/window/core.py
mars/dataframe/window/ewm/__init__.py
mars/dataframe/window/ewm/aggregation.py
mars/dataframe/window/ewm/core.py
mars/dataframe/window/ewm/tests/__init__.py
mars/dataframe/window/ewm/tests/test_ewm.py
mars/dataframe/window/ewm/tests/test_ewm_execute.py
mars/dataframe/window/expanding/aggregation.py
mars/tiles.py

Add support of {DataFrame,Series}.ewm. adjust=False is not supported currently.
Note: review after #1160 is merged.
Fixes #1138

Add support of {DataFrame,Series}.ewm

---

docs/source/tensor/generated/mars.tensor.trapz.rst
docs/source/tensor/math.rst
mars/serialize/protos/operand.proto
mars/tensor/__init__.py
mars/tensor/base/__init__.py
mars/tensor/base/tests/test_base_execute.py
mars/tensor/base/trapz.py

This PR implements `mt.trapz`.
Resolves #1203 .

Implements `mt.trapz`

---

mars/dataframe/__init__.py
mars/dataframe/base/isin.py
mars/dataframe/datasource/index.py
mars/dataframe/reduction/__init__.py
mars/dataframe/reduction/core.py
mars/dataframe/reduction/tests/test_reduction_execute.py
mars/dataframe/reduction/unique.py
mars/optimizes/tileable_graph/column_pruning.py

Support `DataFrame.unique` and return a Mars tensor.
Resolves #1204.

Add dataframe.unique support

---

mars/dataframe/base/standardize_range_index.py
mars/optimizes/tileable_graph/column_pruning.py
mars/optimizes/tileable_graph/core.py
mars/optimizes/tileable_graph/tests/test_column_pruning.py

Column pruning led to the wrong result, this PR fixes the behavior in some special cases.
Fixes #1214.

Fix wrong result of column pruning

---

docs/source/tensor/generated/mars.tensor.trapz.rst
docs/source/tensor/math.rst
mars/serialize/protos/operand.proto
mars/tensor/__init__.py
mars/tensor/base/__init__.py
mars/tensor/base/tests/test_base_execute.py
mars/tensor/base/trapz.py

[BACKPORT] Implements `mt.trapz` (#1205)

---

mars/dataframe/__init__.py
mars/dataframe/base/isin.py
mars/dataframe/datasource/index.py
mars/dataframe/reduction/__init__.py
mars/dataframe/reduction/core.py
mars/dataframe/reduction/tests/test_reduction_execute.py
mars/dataframe/reduction/unique.py
mars/optimizes/tileable_graph/column_pruning.py

[BACKPORT] Add dataframe.unique support (#1208)

---

docs/source/dataframe/reference/api/mars.dataframe.to_datetime.rst
docs/source/dataframe/reference/general_functions.rst
mars/dataframe/__init__.py
mars/dataframe/indexing/__init__.py
mars/dataframe/indexing/setitem.py
mars/dataframe/indexing/tests/test_indexing_execution.py
mars/dataframe/tseries/__init__.py
mars/dataframe/tseries/tests/__init__.py
mars/dataframe/tseries/tests/test_tseries.py
mars/dataframe/tseries/tests/test_tseries_execution.py
mars/dataframe/tseries/to_datetime.py
mars/serialize/protos/operand.proto

[BACKPORT] Implements `md.to_datetime`, support `__setitem__` for DataFrame as well (#1207)

---

.dockerignore
.github/workflows/ci.yml
.github/workflows/install-conda.sh
mars/deploy/kubernetes/docker/Dockerfile.base
mars/deploy/local/core.py
mars/deploy/local/tests/test_cluster.py
mars/operands.py
mars/scheduler/graph.py
mars/scheduler/operands/common.py
mars/utils.py
mars/web/__main__.py
mars/web/apihandlers.py
mars/web/session.py
mars/web/tests/test_api.py

Backport of #1229 and #1232
NA

[BACKPORT] Fix error in starting local cluster with IPython & latest gevent version (#1232)

---

mars/dataframe/base/standardize_range_index.py
mars/optimizes/tileable_graph/column_pruning.py
mars/optimizes/tileable_graph/core.py
mars/optimizes/tileable_graph/tests/test_column_pruning.py

[BACKPORT] Fix wrong result of column pruning (#1215)

---

mars/dataframe/base/__init__.py
mars/dataframe/base/astype.py
mars/dataframe/base/tests/test_base.py
mars/dataframe/base/tests/test_base_execution.py
mars/serialize/jsonserializer.pyx
mars/serialize/pbserializer.pyx
mars/web/apihandlers.py

[BACKPORT] Add support for Series.astype and DataFrame.astype (#1224)

---

mars/_version.py

[SKIP CI] Bump version to v0.5.0a1

---

mars/_version.py
mars/context.py
mars/dataframe/base/transform.py
mars/dataframe/groupby/transform.py
mars/deploy/local/tests/test_cluster.py
mars/executor.py
mars/operands.py
mars/remote/__init__.py
mars/remote/core.py
mars/remote/tests/__init__.py
mars/remote/tests/test_remote_function.py
mars/remote/utils.py
mars/serialize/jsonserializer.pyx
mars/serialize/pbserializer.pyx
mars/serialize/protos/operand.proto
mars/session.py
mars/utils.py

[BACKPORT] Add preliminary remote function support (#1238)

---

docs/source/dataframe/reference/api/mars.dataframe.groupby.GroupBy.size.rst
docs/source/dataframe/reference/frame.rst
docs/source/dataframe/reference/groupby.rst
docs/source/locale/zh_CN/LC_MESSAGES/dataframe/reference/api/mars.dataframe.groupby.GroupBy.size.po
docs/source/locale/zh_CN/LC_MESSAGES/dataframe/reference/groupby.po
mars/dataframe/groupby/__init__.py
mars/dataframe/groupby/aggregation.py
mars/dataframe/groupby/tests/test_groupby_execution.py
mars/dataframe/reduction/aggregation.py
mars/dataframe/reduction/tests/test_reduction_execute.py

Add size function for {DataFrame,Series}.agg() and GroupBy.
Fixes #1245

Add size function for dataframes and groupbys

---

mars/executor.py
mars/optimizes/tileable_graph/core.py
mars/optimizes/tileable_graph/tests/test_column_pruning.py
mars/tests/test_session.py
mars/utils.py

[BACKPORT] Fix `.fetch()` that may cause some op executed again (#1243)

---

docs/source/dataframe/reference/api/mars.dataframe.groupby.GroupBy.size.rst
docs/source/dataframe/reference/frame.rst
docs/source/dataframe/reference/groupby.rst
docs/source/locale/zh_CN/LC_MESSAGES/dataframe/reference/api/mars.dataframe.groupby.GroupBy.size.po
docs/source/locale/zh_CN/LC_MESSAGES/dataframe/reference/groupby.po
mars/dataframe/groupby/__init__.py
mars/dataframe/groupby/aggregation.py
mars/dataframe/groupby/tests/test_groupby_execution.py
mars/dataframe/reduction/aggregation.py
mars/dataframe/reduction/tests/test_reduction_execute.py
requirements-extra.txt

[BACKPORT] Add size function for dataframes and groupbys (#1250)

---

mars/_version.py
mars/deploy/local/tests/test_cluster.py
mars/operands.py
mars/remote/__init__.py
mars/remote/core.py
mars/remote/tests/test_remote_function.py
mars/session.py

This PR added support for running tileables inside functions which spawned via mr.spawn.
support part of #1227 .

Support running tileables inside functions which spawned via mr.spawn

---

mars/_version.py
mars/deploy/local/tests/test_cluster.py
mars/operands.py
mars/remote/__init__.py
mars/remote/core.py
mars/remote/tests/test_remote_function.py
mars/session.py

[BACKPORT] Support running tileables inside functions which spawned via mr.spawn (#1248)

---

docs/source/dataframe/reference/api/mars.dataframe.DataFrame.astype.rst
docs/source/dataframe/reference/api/mars.dataframe.DataFrame.iterrows.rst
docs/source/dataframe/reference/api/mars.dataframe.DataFrame.itertuples.rst
docs/source/dataframe/reference/api/mars.dataframe.Series.astype.rst
docs/source/dataframe/reference/frame.rst
docs/source/dataframe/reference/series.rst
docs/source/locale/zh_CN/LC_MESSAGES/dataframe/reference/api/mars.dataframe.DataFrame.astype.po
docs/source/locale/zh_CN/LC_MESSAGES/dataframe/reference/api/mars.dataframe.DataFrame.iterrows.po
docs/source/locale/zh_CN/LC_MESSAGES/dataframe/reference/api/mars.dataframe.DataFrame.itertuples.po
docs/source/locale/zh_CN/LC_MESSAGES/dataframe/reference/api/mars.dataframe.Series.astype.po
docs/source/locale/zh_CN/LC_MESSAGES/dataframe/reference/frame.po
docs/source/locale/zh_CN/LC_MESSAGES/dataframe/reference/series.po
mars/dataframe/core.py
mars/tests/test_session.py

[BACKPORT] Implements DataFrame.{iterrows, itertuples} (#1252)

---

docs/source/dataframe/reference/api/mars.dataframe.DataFrame.to_sql.rst
docs/source/dataframe/reference/api/mars.dataframe.Series.to_csv.rst
docs/source/dataframe/reference/api/mars.dataframe.Series.to_sql.rst
docs/source/dataframe/reference/frame.rst
docs/source/dataframe/reference/series.rst
docs/source/locale/zh_CN/LC_MESSAGES/dataframe/reference/api/mars.dataframe.DataFrame.to_sql.po
docs/source/locale/zh_CN/LC_MESSAGES/dataframe/reference/api/mars.dataframe.Series.to_csv.po
docs/source/locale/zh_CN/LC_MESSAGES/dataframe/reference/api/mars.dataframe.Series.to_sql.po
mars/_utils.pyx
mars/dataframe/datasource/read_sql_table.py
mars/dataframe/datastore/__init__.py
mars/dataframe/datastore/tests/test_datastore_execute.py
mars/dataframe/datastore/to_csv.py
mars/dataframe/datastore/to_sql.py
mars/dataframe/groupby/tests/test_groupby_execution.py

Add {DataFrame,Series}.to_sql() and Series.to_csv().
Fix partially #952. More studies to do for ``md.read_sql()``.

Add {DataFrame,Series}.to_sql() and Series.to_csv()

---

docs/source/dataframe/reference/api/mars.dataframe.DataFrame.drop.rst
docs/source/dataframe/reference/api/mars.dataframe.DataFrame.pop.rst
docs/source/dataframe/reference/api/mars.dataframe.Series.drop.rst
docs/source/dataframe/reference/frame.rst
docs/source/dataframe/reference/series.rst
docs/source/locale/zh_CN/LC_MESSAGES/dataframe/reference/api/mars.dataframe.DataFrame.drop.po
docs/source/locale/zh_CN/LC_MESSAGES/dataframe/reference/api/mars.dataframe.DataFrame.pop.po
docs/source/locale/zh_CN/LC_MESSAGES/dataframe/reference/api/mars.dataframe.Series.drop.po
mars/dataframe/base/__init__.py
mars/dataframe/base/drop.py
mars/dataframe/base/tests/test_base.py
mars/dataframe/base/tests/test_base_execution.py
mars/dataframe/datasource/index.py
mars/serialize/protos/operand.proto
mars/tests/core.py

[BACKPORT] Add support for {DataFrame,Series,Index}.drop (#1263)

---

docs/source/dataframe/reference/api/mars.dataframe.DataFrame.to_sql.rst
docs/source/dataframe/reference/api/mars.dataframe.Series.to_csv.rst
docs/source/dataframe/reference/api/mars.dataframe.Series.to_sql.rst
docs/source/dataframe/reference/frame.rst
docs/source/dataframe/reference/series.rst
docs/source/locale/zh_CN/LC_MESSAGES/dataframe/reference/api/mars.dataframe.DataFrame.to_sql.po
docs/source/locale/zh_CN/LC_MESSAGES/dataframe/reference/api/mars.dataframe.Series.to_csv.po
docs/source/locale/zh_CN/LC_MESSAGES/dataframe/reference/api/mars.dataframe.Series.to_sql.po
mars/_utils.pyx
mars/dataframe/datasource/read_sql_table.py
mars/dataframe/datastore/__init__.py
mars/dataframe/datastore/tests/test_datastore_execute.py
mars/dataframe/datastore/to_csv.py
mars/dataframe/datastore/to_sql.py
mars/dataframe/groupby/tests/test_groupby_execution.py

[BACKPORT] Add {DataFrame,Series}.to_sql() and Series.to_csv() (#1264)

---

.github/workflows/install-conda.sh
mars/deploy/local/tests/test_cluster.py
mars/scheduler/graph.py

[BACKPORT] Fix `NearestNeighbors` that run failed in cluster mode (#1262)

---

.github/workflows/install-conda.sh
mars/deploy/local/tests/test_cluster.py
mars/scheduler/graph.py
mars/utils.py

Fix graph hang on tile failure and execution failure. Also fix exception log missing issue.
Fixes #1271

Fix graph hang on tile failure and execution failure

---

mars/deploy/local/tests/test_cluster.py
mars/scheduler/graph.py
mars/utils.py

[BACKPORT] Fix graph hang on tile failure and execution failure (#1272)

---

mars/scheduler/tests/integrated/test_normal_execution.py
mars/web/server.py
mars/worker/service.py
mars/worker/storage/client.py

[BACKPORT] Fix failure for None-result spawn functions (#1276)

---

.github/workflows/ci.yml
mars/api.py
mars/learn/contrib/tsfresh/__init__.py
mars/learn/contrib/tsfresh/core.py
mars/learn/contrib/tsfresh/tests/__init__.py
mars/learn/contrib/tsfresh/tests/integrated/test_distributed_tsfresh.py
mars/learn/contrib/tsfresh/tests/test_tsfresh.py
mars/remote/utils.py
mars/session.py
mars/web/server.py
mars/web/session.py

Add MarsDistributor for tsfresh library to distribute local dataset into multiple workers.
Deal with #1218 (please check if the issue can be closed after this PR is merged).

Add MarsDistributor for tsfresh library

---

.github/workflows/ci.yml
mars/api.py
mars/learn/contrib/tsfresh/__init__.py
mars/learn/contrib/tsfresh/core.py
mars/learn/contrib/tsfresh/tests/__init__.py
mars/learn/contrib/tsfresh/tests/integrated/test_distributed_tsfresh.py
mars/learn/contrib/tsfresh/tests/test_tsfresh.py
mars/remote/utils.py
mars/session.py
mars/web/server.py
mars/web/session.py

[BACKPORT] Add MarsDistributor for tsfresh library (#1277)

---

docs/source/dataframe/reference/api/mars.dataframe.DataFrame.drop_duplicates.rst
docs/source/dataframe/reference/api/mars.dataframe.DataFrame.rst
docs/source/dataframe/reference/api/mars.dataframe.Series.drop_duplicates.rst
docs/source/dataframe/reference/api/mars.dataframe.Series.rst
docs/source/dataframe/reference/frame.rst
docs/source/dataframe/reference/series.rst
mars/dataframe/base/__init__.py
mars/dataframe/base/drop_duplicates.py
mars/dataframe/base/tests/test_base.py
mars/dataframe/base/tests/test_base_execution.py
mars/dataframe/core.py
mars/dataframe/merge/concat.py
mars/dataframe/utils.py
mars/learn/__init__.py
mars/serialize/protos/operand.proto

This PR added support for `{DataFrame,Series,Index}.drop_duplicates`.
Resolves #1241 .

Implements `{DataFrame,Series,Index}.drop_duplicates`

---

mars/deploy/local/tests/test_cluster.py
mars/remote/core.py
mars/remote/operands.py
mars/remote/tests/test_remote_function.py

This PR added support for fusion in Mars Remote.
Fixes #1269 .

Support fuse for Mars Remote

---

docs/source/dataframe/reference/api/mars.dataframe.DataFrame.melt.rst
docs/source/dataframe/reference/api/mars.dataframe.melt.rst
docs/source/dataframe/reference/frame.rst
docs/source/dataframe/reference/general_functions.rst
mars/dataframe/__init__.py
mars/dataframe/base/__init__.py
mars/dataframe/base/melt.py
mars/dataframe/base/tests/test_base_execution.py
mars/deploy/kubernetes/config.py
mars/serialize/protos/operand.proto

Implements DataFrame.melt.
Fixes #1279

Implements DataFrame.melt

---

mars/api.py
mars/config.py
mars/dataframe/datasource/read_csv.py
mars/dataframe/datasource/tests/test_hdfs.py
mars/deploy/local/tests/test_cluster.py
mars/filesystem.py
mars/graph.pyx
mars/serialize/core.pxd
mars/serialize/core.pyx
mars/serialize/dataserializer.py
mars/serialize/jsonserializer.pyx
mars/serialize/pbserializer.pyx
mars/serialize/tests/test_serialize.py
mars/session.py
mars/utils.py
mars/web/apihandlers.py
mars/web/server.py
mars/web/session.py
mars/web/tests/test_api.py
mars/worker/dataio.py
mars/worker/storage/diskhandler.py
mars/worker/storage/sharedhandler.py
mars/worker/storage/tests/test_disk_io.py
mars/worker/storage/tests/test_shared_io.py
mars/worker/tests/test_dataio.py
mars/worker/transfer.py
requirements-extra.txt
requirements.txt

[ENH] Allow client-side to use pickle to serialize / deserialize tensor data (#1289)

---

mars/tensor/indexing/getitem.py

[BACKPORT] Fix shape calculation in TensorIndex for tensor.__setitem__ (#1283)

---

docs/source/dataframe/reference/api/mars.dataframe.DataFrame.drop_duplicates.rst
docs/source/dataframe/reference/api/mars.dataframe.DataFrame.rst
docs/source/dataframe/reference/api/mars.dataframe.Series.drop_duplicates.rst
docs/source/dataframe/reference/api/mars.dataframe.Series.rst
docs/source/dataframe/reference/frame.rst
docs/source/dataframe/reference/series.rst
mars/dataframe/base/__init__.py
mars/dataframe/base/drop_duplicates.py
mars/dataframe/base/tests/test_base.py
mars/dataframe/base/tests/test_base_execution.py
mars/dataframe/core.py
mars/dataframe/merge/concat.py
mars/dataframe/utils.py
mars/learn/__init__.py
mars/serialize/protos/operand.proto

[BACKPORT] Implements `{DataFrame,Series,Index}.drop_duplicates` (#1285)

---

mars/deploy/local/tests/test_cluster.py
mars/remote/core.py
mars/remote/operands.py
mars/remote/tests/test_remote_function.py

[BACKPORT] Support fuse for Mars Remote (#1287)

---

docs/source/dataframe/reference/api/mars.dataframe.DataFrame.melt.rst
docs/source/dataframe/reference/api/mars.dataframe.melt.rst
docs/source/dataframe/reference/frame.rst
docs/source/dataframe/reference/general_functions.rst
mars/dataframe/__init__.py
mars/dataframe/base/__init__.py
mars/dataframe/base/melt.py
mars/dataframe/base/tests/test_base_execution.py
mars/deploy/kubernetes/config.py
mars/serialize/protos/operand.proto

[BACKPORT] Implement DataFrame.melt (#1284)

---

mars/_utils.pyx
mars/context.py
mars/deploy/local/tests/test_cluster.py
mars/executor.py
mars/remote/core.py
mars/remote/tests/test_remote_function.py
mars/remote/utils.py
mars/session.py
mars/utils.py

[BACKPORT] Support tileables as arguments for spawned functions (#1296)

---

mars/api.py
mars/context.py
mars/dataframe/__init__.py
mars/dataframe/initializer.py
mars/deploy/local/tests/test_cluster.py
mars/executor.py
mars/learn/contrib/pytorch/dataset.py
mars/learn/contrib/pytorch/run_script.py
mars/learn/contrib/pytorch/tests/dataset_sample.py
mars/learn/contrib/pytorch/tests/integrated/test_distributed_dataset.py
mars/scheduler/tests/integrated/test_normal_execution.py
mars/session.py
mars/tensor/__init__.py
mars/tensor/datasource/__init__.py
mars/tensor/datasource/array.py
mars/tests/test_session.py
mars/web/apihandlers.py
mars/web/session.py

- Support create session from environment variables including 'MARS_SCHEDULER_ADDRESS' and 'MARS_SESSION_ID'.
- Add `named` support for local and cluster mode.

Support create session from environment variables

---

docs/source/locale/zh_CN/LC_MESSAGES/reference/dataframe/api/mars.dataframe.Series.to_frame.po
docs/source/locale/zh_CN/LC_MESSAGES/reference/dataframe/series.po
docs/source/reference/dataframe/api/mars.dataframe.Series.to_frame.rst
docs/source/reference/dataframe/series.rst
mars/dataframe/__init__.py
mars/dataframe/core.py
mars/dataframe/datasource/from_tensor.py
mars/dataframe/initializer.py
mars/dataframe/tests/test_core.py
mars/dataframe/tests/test_utils.py
mars/tensor/datasource/from_dataframe.py
mars/tensor/datasource/tests/test_datasource_execute.py
mars/web/templates/base.html

Implements {Series,Index}.to_frame() and Index.to_series(). Fixes MultiIndex.to_pandas() as well.
Fixes #1308
Fixes #1309
Fixes #1316

Implements {Series,Index}.to_frame() and Index.to_series()

---

mars/api.py
mars/context.py
mars/dataframe/__init__.py
mars/dataframe/initializer.py
mars/deploy/local/tests/test_cluster.py
mars/executor.py
mars/learn/contrib/pytorch/dataset.py
mars/learn/contrib/pytorch/run_script.py
mars/learn/contrib/pytorch/tests/dataset_sample.py
mars/learn/contrib/pytorch/tests/integrated/test_distributed_dataset.py
mars/scheduler/tests/integrated/test_normal_execution.py
mars/session.py
mars/tensor/__init__.py
mars/tensor/datasource/__init__.py
mars/tensor/datasource/array.py
mars/tests/test_session.py
mars/web/apihandlers.py
mars/web/session.py

[BACKPORT] Support create session from environment variables (#1265)

---

docs/source/dataframe/reference/series.rst
docs/source/locale/zh_CN/LC_MESSAGES/dataframe/reference/api/mars.dataframe.Series.to_frame.po
mars/dataframe/__init__.py
mars/dataframe/core.py
mars/dataframe/datasource/from_tensor.py
mars/dataframe/initializer.py
mars/dataframe/tests/test_core.py
mars/dataframe/tests/test_utils.py
mars/tensor/datasource/from_dataframe.py
mars/tensor/datasource/tests/test_datasource_execute.py
mars/web/templates/base.html

[BACKPORT] Implements {Series,Index}.to_frame() and Index.to_series() (#1317)

---

mars/core.py
mars/dataframe/base/__init__.py
mars/dataframe/base/set_label.py
mars/dataframe/base/tests/test_base_execution.py
mars/dataframe/core.py
mars/serialize/protos/operand.proto

This PR added support for setting columns for DataFrame.
Resolves #1305 .

Support setting columns for DataFrame

---

mars/core.py
mars/dataframe/base/__init__.py
mars/dataframe/base/set_label.py
mars/dataframe/base/tests/test_base_execution.py
mars/dataframe/core.py
mars/serialize/protos/operand.proto

[BACKPORT] Support setting columns for DataFrame (#1326)

---

mars/lib/groupby_wrapper.py
mars/lib/tests/test_lib.py
mars/utils.py
mars/worker/execution.py

[BACKPORT] Fix error in calc_data_size() for GroupByWrapper (#1307)

---

mars/dataframe/arithmetic/core.py
mars/dataframe/arithmetic/tests/test_comparison.py
mars/dataframe/base/reset_index.py
mars/dataframe/base/tests/test_base.py
mars/dataframe/base/tests/test_base_execution.py

[BACKPORT]Fix wrong columns value in `reset_index` (#1320)

---

mars/_version.py

[Skip CI] Bump version to 0.4.2

---

requirements-wheel.txt

Use latest pandas wheel for Python 3.8

---

mars/dataframe/datasource/read_sql.py

Stop using ``WHERE 1=0`` to detect output schema in SQL statements to avoid potential syntax error.
Fixes #1334

Remove reliance on ``WHERE 1=0`` in ``read_sql``

---

mars/dataframe/datasource/read_sql.py

[BACKPORT] Remove reliance on `WHERE 1=0` in `read_sql` (#1335)

---

mars/_version.py

[Skip CI] Bump version to v0.5.0a3

---

docs/source/locale/zh_CN/LC_MESSAGES/reference/dataframe/api/mars.dataframe.DataFrame.rename.po
docs/source/locale/zh_CN/LC_MESSAGES/reference/learn/generated/mars.learn.model_selection.train_test_split.po
docs/source/reference/dataframe/api/mars.dataframe.DataFrame.rename.rst
docs/source/reference/dataframe/frame.rst
mars/dataframe/base/__init__.py
mars/dataframe/base/rename.py
mars/dataframe/base/tests/test_base_execution.py
mars/serialize/protos/operand.proto

Implements DataFrame.rename.
Fixes #1337

Implements DataFrame.rename

---

.github/workflows/run-tests.sh
mars/learn/contrib/lightgbm/train.py
mars/learn/contrib/pytorch/run_script.py
mars/learn/contrib/tensorflow/run_script.py
mars/learn/contrib/xgboost/train.py
mars/learn/operands.py
mars/operands.py
mars/remote/__init__.py
mars/remote/run_script.py
mars/remote/tests/test_run_script.py
mars/serialize/protos/operand.proto

- Add `RunScript` operand support.
- `RunPyTorch` and `RunTensorFlow` will be subclass of `RunScript`.
Resolves #1290.

Add `run_script` support

---

mars/dataframe/datasource/read_csv.py
mars/dataframe/indexing/getitem.py
mars/dataframe/indexing/iloc.py
mars/dataframe/indexing/tests/test_indexing.py
mars/dataframe/indexing/tests/test_indexing_execution.py
mars/executor.py
mars/graph.pyx
mars/optimizes/chunk_graph/fuse.py
mars/optimizes/runtime/optimizers/core.py
mars/optimizes/runtime/optimizers/cp.py
mars/optimizes/runtime/optimizers/dataframe.py
mars/optimizes/runtime/optimizers/ne.py
mars/optimizes/runtime/optimizers/tests/test_compose.py
mars/tensor/base/partition.py
mars/tensor/fuse/tests/test_cupy_execute.py
mars/tensor/indexing/index_lib.py
mars/tensor/statistics/histogram.py
mars/tests/core.py
mars/tests/test_utils.py
mars/utils.py
setup.py

[BACKPORT] Optimize DataFrame.{head, tail} when DataFrame has unknown chunk shape (#1328)

---

docs/source/locale/zh_CN/LC_MESSAGES/reference/dataframe/api/mars.dataframe.Series.rename.po
docs/source/reference/dataframe/api/mars.dataframe.Series.rename.rst
docs/source/reference/dataframe/series.rst
mars/dataframe/base/__init__.py
mars/dataframe/base/rename.py
mars/dataframe/base/tests/test_base_execution.py
mars/dataframe/core.py
mars/dataframe/initializer.py
mars/learn/operands.py

Implements {Series,Index}.rename.
NA

Implements {Series,Index}.rename

---

docs/source/dataframe/reference/api/mars.dataframe.DataFrame.rename.rst
docs/source/dataframe/reference/frame.rst
docs/source/locale/zh_CN/LC_MESSAGES/reference/dataframe/api/mars.dataframe.DataFrame.rename.po
docs/source/locale/zh_CN/LC_MESSAGES/reference/learn/generated/mars.learn.model_selection.train_test_split.po
mars/dataframe/base/__init__.py
mars/dataframe/base/rename.py
mars/dataframe/base/tests/test_base_execution.py
mars/dataframe/core.py
mars/dataframe/initializer.py
mars/serialize/protos/operand.proto

[BACKPORT] Implements {DataFrame,Series,Index}.rename (#1359) (#1361)

---

mars/deploy/local/tests/test_cluster.py
mars/learn/metrics/_ranking.py
mars/optimizes/chunk_graph/fuse.py
mars/scheduler/assigner.py
mars/scheduler/graph.py
mars/scheduler/operands/base.py
mars/scheduler/operands/common.py
mars/scheduler/tests/test_session.py
mars/tensor/indexing/getitem.py
mars/tensor/lib/index_tricks.py
mars/web/session.py
mars/web/tests/test_api.py
setup.py

[BACKPORT] Fix hang for distributed `roc_curve` (#1362)

---

mars/dataframe/datasource/read_sql.py
mars/dataframe/datasource/tests/test_datasource_execution.py
mars/scheduler/graph.py
mars/scheduler/tests/integrated/test_normal_execution.py
mars/scheduler/tests/test_graph.py

[BACKPORT] Fix read_sql when no data selected & refine error when no worker attached (#1371)

---

mars/lib/sparse/__init__.py
mars/lib/sparse/array.py
mars/serialize/protos/operand.proto
mars/tensor/__init__.py
mars/tensor/arithmetic/core.py
mars/tensor/special/__init__.py
mars/tensor/special/core.py
mars/tensor/special/entr.py
mars/tensor/special/erf.py
mars/tensor/special/gammaln.py
mars/tensor/special/rel_entr.py
mars/tensor/special/tests/test_special.py
mars/tensor/special/tests/test_special_execute.py
mars/tensor/stats/__init__.py
mars/tensor/stats/entropy.py
mars/tensor/stats/tests/__init__.py
mars/tensor/stats/tests/test_stats_execute.py

This PR added:
* `mars.tensor.special.entr`.
* `mars.tensor.special.rel_entr`.
* `mars.tensor.stats.entropy`.
Resolves #1375 .

Implements `mars.tensor.stats.entropy`

---

mars/lib/sparse/__init__.py
mars/lib/sparse/array.py
mars/serialize/protos/operand.proto
mars/tensor/__init__.py
mars/tensor/arithmetic/core.py
mars/tensor/special/core.py
mars/tensor/special/entr.py
mars/tensor/special/erf.py
mars/tensor/special/gammaln.py
mars/tensor/special/rel_entr.py
mars/tensor/special/tests/test_special_execute.py
mars/tensor/stats/__init__.py
mars/tensor/stats/entropy.py
mars/tensor/stats/tests/__init__.py
mars/tensor/stats/tests/test_stats_execute.py

[BACKPORT] Implements `mars.tensor.stats.entropy` (#1376)

---

mars/dataframe/datasource/read_csv.py
mars/dataframe/datasource/read_sql.py
mars/dataframe/datasource/tests/test_datasource_execution.py
mars/dataframe/indexing/iloc.py
mars/dataframe/indexing/loc.py
mars/dataframe/indexing/tests/test_indexing.py
mars/dataframe/indexing/tests/test_indexing_execution.py
mars/optimizes/runtime/optimizers/dataframe.py

[BACKPORT] Optimize `read_sql` + `head` (#1377)

---

mars/cluster_info.py
mars/web/server.py
mars/web/task_pages.py
mars/web/templates/base.html
mars/web/templates/scheduler_pages/list.html
mars/web/templates/worker_pages/list.html
mars/web/worker_pages.py

Fix progress display for bokeh 2.1.x. The problem is caused by conflicts between JS code of bokeh and bootstrap-table.
Fixes #1381

Fix progress display for bokeh 2.1.x

---

mars/cluster_info.py
mars/web/server.py
mars/web/task_pages.py
mars/web/templates/base.html
mars/web/templates/scheduler_pages/list.html
mars/web/templates/worker_pages/list.html
mars/web/worker_pages.py

[BACKPORT] Fix progress display for bokeh 2.1.x (#1382)

---

.github/workflows/install-minikube.sh
mars/deploy/local/tests/test_cluster.py
mars/executor.py
mars/learn/decomposition/pca.py
mars/learn/metrics/_ranking.py
mars/learn/metrics/tests/integrated/__init__.py
mars/learn/metrics/tests/integrated/test_ranking.py
mars/learn/semi_supervised/_label_propagation.py
mars/learn/tests/integrated/base.py
mars/scheduler/graph.py
mars/worker/tests/test_transfer.py
mars/worker/transfer.py

This PR tried to fix hang for distributed `roc_curve`.
Fixes #1363 .

Fix hang for distributed roc_curve

---

.github/workflows/install-minikube.sh
mars/deploy/local/tests/test_cluster.py
mars/executor.py
mars/learn/decomposition/pca.py
mars/learn/metrics/_ranking.py
mars/learn/metrics/tests/integrated/__init__.py
mars/learn/metrics/tests/integrated/test_ranking.py
mars/learn/semi_supervised/_label_propagation.py
mars/learn/tests/integrated/base.py
mars/scheduler/graph.py
mars/worker/tests/test_transfer.py
mars/worker/transfer.py

[BACKPORT] Fix hang for distributed roc_curve (#1380)

---

.github/workflows/run-tests.sh
mars/dataframe/datasource/read_csv.py
mars/filesystem.py
mars/scheduler/graph.py
mars/scheduler/operands/shuffle.py
mars/tests/test_filesystem.py

[BACKPORT] Make local filesystem work when PyArrow not installed (#1356)

---

.github/workflows/run-tests.sh
mars/learn/contrib/lightgbm/train.py
mars/learn/contrib/pytorch/run_script.py
mars/learn/contrib/tensorflow/run_script.py
mars/learn/contrib/xgboost/train.py
mars/learn/operands.py
mars/operands.py
mars/remote/__init__.py
mars/remote/run_script.py
mars/remote/tests/test_run_script.py
mars/serialize/protos/operand.proto

[BACKPORT] Add `run_script` support (#1299)

---

mars/deploy/local/tests/test_cluster.py
mars/learn/__init__.py
mars/learn/utils/shuffle.py
mars/remote/core.py
mars/remote/tests/test_remote_function.py
mars/serialize/protos/fusechunk.proto

This PR fixes serialization issue when remote function has argument which is an executed tileable.
Fixes #1393 .

Fix serialization issue when remote function has argument which is an executed tileable

---

mars/learn/contrib/lightgbm/align.py
mars/learn/contrib/lightgbm/classifier.py
mars/learn/contrib/lightgbm/ranker.py
mars/learn/contrib/lightgbm/regressor.py
mars/learn/contrib/lightgbm/tests/integrated/test_distributed_lightgbm.py
mars/learn/contrib/lightgbm/train.py
mars/scheduler/graph.py

This PR tries to fix LightGBM when input tileables have unknown shape
Fixes #1395 .

Fix LightGBM when input tileables have unknown shape

---

mars/_version.py

[Skip CI] Bump version to v0.5.0b1

---

setup.py

Specifying encoding for long_description.
NA

Specifying encoding for long_description

---

mars/deploy/local/tests/test_cluster.py
mars/learn/__init__.py
mars/learn/utils/shuffle.py
mars/remote/core.py
mars/remote/tests/test_remote_function.py

[BACKPORT] Fix serialization issue when remote function has executed tileable arguments (#1394)

---

mars/_version.py
mars/learn/contrib/lightgbm/align.py
mars/learn/contrib/lightgbm/classifier.py
mars/learn/contrib/lightgbm/ranker.py
mars/learn/contrib/lightgbm/regressor.py
mars/learn/contrib/lightgbm/tests/integrated/test_distributed_lightgbm.py
mars/learn/contrib/lightgbm/train.py
mars/scheduler/graph.py
setup.py

[BACKPORT] Fix LightGBM when input tileables have unknown shape (#1396)

---

mars/api.py
mars/context.py
mars/scheduler/graph.py
mars/scheduler/tests/integrated/base.py
mars/scheduler/tests/integrated/test_normal_execution.py
mars/scheduler/tests/integrated/test_worker_failover.py
mars/session.py
mars/worker/calc.py
mars/worker/daemon.py
mars/worker/dispatcher.py
mars/worker/execution.py
mars/worker/tests/base.py
mars/worker/tests/test_calc.py
mars/worker/tests/test_dispatcher.py
mars/worker/tests/test_transfer.py

[BACKPORT] Create backup CalcActor when spawning a new graph in mars.remote (#1411)

---

mars/dataframe/datasource/read_sql.py
mars/operands.py
mars/utils.py
mars/worker/execution.py

[BACKPORT] Fix query alias & add estimation for object types (#1416)

---

mars/learn/contrib/lightgbm/tests/test_ranker.py
mars/learn/contrib/lightgbm/tests/test_regressor.py
mars/learn/contrib/lightgbm/train.py

[BACKPORT] Fix the dtype of LightGBM model's predicted results (#1419)

---

mars/dataframe/base/tests/test_base_execution.py
mars/dataframe/base/transform.py

[BACKPORT] Fix the error raised when inferring dtype in DataFrame.transform (#1424)

---

.github/workflows/ci.yml
mars/dataframe/core.py
mars/dataframe/sort/psrs.py
mars/dataframe/utils.py
mars/learn/cluster/_k_means_common.py
mars/learn/cluster/_kmeans.py
mars/learn/tests/integrated/base.py
mars/operands.py
mars/scheduler/operands/base.py
mars/scheduler/operands/common.py
mars/scheduler/operands/shuffle.py
mars/scheduler/operands/successors_exclusive.py
mars/scheduler/operands/tests/test_common_exec.py
mars/scheduler/tests/integrated/base.py
mars/scheduler/tests/integrated/test_normal_execution.py
mars/serialize/protos/indexvalue.proto
mars/tensor/special/rel_entr.py
mars/utils.py
mars/web/tests/test_api.py
mars/worker/calc.py
mars/worker/execution.py
mars/worker/service.py
mars/worker/storage/sharedstore.py
mars/worker/storage/tests/test_objectholder.py
mars/worker/tests/test_execution.py

Fix crash when storing data inside Docker containers by refining memory estimation and reducing total size of shared store given code of Plasma Store.
Fixes #1430

Fix crash when storing data inside Docker containers

---

.github/workflows/ci.yml
mars/dataframe/core.py
mars/dataframe/sort/psrs.py
mars/dataframe/utils.py
mars/learn/cluster/_k_means_common.py
mars/learn/cluster/_kmeans.py
mars/learn/tests/integrated/base.py
mars/operands.py
mars/scheduler/operands/base.py
mars/scheduler/operands/common.py
mars/scheduler/operands/shuffle.py
mars/scheduler/operands/successors_exclusive.py
mars/scheduler/operands/tests/test_common_exec.py
mars/scheduler/tests/integrated/base.py
mars/scheduler/tests/integrated/test_normal_execution.py
mars/serialize/protos/indexvalue.proto
mars/tensor/special/rel_entr.py
mars/utils.py
mars/web/tests/test_api.py
mars/worker/calc.py
mars/worker/execution.py
mars/worker/service.py
mars/worker/storage/sharedstore.py
mars/worker/storage/tests/test_objectholder.py
mars/worker/tests/test_execution.py
mars/worker/transfer.py
requirements-dev.txt
requirements.txt

[BACKPORT] Fix crash when storing data inside Docker containers (#1429)

---

mars/dataframe/__init__.py
mars/dataframe/arrays.py
mars/dataframe/tests/test_arrays.py
mars/dataframe/utils.py
mars/serialize/dataserializer.py

This PR added support for arrow-based string dtype.
Resolves #1439 .

Add support for arrow-based string dtype

---

docs/source/reference/dataframe/api/mars.dataframe.DataFrame.memory_usage.rst
docs/source/reference/dataframe/api/mars.dataframe.Series.memory_usage.rst
docs/source/reference/dataframe/frame.rst
docs/source/reference/dataframe/series.rst
mars/dataframe/base/__init__.py
mars/dataframe/base/memory_usage.py
mars/dataframe/base/tests/test_base.py
mars/dataframe/base/tests/test_base_execution.py
mars/serialize/protos/operand.proto

Support memory_usage on md.{DataFrame,Series,Index}.
Fixes #1216

Support memory_usage on DataFrame objects

---

.github/workflows/ci.yml
mars/dataframe/__init__.py
mars/dataframe/arrays.py
mars/dataframe/tests/test_arrays.py
mars/dataframe/utils.py
mars/serialize/dataserializer.py

[BACKPORT] Add support for arrow-based string dtype (#1438)

---

mars/actors/pool/gevent_pool.pyx
mars/deploy/local/tests/test_cluster.py
mars/learn/cluster/_kmeans.py
mars/promise.py

This PR fixes kmeans hang for local cluster
Fixes #1444 .

Fix kmeans hang for local cluster

---

mars/dataframe/core.py
mars/dataframe/datasource/read_sql.py
mars/dataframe/indexing/loc.py
mars/learn/utils/shuffle.py
mars/tensor/base/repeat.py
mars/tensor/base/unique.py
mars/tensor/datasource/diag.py
mars/tensor/datasource/from_tiledb.py
mars/tensor/datasource/tri.py
mars/tensor/indexing/core.py
mars/tensor/indexing/index_lib.py
mars/tensor/linalg/core.py
mars/tensor/random/core.py
mars/tensor/reshape/reshape.py
mars/tensor/spatial/distance/pdist.py
mars/tensor/utils.py
mars/tests/core.py

Fix failed when serializing `LearnShuffle` operand & `AttributeError` when call `MultiIndex.to_pandas()`.
Fixes #1441.
Fixes #1433.

Fix failed when serializing `LearnShuffle` operand.

---

mars/_version.py

[Skip CI] Bump version to v0.5.0b3

---

mars/_version.py
mars/dataframe/core.py
mars/dataframe/datasource/read_sql.py
mars/dataframe/indexing/loc.py
mars/learn/utils/shuffle.py
mars/tensor/base/repeat.py
mars/tensor/base/unique.py
mars/tensor/datasource/diag.py
mars/tensor/datasource/from_tiledb.py
mars/tensor/datasource/tri.py
mars/tensor/indexing/core.py
mars/tensor/indexing/index_lib.py
mars/tensor/linalg/core.py
mars/tensor/random/core.py
mars/tensor/reshape/reshape.py
mars/tensor/spatial/distance/pdist.py
mars/tensor/utils.py
mars/tests/core.py

[BACKPORT] Fix failed when serializing `LearnShuffle` operand. (#1442)

---

.github/workflows/ci.yml
.github/workflows/reload-env.sh
docs/source/dataframe/reference/api/mars.dataframe.DataFrame.memory_usage.rst
docs/source/dataframe/reference/api/mars.dataframe.Series.memory_usage.rst
docs/source/dataframe/reference/frame.rst
mars/dataframe/base/__init__.py
mars/dataframe/base/memory_usage.py
mars/dataframe/base/tests/test_base.py
mars/dataframe/base/tests/test_base_execution.py
mars/serialize/protos/operand.proto
setup.py

[BACKPORT] Add support for memory usage (#1217)

---

.github/workflows/ci.yml
.github/workflows/reload-env.sh
mars/actors/pool/gevent_pool.pyx
mars/actors/pool/tests/test_gevent_pool.py
mars/base_app.py
mars/context.py
mars/promise.py
mars/serialize/protos/__init__.py
mars/worker/__init__.py
mars/worker/events.py
mars/worker/execution.py
mars/worker/service.py
mars/worker/storage/client.py
mars/worker/tests/test_events.py
mars/worker/tests/test_transfer.py
mars/worker/transfer.py
mars/worker/utils.py
setup.py

Use weakref in promise.all_. Add other memory optimizations as well.
Fixes #1451

Fix reference cycle in promise.all_

---

.github/workflows/ci.yml
mars/actors/pool/gevent_pool.pyx
mars/actors/pool/tests/test_gevent_pool.py
mars/base_app.py
mars/context.py
mars/dataframe/datasource/read_sql.py
mars/promise.py
mars/serialize/protos/__init__.py
mars/worker/__init__.py
mars/worker/events.py
mars/worker/execution.py
mars/worker/service.py
mars/worker/storage/client.py
mars/worker/tests/test_events.py
mars/worker/tests/test_transfer.py
mars/worker/transfer.py
mars/worker/utils.py

[BACKPORT] Fix reference cycle in promise.all_ (#1452)

---

mars/actors/pool/gevent_pool.pyx
mars/base_app.py
mars/core.py
mars/dataframe/datasource/read_sql.py
mars/deploy/local/tests/test_cluster.py
mars/learn/cluster/_kmeans.py
mars/node_info.py
mars/promise.py

[BACKPORT] Fix kmeans hang for local cluster (#1445)

---

mars/_utils.pyx
mars/core.py
mars/dataframe/arrays.py
mars/dataframe/base/rechunk.py
mars/dataframe/datasource/read_sql.py
mars/dataframe/sort/tests/test_sort_execute.py
mars/dataframe/tests/test_arrays.py
mars/dataframe/utils.py
mars/scheduler/tests/integrated/test_normal_execution.py

This PR supports ArrowStringDtype for DataFrame.sort_values()
Fixes #1454 .
Fixes #1448 .

Support ArrowStringDtype for DataFrame.sort_values()

---

.github/workflows/ci.yml
.github/workflows/reload-env.sh
mars/_utils.pyx
mars/dataframe/arrays.py
mars/dataframe/base/rechunk.py
mars/dataframe/sort/tests/test_sort_execute.py
mars/dataframe/tests/test_arrays.py
mars/dataframe/utils.py
mars/scheduler/tests/integrated/test_normal_execution.py

[BACKPORT] Support ArrowStringDtype for DataFrame.sort_values() (#1455)

---

.github/workflows/reload-env.sh
mars/_utils.pyx
mars/dataframe/arrays.py
mars/dataframe/base/tests/test_base_execution.py
mars/dataframe/tests/test_arrays.py
mars/errors.py
mars/lib/nvutils.py
mars/serialize/dataserializer.py
mars/serialize/tests/test_serialize.py
mars/session.py
mars/worker/service.py
mars/worker/storage/manager.py
mars/worker/storage/sharedstore.py

[BACKPORT] Support `ExtensionDtype ` in `df.astype` and complex serialization (#1459) (#1462)

---

docs/source/reference/dataframe/api/mars.dataframe.DataFrame.rst
docs/source/reference/dataframe/api/mars.dataframe.ExecutableTuple.rst
docs/source/reference/dataframe/api/mars.dataframe.Series.rst
docs/source/reference/dataframe/api/mars.dataframe.qcut.rst
docs/source/reference/dataframe/general_functions.rst
docs/source/reference/remote/generated/mars.remote.ExecutableTuple.rst
docs/source/reference/tensor/generated/mars.tensor.ExecutableTuple.rst
mars/dataframe/__init__.py
mars/dataframe/base/__init__.py
mars/dataframe/base/qcut.py
mars/dataframe/base/tests/test_base_execution.py
mars/dataframe/core.py
mars/tests/test_session.py

This PR implements `md.qcut`. 
Resolves #1453

Implements `md.qcut`

---

docs/source/dataframe/reference/api/mars.dataframe.ExecutableTuple.rst
docs/source/dataframe/reference/api/mars.dataframe.Series.rst
docs/source/dataframe/reference/api/mars.dataframe.qcut.rst
docs/source/dataframe/reference/general_functions.rst
docs/source/remote/generated/mars.remote.ExecutableTuple.rst
docs/source/tensor/generated/mars.tensor.ExecutableTuple.rst
mars/dataframe/__init__.py
mars/dataframe/base/__init__.py
mars/dataframe/base/cut.py
mars/dataframe/base/qcut.py
mars/dataframe/base/tests/test_base_execution.py
mars/dataframe/core.py
mars/tests/test_session.py

[BACKPORT] Implements `md.qcut` (#1468)

---

mars/base_app.py
mars/dataframe/arrays.py
mars/deploy/local/tests/test_cluster.py
mars/lib/mkl_interface.py
mars/scheduler/__main__.py
mars/serialize/dataserializer.py
mars/tests/test_base_app.py
mars/web/__main__.py
mars/web/session.py
mars/web/tests/test_api.py
mars/worker/__main__.py
mars/worker/calc.py
mars/worker/execution.py
mars/worker/prochelper.py
mars/worker/quota.py
mars/worker/storage/client.py
mars/worker/storage/core.py
mars/worker/storage/cudahandler.py
mars/worker/storage/procmemhandler.py
mars/worker/storage/sharedhandler.py
mars/worker/storage/vineyardhandler.py
mars/worker/tests/test_calc.py
requirements-dev.txt

[BACKPORT] Serialize results in worker before storing into shared storages (#1470)

---

mars/actors/core.pxd
mars/actors/core.pyx
mars/actors/pool/gevent_pool.pyx
mars/base_app.py
mars/config.py
mars/scheduler/assigner.py
mars/scheduler/graph.py
mars/scheduler/resource.py
mars/scheduler/tests/integrated/test_worker_failover.py
mars/scheduler/tests/test_assigner.py
mars/worker/__main__.py
mars/worker/daemon.py
mars/worker/execution.py
mars/worker/service.py
mars/worker/status.py

[BACKPORT] Raise timeout when assigning failed for a long time (#1475)

---

mars/api.py
mars/base_app.py
mars/config.py
mars/deploy/kubernetes/client.py
mars/scheduler/__main__.py
mars/scheduler/service.py
mars/scheduler/tests/integrated/base.py
mars/scheduler/tests/integrated/test_normal_execution.py
mars/scheduler/tests/integrated/test_worker_failover.py
mars/utils.py
mars/web/tests/test_api.py
mars/worker/__main__.py
mars/worker/service.py
mars/worker/storage/iorunner.py
mars/worker/storage/tests/test_client.py

[BACKPORT] Fix pickling arrow types & allow specifying parallel number in IO runners (#1480)

---

docs/source/reference/dataframe/api/mars.dataframe.DataFrame.reindex.rst
docs/source/reference/dataframe/api/mars.dataframe.DataFrame.rst
docs/source/reference/dataframe/api/mars.dataframe.Series.reindex.rst
docs/source/reference/dataframe/api/mars.dataframe.Series.rst
docs/source/reference/dataframe/frame.rst
docs/source/reference/dataframe/series.rst
mars/dataframe/base/qcut.py
mars/dataframe/base/tests/test_base_execution.py
mars/dataframe/datasource/from_tensor.py
mars/dataframe/datasource/tests/test_datasource_execution.py
mars/dataframe/indexing/__init__.py
mars/dataframe/indexing/index_lib.py
mars/dataframe/indexing/loc.py
mars/dataframe/indexing/reindex.py
mars/dataframe/indexing/tests/test_indexing.py
mars/dataframe/indexing/tests/test_indexing_execution.py
mars/dataframe/initializer.py
mars/dataframe/utils.py
mars/scheduler/tests/integrated/test_normal_execution.py
mars/serialize/dataserializer.py
mars/serialize/protos/operand.proto
mars/serialize/tests/test_serialize.py

This PR implements `{DataFrame, Series}.reindex`.
Resolves #1115 .

Implements {DataFrame, Series}.reindex

---

docs/source/dataframe/reference/api/mars.dataframe.DataFrame.reindex.rst
docs/source/dataframe/reference/api/mars.dataframe.Series.reindex.rst
docs/source/dataframe/reference/api/mars.dataframe.Series.rst
docs/source/dataframe/reference/frame.rst
mars/_version.py
mars/dataframe/base/qcut.py
mars/dataframe/base/tests/test_base_execution.py
mars/dataframe/datasource/from_tensor.py
mars/dataframe/datasource/tests/test_datasource_execution.py
mars/dataframe/indexing/__init__.py
mars/dataframe/indexing/index_lib.py
mars/dataframe/indexing/loc.py
mars/dataframe/indexing/reindex.py
mars/dataframe/indexing/tests/test_indexing.py
mars/dataframe/indexing/tests/test_indexing_execution.py
mars/dataframe/initializer.py
mars/dataframe/utils.py
mars/scheduler/tests/integrated/test_normal_execution.py
mars/serialize/dataserializer.py
mars/serialize/protos/operand.proto
mars/serialize/tests/test_serialize.py

[BACKPORT] Implements {DataFrame, Series}.reindex (#1481)

---

mars/config.py
mars/dataframe/__init__.py
mars/dataframe/arrays.py
mars/dataframe/reduction/nunique.py
mars/dataframe/reduction/tests/test_reduction_execute.py
mars/dataframe/tests/test_arrays.py
mars/dataframe/utils.py
mars/serialize/dataserializer.py
mars/serialize/tests/test_serialize.py
mars/utils.py

[BACKPORT] Add support for `ArrowListDtype` as well as `ArrowListArray` (#1486)

---

mars/lib/gipc.pyx
mars/serialize/core.pyx
mars/serialize/jsonserializer.pyx
mars/serialize/pbserializer.pyx
mars/serialize/tests/test_serialize.py
mars/utils.py
mars/web/session.py
requirements-extra.txt

[BACKPORT] Fix compatibility for gevent>=20.5.1 for v0.4 (#1490)

---

mars/lib/gipc.pyx
mars/serialize/core.pyx
mars/serialize/jsonserializer.pyx
mars/serialize/pbserializer.pyx
mars/serialize/tests/test_serialize.py
mars/utils.py
mars/web/session.py
requirements-extra.txt

[BACKPORT] Fix compatibility for gevent>=20.5.1 for v0.5 (#1490)

---

mars/scheduler/graph.py
mars/scheduler/session.py
mars/web/apihandlers.py
mars/web/server.py
mars/web/tests/test_api.py

[BACKPORT] Store and query graph info in batch for v0.4 (#1501)

---

mars/scheduler/graph.py
mars/scheduler/session.py
mars/web/apihandlers.py
mars/web/server.py
mars/web/tests/test_api.py

[BACKPORT] Store and query graph information in batch for v0.5 (#1501)

---

README.rst

Fix URL of contribution guide

---

mars/tensor/arithmetic/arctan2.py
mars/tensor/arithmetic/tests/test_arithmetic_execution.py

[BACKPORT] Fix arctan2 when arguments contains scalar (#1502)

---

mars/cluster_info.py
mars/dataframe/arrays.py
mars/scheduler/assigner.py
mars/scheduler/graph.py
mars/scheduler/mutable.py
mars/scheduler/operands/base.py
mars/scheduler/operands/tests/test_common_exec.py
mars/scheduler/resource.py
mars/scheduler/session.py
mars/worker/dispatcher.py
mars/worker/execution.py
mars/worker/utils.py

[BACKPORT] Unregister scheduler observer when destroying actors (#1525)

---

mars/cluster_info.py
mars/config.py
mars/dataframe/arrays.py
mars/scheduler/assigner.py
mars/scheduler/graph.py
mars/scheduler/mutable.py
mars/scheduler/operands/base.py
mars/scheduler/operands/tests/test_common_exec.py
mars/scheduler/resource.py
mars/scheduler/session.py
mars/worker/__main__.py
mars/worker/calc.py
mars/worker/dispatcher.py
mars/worker/execution.py
mars/worker/quota.py
mars/worker/service.py
mars/worker/storage/diskhandler.py
mars/worker/transfer.py
mars/worker/utils.py

[BACKPORT] Add an option to control writing shuffle data into disk for v0.4 (#1513)

---

mars/_utils.pyx
mars/core.py
mars/dataframe/arithmetic/__init__.py
mars/dataframe/arithmetic/tests/test_comparison.py
mars/dataframe/arrays.py
mars/dataframe/core.py
mars/dataframe/tests/test_arrays.py
mars/executor.py
mars/graph_builder.py
mars/optimizes/tileable_graph/core.py
mars/scheduler/graph.py
mars/tensor/arithmetic/__init__.py
mars/tensor/arithmetic/tests/test_arithmetic.py
mars/tensor/core.py
mars/tensor/datasource/tests/test_datasource.py
mars/tests/test_utils.py
mars/tiles.py
mars/utils.py

[BACKPORT] Unify logic of modes including `eager`, `kernel` and `build` (#1528)

---

mars/dataframe/datasource/tests/test_datasource_execution.py
mars/dataframe/utils.py
mars/tensor/utils.py

[BACKPORT] Fix creating Mars DataFrame from an empty pandas DataFrame (#1522)

---

.github/workflows/ci.yml
conda-spec.txt
mars/dataframe/merge/concat.py
mars/dataframe/reduction/core.py
mars/dataframe/reduction/tests/test_reduction_execute.py
mars/deploy/local/tests/test_cluster.py
mars/learn/neighbors/tests/test_nearest_neighbors.py
mars/scheduler/__init__.py
mars/scheduler/assigner.py
mars/scheduler/operands/common.py
mars/scheduler/operands/tests/test_common_exec.py
mars/session.py
mars/tests/core.py
mars/utils.py
mars/web/session.py
mars/worker/calc.py
mars/worker/service.py
mars/worker/storage/sharedstore.py
mars/worker/tests/test_main.py
mars/worker/tests/test_transfer.py

Fix DataFrame reduction execution on GPU.
Fixes #1533

Fix DataFrame reduction on GPU

---

.github/workflows/ci.yml
conda-spec.txt
mars/dataframe/merge/concat.py
mars/dataframe/reduction/core.py
mars/dataframe/reduction/tests/test_reduction_execute.py
mars/deploy/local/tests/test_cluster.py
mars/learn/neighbors/tests/test_nearest_neighbors.py
mars/scheduler/__init__.py
mars/scheduler/assigner.py
mars/scheduler/operands/common.py
mars/scheduler/operands/tests/test_common_exec.py
mars/session.py
mars/tests/core.py
mars/utils.py
mars/web/session.py
mars/worker/calc.py
mars/worker/service.py
mars/worker/storage/sharedstore.py
mars/worker/tests/test_main.py
mars/worker/tests/test_transfer.py

[BACKPORT] Fix DataFrame reduction on GPU (#1534)

---

.github/workflows/ci.yml

This PR fixed statsmodel version for v0.4
NA

Fixed statsmodel version for v0.4

---

.github/workflows/ci.yml
mars/learn/cluster/_k_means_init.py
mars/learn/cluster/_kmeans.py
mars/learn/cluster/tests/test_k_means.py
mars/learn/metrics/pairwise/euclidean.py
mars/learn/metrics/pairwise/tests/test_euclidean_distances.py
mars/serialize/dataserializer.py
mars/serialize/tests/test_serialize.py
mars/worker/calc.py
mars/worker/quota.py

[BACKPORT] Optimize `mars.learn.cluster.KMeans` when `n_clusters` is relatively large (#1511)

---

mars/deploy/kubernetes/client.py
mars/deploy/kubernetes/config.py
mars/deploy/kubernetes/core.py
mars/deploy/kubernetes/docker/Dockerfile.base
mars/deploy/kubernetes/tests/test_config.py
mars/deploy/kubernetes/tests/test_kubernetes.py
mars/web/static/js/mars.js
mars/web/templates/dashboard.html

Add label options for ``new_cluster`` to add customized labels.
Fixes #1546

Add configurable label options in Kubernetes cluster

---

mars/context.py
mars/dataframe/base/apply.py
mars/dataframe/groupby/apply.py
mars/dataframe/groupby/tests/test_groupby_execution.py
mars/dataframe/utils.py
mars/deploy/local/tests/test_cluster.py

[BACKPORT] Allow returning None when using groupby.apply (#1544)

---

mars/deploy/kubernetes/client.py
mars/deploy/kubernetes/config.py
mars/deploy/kubernetes/core.py
mars/deploy/kubernetes/tests/test_config.py
mars/deploy/kubernetes/tests/test_kubernetes.py
mars/web/static/js/mars.js
mars/web/templates/dashboard.html

[BACKPORT] Add configurable label options in Kubernetes cluster (#1547)

---

mars/dataframe/base/apply.py
mars/dataframe/base/map.py
mars/dataframe/base/transform.py
mars/dataframe/groupby/aggregation.py
mars/dataframe/groupby/apply.py
mars/dataframe/groupby/transform.py
mars/deploy/local/tests/test_cluster.py
mars/remote/core.py
mars/utils.py

Set current session to default session in the execution of user defined functions, it allows submitting jobs in custom functions.
Closes #1558.

Allow submitting Mars jobs in custom functions

---

mars/dataframe/base/apply.py
mars/dataframe/base/map.py
mars/dataframe/base/transform.py
mars/dataframe/groupby/aggregation.py
mars/dataframe/groupby/apply.py
mars/dataframe/groupby/transform.py
mars/deploy/local/tests/test_cluster.py
mars/remote/core.py
mars/utils.py

[BACKPORT] Allow submitting Mars jobs in custom functions (#1559)

---

.codecov.yml
.coveragerc
.coveragerc-threaded
.github/codecov-upstream.yml
.github/workflows/ci.yml
mars/deploy/kubedl/__init__.py
mars/deploy/kubedl/client.py
mars/deploy/kubedl/config.py

Support running Mars as a CRD under https://github.com/alibaba/kubedl . No tests added as we do not have a test environment.

Support running Mars under KubeDL

---

mars/_version.py
mars/dataframe/groupby/aggregation.py

CI of master has failed due to release of pandas 1.1.2, https://github.com/mars-project/mars/actions/runs/245612099 .
This PR tries to address the issue.
NA

Fix pandas 1.1.2 compatibility

---

mars/_version.py
mars/dataframe/groupby/aggregation.py

[BACKPORT] Fix pandas 1.1.2 compatibility (#1562)

---

mars/learn/contrib/tsfresh/core.py
mars/serialize/core.pxd
mars/serialize/core.pyx
mars/serialize/jsonserializer.pyx
mars/serialize/pbserializer.pyx
mars/serialize/protos/value.proto
mars/serialize/tests/test_serialize.py
mars/serialize/tests/testser.proto

This PR fixes compatibility for tsfresh 0.17.0.
NA

Fix compatibility for tsfresh 0.17.0

---

docs/source/reference/dataframe/api/mars.dataframe.DataFrame.select_dtypes.rst
docs/source/reference/dataframe/frame.rst
mars/dataframe/base/__init__.py
mars/dataframe/base/select_dtypes.py
mars/dataframe/base/tests/test_base_execution.py
requirements-dev.txt

This PR adds `select_dtypes` support. 
Fixes #1351

Add `df.select_dtypes` support

---

mars/learn/contrib/tsfresh/core.py
mars/serialize/core.pxd
mars/serialize/core.pyx
mars/serialize/jsonserializer.pyx
mars/serialize/pbserializer.pyx
mars/serialize/protos/value.proto
mars/serialize/tests/test_serialize.py
mars/serialize/tests/testser.proto

[BACKPORT] Fix compatibility for tsfresh 0.17.0 (#1566)

---

docs/source/reference/dataframe/api/mars.dataframe.DataFrame.select_dtypes.rst
docs/source/reference/dataframe/frame.rst
mars/dataframe/base/__init__.py
mars/dataframe/base/select_dtypes.py
mars/dataframe/base/tests/test_base_execution.py
requirements-dev.txt

[BACKPORT] Add `df.select_dtypes` support (#1565)

---

mars/dataframe/base/__init__.py
mars/dataframe/base/map_chunk.py
mars/dataframe/base/tests/test_base_execution.py
mars/serialize/protos/operand.proto

This PR added `df.map_chunk` support.
Resolves #1556 .

Add `df.map_chunk` support

---

mars/dataframe/base/__init__.py
mars/dataframe/base/map_chunk.py
mars/dataframe/base/tests/test_base_execution.py
mars/serialize/protos/operand.proto

[BACKPORT] Add `df.map_chunk` support (#1569)

---

docs/source/installation/kubernetes.rst
docs/source/locale/zh_CN/LC_MESSAGES/installation/kubernetes.po
mars/api.py
mars/base_app.py
mars/cluster_info.py
mars/deploy/kubernetes/client.py
mars/deploy/kubernetes/core.py
mars/deploy/kubernetes/scheduler.py
mars/deploy/kubernetes/tests/test_kubernetes.py
mars/deploy/local/core.py
mars/deploy/local/tests/test_cluster.py
mars/deploy/yarn/client.py
mars/deploy/yarn/core.py
mars/executor.py
mars/learn/semi_supervised/_label_propagation.py
mars/session.py
mars/utils.py
mars/web/__main__.py
mars/web/apihandlers.py
mars/web/session.py
mars/web/tests/test_api.py
mars/worker/execution.py

Support rescaling workers in Mars by calling
```python
cluster.rescale_workers(num_of_workers)
```
Fixes #1551

Support rescaling worker numbers in Kubernetes

---

docs/source/reference/dataframe/api/mars.dataframe.DataFrame.map_chunk.rst
docs/source/reference/dataframe/api/mars.dataframe.DataFrame.rebalance.rst
docs/source/reference/dataframe/api/mars.dataframe.DataFrame.rst
docs/source/reference/dataframe/api/mars.dataframe.Series.dt.rst
docs/source/reference/dataframe/api/mars.dataframe.Series.map_chunk.rst
docs/source/reference/dataframe/api/mars.dataframe.Series.rst
docs/source/reference/dataframe/api/mars.dataframe.Series.str.rst
docs/source/reference/dataframe/frame.rst
docs/source/reference/dataframe/series.rst
mars/api.py
mars/context.py
mars/dataframe/base/__init__.py
mars/dataframe/base/map_chunk.py
mars/dataframe/base/rebalance.py
mars/dataframe/base/rechunk.py
mars/dataframe/base/tests/test_base.py
mars/dataframe/base/tests/test_base_execution.py
mars/operands.py
mars/scheduler/analyzer.py
mars/scheduler/graph.py
mars/scheduler/resource.py
mars/scheduler/tests/integrated/base.py
mars/scheduler/tests/integrated/test_normal_execution.py
mars/serialize/protos/operand.proto
mars/session.py
mars/web/apihandlers.py
mars/worker/calc.py

This PR added support for `df.rebalance()`.
Resolves #1557 .

Implements `df.rebalance()`

---

docs/source/reference/dataframe/api/mars.dataframe.DataFrame.mask.rst
docs/source/reference/dataframe/api/mars.dataframe.DataFrame.rst
docs/source/reference/dataframe/api/mars.dataframe.DataFrame.where.rst
docs/source/reference/dataframe/api/mars.dataframe.Series.mask.rst
docs/source/reference/dataframe/api/mars.dataframe.Series.rst
docs/source/reference/dataframe/api/mars.dataframe.Series.where.rst
docs/source/reference/dataframe/frame.rst
docs/source/reference/dataframe/series.rst
mars/dataframe/core.py
mars/dataframe/indexing/__init__.py
mars/dataframe/indexing/tests/test_indexing_execution.py
mars/dataframe/indexing/where.py

[BACKPORT] Add support for {DataFrame,Series}.{where,mask} (#1577)

---

.github/workflows/ci.yml
mars/dataframe/__init__.py
mars/dataframe/datasource/read_csv.py
mars/dataframe/datasource/read_parquet.py
mars/dataframe/datasource/tests/test_datasource_execution.py
mars/dataframe/utils.py

[BACKPORT] Add `read_parquet` support (#1576)

---

.github/workflows/ci.yml
mars/session.py
mars/tests/test_session.py

If Series element is a numpy ndarray, it fails when fetch the sum of Series, we need to check result size when fetch data.
Fixes #1580.

Fix the failure when fetching the result of Series.sum

---

docs/source/getting_started/execution.rst
mars/_version.py
mars/dataframe/base/__init__.py
mars/dataframe/base/isin.py
mars/dataframe/base/tests/test_base.py
mars/dataframe/base/tests/test_base_execution.py

This PR added `DataFrame.isin` support.
Resolves #756 .

Added `DataFrame.isin` support

---

.github/workflows/ci.yml
mars/session.py
mars/tests/test_session.py

[BACKPORT] Fix the failure when fetching the result of Series.sum (#1583)

---

docs/source/reference/dataframe/api/mars.dataframe.DataFrame.rst
docs/source/reference/dataframe/api/mars.dataframe.DataFrame.stack.rst
docs/source/reference/dataframe/frame.rst
mars/dataframe/base/__init__.py
mars/dataframe/base/stack.py
mars/dataframe/base/tests/test_base_execution.py

This PR implements `DataFrame.stack`.
Resolves #1120 .

Implements `DataFrame.stack`

---

docs/source/getting_started/execution.rst
mars/_version.py
mars/dataframe/base/__init__.py
mars/dataframe/base/isin.py
mars/dataframe/base/tests/test_base.py
mars/dataframe/base/tests/test_base_execution.py

[BACKPORT] Add `DataFrame.isin` support (#1584)

---

docs/source/reference/dataframe/api/mars.dataframe.DataFrame.rst
docs/source/reference/dataframe/api/mars.dataframe.DataFrame.stack.rst
docs/source/reference/dataframe/frame.rst
mars/dataframe/base/__init__.py
mars/dataframe/base/stack.py
mars/dataframe/base/tests/test_base_execution.py

[BACKPORT] Implements `DataFrame.stack` (#1591)

---

mars/dataframe/arithmetic/core.py
mars/dataframe/arithmetic/tests/test_arithmetic.py
mars/dataframe/datasource/read_parquet.py
mars/dataframe/indexing/where.py
mars/dataframe/reduction/tests/test_reduction_execute.py
mars/dataframe/utils.py

[BACKPORT] Fix failures of DataFrame reduction operators (#1589)

---

mars/graph.pyx
mars/learn/contrib/lightgbm/tests/integrated/test_distributed_lightgbm.py
mars/learn/contrib/lightgbm/train.py
mars/learn/tests/integrated/base.py

[BACKPORT] Fix error on fitting LGBMModel twice (#1598)

---

docs/source/reference/dataframe/api/mars.dataframe.DataFrame.all.rst
docs/source/reference/dataframe/api/mars.dataframe.DataFrame.any.rst
docs/source/reference/dataframe/api/mars.dataframe.Series.all.rst
docs/source/reference/dataframe/api/mars.dataframe.Series.any.rst
docs/source/reference/dataframe/api/mars.dataframe.groupby.GroupBy.all.rst
docs/source/reference/dataframe/api/mars.dataframe.groupby.GroupBy.any.rst
docs/source/reference/dataframe/frame.rst
docs/source/reference/dataframe/groupby.rst
docs/source/reference/dataframe/series.rst
mars/dataframe/groupby/__init__.py
mars/dataframe/groupby/aggregation.py
mars/dataframe/groupby/tests/test_groupby_execution.py
mars/dataframe/reduction/__init__.py
mars/dataframe/reduction/aggregation.py
mars/dataframe/reduction/all.py
mars/dataframe/reduction/any.py
mars/dataframe/reduction/core.py
mars/dataframe/reduction/tests/test_reduction.py
mars/dataframe/reduction/tests/test_reduction_execute.py
mars/tests/core.py

Implements {DataFrame,Series,GroupBy}.{all,any}.
Fixes #1342

Implements {DataFrame,Series,GroupBy}.{all,any}

---

docs/source/reference/dataframe/api/mars.dataframe.DataFrame.all.rst
docs/source/reference/dataframe/api/mars.dataframe.DataFrame.any.rst
docs/source/reference/dataframe/api/mars.dataframe.Series.all.rst
docs/source/reference/dataframe/api/mars.dataframe.Series.any.rst
docs/source/reference/dataframe/api/mars.dataframe.groupby.GroupBy.all.rst
docs/source/reference/dataframe/api/mars.dataframe.groupby.GroupBy.any.rst
docs/source/reference/dataframe/frame.rst
docs/source/reference/dataframe/groupby.rst
docs/source/reference/dataframe/series.rst
mars/dataframe/groupby/__init__.py
mars/dataframe/groupby/aggregation.py
mars/dataframe/groupby/tests/test_groupby_execution.py
mars/dataframe/reduction/__init__.py
mars/dataframe/reduction/aggregation.py
mars/dataframe/reduction/all.py
mars/dataframe/reduction/any.py
mars/dataframe/reduction/core.py
mars/dataframe/reduction/tests/test_reduction.py
mars/dataframe/reduction/tests/test_reduction_execute.py
mars/tests/core.py

[BACKPORT] Add support for {DataFrame,Series,GroupBy}.{all,any} (#1600)

---

mars/dataframe/sort/psrs.py
mars/dataframe/sort/sort_values.py
mars/dataframe/sort/tests/test_sort_execute.py
mars/learn/contrib/lightgbm/core.py
mars/learn/contrib/lightgbm/regressor.py
mars/learn/contrib/lightgbm/tests/test_regressor.py
mars/scheduler/tests/integrated/test_normal_execution.py
mars/utils.py
mars/worker/prochelper.py
mars/worker/quota.py
mars/worker/storage/objectholder.py
mars/worker/storage/tests/test_objectholder.py

[BACKPORT] Add extra sort key in PSRS to make distinct pivot (#1612)

---

.github/workflows/ci.yml
mars/learn/neighbors/_faiss.py
mars/learn/neighbors/tests/test_faiss.py

[BACKPORT] Fix `build_faiss_index` when some index type cannot be merged (#1609)

---

mars/deploy/kubernetes/config.py
mars/learn/model_selection/tests/test_split.py
mars/learn/utils/validation.py

[BACKPORT] Fix `train_test_split` when some input is Series (#1610)

---

docs/source/reference/dataframe/api/mars.dataframe.DataFrame.corr.rst
docs/source/reference/dataframe/api/mars.dataframe.DataFrame.corrwith.rst
docs/source/reference/dataframe/api/mars.dataframe.Series.autocorr.rst
docs/source/reference/dataframe/api/mars.dataframe.Series.corr.rst
docs/source/reference/dataframe/frame.rst
docs/source/reference/dataframe/series.rst
mars/dataframe/reduction/__init__.py
mars/dataframe/statistics/__init__.py
mars/dataframe/statistics/corr.py
mars/dataframe/statistics/tests/test_statistics_execute.py
mars/serialize/protos/operand.proto

[BACKPORT] Add support for pearson coefficients (corr, corrwith and autocorr) (#1587)
